### ISSUE TITLE
Follow button on Peerlyst blocked

### ISSUE THREAD

**Issue by chouma** [ryanbr/fanboy-adblock#1]
Hi @ryanbr - Just activated fanboys annoyances and suddenly the button to follow a user on Peerlyst was gone.

I checked the different lists and our website isnt on your list.

**Comment by ryanbr** [comment]
If you manually add `peerlyst.com#@#.follow-button` does that help?

**Comment by chouma** [comment]
Add it to the blocklists? I want to allow it

**Comment by ryanbr** [comment]
add it as a custom filter

**Comment by chouma** [comment]
That probably won't fix it for any other Peerlyst user.

**Comment by ryanbr** [comment]
examples sites?

**Comment by chouma** [comment]
www.peerlyst.com - anyone with this active in Adblock plus can't see follow buttons for users

**Comment by ryanbr** [comment]
peerlyst.com#@#.follow-button  <-- Everything on peerlyst.com

**Comment by chouma** [comment]
Do you mean that you added it as a whitelist item?

**Comment by ryanbr** [comment]
Its pretty obvious its a whitelist item, why asked on the very first post because I wanted you to test it.

**Comment by chouma** [comment]
Doesn't work, follow button still gone when the filter active

**Comment by ryanbr** [comment]
It worked for me, showed the "Follow" button.

https://hg.adblockplus.org/easylist/rev/632eb3fb22b0

Considered fixed here.
