### ISSUE TITLE
Remnant of ads appear on CBS.com

### ISSUE THREAD

**Issue by yashendra2797** [ryanbr/fanboy-adblock#10]
Ads are blocked while watching videos with CBS All Access, but the buffering ring is still on the screen while the video keeps on playing. If I pause, the ad starts playing, and when the ads are over the buffering icon is gone.

Any help with this?

Thanks!

**Comment by SMed79** [comment]
Hi, 
use only one adblocking addon / update your filter lists /cleare cookies and cache / add these filters and test again : 
```
@@||pubads.g.doubleclick.net/gampad/ads?*rule=$domain=cbs.com
@@|http://$xmlhttprequest,image,domain=cbs.com
@@/adblock$domain=cbs.com
```
if not work seek assistance on easylist forum: https://forums.lanik.us/viewforum.php?f=62

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/7550a17a08853946d6bca19852a430faf370f153
