### ISSUE TITLE
Reddit is blocked on the AdGuard "Enhanced Tracking List"

### ISSUE THREAD

**Issue by groovybluedog** [ryanbr/fanboy-adblock#1000]
### List the website(s) you're having issues:

`https://reddit.com`

### What happens?

The entire reddit website is blocked. You cannot sign in or load content, including in the reddit app and within third party apps.

When the list is disabled, reddit loads as normal.

### List Subscriptions you're using:

Various, but I have tracked it down via AdGuards filtering log to "Fanboy's Enhanced Tracking List".

### Your settings

- OS/version: Android 8
- Browser/version: Reddit app
- Adblock Extension/version: AdGuard 3.0.264

### Other details:

![Screenshot_20190408-130222_AdGuard](https://user-images.githubusercontent.com/16142383/55722588-9cdff900-59fe-11e9-99cf-8fe8c964c7c6.jpg)

**Comment by ryanbr** [comment]
Was fixed, just force update.
