### ISSUE TITLE
Yahoo / Oath bad filters in Cookie list

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1003]
## URL [](https://github.com/MajkiIT/polish-ads-filter/issues/12824)

```
https://consent.yahoo.com/collectConsent?sessionId=3_cc-session_3fc41adb-f16a-4965-8bc9-a2d90e319ddc&lang=&inline=false
```

## Exception

```
yahoo.com#@#.consent-container
```

## Screenshots

Before:

![obraz](https://i.imgur.com/i1ILW5T.png) |
--- |

After:

![obraz](https://i.imgur.com/4Dbd6aG.png) |
--- |

**Comment by kulfoon** [comment]
Duplicate of https://github.com/ryanbr/fanboy-adblock/issues/980.
