### ISSUE TITLE
Podbean.com - broken pages (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1006]
### Affected site:
`https://www.podbean.com/`

### Issue:
Completely broken pages. 

### Example:
`https://www.podbean.com/media/share/dir-68n66-5f41892/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.share-content`

### Possible fix:
`podbean.com#@#.share-content`

### Note:
Also, some filters are blocking the audio stream, but this has been reported to the respective filter authors.

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by krystian3w** [comment]
I can reproduce, this is bad generic filter (cosmetic).
