### ISSUE TITLE
vitaminshoppe.com

### ISSUE THREAD

**Issue by jo2dan23** [ryanbr/fanboy-adblock#101]
@@||recs.richrelevance.com/rrserver/api/rrPlatform/recsForPlacements?apiClientKey=$domain=vitaminshoppe.com

fixes add to cart

https://www.vitaminshoppe.com/p/complete-cookie-snickerdoodle-12-cookie-s/le-1017

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/87447888b026a6f63ac8006a679d4bead3ac8482
