### ISSUE TITLE
Cookie banner not blocked: granini.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1011]
### List the website(s) you're having issues:
`https://www.granini.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 65.0.2
- Adblock Extension/version: uBlock Origin 1.18.6

**Comment by ryanbr** [comment]
Should also be fixed.
