### ISSUE TITLE
Tweetdeck.twitter.com

### ISSUE THREAD

**Issue by rpodric** [ryanbr/fanboy-adblock#1015]
### List the website(s) you're having issues:
`https://tweetdeck.twitter.com`

### What happens?
This is new as of the last week or so (can't recall, exactly), but there are at least two, related issues:
1) When you click a username of anyone showing up in your timeline, the Following/Unfollow oval on the right side of the form doesn't fill out and instead just contains a spinning animation.
2) When you click "Tweets" on that same form, instead of a list of the user's past tweets displaying, you just get a "Loading" message with a spinning animation.

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak​​​​​
EasyList
EasyPrivacy
Malware Domain List
Malware domains​
Fanboy’s Annoyance List​
Peter Lowe’s Ad and tracking server list​
### Your settings

OS/version: Win 10
Browser/version: Chrome 73
Adblock Extension/version: uBO 1.18.16

### Other details:
_Disabling Fanboy’s Annoyance List resolves the issue._

What the issues looks like:
`https://i.imgur.com/xw4s8SB.png`
`https://i.imgur.com/RGwdfTj.png`

**Comment by ryanbr** [comment]
Update lists, see if it helps. not sure if I fixed it.

**Comment by rpodric** [comment]
You did. Thanks!

**Comment by rpodric** [comment]
I notice today, though, that it's back to not working. I'm not sure how that's possible, since when I checked this filter, it hadn't been updated since a day ago (when I triggered the update yesterday).

**Comment by Khrin** [comment]
Weird, it is working correctly for me...

**Comment by rpodric** [comment]
With Fanboy’s Annoyance List​?

**Comment by ryanbr** [comment]
with Annoyances List, i have no issues. looks fine here. You'll need to debug more otherwise it won't be fixed.

**Comment by rpodric** [comment]
Will do. It must be some kind of freak holdover here (which goes away if that filter is disabled), because I can't reproduce it in a VM.
