### ISSUE TITLE
Bethesda.net [Issue #981 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1017]
This issue needs to be addressed!
Read my post here:
https://github.com/ryanbr/fanboy-adblock/issues/981#issuecomment-486278226

**Comment by krystian3w** [comment]
`##visor-alert > div > div > div:last-child`

Should hide faster as older sugestion, and has potential (no generic this bug if we close cookie notification in the past).

**Comment by krystian3w** [comment]
another sugestion:

`##visor-alert > div > div > div:last-child`

But still cut error login alert if we close cookies norification in the past.

**Comment by krystian3w** [comment]
@Khrin can you test this with login form when you put random text into inputs in form?

**Comment by peace2000** [comment]
How is this now ?

**Comment by krystian3w** [comment]
Still cut error after typo in login form - @Khrin.

**Comment by THEtomaso** [comment]
> How is this now ?

Unchanged.
I've already tried to explain the importance of Bethesda's messaging system.
Don't know why the hell this issue hasn't been resolved yet!

**Comment by krystian3w** [comment]
EasyList avoid use `-abp-` "JavaScript synatx...?

**Comment by THEtomaso** [comment]
Then simply delete the problem rule!

**Comment by krystian3w** [comment]
Cookie bar can again visible and hidden with advanced "slow" filter?

**Comment by THEtomaso** [comment]
Don't know what that means, but **AdGuard Annoyances filter** (@BlazDT) filter still breaks Bethesda's messaging system too, with the following rule (which obviously doesn't work entirely like intended):
`bethesda.net#?#visor-alert:has(> div > div > div > a[href$="/cookie-policy"])`

**Comment by krystian3w** [comment]
Polish works property:

`bethesda.net#?#visor-alert > div > div > div:last-child:has(a[href="/pl/document/cookie-policy"])`

international:

`bethesda.net#?#visor-alert > div > div > div:last-child:has(a[href$="/document/cookie-policy"])`

I do not know who update this so bad: https://github.com/AdguardTeam/AdguardFilters/commit/75bd3ca9d1711d4bfc70461871734cf40fff38c4

**Comment by krystian3w** [comment]
I found it - https://github.com/AdguardTeam/AdguardFilters/commit/66bf751d3cc5992b1bd848fc8089f4c25660d5d2 @slavaleleka failed and broken logon page.

**Comment by peace2000** [comment]
Made a pull request to disable that rule. That's the best option at the moment, can later decide how to block it properly.

Imo it's better to disable it with a comment instead of deleting it, so that it won't be added back some day.

**Comment by BlazDT** [comment]
> `bethesda.net#?#visor-alert > div > div > div:last-child:has(> a[href$="/cookie-policy"])`

Thank you, modified existing rule to above

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/faa3dabdcccaf8f421fa87600c03d776800bfbe8 - try now

**Comment by THEtomaso** [comment]
> try now

What's the reason for modifying the rule any further?
You previous fix, which was adopted by BlazDT, seems to work just fine, so why add a slightly more resource demanding `-abp-` syntax to it?
