### ISSUE TITLE
toutelanutrition.com: unable to read articles

### ISSUE THREAD

**Issue by ariasuni** [ryanbr/fanboy-adblock#102]
The website seems to break because of Fanboy’s Annoyance List.

<https://www.toutelanutrition.com/blog/supplementation/etude-suvimax-supplements-de-vitamines-risque-de-cancer-homme>

**Comment by mapx-** [comment]
`toutelanutrition.com#@#.footer-newsletter`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/763d3333bea02d265c2a10341cea07ca4221cd48
