### ISSUE TITLE
bit.tube

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#1020]
### List the website(s) you're having issues:
`
https://bit.tube/play?hash=Qmah8QssFry2n5ivfLhCBkf9GVLMK1jGNVxHKe8gGY57XQ&channel=77471
`

### What happens?

Broken link if i try to share

##.contentShare

Fanboy’s Annoyance List 
Fanboy’s Social Blocking List 

### List Subscriptions you're using:

https://gist.github.com/KonoromiHimaries/9bc55fcafd3fab612f1f8dfa59f8f572

### Your settings

- OS/version: w10
- Browser/version: chr latest stable 
- Adblock Extension/version: ubo latest stable

**Comment by THEtomaso** [comment]
This is simply the filters doing their job, blocking the social elements, like they're supposed to.
If anything, the sharing button should be blocked all togehter!:
`bit.tube##.divIconUserAction:nth-child(2)`

**Comment by ryanbr** [comment]
Seems fine here, and video played well. now i know i need more bitcoins, and definitely not litecoin.
