### ISSUE TITLE
Cookie banner not blocked: bayrisches-woerterbuch.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1022]
### List the website(s) you're having issues:
`https://www.bayrisches-woerterbuch.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.18.6

**Comment by ryanbr** [comment]
Its fine? I see no cookie notices. check your subs. closing this.
