### ISSUE TITLE
finanztip.de [overlay]

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1033]
### List the website(s) you're having issues:

`https://www.finanztip.de/girokonto/konto-eroeffnen/`

### What happens?

After ~20 seconds a overlay appears (newspaper)

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3184258/Settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 66.0.5
- Adblock Extension/version: uBlock Origin v1.19.2

**Comment by krystian3w** [comment]
`##.react-newsletter-overlay` or 

`##.react-newsletter-overlay > .overlay`
