### ISSUE TITLE
Google.* bad filter

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1034]
### What happens?

Different filters break another filter from uBlock Origin

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3187172/Settings.txt)

### Your settings

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3187176/Settings.txt)

- OS/version: Windows 10
- Browser/version: Firefox 66.0.5
- Adblock Extension/version: uBlock Origin v1.19.2

### Other details:

Examples:
Without cosmetic filters:
<img width="956" alt="purevpn_no_cosmetic" src="https://user-images.githubusercontent.com/48647394/57856085-8b9fbe80-77ec-11e9-8343-703df678f5d1.PNG">

With cosmetic filters:
<img width="930" alt="purevpn_with_cosmetic" src="https://user-images.githubusercontent.com/48647394/57856102-94909000-77ec-11e9-9ff8-e7d8f5a33478.PNG">

With cosmetic filters but `##[href*=".purevpn.com"]` filter is withelisted:
<img width="691" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/57856184-bc7ff380-77ec-11e9-9bd8-5e0a40053b94.PNG">

The bad filter on this example is `##[href*=".purevpn.com"]` from Fanboy’s Enhanced Tracking List

**Comment by krystian3w** [comment]
google needed:

`google.com##.rc:-abp-has([href*=".purevpn.com"])`

![obraz](https://user-images.githubusercontent.com/35370833/57968472-5cfc2200-796b-11e9-9370-7a69f65cec88.png) |
--- |

**Comment by ryanbr** [comment]
has been modified.
