### ISSUE TITLE
pihlajalinna.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1036]
### List the website(s) you're having issues:

`https://www.pihlajalinna.fi/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 66.0.5
- Adblock Extension/version: Ublock Origin 1.19.02

### Other details:

-

**Comment by krystian3w** [comment]
`###root > div[aria-live="polite"][role="alert"]`

or use randomized / compressed classes?
