### ISSUE TITLE
Tinder.com [Issue #950 reopen-reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1037]
The issue has NOT been resolved!
Please read this exact post, to see what the actual issue is!:
https://github.com/ryanbr/fanboy-adblock/issues/950#issuecomment-466758171
(The cookie bar issue, reported by krystian3w, is not related to it)

**Comment by ryanbr** [comment]
I've looked into it, whitelist and non-whitelist, seems to be fixed. unless there isn't something else i'm missing? I will close this.

**Comment by THEtomaso** [comment]
I see what the problem is now..
**uBlock Origin** uses your '**Anti-Facebook List**' which is hosted at this URL:
`https://fanboy.co.nz/fanboy-antifacebook.txt`
It hasn't been updated since **19 May 2018**.

But the one located at GitHub is more recent (**24 Feb 2019**):
`https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fanboy-antifacebook.txt`

So where does the problem lie?
Is there a problem at your end, preventing those files from being synced, or should I report the issue to gorhill, requesting for uBO to use the GitHub file instead?

**Comment by ryanbr** [comment]
wasn't aware of this, i'll get it fixed up.

**Comment by ryanbr** [comment]
Should be resolved now, thanks for the notification.
