### ISSUE TITLE
Cookie banner not blocked: liliput-lounge.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1038]
### List the website(s) you're having issues:
`https://www.liliput-lounge.de`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:

fanboy's cookie list
### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.19.2

**Comment by ryanbr** [comment]
Is there another filter in another list using $generichide?

**Comment by bestoernesto** [comment]
Sorry, that was my mistake. The page was not fully loaded when I moved here to report the cookie banner. Everything is ok. You can close it.
