### ISSUE TITLE
Some change made prevents the game "Game of Thrones Ascent" from loading

### ISSUE THREAD

**Issue by ipodah** [ryanbr/fanboy-adblock#104]
A change has been made recently on the list. That change prevents the following game from loading : http://www.kongregate.com/games/DisruptorBeam/game-of-thrones-ascent

The game gets stuck on its "Loading :" screen and the progress bar doesn't move further. 

Disabling the "Fanboy's Enhanced Tracking List" in uBlock Origin allows the game to load. Something has changed, I've been using the list and the game without issues so far.

**Comment by ryanbr** [comment]
Force an update

**Comment by ipodah** [comment]
That fixed it! Thanks.
