### ISSUE TITLE
oculus.com [cookiebar]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1046]
```
https://www.oculus.com/
```

kiboke solution:

`oculus.com##section[colorscheme="dark"]`

---

another: [](https://github.com/MajkiIT/polish-ads-filter/issues/13519)

`oculus.com##div[data-cookiebanner="banner"]` 

cut less as kiboke filter but "`section[colorscheme="dark"]`" no have sizes.

**Comment by ryanbr** [comment]
would this work?

##div[data-cookiebanner]

**Comment by krystian3w** [comment]
Yes, I suppose possible use only name html attrib.
