### ISSUE TITLE
Need to block

### ISSUE THREAD

**Issue by edtw** [ryanbr/fanboy-adblock#1047]
### List the website(s) you're having issues:
This is the ad delivery chain, please block it.
sp.aifei0755.net/123/
ad.ettoday.net

### What happens?
Send a lot of ads, please block it.

### List Subscriptions you're using:
Complete / Ultimate

### Your settings
Adblock Plus

- OS/version: Windows 7
- Browser/version: Chrome 76
- Adblock Extension/version: Adblock Plus 3.5.2

**Comment by ryanbr** [comment]
which site does it come from?

**Comment by edtw** [comment]
They come from these two websites.

sp.aifei0755.net/123/
ad.ettoday.net

**Comment by ryanbr** [comment]
if its non-english sites, it won't for these lists.
