### ISSUE TITLE
Объявления, социальные, досадные

### ISSUE THREAD

**Issue by l000ser** [ryanbr/fanboy-adblock#105]
Здравствуйте

Добавьте в свои списки
```
adguard.com##.main-partner
https://adguard.com/en/
```
---
```
adguard.com##.share
adguard.com##.gh-subscribe
https://blog.adguard.com/en/kids_vs_ads/
```

**Comment by ryanbr** [comment]
Didn't see the need for the other 2 filters;

https://github.com/easylist/easylist/commit/923720037674bdbd2e618c33cc2f0d295b94de9a
