### ISSUE TITLE
nytimes.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1051]
### What happens?

Cookie banner after a few seconds

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3223453/Settings.txt)

### Your settings

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3223455/Settings.txt)

- OS/version: Windows 10
- Browser/version: Firefox 67.0
- Adblock Extension/version: uBlock Origin v1.19.6

**Comment by ryanbr** [comment]
see;
https://github.com/ryanbr/fanboy-adblock/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+nytimes
