### ISSUE TITLE
Newgrounds.com broken by Fanboy's annoyance list

### ISSUE THREAD

**Issue by qwertychouskie** [ryanbr/fanboy-adblock#1054]
### List the website(s) you're having issues:
`newgrounds.com`

### What happens?
The top bar with the search and such is missing

### List Subscriptions you're using:
Fanboy's annoyance list

### Your settings

- OS/version: Linux/Xubuntu 19.04
- Browser/version: FF Nightly
- Adblock Extension/version: uBlock Origin v1.19.6

### Other details:
List has a filter for `www.newgrounds.com##.notification-bar`, which disables the top bar.  This filter should be removed.  Also, consider adding this filter: `www.newgrounds.com##.skin-wrapper` as the background is quite visually distracting.

**Comment by ryanbr** [comment]
was removed.

**Comment by THEtomaso** [comment]
> was removed.

What was removed?
This generic rule (found in '**Fanboy's Annoyance List**') still breaks the site's top bar!:
`##.notification-bar`

**Comment by krystian3w** [comment]
`##.skin-wrapper` I suppose only deleted.

**Comment by THEtomaso** [comment]
> `##.skin-wrapper` I suppose only deleted.

No, the OP did actually recommend that as an addition..
But as a site-specific filter of course.
I'd imagine adding it as a generic one would be a big mistake.
