### ISSUE TITLE
Patient.info - Unable to access forum (Fanboy's Annoyance List / Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1057]
### Affected page:
`https://patient.info/forums/`

### Issue:
Unable to access forum, because of a blocked cookie consent.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rules:
```
##.alert--cookie
###cookie-policy
```

### Possible fix:
```
patient.info#@#.alert--cookie
patient.info#@##cookie-policy
```

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.5.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by krystian3w** [comment]
I reported also to uAssets: https://github.com/uBlockOrigin/uAssets/issues/5763

**Comment by THEtomaso** [comment]
> AdGuard: https://github.com/AdguardTeam/AdguardFilters/issues/34767

That's a duplicate.
I filed reports here too, four days ago:
https://github.com/AdguardTeam/AdguardFilters/issues/34618/ 
https://github.com/lassekongo83/Frellwits-filter-lists/issues/55/
