### ISSUE TITLE
dgbrechtsschutz.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1062]
### List the website(s) you're having issues:

`https://www.dgbrechtsschutz.de/`

### What happens?

Newsletter overlay

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3273442/Settings.txt)

### Your settings
[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3273443/Settings.txt)

- OS/version: Windows 10
- Browser/version: Firefox 67.0.1
- Adblock Extension/version: uBlock Origin v1.19.6

**Comment by ryanbr** [comment]
If I block this, it'll block the scroll bar :(
