### ISSUE TITLE
Newgrounds.com [Issue #1054 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1065]
The site's top bar is still broken by '**Fanboy's Annoyance List**'!

Details here:
https://github.com/ryanbr/fanboy-adblock/issues/1054#issuecomment-502365965

**Comment by llacb47** [comment]
’newgrounds.com#@#.notification-bar’

**Comment by ryanbr** [comment]
Was fixed, since we removed the filter
