### ISSUE TITLE
DSREPS.com - All images are blocked (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1068]
### Affected site:
`http://www.dsreps.com/`

### Issue:
All images are blocked.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`/social-icons-`

### Blocked script:
`http://www.dsreps.com/js/social-icons-bio.js`

### Possible fix:
`@@||dsreps.com/js/social-icons-bio.js`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.5.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by Khrin** [comment]
Thank you, fixed.
