### ISSUE TITLE
https://stocktwits.com

### ISSUE THREAD

**Issue by VernonStow** [ryanbr/fanboy-adblock#107]
Stocktwits.com is broken by the Enhanced Tracking List filter `/\.cloudfront\.net\/.*[a-zA-Z0-9]{30}/$third-party,script`

Example: the page at https://stocktwits.com/CUPandHANDLE_CHARTS/message/87798468?

Using uBlock Origin on Firefox 54.0.1 32-bit w/ Windows 7 HP

**Comment by gwarser** [comment]
This was also breaking strava.com settings page, but looks fixed now.
