### ISSUE TITLE
Dazn.com - Cookie notice

### ISSUE THREAD

**Issue by Nikimen16999999999** [ryanbr/fanboy-adblock#1070]
List the website(s) you're having issues:

https://www.dazn.com/it-IT/hom

Screenshot
Cookie-note at the bottom:
<a href="https://imgur.com/6sywO4R"><img src="https://i.imgur.com/6sywO4R.png" title="source: imgur.com" /></a>
What happens?

Cookie banner not blocked
List Subscriptions you're using:

fanboy's cookie list
Your settings

    OS/version: Win10
    Browser/version: Chrome 75.0.3770.100
    Adblock Extension/version: uBlock Origin 1.20.0

**Comment by Khrin** [comment]
Ciao, immagino che tu sia italiano. Ora penso che questa nota sia correttamente bloccata, aggiorna pure Cookie monster.
