### ISSUE TITLE
rp.pl [hidden video] [FCL / IDCACA / AA / PFRC]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#1071]
### List the website(s) you're having issues:
Example article link:
`https://www.rp.pl/Media-i-internet/311079936-Wlasciciele-Multimediow-wycofali-sie-z-transakcji-z-Vectra.html`

### What happens?

breakage - hidden video, the bug is nasty - 4 different anti-cookie list affected...
uszkodzenie - ukryte video, błąd jest sprośny - dotknięte są 4 różne listy ciasteczkowe... 

### List Subscriptions you're using:

uBO default +
Fanboy’s Cookie List
I don't care about cookies
AdGuard Annoyances
Polskie Filtry RODO-Ciasteczkowe

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 67.0.4 64bit / Opera 60 64bit
- Adblock Extension/version: uBlock Origin version: 1.20.1b1

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling affected lists</summary>

![rp1](https://user-images.githubusercontent.com/43844449/59919071-c7025e00-9426-11e9-8490-a399193ff98d.gif)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the lists</summary>

![rp3](https://user-images.githubusercontent.com/43844449/59919235-2d877c00-9427-11e9-8e39-71a18fdc2c64.gif)

</details>

<br>
<details not-open>
<summary>screenshoot 3 - after accepting/closing the message and reloading the page</summary>

![rp2](https://user-images.githubusercontent.com/43844449/59919148-fa44ed00-9426-11e9-9ff2-e27125b9b5fa.gif)

</details>

**Comment by ryanbr** [comment]
`+/rodo-agreement-popup/rodo-agreement-popup.min.js$domain=gremimedia.pl|rpkom.pl|zw.com.pl|parkiet.com`

Thats a block and not a whitelist? 

We're fine with ​"/rodo-agreement-" (comparing with the other commit).
