### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1075]
### List the website(s) you're having issues:

`https://youtube.com`

### What happens?

Terms of Service overlay

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3335370/Settings.txt)

### Your settings

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3335371/Settings.txt)

- OS/version: Windows 10
- Browser/version: Firefox 67.0.3
- Adblock Extension/version: uBlock Origin v1.20.0

### Other details:

<img width="1853" alt="45674754" src="https://user-images.githubusercontent.com/48647394/60277282-8e1e2980-98fd-11e9-9891-b9aabcaa3c7c.PNG">

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d5e09ee98ee7210c377b7b65cc3ba2258a210464

**Comment by krystian3w** [comment]
this is not cookie / GDPR bar - only Annoyance.
