### ISSUE TITLE
ideal.es

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#108]
anti adblock

`/adblocker/modal.`

same antiadblock on
```
ideal.es
hoy.es
elcorreo.com
larioja.com
elnortedecastilla.es
diariovasco.com
elcomercio.es
diariosur.es
lasprovincias.es
eldiariomontanes.es
laverdad.es
leonoticias.com
```
source https://forums.lanik.us/viewtopic.php?p=120420#p120420

**Comment by ryanbr** [comment]
Was added to Easylist spanish in this case, happy with that.

**Comment by SMed79** [comment]
Suggested here to be added to [Problematic-sites](https://forums.lanik.us/viewtopic.php?f=106&t=35815&hilit=problematic+sites+Anti+adblock+messages#p114372) filter list.

**Comment by ryanbr** [comment]
Okay I guess so, https://github.com/ryanbr/fanboy-adblock/commit/905ec1b1c9cd9b3439b1e05338dee74b83ba0058
