### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by Noruas29** [ryanbr/fanboy-adblock#1080]
Can't solve captcha when Fanboy's Enhanced Tracking List activated. Every websites.

**Comment by ryanbr** [comment]
given the lack of any details, closing.

**Comment by aurmil** [comment]
hello
which details do you need?
it is not possible anymore to valid a Google reCaptacha when Fanboy’s Enhanced Tracking List is enabled, on any site

**Comment by ryanbr** [comment]
If no one reads the templates when an issue report is created. I'm closing it.
