### ISSUE TITLE
Cookie banner not blocked: apps.derstandard.at

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1081]
### List the website(s) you're having issues:
`https://apps.derstandard.at`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.20.0

**Comment by ryanbr** [comment]
we can't block these types.
