### ISSUE TITLE
Cookie banner not blocked: impactpool.org

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1083]
### List the website(s) you're having issues:
`https://www.impactpool.org/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.20.0

**Comment by ryanbr** [comment]
Its blocked here; with the following filter ###cookies-banner
