### ISSUE TITLE
danbolig.dk cookie overlay

### ISSUE THREAD

**Issue by Mncdk** [ryanbr/fanboy-adblock#1084]
Seen on `https://www.danbolig.dk/bolig/bornholm/3720/villa/n09620-112`

### What happens?

There's a big central cookie consent overlay which is removed, but when it's initially loaded, it's "greying out" the site and removing the scroll bars (and ability to scroll, even with mousewheel), and this is not reversed, which renders the page less usable.

### List Subscriptions you're using:

Built-in (5/7)
    uBlock filters​
    uBlock filters – Badware risks​
    uBlock filters – Privacy​​​​​
    uBlock filters – Resource abuse​​​​​
    uBlock filters – Unbreak​​​​​

Ads (1/4)
    EasyList​

Privacy (1/3)
    EasyPrivacy​

Malware domains (4/4)
    Malvertising filter list by Disconnect​​​​​
    Malware Domain List​​​​​
    Malware domains​
    Spam404​

Annoyances (2/6)
    Fanboy's Cookie List​
    Fanboy’s Annoyance List​

Multipurpose (1/4)
    Peter Lowe’s Ad and tracking server list​

Regions, languages (1/36)
    NOR, DNK, ISL: Dandelion Sprouts nordiske filtre​

Custom (1/1)
    Schacks Adblock Plus liste

### Your settings

None of those other extensions names ring a bell, other than having read about them.

- OS: Win 10 1809 build 17763.557
- Browser/version: Firefox 67.0.4
- Adblock Extension/version: uBlock Origin v1.20.0

### Other details:

I disabled my filters one by one from the bottom, and reloaded the page each time. Only when disabling the `Fanboy's Cookie List​` did it stop removing the cookie overlay.

**Comment by ryanbr** [comment]
Fixed.
