### ISSUE TITLE
Breaks Last.fm

### ISSUE THREAD

**Issue by giogziro95** [ryanbr/fanboy-adblock#109]
### Issue

A filter in the Fanboy's Enhanced Tracking List is preventing a delete confirmation modal dialog from showing up in Last.fm inbox.

- Filter: `last.fm##div[style*="visibility:"]` ([line 1752](https://github.com/ryanbr/fanboy-adblock/blob/master/enhancedstats-addon.txt#L1752))
- Affected page: _https://www.last.fm/inbox_
- Blocked element CSS selector: `#j-popup-72766904_wrapper`

It's blocked because of the _visibility_ property inside the _style_ attribute of _div_ elements.

### Solution

Remove the filter; it's not a good practice to block elements on a domain by the existence of a single CSS property within the _style_ attribute of elements.

**Comment by ryanbr** [comment]
Filter was removed a while back.
