### ISSUE TITLE
AirFrance.* - Frozen pages (Fanboy's Annoyance List / Fanboy's Cookie List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1092]
### Affected sites:
```
https://www.airfrance.com/
https://www.airfrance.fr/
https://www.airfrance.gf/
https://www.airfrance.gp/
https://www.airfrance.mq/
https://www.airfrance.nc/
https://www.airfrance.pf/
https://www.airfrance.re/
```

### Issue:
The pages are frozen, due to a blocked GDPR consent, which needs to be accepted.

### Screenshots:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rules:
```
##.gdpr-agree
##.gdpr-container
##.gdpr-modal
```

### Possible fixes:
**Alternative 1:**
Remove the offending rules, as chances are that they have the same effect on all sites, wherever they might be applied!

**Alternative 2:**
```
airfrance.com,airfrance.fr,airfrance.gf,airfrance.gp,airfrance.mq,airfrance.nc,airfrance.pf,airfrance.re#@#.gdpr-agree
airfrance.com,airfrance.fr,airfrance.gf,airfrance.gp,airfrance.mq,airfrance.nc,airfrance.pf,airfrance.re#@#.gdpr-container
airfrance.com,airfrance.fr,airfrance.gf,airfrance.gp,airfrance.mq,airfrance.nc,airfrance.pf,airfrance.re#@#.gdpr-modal
```

### Note:
Also there is `##.gdpr-panel`, but I don't see the need to whitelist it, right off the bat.

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by Khrin** [comment]
Should be working now.

**Comment by THEtomaso** [comment]
Sure, but as I see it, `:not()` actually prevents the rules from being applied anywhere.
Why not simply delete them then?

**Comment by Khrin** [comment]
That's true, my bad.

**Comment by THEtomaso** [comment]
`:not(body)` did the trick! :)

**Comment by THEtomaso** [comment]
I have to reopen this issue..
Indeed `:not(body)` makes the site menus clickable, but unfortunately there's still a freezing issue which prevents page scrolling! :(

**Comment by krystian3w** [comment]
No block scroll?

**Comment by krystian3w** [comment]
```html
<body class="nav--home" style="overflow: hidden; position: fixed; width: 100%;">
```

so possible only exceptions for ABP / AdBlock.

**Comment by THEtomaso** [comment]
For the lists to be compatible with as many adblockers as possible, the best option might be to simply remove the rules all together.

**Comment by Khrin** [comment]
Bad idea.

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/commit/1661657ddbf204f9c6689f18ddd30ece3d486f66

@Khrin:
That's a lot of Air France URLs, but you forgot to include `airfrance.nc`.
:)

**Comment by Khrin** [comment]
Doesn't seems that also ```airfrance.gr``` is affected.

**Comment by THEtomaso** [comment]
> Doesn't seems that also `airfrance.gr` is affected.

Confirmed.
`airfrance.nc` is though.

**Comment by THEtomaso** [comment]
@Khrin:

I'm opening this issue back up again, because you did not include `airfrance.com` amongst the exceptions.
While AF's main `.com` page lacks page scrolling, this is not the case for some regional subpages.
For those pages, the freezing issue is a problem!

Examples:
```
https://www.airfrance.com/ci/
https://www.airfrance.com/cu/
https://www.airfrance.com/gn/
```

**Comment by Khrin** [comment]
Added, thank you.
