### ISSUE TITLE
www.google.fi - data privacy prompt not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1093]
### List the website(s) you're having issues:

`www.google.fi`

### What happens?

Data privacy prompt not blocked. I'm forced to accept it, otherwise I cannot use Google.

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Chrome 75.0.3770.100
- Adblock Extension/version: Ublock Origin 1.20.0

### Other details:

When I access `www.google.fi` I'm forcefully redirected to `https://www.google.fi/#cns=1`  where is the prompt. Here is a screenshot:

![google](https://user-images.githubusercontent.com/17256841/61030062-384d8500-a3c5-11e9-8f6b-6de80a441c57.png)

**Comment by peace2000** [comment]
That overlay can be blocked by using element picking tool but every time I block it, it will be replaced by another one...

`www.google.fi##.iD9H_hEg8GvE-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.ip5ijuaHc_OM-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.i86KsmKWftQ8-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.iWUV1e2j0z8o-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.iHWILgxDIy7I-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.imaWKlsrNJi4-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.iSR2e_SKdo5A-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.iJthGNaZGfos-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.iJUYkEGMIU7U-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.iIawQjsgV1fI-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.iNGwc5ia7Fmo-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`
`www.google.fi##.i_3HnnxVMDzI-NEtT1Mcs_w8.fAwjXaCTMo5__visible.m114nf.fAwjXaCTMo5__overlay`

**Comment by krystian3w** [comment]
www.google.fi##body > #lb > div[id^="_"][class]
www.google.fi##div[class][role="dialog"] > #cnsp:has(> div[class][aria-live="polite"])
www.google.fi##html.nsc:style(overflow-y: visible !important;)
www.google.fi##html:not(.nsc) > body.nsc:style(position: static !important; overflow-y: visible !important;)
www.google.fi##jsl > #consent-bump > .widget-consent
www.google.fi###main > #body ~ #footer > div[id] > div[id] > #fbar > .fbar > #cnsi > g-dialog > div[id^="_"][class^=" "]
www.google.fi###main > #lb > div[id^="_"][class] > div[class*="__overlay"]:not([id])
www.google.fi###main > #lb > div[id^="_"][class] > div[class*="__"]:has(iframe[src^="https://consent.google.com"])

**Comment by krystian3w** [comment]
Works fine for uBlock Origin / AdGuard / Nano Adblocker.
Few sites have blocked scrolling...

```
www.google.fi##body > #lb > div[id^="_"][class]
www.google.fi#?#div[class][role="dialog"] > #cnsp:-abp-has(> div[class][aria-live="polite"])

! for uBlock Origin / AdGuard / Nano Adblocker only!!!
www.google.fi##html.nsc:style(overflow-y: visible !important;)
www.google.fi##html:not(.nsc) > body.nsc:style(position: static !important; overflow-y: visible !important;)

www.google.fi##jsl > #consent-bump > .widget-consent
www.google.fi###main > #body ~ #footer > div[id] > div[id] > #fbar > .fbar > #cnsi > g-dialog > div[id^="_"][class^=" "]
www.google.fi###main > #lb > div[id^="_"][class] > div[class*="__overlay"]:not([id])
www.google.fi#?##main > #lb > div[id^="_"][class] > div[class*="__"]:-abp-has(iframe[src^="https://consent.google.com"])
```

**Comment by ryanbr** [comment]
Might not bother, just the problematic filters. little gain with changes of false positives.

**Comment by krystian3w** [comment]
`-abp-has(iframe[src^="https://consent.google.com"])` disable most FP.

cuted empty backgroud (overlay) IMO is on FP.

**Comment by peace2000** [comment]
krystian3w, I appreciate your effort but that consent screen still displays every time quickly and then goes away.

**Comment by krystian3w** [comment]
AdGuard policy no recomend faster filters: https://github.com/AdguardTeam/AdguardFilters/issues/30370#issuecomment-481803563

No body have years to see all google pop-ups, be create faster filter as with `-abp-has` syntax.

**Comment by peace2000** [comment]
Oh I messed something probably some of those filters were intended for ABP?

With these filters, I managed to block that consent on Ubo without an issue:

`google.fi##body > #lb > div[id^="_"][class]`
`google.fi##div[class][role="dialog"] > #cnsp > div[class][aria-live="polite"]`
`google.fi###main > #body ~ #footer > div[id] > div[id] > #fbar > .fbar > #cnsi > g-dialog > div[id^="_"][class^=" "]`
`google.fi###main > #lb > div[class] > div[class*="__"]`
`google.fi###main > #lb > div[id^="_"][class^=" "]`

! Scroll recover:
`google.fi#$#html.nsc {overflow-y: visible!important; }`
`google.fi#$#html:not(.nsc) > body.nsc {position: static!important; overflow-y: visible!important; }`

**Comment by krystian3w** [comment]
Locked scrolling is the biggest problem for ABP (after FP).


"`##html:not(.nsc)  > body:not(.nsc) ...`"

But this "construction" can slowdown filtering.

**Comment by krystian3w** [comment]
Google no give up, start use random classes and move pop-up:

```
www.google.com###main > #lb > div[id^="_"]:has(#cnsw > iframe[src*="://consent.google.com"])
www.google.com##html.QVCmK:style(overflow-y: visible !important;)
www.google.com###main > #lb > div:not([id]):not([class]):has(#cnsw > iframe[src*="://consent.google.com"])
 
www.google.com##body.QVCmK:style(position: static !important; overflow-y: visible !important;)
www.google.com###lb > div[id^="_"]:has(#cnskc)

**Comment by peace2000** [comment]
I cannot test this anymore as I stopped seeing that window. Removing cookies etc. does not bring it back nor does incognito window. I come back to this topic if some day it appears to me again. Thank you for your efforts.

**Comment by krystian3w** [comment]
Maybe back in 14 days, I suppose also no have cookies guilty generate pop-up.

**Comment by krystian3w** [comment]
Or try with parametr:

    https://www.google.if/#cns=1

AdGuard 3.x Remove parametr in Stealth Mode.

**Comment by peace2000** [comment]
I'm now with the same problem. But now the address is `https://www.google.fi`, I'm not redirected to `https://www.google.fi/#cns=1` as before.

**Comment by krystian3w** [comment]
I can't help it..., blocked scrolling so `EasyList Cookie` doesn't have much to cut out, because they don't plan to use syntax for uBlock Origin.

**Comment by peace2000** [comment]
For Ubo, these rules seem to do the trick reliably:

`google.*##+js(aeld, DOMContentLoaded, CONSENT)`
`google.*##+js(aeld, message, function(a){var d=a.data)`

**Comment by krystian3w** [comment]
For my first newer works, second need few test before publish in any list as stable/safe (wide range usage).

**Comment by peace2000** [comment]
Those are meant to be used together.

**Comment by krystian3w** [comment]
So for my both no works in my Firefox 82 (with `csp.enabled`=`false).

**Comment by krystian3w** [comment]
Fixed or too risky is copy ublock-user ideas (orgin author try found at reddit)  like scriptlets and html filtering.
