### ISSUE TITLE
www.gamefront.com

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1094]
`https://www.gamefront.com`

Social media links in right middle columb and footer:

- Facebook
- Intagram
- YouTube

> ![Screenshot_2019-07-12-10-42-52-1](https://user-images.githubusercontent.com/35370833/61115112-09e9ab80-a492-11e9-982d-958c46d23f66.png) |
> --- |

> ![Screenshot_2019-07-12-10-30-09-1](https://user-images.githubusercontent.com/35370833/61114799-61d3e280-a491-11e9-9625-c20d608485f5.png) |
> --- |

**Comment by ryanbr** [comment]
Not worth. But the ads, thats worth it.

https://github.com/easylist/easylist/commit/d4abef020cb93fdd534517ee236d39fce57ec6c7

Pretty sure there are many other sites like this.

**Comment by krystian3w** [comment]
So recover hiddeb two social buttons...

**Comment by krystian3w** [comment]
```
gamefront.com#@#.fa-twitter-square
gamefront.com#@#.fa-pinterest-square
``

**Comment by krystian3w** [comment]
> But the ads, thats worth it.

blocked faster in:

https://github.com/abp-filters/abp-filters-anti-cv/commit/60150d4e0c9bc579edd0a2cfbf3e21896ef2d227
