### ISSUE TITLE
jysk.no - Fanboy's Annoyance List

### ISSUE THREAD

**Issue by Rudolpher** [ryanbr/fanboy-adblock#1095]
# List the website(s) you're having issues:
`https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter`
(All guide/blog-pages tested, fail to load)

# What happens?
Believe the filter `###CookieConsent` from Fanboy's Annoyance List prevents loading of the actual articles(below the larger picture).
Either ways the only possible causes as I see it, are 6 filters from Fanboy's Annoyance List
`###social-share` `##.social-share` `##.site-social` `##a[href*="facebook.com/sharer/sharer.php?"]
` `##a[href^="https://www.facebook.com/sharer/sharer.php"]` 
`###CookieConsent`

I'm not knowledgeable enough to narrow it down further, just assuming the webmaster isn't so evil that articles are prevented from loading if Facebook-elements are blocked.

# Process of elimination:
Privacy Badger disabled
Open uBlock Origin logger - Toggle filtering: 'blocked'
Load page, text fails to load
Disable cosmetic filtering in uBlock Origin
Reload page, text loads correctly
Compare lists - 6 missing entries, all from Fanboy's Annoyance List

<details><summary>Logger output</summary>

```
+11
||cookieinformation.com^$third-party
--
jysk.no
3
script
https://policy.app.cookieinformation.com/f64e55/jysk.no/nb.js
```
```
+10
||cookieinformation.com^$third-party
--
jysk.no
3
frame
https://policy.app.cookieinformation.com/cookiesharingiframe.html
```
```
+10
googletagmanager.com/gtm.js
<<
jysk.no
script
https://www.googletagmanager.com/gtm.js?id=
```
```
+10
||googletagmanager.com/gtm.js$script
--
jysk.no
3
script
https://www.googletagmanager.com/gtm.js?id=
```
```
+10
no-cosmetic-filtering: jysk.no true
--
jysk.no
dom
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+10
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+1
##a[href^="https://www.facebook.com/sharer/sharer.php"]
jysk.no
dom
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+1
##a[href*="facebook.com/sharer/sharer.php?"]
jysk.no
dom
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+1
##.social-share
jysk.no
dom
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+1
##.site-social
jysk.no
dom
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+1
###social-share
jysk.no
dom
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+1
###CookieConsent
jysk.no
dom
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
```
+1
||cookieinformation.com^$third-party
--
jysk.no
3
script
https://policy.app.cookieinformation.com/f64e55/jysk.no/nb.js
```
```
+0
googletagmanager.com/gtm.js
<<
jysk.no
script
https://www.googletagmanager.com/gtm.js?id=
```
```
+0
||googletagmanager.com/gtm.js$script
--
jysk.no
3
script
https://www.googletagmanager.com/gtm.js?id=
```
```
+0
||cookieinformation.com^$third-party
--
jysk.no
3
frame
https://policy.app.cookieinformation.com/cookiesharingiframe.html
```
```
+0
https://jysk.no/guide/pleie-og-vedlikehold-av-dyner-og-puter
```
</details>

`||googletagmanager.com/gtm.js$script` comes from uBlock filters – Privacy

**Comment by THEtomaso** [comment]
Summary:

### Affected sites:
All of Jysk's domains.

### Example:
The same page that Rudolpher posted, but at their `co.uk` domain:
`https://jysk.co.uk/guide/care-and-maintenance-duvets-and-pillows/`

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.social-share`

Possible fix:
`daenischesbettenlager.at,daenischesbettenlager.de,jysk.al,jysk.am,jysk.ba,jysk.be,jysk.bg,jysk.by,jysk.ca,jysk.co.id,jysk.co.uk,jysk.com,jysk.com.cy,jysk.com.kw,jysk.com.mt,jysk.ch,jysk.cz,jysk.dk,jysk.ee,jysk.es,jysk.fi,jysk.fr,jysk.ge,jysk.gr,jysk.hr,jysk.hu,jysk.ie,jysk.it,jysk.kz,jysk.lt,jysk.lv,jysk.nl,jysk.md,jysk.me,jysk.mk,jysk.no,jysk.pl,jysk.pt,jysk.ro,jysk.rs,jysk.se,jysk.si,jysk.sk,jysk.ua,jysk.vn,jysk-ks.com,jyskthailand.com,pisiffik.gl,rumfatalagerinn.is,skemman.fo#@#.social-share`

**Comment by krystian3w** [comment]
No all jysk.pl works fine IMO.

**Comment by krystian3w** [comment]
https://jysk.pl/guide/jak-wybrac-zaslony-i-zaluzje

**Comment by krystian3w** [comment]
Fixed for Poland 🇵🇱:

https://github.com/MajkiIT/polish-ads-filter/blob/427ffbde47b5bd74ce78ccf757917f25456cbc42/adblock_social_filters/adblock_social_list.txt#L4481
