### ISSUE TITLE
Poland no blocked social

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1098]
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt

**Comment by ryanbr** [comment]
Not sure what this post is about, so closing.

**Comment by krystian3w** [comment]
Filters can by merged into here:

https://github.com/easylist/easylist/tree/master/fanboy-addon as extend block social links / buttons / widgets.
