### ISSUE TITLE
Alot of ads on http://dreamfilmhd.bz/ (Swedish website)

### ISSUE THREAD

**Issue by BourbonCrow** [ryanbr/fanboy-adblock#11]
Example of all the ads (Marked with red)
http://i.imgur.com/luf2H2q.jpg

The code below is what i used to remove them (could maybe be written better i dont know never done before but it blocks all it should and nothing it shouldn't.

```
! 4/27/2016, 7:39:34 AM http://dreamfilmhd.bz/ (removes all ads)
 dreamfilmhd.bz##.container  a[target="_blank"] > img

! 4/27/2016, 7:41:56 AM http://dreamfilmhd.bz/ (Div with grey box left over after ad removed from the line above http://i.imgur.com/kOAGMED.jpg)
 dreamfilmhd.bz##.container div[style^="background-color:rgba(0,0,0,0.1);width:750px;height:100px;max-width:100%;margin:0 5px 10px 8px"]

```

**Comment by SMed79** [comment]
add: https://forums.lanik.us/viewtopic.php?f=62&t=30046#p92417

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/25ff181afb21b23f3fd5f00028004aa2cc10738d
https://github.com/ryanbr/fanboy-adblock/commit/53245189f7c2ea21064277b3a2531ddd4c909529

**Comment by flyingzebras** [comment]
This will remove the new banner ad
`||dreamvtt.com/imagehost/data/uploads/users/c8bd9154-1306-4733-9432-a0cb0a88b4f4/2110187740.jpg$image`

**Comment by BourbonCrow** [comment]
This website have done it again and worse then ever.. like just when you click the search bar it closes it self and opens an ad window instead with like a cooldown of.. 15ish.. mins or so its some kind of js that is REALLY annoying hope you can block it

cant really give any details on how to cause i have no idea just wanted to report it

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=106861#p106861

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/f73e7c7bf190133b5e0b2a676b04c11eb1858caa
