### ISSUE TITLE
amazon account profile page broken

### ISSUE THREAD

**Issue by Antonius-git** [ryanbr/fanboy-adblock#110]
Affected link: e.g. https://www.amazon.co.uk/gp/profile/
Just get a page without anything useful on it. Narrowed it down to Fanboy's Enhanced Tracking List within ublock origin.

Had a similar issue recently on stocktwits.com (as per issue 107) but that was sorted a few days ago.
I think it's another 'cloudfront.net' related issue unless anything amazon related was recently changed/added?

The page has a connection to 'd1k8kvpjaf8geh.cloudfront.net' - blocking this with noscript without the filter results in the same effect.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/d739b9c5e72eb6feb32b781cffd1f4875fa77bc1

**Comment by Antonius-git** [comment]
Was just gonna say I narrowed it down further to 
`/\.cloudfront\.net/.*[a-zA-Z0-9]{45}/$script,third-party` as the culprit (with and without the 30 quantifier)
but `@@||cloudfront.net/gp/$script,third-party` certainly works as well!

Thanks very much :+1:
