### ISSUE TITLE
Cookiemonster makes sourceforge.net unscrollable

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1101]
### List the website(s) you're having issues:

`https://sourceforge.net/`

### What happens?

When Cookiemonster list blocks the gdpr notification, the site becomes also unscrollable.

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 68
- Adblock Extension/version: Ublock Origin 1.20.2

### Other details:

It seems this is caused by dom rules.

**Comment by llacb47** [comment]
Previously discussed here: https://github.com/NanoAdblocker/NanoFilters/issues/119#issuecomment-509315441

**Comment by THEtomaso** [comment]
From my location, I don't even get a GDPR warning @ SourceForge.

Nevertheless, is looks like 'AdGuard Annoyances filter' might contain rules that fixes this particular issue:

`https://github.com/AdguardTeam/AdguardFilters/commit/1fa469a127b3d07773471203f9123384dac35a53`

`https://github.com/AdguardTeam/AdguardFilters/commit/8de72b10de0b0e41c1332a9d0c618634867ffc94`

**Comment by krystian3w** [comment]
For me this no works https://github.com/AdguardTeam/AdguardFilters/commit/8de72b10de0b0e41c1332a9d0c618634867ffc94#diff-bf7d8dd0f863494a37580386cb5c1c28

 without scriplet https://github.com/AdguardTeam/AdguardFilters/commit/1fa469a127b3d07773471203f9123384dac35a53

Download counter stay at "5".
