### ISSUE TITLE
lonewolfonline.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1103]
### List the website(s) you're having issues:

`https://lonewolfonline.net`

### What happens?

cookie banner

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3398110/Settings.txt)

### Your settings

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3398111/Settings.txt)

- OS/version: Windows 10
- Browser/version: Firerfox 68.0
- Adblock Extension/version: uBlock Origin v1.20.2

**Comment by krystian3w** [comment]
`lonewolfonline.net###cookie`
