### ISSUE TITLE
neowin.net - adblock prompt added

### ISSUE THREAD

**Issue by thedjnK** [ryanbr/fanboy-adblock#1106]
### List the website(s) you're having issues:

`neowin.net`

### What happens?

Page banner pops up

### List Subscriptions you're using:

Fanboy annoyances

### Other details:

Domain that needs to be blocked `mdn.neowin.net`

**Comment by bug-rules** [comment]
@mapx- / @okiehsch

**Comment by THEtomaso** [comment]
..or simply `||neowin.net/js/mdn.neowin.js`

**Comment by bug-rules** [comment]
Added hard method:

`neowin.net##+js(abort-on-property-read.js, _sp_.mms.startMsg)`

As non default annoyance list.

**Comment by ryanbr** [comment]
Its fixed in Enhanced Trackers.

**Comment by bug-rules** [comment]
https://github.com/ryanbr/fanboy-adblock/blob/62f765db28fbf53d9903f34b6f9d71e1695a553e/enhancedstats-addon.txt#L543
