### ISSUE TITLE
Cookie banner not blocked: aphorismen.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1109]
### List the website(s) you're having issues:
`https://www.aphorismen.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.20.2

**Comment by krystian3w** [comment]
`##cookiebar`

Yes:

`<cookiebar> ... <cookiebar>`

**Comment by ryanbr** [comment]
Seems fine here. cookies element is blocked.

**Comment by krystian3w** [comment]
@bestoernesto  reinstall uBlock Origin or try use Firefox 68.0.1.
