### ISSUE TITLE
drudgereport.com

### ISSUE THREAD

**Issue by sterling101** [ryanbr/fanboy-adblock#111]
Since the July 9 update on the fanboy ultimate list, drudgereport.com will not load at all and gives the error:

Something interfered with this website loading

This could be a temporary problem with your network, or due to your adblocker

Try:

Check your internet connection and reload the page
If you are using an adblocker disable it by clicking on the adblock icon in your browser toolbar

**Comment by sterling101** [comment]
Additional investigation shows that easylist is being updated often to try to counter these issues. Apparently disabling javascript on this site solves the problem as well if the current easylist is not working.

**Comment by SMed79** [comment]
> Apparently disabling javascript on this site solves the problem

https://forums.lanik.us/viewtopic.php?p=119426#p119426

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3f9adb28f875d3709eb701a54f77331bc21b00d5
