### ISSUE TITLE
gartenjournal.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1110]
### List the website(s) you're having issues:

`gartenjournal.net`

### What happens?

blank page

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3415531/Settings.txt)

### Your settings

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3415532/Settings.txt)

- OS/version: Windows 10
- Browser/version: Firefox 68.0.1 
- Adblock Extension/version: uBlock Origin v1.20.2

### Other details:

the bad filter is `##.show-cookie-popup` from `Fanboy’s Annoyance List`
to fix this: `gartenjournal.net#@#.show-cookie-popup`

**Comment by krystian3w** [comment]
or:

`##.show-cookie-popup:not(body)`

---

`##.show-cookie-popup:not(body):not(html)`
