### ISSUE TITLE
cnet.com - popover video (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by hfiguiere** [ryanbr/fanboy-adblock#1111]
### List the website(s) you're having issues:

`https://www.cnet.com/news/five-details-about-adblock-plus-you-should-know-about/`
But happen with many other articles.

### What happens?

Autoplaying video shows in the bottom left corner (I have the harshest settings for that in Firefox so I only see the notification about autoplaying). Video is unrelated (ie not the what the article is about).

### List Subscriptions you're using:

ABP + EasyList + Fanboy's Annoyances

### Your settings

- OS/version: macOS 10.12
- Browser/version:  Firefox 68
- Adblock Extension/version: ABP 3.5.2

### Other details:

Here is the filter I added:
`||cnet3.cbsistatic.com/fly/js/pages/desktop/article_video*.js`

This block the script that implement the video. But it's a bit excessive as it break the rest of the video feature of the website. I call that a good trade off.

**Comment by ryanbr** [comment]
Yeah, if implemented, we'd get so many complaints but thanks for the suggestion.
