### ISSUE TITLE
warscrap.io

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1112]
### List the website(s) you're having issues:

`https://warscrap.io`

### What happens?

Javascript alert because the site `cookiebot.com` is blocked. When you close this error you are not able to play this game as guest.

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3427162/Settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firerfox 68.0.1
- Adblock Extension/version: uBlock Origin v1.20.2

### Other details:

<img width="888" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/61800046-939f5e80-ae2c-11e9-9344-11404e5fa566.PNG">

The filter `@@||cookiebot.com^$third-party,domain=warscrap.io` will fix this.

**Comment by krystian3w** [comment]
Bad, recover cookie bar?

**Comment by krystian3w** [comment]
`||consent.cookiebot.com/*/cc.js$script,domain=warscrap.io` this is needed IMO.
