### ISSUE TITLE
Moshi.com - Login blocked (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1113]
### Affected site:
`https://www.moshi.com/`

### Issue:
Login is blocked.

### How to reproduce:
1 - Click on the "**MENU**" button, in the top left corner.
2 - Click on "**Login / Create an Account**".

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`||apis.google.com/js/platform.js$third-party`

### Possible fix:
`@@||apis.google.com/js/platform.js$third-party,domain=moshi.com`

### Other problem filters (Referece only):
* AdGuard Social Media filter
https://github.com/AdguardTeam/AdguardFilters/issues/37423/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by krystian3w** [comment]
So no disable AdGuard Social and problem gone.
