### ISSUE TITLE
Cookie banner at https://pnbbanka.eu/

### ISSUE THREAD

**Issue by soshial** [ryanbr/fanboy-adblock#1117]
### List the website(s) you're having issues:

`https://pnbbanka.eu/`

### What happens?

Cookie banner not blocked

### List Subscriptions you're using:

fanboy's cookie list

### Your settings

- OS/version: MacOS 10.14.6
- Browser/version: Firefox 68.0.1
- Adblock Extension/version: uBlock Origin v1.21.2

**Comment by krystian3w** [comment]
`pnbbanka.eu##.cookie`

**Comment by krystian3w** [comment]
Also no blocked social in footer:

`##.footer-social-bar`

![obraz](https://user-images.githubusercontent.com/35370833/62423934-efd56e80-b6c7-11e9-97d2-40f658a98820.png) |
--- |

**Comment by soshial** [comment]
Thank you, guys!
