### ISSUE TITLE
Cookie banner not blocked: klett.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1118]
### List the website(s) you're having issues:
`https://www.klett.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.21.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f11958382bcc76bd707eb8a4fdc388ab2230b43e
