### ISSUE TITLE
elconfidencial.com

### ISSUE THREAD

**Issue by NubN** [ryanbr/fanboy-adblock#1119]
### List the website(s) you're having issues:

` https://www.vanitatis.elconfidencial.com/casas-reales/2019-07-27/marie-chevallier-quien-es-louis-ducruet-novia_2146859/ `

### What happens?

**Fanboy's Cookie List** is blocking content (images, system comment, popular post widget)

### List Subscriptions you're using:

· Default Settings
· Fanboy's Cookie List​​​​​
· spa, por: AdGuard Spanish/Portuguese​​​​​
· spa: EasyList Spanish​​​​​

### Adblocker and Browser Version

- OS/version: Windows 10
- Browser/version: Chrome 76.0.3809.87
- Adblock Extension/version:  uBlock Origin v1.21.6 & uBlock Extra

### Picture
· https://i.imgur.com/KlaaJ9K.png
· https://i.imgur.com/A3WReed.png

**Comment by ryanbr** [comment]
Thats the site, its broken on their end. I tested with Cookies disabled, still an issue as expected.
