### ISSUE TITLE
Travis-ci job log blocked

### ISSUE THREAD

**Issue by nkovacs** [ryanbr/fanboy-adblock#112]
This line blocks the job log on travis-ci.org:

https://github.com/ryanbr/fanboy-adblock/blob/d29894449458a4656302b8b6320f18190f95ab2f/enhancedstats-addon.txt#L990

I'm using uBlock Origin 1.13.2.
Here's an example page where this happens: https://travis-ci.org/yiisoft/yii2/jobs/251945922

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/7273d0887cb864f76b03a2374b628fca65ad2375

Temp fix till I find a better regex, maybe exclude non-hex chars as an option
