### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by injust** [ryanbr/fanboy-adblock#1120]
### List the website(s) you're having issues:
`dropbox.com`

### What happens?
`Download` and `Share` buttons are removed in file previews

### List Subscriptions you're using:
Fanboy's Annoyance List

### Other details:
Rule `/share_button.` is blocking `https://cfl.dropboxstatic.com/static/compiled/js/modules/clean/react/file_viewer/share_button.min-vfl8yhDaX.js`

**Comment by krystian3w** [comment]
duplicate of #959

**Comment by krystian3w** [comment]
Duplicate of #959

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5657993edef055083e8014bf6936d1165c764ff3
