### ISSUE TITLE
home.unicode.org

### ISSUE THREAD

**Issue by sjorford** [ryanbr/fanboy-adblock#1122]
### List the website(s) you're having issues:
`https://home.unicode.org/`

### What happens?
Modal dialog does not display, but the modal wrapper does

### List Subscriptions you're using:

uBlock filters​
uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
​​​​Fanboy's Cookie List​
​​​​
### Your settings

- OS/version: Windows 10 1803
- Browser/version: Firefox 68.0.1 64-bit
- Adblock Extension/version: uBlock Origin 1.21.2

### Other details:

Seems to be this filter:
`div[data-nconvert-cookie],`

How it displays with uBlock:
![image](https://user-images.githubusercontent.com/10633357/62632235-10046800-b92a-11e9-881d-ebbcb22ec78f.png)

How it displays without uBlock:
![image](https://user-images.githubusercontent.com/10633357/62632329-388c6200-b92a-11e9-86fc-de58d67ca8e2.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/65a9e56f4287f4e0d1a7afe69c3a2f0bdb45407c
