### ISSUE TITLE
BidOrBuy.co.za - Subscription settings blocked (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1123]
### Affected site:
`https://www.bidorbuy.co.za/`

### Issue:
Users are unable to access their subscription settings panel, because it's blocked.

### Problem filter:
* Fanboy's Annoyance List

### Problem rule:
`##.newsletterContainer`

### Possible fix:
`bidorbuy.co.za#@#.newsletterContainer`

### Screenshot 1 (Problem rule shown in uBO's logger):
![filterissue-bidorbuy1](https://user-images.githubusercontent.com/9382674/62634836-da19b080-b936-11e9-8f9d-da48d6fe3ed9.jpg)

### Screenshot 2 (Problem rule enabled):
![filterissue-bidorbuy2](https://user-images.githubusercontent.com/9382674/62634864-e3a31880-b936-11e9-8749-2c921645a4fa.jpg)

### Screenshot 3 (Problem rule disabled):
![filterissue-bidorbuy3](https://user-images.githubusercontent.com/9382674/62634894-eef64400-b936-11e9-9111-81b91c65cd6a.jpg)

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/dd8549e9c13b538cff7325efe98baed8aa541e7d
