### ISSUE TITLE
thewirecutter.com

### ISSUE THREAD

**Issue by TeardropOmen** [ryanbr/fanboy-adblock#1124]
### List the website(s) you're having issues:

`https://thewirecutter.com/`

### What happens?

The newsletter banner doesn't get blocked.

![Screenshot_2019-08-08 Wirecutter](https://user-images.githubusercontent.com/51370082/62664538-3e129800-b97c-11e9-9d2e-71b7e03a54c0.png)

### List Subscriptions you're using:

Fanboy Ultimate List

### Your settings

- OS/version: Windows 10 
- Browser/version: Firefox 68.0.1
- Adblock Extension/version: uBlock Origin v1.21.2

### Other details:

The class attribute changes sporadically.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1c779b384c34f254a024dc18e62aa2d98bdc85d8
