### ISSUE TITLE
us-store.acer.com

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1125]
### What happens?

Social icons on footer.

### List Subscriptions you're using:
Default + Fanboy's Social

### Your settings

- OS/version: Manjaro 18.0.4 Illyria
- Browser/version: Vivaldi 2.6.1566.49 (Stable channel) (64-bit)
- Adblock Extension/version: Nano Adblocker v1.0.0.123

### Other details:
![Screenshot_20190808_162723](https://user-images.githubusercontent.com/19818572/62711496-6e4c4c00-b9f9-11e9-8f12-1bc4c70674b0.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d614470e5bb1263ab7fda6ebd8b1df696b81fdfc

**Comment by hawkeye116477** [comment]
@ryanbr I didn't see that rule on `https://fanboy.co.nz/fanboy-social.txt`. Something broke on your side?
