### ISSUE TITLE
Dropbox.com [Issue #959/1120 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1126]
The wrong exception rule was added.

The rule that breaks the buttons now is this one (found in **Fanboys Annoyance List** / **Fanboys Social Blocking List**):
`/share_button.`
..like pointed out by krystian3w and injust in these posts:
https://github.com/ryanbr/fanboy-adblock/issues/959#issuecomment-519189759
https://github.com/ryanbr/fanboy-adblock/issues/1120/#issue-476684447

**Example:**
`https://www.dropbox.com/s/b8ejrqnv24xxfff/`

**Possible fix:**
`@@/share_button.$domain=dropbox.com`

**Note:**
That other exception rule doesnt't seem to be needed anymore.
This was pointed out by krystian3w here:
https://github.com/ryanbr/fanboy-adblock/issues/959#issuecomment-478170971

--

**EDIT:**
OK, there seems to be some weird stuff going on.
More info here:
https://github.com/ryanbr/fanboy-adblock/issues/1126#issuecomment-520179393

**Comment by krystian3w** [comment]
Older never added becasue nobody test closed issue?

And if good remeber network rule has ben deleted after report few bad block not social photos.

**Comment by krystian3w** [comment]
for some reasons bot fail generate new list: https://travis-ci.org/easylist/easylist/builds/570186496, maybe this is trouble.

**Comment by krystian3w** [comment]
`https://easylist.to/easylist/fanboy-social.txt` have added:

`@@||dropboxstatic.com/static/compiled/js/$script,domain=dropbox.com` and should works with Modern browsers (no tested PaleMoon 28 / Basilisk).

**Comment by THEtomaso** [comment]
> `https://easylist.to/easylist/fanboy-social.txt` have added:
> 
> `@@||dropboxstatic.com/static/compiled/js/$script,domain=dropbox.com`

I know, but like i pointed out; that exception rule doesnt't seem to be needed anymore.
The Dropbox buttons are blocked by `/share_button.` now!

**Comment by krystian3w** [comment]
So you have other path? as:

```
dropboxstatic.com/static/compiled/js/modules/clean/react/file_viewer/
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```



 `/file_viewer/share_button.min-vflSBcq8X.js` have string `/share_button.`

IMO better unlock all folder as long no unlock ads / tracking.
Then you don't have to check every ~4 months what has changed in the Dropbox files.

**Comment by THEtomaso** [comment]
What the hell!?..
I get `dropboxstatic.com/static/compiled/js/modules/clean/react/file_viewer/share_button.min-vflSBcq8X.js` too now!
It must have been different earlier, since `@@||dropboxstatic.com/static/compiled/js/$script,domain=dropbox.com` didn't work at my end.
Therefore, I think something like `@@/share_button.$domain=dropbox.com` is a better solution in this case, as it specifically targets the blocking rule, and will cover every potential alternate URLs!

**Comment by krystian3w** [comment]
> What the hell!?.. I get `...` too now!

Maybe uBO download filter from: `https://easylist.to/easylist/fanboy-social.txt` 
if you not put exception in "My filters Panel".

these mirrors, now no have added few filters - something broken or have too much cache refresh time?

https://easylist-downloads.adblockplus.org/fanboy-social.txt
https://fanboy.co.nz/fanboy-social.txt

**Comment by THEtomaso** [comment]
No, I confirmed that the exception rule was present, before testing!

**Comment by krystian3w** [comment]
Bug with broken mirror is fixed? All have exception but on based on file name (still path):


![obraz](https://user-images.githubusercontent.com/35370833/63215170-f8479380-c122-11e9-8d0d-97d8d31694f3.png) |
--- |

**Comment by THEtomaso** [comment]
I'm closing this, for now.

When testing this particular issue last week, I was troubleshooting this other thing simultaneously:
`https://forum.palemoon.org/viewtopic.php?f=29&t=22714/`

There's a chance that messing around with cache files might have played a trick on me!
