### ISSUE TITLE
Cookie banner at https://www.blueorangebank.com/

### ISSUE THREAD

**Issue by soshial** [ryanbr/fanboy-adblock#1127]
### List the website(s) you're having issues:

`https://www.blueorangebank.com/`

### What happens?

Cookie banner not blocked

### List Subscriptions you're using:

fanboy's cookie list

### Your settings

- OS/version: MacOS 10.14.6
- Browser/version: Firefox 68.0.1
- Adblock Extension/version: uBlock Origin v1.21.2

**Comment by krystian3w** [comment]
No fixable in `fanboy's cookie list`. Because website block scrolling.

No see script or CSS file to block by network file. Block all inline-script can break site.

---

@mapx- / @okiehsch?

```
blueorangebank.com###GDPR-modal, .modal-backdrop
blueorangebank.com##body:style(overflow: auto !important; padding: 0 !important;)
```

If nope, I try found this in AdGuard Annoyance.

**Comment by mapx-** [comment]
annoyances list
