### ISSUE TITLE
Amazon EC2 console broken

### ISSUE THREAD

**Issue by eriksw** [ryanbr/fanboy-adblock#113]
The `/\.cloudfront\.net\/[\w\/\-.+]{90,}/$script,third-party` rule is blocking scripts needed by the Amazon EC2 console:

* `https://d3h6vjalfnzkit.cloudfront.net/35165b794f43cf7e1f925d3b79ef2c9982cf4dc3/ec2/deferredjs/45B554EA56F1BD667839246C67D2DE00/15.cache.js` (from `console.aws.amazon.com`)

*   `https://d1gmaa4bv8uttx.cloudfront.net/35165b794f43cf7e1f925d3b79ef2c9982cf4dc3/ec2/deferredjs/45B554EA56F1BD667839246C67D2DE00/15.cache.js` (from `us-west-2.console.aws.amazon.com`)

Note: The cloudfront domain varies by which region you're looking at.

**Comment by ryanbr** [comment]
Does this help?

https://github.com/ryanbr/fanboy-adblock/commit/47a0b38a295a09b42bbe2a11bf2b8ec1fe17bd09

**Comment by eriksw** [comment]
Yes, WFM.
