### ISSUE TITLE
Cookie banner not blocked: onb.ac.at

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1131]
### List the website(s) you're having issues:
`https://www.onb.ac.at`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.21.2

**Comment by krystian3w** [comment]
`www.onb.ac.at##.notification-wrapper`
