### ISSUE TITLE
White screen on dollartree.com with annoyance list enabled

### ISSUE THREAD

**Issue by nl255** [ryanbr/fanboy-adblock#1132]
### List the website(s) you're having issues:
`https://www.dollartree.com/`

### What happens?

Blank white screen immediately on visting

### List Subscriptions you're using:

Fanboy's Annoyance List​​​​​​​​​  

### Your settings

Nano Defender on both the latest Waterfox and Chromium (SRware Iron fork) on Windows 10.

### Other details:

After checking each list one at a time using the half method (disable half the lists, check, then either enable half of the ones that were disabled or disable half of the ones that weren't disabled the first time, and repeating) to determine which one was responsible I confirmed that it was Fanboy's Annoyance List​​​​​​​​​ by disabling every other list except that one.

This exception filter makes the site work again but also brings back the "back to top" button.

`@@||www.dollartree.com/file/v2260504050890677683/global/backToTop.min.js$script,domain=www.dollartree.com`

**Comment by Khrin** [comment]
Page is blank for me even disabling all lists. I can only guess they're running into some difficulties.

**Comment by llacb47** [comment]
The page works if you wait 15 seconds after load
