### ISSUE TITLE
Krefting.de - Frozen page (Fanboy's Annoyance List / Fanboy's Cookie List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1137]
### Affected site:
`http://www.krefting.de/`

### Issue:
Blocked GDPR consent results in frozen page, covered by a modal backdrop.

### Screenshots:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`###cookieNote`

### Possible fix (allowing the popop):
`krefting.de#@##cookieNote`

### Note:
As a workaround, simply refreshing the page works too.
The issue should be fixed regardlessly though.

### Other problem filters:
* I don't care about cookies (*reported*)

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by kiboke** [comment]
Thank you, I'll modify IDCAC filter list, it will not hide this cookie warning.
