### ISSUE TITLE
mr-bricolage.fr

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#114]
Hi,

`mr-bricolage.fr` force an overlay geolocation http://i.imgur.com/aX7HO7J.png

`||mr-bricolage.fr/shop/index/popin/`

`https://www.mr-bricolage.fr/` ([#p120904](https://forums.lanik.us/viewtopic.php?p=120904#p120904))

**Comment by ryanbr** [comment]
I don't think its a good idea to hide geo questions, since it might break or limit things.
