### ISSUE TITLE
Medium.com

### ISSUE THREAD

**Issue by And96** [ryanbr/fanboy-adblock#1141]
### List the website(s) you're having issues:

https://medium.com

### What happens?

Annoying message, on every page.
> To make Medium work, we log user data. By using Medium, you agree to our Privacy Policy, including cookie policy.

### List Subscriptions you're using:

Fanboy's Cookie List​​​​​ in uBlock Origin
### Your settings

- OS/version: Android
- Browser/version: Firefox 68.0.2
- Adblock Extension/version: uBlock Origin 1.21.2

### Other details:

Login to medium not required.

The message is on every article, home page and section.

Here is a screenshot

![IMG_20190824_085122](https://user-images.githubusercontent.com/42185838/63633680-6e308b00-c64c-11e9-9db7-6264911a2357.jpg)

**Comment by ryanbr** [comment]
Not the best filter, but medium has a nice case of making (really) random css elements.
