### ISSUE TITLE
m.spiegel.de "Open with app" banner

### ISSUE THREAD

**Issue by KAMiKAZOW** [ryanbr/fanboy-adblock#1142]
### List the website(s) you're having issues:

`https://m.spiegel.de`

### What happens?

Website displays a banner on mobile to open the app instead.

### List Subscriptions you're using:

Fanboy Annoyances

### Your settings

- OS/version: Android 9
- Browser/version: Firefox 68.0.2
- Adblock Extension/version: ABP 3.6.3

### Other details:

![Screenshot](https://user-images.githubusercontent.com/3259076/63634582-ce2d2e80-c658-11e9-91b4-96a6675c79f3.png)

**Comment by ryanbr** [comment]
Has been resolved, thanks.
