### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by Hakatitla** [ryanbr/fanboy-adblock#1143]
`theverge.com`

Cookie warning

### List Subscriptions you're using:

Fanboy's Cookie List​​​​​

### Your settings
- OS/version: win10
- Browser/version: FF latest
- Adblock Extension/version: uBlock Origin v1.21.2

**Comment by Khrin** [comment]
AFAIK it can't removed due to some issues with videos and other site features.

**Comment by krystian3w** [comment]
Still cookies neeed accept.

**Comment by Hakatitla** [comment]
@Khrin ok
