### ISSUE TITLE
##.cdk-overlay-pane - Breaks all angular/material websites

### ISSUE THREAD

**Issue by JohannesBe** [ryanbr/fanboy-adblock#1144]
### List the website(s) you're having issues:

Any site using angular material, e.g.
https://material.angular.io/components/select/examples

### What happens?

The angular material elements have custom implementations of most form elements. An example is the `select` combobox. These elements are rendered on a global overlay-div, with the class `.cdk-overlay-pane`. 

### List Subscriptions you're using:

- My filters‎
- uBlock filters‎
- uBlock filters – Privacy‎
- ABP Anti-Circumvention Filter List‎
- Adblock Warning Removal List‎ 
- Adguard Base Filters‎
- Anti-Adblock Killer | Reek‎
- EasyList‎
- Peter Lowe’s Ad server list‎
- Cryptocurrency (Bitcoin) Mining Protection List‎
- EasyPrivacy‎
- Fanboy's Enhanced Tracking List‎
- Adguard’s Annoyance List‎
- Anti-ThirdpartySocial
- Dan Pollock’s hosts file‎ 
- Fanboy+Easylist-Merged Ultimate List‎ 
- hpHosts’s Ad and tracking servers‎ 
- MVPS HOSTS‎
- EU: Prebake - Filter Obtrusive Cookie Notices
- NLD: EasyList Dutch‎ 

### Your settings

- OS/version: Arch linux
- Browser/version: Firefox Nightly, 70.0a1 (2019-07-14) (64-bit)
- Adblock Extension/version: Ublock origin 0.9.5.20

### Other details:

I found that in https://fanboy.co.nz/fanboy-annoyance.txt the following was present:

    ##.cdk-overlay-pane

You can see that this is actually very deeply ingrained in angular over here:
https://github.com/angular/components/blob/d48b1baa3d4dd337ac74de8260daeefa526af5ba/src/cdk/overlay/overlay.ts#L95

And if you [search for it](https://github.com/angular/components/search?q=cdk-overlay-pane&unscoped_q=cdk-overlay-pane) in the angular components repository you have over 10 matches.

**Comment by tbunique** [comment]
Just noticed this, the website I'm developing suddenly wasn't working correctly anymore.

**Comment by YuriHoogeweg** [comment]
Also just came across this. Wasted a couple of hours trying to debug my Material dialogs... (e.g. clicking 'Pick one' on https://material.angular.io/components/dialog/overview) 
Had to disable both Fanboy’s Annoyance List and Fanboy’s Cookie List

**Comment by ElegyD** [comment]
Same issue on Chrome, especially with dropdown menus from various Google/Material/Firebase websites.

### List the website(s) you're having issues:

`https://material.io/resources/icons/?icon=3d_rotation&style=baseline`

### What happens?

Dropdown menus not working

### List Subscriptions you're using:

- Default uBlock Origin Lists
- DEU: EasyList Germany​​​​​
- [Nano filters](https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin)

### Your settings

- OS/version: macOS 10.14.6
- Browser/version: Chrome 76.0.3809.132
- Adblock Extension/version: uBlock Origin 1.21.6

**Comment by Chiron1991** [comment]
This is breaking our Angular Material website. The `##.cdk-overlay-pane` selector seems to be way too generic.
