### ISSUE TITLE
Cookie banner not blocked: pcwelt.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1147]
### List the website(s) you're having issues:
`https://www.pcwelt.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.20.0

**Comment by krystian3w** [comment]
Similar #1145 

---

Another similar:

`http://www.skynews.com/`
`https://news.sky.com/`

**Comment by krystian3w** [comment]
@llacb47 you see domains to block or reddirect / rewrite ("`ewrite=abp-resource:blank-js`")?

**Comment by krystian3w** [comment]
Similar:

* #1145 - rewrite recommend to no detect block file faster
* #1150

--

@llacb47 you see domains to block or redirect / rewrite ("`rewrite=abp-resource:blank-js`")?

**Comment by krystian3w** [comment]
Similar:

* #1145 - rewrite recommend to no detect block file faster
* #1150

---

@llacb47 you see domains to block or redirect / rewrite ("`rewrite=abp-resource:blank-js`")?
