### ISSUE TITLE
newonce.net [social breakage] [anti-adblock]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1149]
`https://newonce.net/2019/08/polski-rap-i-lo-fi-przedstawiamy-5-najciekawszych-przykladow/`

---

hidden share as long link (copy-paste manualy anywhere) / e-mail above article:

Fix:

`newonce.net#@#.post__social-item`

effect:

![obraz](https://user-images.githubusercontent.com/35370833/64067989-fb1daa80-cc31-11e9-8485-9526b7a76663.png) |
--- |

---

Also you can fix anti-adblock:

![obraz](https://user-images.githubusercontent.com/35370833/64068057-ebeb2c80-cc32-11e9-9c1f-fe31e67a1c48.png) |
--- |

fix:

`newonce.net#@##adsense`

**Comment by hawkeye116477** [comment]
Fanboy hides share link through mail, this is not a bug.

**Comment by krystian3w** [comment]
Once repair mail share.

**Comment by krystian3w** [comment]
Also maybe add filter into `Fanboy's Enhanced Tracking List`?

**Comment by hawkeye116477** [comment]
It is many others generic like this `##.social-link-email`, so rather it's not a bug, it's feature :smile:
