### ISSUE TITLE
Rule breaking Jira

### ISSUE THREAD

**Issue by fabiocatalao** [ryanbr/fanboy-adblock#115]
This rule is breaking Atlassian Jira:
`/\.cloudfront\.net\/[\w\/\-.+]{90,}/$third-party,script,domain=~amazon.com`
Is it possible to add an exception on **Fanboy’s Enhanced Tracking List** for to fix it?

**Comment by ryanbr** [comment]
whats the full url being blocked?

**Comment by fabiocatalao** [comment]
There are some scripts that are being blocked such as:
- https://d2vj1jlnoa5x8o.cloudfront.net/byside.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-m5nevv/b/c/827490b7b225b9b9dcc1791bf339fc8b/_/download/batch/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-init/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-init.js
- https://d2vj1jlnoa5x8o.cloudfront.net/byside.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-m5nevv/b/c/34fe461144f62d8b3eb7b74d1b2294cd/_/download/batch/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-js/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-js.js

**Comment by fabiocatalao** [comment]
There are some scripts that are being blocked such as:

https://d2vj1jlnoa5x8o.cloudfront.net/mycompany.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-m5nevv/b/c/827490b7b225b9b9dcc1791bf339fc8b/_/download/batch/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-init/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-init.js
https://d2vj1jlnoa5x8o.cloudfront.net/mycompany.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-m5nevv/b/c/34fe461144f62d8b3eb7b74d1b2294cd/_/download/batch/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-js/com.atlassian.plugins.atlassian-plugins-webresource-plugin:bigpipe-js.js

**Comment by ryanbr** [comment]
okay, disabled the filter. Will Look for a better solution/regex.

**Comment by fabiocatalao** [comment]
Ok, thanks! :)
