### ISSUE TITLE
skynews.com

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1150]
```
http://www.skynews.com/
https://news.sky.com/
```

no blocked privacy policy.

![obraz](https://user-images.githubusercontent.com/35370833/64068247-d75c6380-cc35-11e9-9968-9757444f42ac.png) |
--- |

Fix by @llacb47: https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-526766515

```
||consensu.org^$domain=sky.com
||mms.cmpsky.com^$domain=sky.com
```

**Comment by llacb47** [comment]
Consensu already in cookie monster, so I think only
`||mms.cmpsky.com^$third-party`
should be added.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9650d9edf48d12facf3bd00e9ac01118cfd0acac
