### ISSUE TITLE
Does not block the Reddit cookie notice

### ISSUE THREAD

**Issue by Noexpert** [ryanbr/fanboy-adblock#1152]
At the moment I'm using the ublock with Fanboy's Cookie List which does not seem to block the Reddit cookie notice.

I'm aware the issue was raised here too: https://github.com/ryanbr/fanboy-adblock/issues/882

On mobile, blocking works if I manually add `##.EUCookieNotice_content`.
I've not figured out how to block it on desktop yet.

Thanks

**Comment by krystian3w** [comment]
Too random, please use for this `AdGuard Annoyance` in uBO / AdGuard.

**Comment by krystian3w** [comment]
```
reddit.com#?##SHORTCUT_FOCUSABLE_DIV > div > div[class*=" "]:-abp-has(div[role="dialog"][aria-modal]:empty)
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8063b37867575c83ed8d5180bfbe38aef3504cdf

**Comment by Noexpert** [comment]
Hi @ryanbr 

thanks for the commit.
This works on desktop but I think we still need the mobile specific one (`##.EUCookieNotice_content`) as I can still see the notice on my phone.

**Comment by Khrin** [comment]
Please look better. It was added in the next commit above your message.

**Comment by Noexpert** [comment]
Hi @Khrin 

I can see `##.EUCookieNotice_content` in my `fanboy_cookie_general_block.txt` list but when I visit Reddit on my mobile for some reason I can still see the notice.

Could you please check whether it works at your end?

Thanks

**Comment by krystian3w** [comment]
Try uBO logger maybe someone add generichide for github or use: `#@##EUCookieNotice_content`
