### ISSUE TITLE
ura.barona.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1153]
### List the website(s) you're having issues:

`https://ura.barona.fi/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 68.0.2
- Adblock Extension/version: Ublock Origin 1.21.2

### Other details:

Can be blocked by a general rule:

`##.cookie-notification-box`

**Comment by krystian3w** [comment]
Because need login.

**Comment by krystian3w** [comment]
`https://barona.fi/`

`##.some-icon-share`
