### ISSUE TITLE
chobani.com

### ISSUE THREAD

**Issue by jo2dan23** [ryanbr/fanboy-adblock#116]
@@||chobani.com/js/views/newsletter-signup.js

fixes page

http://www.chobani.com/products/fruit-on-the-bottom#banana

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&p=121131

**Comment by jo2dan23** [comment]
Both filters are needed. Just didnt know if you use the forum anymore

**Comment by jo2dan23** [comment]
Oh your not fanboy

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4a20257f16093c621fa4b24090f560c4332a7ce5
