### ISSUE TITLE
vapaasana.swedishforum.net - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1160]
### List the website(s) you're having issues:

`http://vapaasana.swedishforum.net`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock Origin 1.22.0

### Other details:

-

**Comment by ryanbr** [comment]
Screenshot? I'm not seeing this @peace2000

**Comment by peace2000** [comment]
![Näyttökuva (82)](https://user-images.githubusercontent.com/17256841/67633116-77401180-f8b4-11e9-8e5f-183a8aa26989.png)

Here is a screenshot.

It can be blocked by using a site based cosmetic filter `vapaasana.swedishforum.net###aARi3603nsfz3w`

**Comment by krystian3w** [comment]
`##.conteneur_layout_IE > div[id]:nth-of-type(2)`

?

**Comment by peace2000** [comment]
@krystian3w Thank you but it doesn't work on subpages : `http://vapaasana.swedishforum.net/f24-yllapito-ja-saannot`

**Comment by krystian3w** [comment]
For my is visible on "homepage" only.

**Comment by krystian3w** [comment]
`###redirect_rgpd:nth-ancestor(4)` or 
`###close_rgpd:nth-ancestor(4)` or  
`###accept_rgpd:nth-ancestor(4)`

but for uBO only (maybe for AdGuard 3.4/4.X if added support `:xpath(../../../..)`)

---

construction with has:

`vapaasana.swedishforum.net#?#div[id]:not([class]):-abp-has(#close_rgpd)`

or

`vapaasana.swedishforum.net#?#div[id]:nth-of-type(2):not([class]):-abp-has(> div > ul > li > #close_rgpd)`

**Comment by peace2000** [comment]
Maybe @ryanbr wants to maintain abp and ubo compability at the same time. :) `###accept_rgpd:nth-ancestor(4)` worked fine on the home page and on the subpages where I tested.

**Comment by krystian3w** [comment]
Nope for ABP try `Has` construction (under HR).

**Comment by ryanbr** [comment]
Does this work?

`vapaasana.swedishforum.net##.conteneur_minwidth_IE > .conteneur_layout_IE > div:not([class])`

**Comment by krystian3w** [comment]
First nope.

Second works.

---

For subpages @kiboke used generic:

   ##.conteneur_minwidth_IE ~ style:not([type]) + div[id]

**Comment by peace2000** [comment]
`vapaasana.swedishforum.net##.conteneur_minwidth_IE > .conteneur_layout_IE > div:not([class])` This works only for the front page.

This works only for subpages: `vapaasana.swedishforum.net##.conteneur_minwidth_IE ~ style:not([type]) + div[id]`

So both of those two filters are needed in order to fix this issue. Both of them work on Ubo & Abp.

(Sidenote: this page is a Finnish one, even though part of the domain name contains word "swedish").

**Comment by krystian3w** [comment]
`##div[class^="conteneur"][class$="IE"] ~ div[id]:not(class)`

Also cut both I no see cut too much elements.

**Comment by krystian3w** [comment]
`##div[class^="conteneur"][class$="IE"] ~ div[id]:not([class])`

or

```
##div[class^="conteneur"][class$="IE"] ~ style ~ div[id]:not([class])
```

Also cut both - I no see cut too many elements as FP.

**Comment by peace2000** [comment]
I made this topic when I didn't do any pull reqs yet. Thanks for these ones, I'll make a pull req.

All these three rules:

`vapaasana.swedishforum.net#?#div[id]:not([class]):-abp-has(#close_rgpd)`
`##div[class^="conteneur"][class$="IE"] ~ div[id]:not([class])`
`##div[class^="conteneur"][class$="IE"] ~ style ~ div[id]:not([class])`

Do work alone to block that cookie element on the front and on the subpages. To be honest those syntaxes are a bit too advanced to mee to actually fully understand them, but I'll pick the first one because it feels safest for me. (I could be wrong, this is just a guess within my limited understanding.)

**Comment by krystian3w** [comment]
Speed better analyze with devtools.

**Comment by peace2000** [comment]
> Speed better analyze with devtools.

You mean that those rules that you gave, are faster?
