### ISSUE TITLE
www.kotimaa24.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1161]
### List the website(s) you're having issues:

`https://www.kotimaa24.fi`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock Origin 1.22.0

### Other details:

-

**Comment by krystian3w** [comment]
`###kotimaa-cookie-notification` ...

**Comment by peace2000** [comment]
I realized that a general and better filter could be made:

`##[id*="cookie-notification"]`

@ryanbr
