### ISSUE TITLE
Cookie List preventing account.arena.net from loading

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [ryanbr/fanboy-adblock#1163]
https://account.arena.net/login

I get a blank white page.  However if I disable Fanboy's Cookie List the site appears.

I believe this is related to account.staticwars.com  because when I go to allow that it works.

**Comment by krystian3w** [comment]
@kiboke you also broke site, I have blank withe page.

**Comment by krystian3w** [comment]
"FIX"

`@@/cookie-notification$script,domain=account.arena.net`

**Comment by kiboke** [comment]
> @kiboke you also broke site, I have blank withe page.
> 
> `/services/2bumpers/gen/cookie-notification`
> 
> this is bad generic.

Thank you, I'll fix it!
