### ISSUE TITLE
Ellen Page sites - Blocked images (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1164]
### Affected sites:
```
https://www.ellen-page.net/
https://www.ellenpage.org/
https://www.ellenpageonline.com/
```

### Issue:
Blocked images.

### Examples:
```
https://www.ellen-page.net/gallery/index.php?cat=112
https://www.ellenpage.org/gallery/index.php?cat=112
https://www.ellenpageonline.com/gallery/index.php?cat=112
```

### Screenshots:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`/socialmedia/*$image,script`

### Possible fix:
`@@/gallery/albums/socialmedia/$image,domain=ellen-page.net|ellenpage.org|ellenpageonline.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by ryanbr** [comment]
I just removed the filter, seems too generic.
