### ISSUE TITLE
www.123pelit.com - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1166]
### List the website(s) you're having issues:

`https://www.123pelit.com/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock Origin 1.22.0

### Other details:

-

**Comment by krystian3w** [comment]
All domains Poki Company have this crap @ryanbr  / @khrin

```
poki.at
poki.be
poki.by
poki.cn
poki.co.il
poki.com
poki.com.br
poki.com/ar
poki.com/id
poki.com/kr
poki.com/ru
poki.com/th
poki.com/ua
poki.cz
poki.de
poki.dk
poki.gr
poki.it
poki.jp
poki.nl
poki.no
poki.pl
poki.pt
poki.ro
www.1001oyun.com
www.123pelit.com
www.hrajhry.sk
www.jeuxjeuxjeux.ch
www.jeuxjeuxjeux.fr
www.megajatek.hu
www.megaspel.se
www.moiteigri.com
www.paisdelosjuegos.cl
www.paisdelosjuegos.co.ve
www.paisdelosjuegos.com.ar
www.paisdelosjuegos.com.co
www.paisdelosjuegos.com.do
www.paisdelosjuegos.com.ec
www.paisdelosjuegos.com.mx
www.paisdelosjuegos.com.pa
www.paisdelosjuegos.com.pe
www.paisdelosjuegos.com.uy
www.paisdelosjuegos.cr
www.paisdelosjuegos.es
www.spielyeti.ch
www.trochoi.net
```

please no fix by 1 domain but for fix for ~40 domains.

**Comment by krystian3w** [comment]
1 letter class is not stable, maybe can changed in 14 - 30 days cycles.
