### ISSUE TITLE
www.linnunrata.org - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1168]
### List the website(s) you're having issues:

`https://www.linnunrata.org/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock Origin 1.22.0

### Other details:

-

**Comment by ryanbr** [comment]
Hopefully this helps.

**Comment by peace2000** [comment]
I confirm as a working solution.
