### ISSUE TITLE
kotimikro.fi - separate cookie info subpage wrongly blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1171]
### List the website(s) you're having issues:

`https://kotimikro.fi/`
exact link: `https://kotimikro.fi/evastepolitiikka`

### What happens?

Separate cookie info subpage does not work.

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock Origin 1.22.2

### Other details:

Fixing filter:

`@@||cookieinformation.com/$script,domain=kotimikro.fi`

Fanboy's cookielist blocks correctly cookie info message but that separate subpage that tells about the site cookie usage, should not be blocked.

**Comment by ryanbr** [comment]
`that tells about the site cookie usage`

Why should we care or the end user care? If they're only just after the article..

**Comment by peace2000** [comment]
Isn't the idea of this list just to block cookie messages and notifications? That separate subpage is a legit article and I don't see why the access to that article should be blocked. Whitelisting that subpage doesn't bring any visible popups or notifications anywhere.

**Comment by ryanbr** [comment]
Most sites will have a /cookiedisclaimer/ /cookies/ etc folder, and we'll have false positives there. Just not worth creating yet more element whitelisting. 

Example; `https://www.hotpoint.co.uk/Pages/Cookie-Disclaimer`  Fixing all the cookie subdomains would just bloat the list.

**Comment by peace2000** [comment]
All right. I'll close this then.
