### ISSUE TITLE
enumizmatyczny.pl [social] [breakage]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1172]
Hidden icon on login button by FB:

`https://enumizmatyczny.pl/logowanie`

![obraz](https://user-images.githubusercontent.com/35370833/64633332-4fc3e100-d3fb-11e9-9a56-8f9bcfafbfdd.png) |
--- |

by:

`/img/*facebook.png$domain=~github.io`

URL:

```
https://enumizmatyczny.pl/modules/hifacebookconnect/views/img/icons/xfacebook.png.pagespeed.ic.wGUARGAhyn.png
```

fix:

`@@||enumizmatyczny.pl/modules/hifacebookconnect/views/img/icons/$image`

**Comment by ryanbr** [comment]
Okay, seems logical. probably the best filter.
