### ISSUE TITLE
www.virustotal.com - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1173]
### List the website(s) you're having issues:

`https://www.virustotal.com/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock Origin 1.22.2

### Other details:
-

**Comment by ryanbr** [comment]
I'm not  seeing this, even from an .eu IP

**Comment by peace2000** [comment]
![Näyttökuva (83)](https://user-images.githubusercontent.com/17256841/67633368-bfacfe80-f8b7-11e9-83c5-4a88b722b2f5.png)

@ryanbr It's there as the screenshot shows. @krystian3w saw it also.

I tried virustotal.com through US and Indonese proxies and still got that cookie message. It looks like the displaying of the cookie message is not always fully based on the ip address.

But anyway, whether you see it or not, this rule would be IMO a good general filter anyway:

`###euConsent`

**Comment by peace2000** [comment]
I first thought that a general filter of `###euConsent` would hide that cookie message on Virustotal, but now I have noticed that it can be only hid by using a site specific filter: `www.virustotal.com###euConsent` as `###euConsent` won't work alone. This should be impossible on normal situations but it's probably caused by Virustotal's abnormal "app based" structure. It's not even possible to pick any elements there by using a element picker.

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/803 All right this problem seems to be Ubo specific because of it's performance optimizations. Not a filter based problem.
