### ISSUE TITLE
rytmynatury.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1174]
### List the website(s) you're having issues:

`https://rytmynatury.pl`

### What happens?
Broken scroll and overlay.

### List Subscriptions you're using:
Default+ Fanboy's Social Blocking List

### Your settings

- OS/version: Manjaro 18.1.0 Juhraya
- Browser/version: Vivaldi 2.7.1628.33 
- Adblock Extension/version: Nano Adblocker v1.0.0.126

### Other details:

![Screenshot_20190911_123024](https://user-images.githubusercontent.com/19818572/64690285-4df82d00-d490-11e9-9e70-8eb1df348440.png)

Fix => `@@||rytmynatury.pl/wp-content/plugins/easy-facebook-likebox/`

**Comment by ryanbr** [comment]
Didn't see any issues, but sure i'll take your word.

https://github.com/easylist/easylist/commit/641ecb92d4327d9a60790436c0ccacafc92cb5a4
