### ISSUE TITLE
No Disqus comments on Cyclingnews.com with Annoyance List

### ISSUE THREAD

**Issue by gggirlgeek** [ryanbr/fanboy-adblock#1175]
### List the website(s) you're having issues:

`https://www.cyclingnews.com/news/we-did-a-team-time-trial-of-220km-says-vuelta-a-espana-stage-winner-gilbert/`

### What happens?

Disqus comments do not show at the bottom of the page when the Annoyance list is enabled.

### List Subscriptions you're using:

Fanboy's Annoyance List (moz-extension://e5de1d2b-e1d7-41d9-a345-6ded3ae0b416/asset-viewer.html?url=fanboy-annoyance)

### Your settings

No other adblockers -- tested all other lists in uBlock before reporting.

- OS/version: Win7x64
- Browser/version: Firefox v69.0
- Adblock Extension/version: uBlock Origin v1.22.2

### Other details:

First reported in uBlockOrigin issues by @biwqn here: [https://github.com/uBlockOrigin/uAssets/issues/6284](url). I have since tested this issue on Disqus' Demo page and also here:[https://www.lullabot.com/articles/why-and-how-we-migrated-comments-to-disqus](), but there is no issue with those sites. Disqus comments are shown. Only cyclingnews.com seems affected.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/91cde8a13095acf5240e65ded6c97f2529590a4d
