### ISSUE TITLE
Select.no - Blocked customer form (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1176]
### Affected site:
`https://www.select.no/`

### Issue:
Unable to shop, because of blocked customer form!

### How to reproduce:
1) Put an item in your shopping cart (Legg i handlekurven).
2) Open your shopping cart (Gå til handlekurv).
3) Checkout (Til kassen).
4) Select "Bill" as payment method (Faktura), and click "Continue" (Gå videre)..
Observe, as the entire customer form is blocked!

### Screenshots:
Not needed, as the problem is obvious.

### Problem filter:
* Fanboy's Annoyance List

### Problem rule:
`##.signup1`

### Possible fix:
`select.no#@#.signup1`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by ryanbr** [comment]
Too generic. removed.
https://github.com/easylist/easylist/commit/9bd6de8b8c3c9c2ef0d41d26f2d2cfd842038ea8
