### ISSUE TITLE
musicexpress.pl/pl/ [cookies]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1177]
Inncorect cut GDPR pop-up.

`https://www.musicexpress.pl/pl/`  [](https://github.com/MajkiIT/polish-ads-filter/issues/14671)

Website need addition:

```
musicexpress.pl##.modal-backdrop
```

@ryanbr  / @khrin

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/76a68467cef294261559922e1a12e70428726205
