### ISSUE TITLE
www.ilmarinen.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1178]
### List the website(s) you're having issues:

`https://www.ilmarinen.fi/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock Origin 1.22.2

### Other details:

These rules fixes it:

`www.ilmarinen.fi###ilmGdprCooMod`
`www.ilmarinen.fi##.in.modal-backdrop`
`www.ilmarinen.fi##body:style(overflow: auto !important;)`

**Comment by ryanbr** [comment]
Will be a Ubo specific filter here @peace2000
