### ISSUE TITLE
xdadevelopers Google Plus

### ISSUE THREAD

**Issue by inspector71** [ryanbr/fanboy-adblock#118]
Thank you for your list. Very helpful. On the xdadevelopers site, it blocks FB and Shitter but not G+ This appears to be a chunk of relevant code for you to target:

`<div class="postbit-social">
                        <a href="https://plus.google.com/share?url=https://forum.xda-developers.com//galaxy-s4/help/to-install-cyanogenmod-gt-i9507-t3546452/post70768480" target="_blank" title="Share this post on Google+" class="headerGPlusIcon fal-gplus" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" rel="nofollow"><i class="fagp fa fa-google-plus"></i></a>
                        <a href="/galaxy-s4/help/to-install-cyanogenmod-gt-i9507-t3546452/post70768480" target="_blank" title="Share this post on Facebook" class="postFacebookIcon fbs_post fal-facebook" rel="nofollow" flrttq3="" hidden=""><i class="fafb fa fa-facebook"></i></a>
                        <a href="retweet_forums.php?p=70768480" target="_blank" title="Tweet this post" class="postTwitterIcon fal-twitter" rel="nofollow" flrttq3="" hidden=""><i class="fatw fa fa-twitter"></i></a>					
                    </div>`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4097f9275ee647b2aa4e06d793d7e7dd7b793fa1
