### ISSUE TITLE
discord.me

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1180]
### What happens?
Social icons on top.

### List Subscriptions you're using:

Default + Fanboy's Social

### Your settings

- OS/version: Manjaro 18.1.0 Juhraya
- Browser/version: Vivaldi 2.7.1628.33
- Adblock Extension/version: Nano Adblocker v1.0.0.126

### Other details:
![Screenshot_20190915_205922](https://user-images.githubusercontent.com/19818572/64926255-c6961b00-d7fb-11e9-8f2f-ded33b28bcfb.png)

**Comment by llacb47** [comment]
`discord.me##li.menu-link`
