### ISSUE TITLE
watchhouseonline.net uses blockadblock

### ISSUE THREAD

**Issue by tebbenjo** [ryanbr/fanboy-adblock#1184]
### List the website(s) you're having issues:
```
watchhouseonline.net
blockadblock.com
```

### What happens?

A few seconds to a minute after entering the site an impassable ad block warning appears (blockAdblock type)

Also, invisible ads cover even the warning wall so clicking anywhere leads to a tab or multiple popping up in the background.

### List Subscriptions you're using:

```
ABP filters
Adblock Warning Removal List
Adware filters
EasyList
EasyPrivacy
Fanboy's Enhanced Tracking List
Fanboy's Annoyance List
I don't care about cookies
Malware Domains
NoCoin Filter List
Peter Lowe's list
Spam404
Squidblacklist.org Ad Servers
```

### Your settings

- OS/version: Ubuntu 18.04 for ODROID-XU4
- Browser/version: Chromium Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (32-bit)
- Adblock Extension/version: Adblock Plus Version 3.6.3

### Other details:

I'v tried disabling all but one filter at a time to see which one this "blockadblock" thing is detecting, but having any one filter enabled is enough to set off the site-wall. I also tried adding a custom filter for it, but it doesn't work the filter I tried is below.
```
watchhouseonline.net##script:inject(bab-defuser.js)

watchhouseonline.net##+js(bab-defuser)

blockadblock.com##+js(bab-defuser.js)
```

**Comment by krystian3w** [comment]
fixed in uAssets...

**Comment by tebbenjo** [comment]
Replaced ABP with uBlock Origin and there's no issue now. I will use uBO from now on. closing issue.
