### ISSUE TITLE
[iOS] bbc.com

### ISSUE THREAD

**Issue by BlazDT** [ryanbr/fanboy-adblock#1189]
When visiting https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.bbc.com%2Farabic on iOS the navigation menu is hidden unless "Fanboy's Annoyances" is disabled.

Screenshot
https://camo.githubusercontent.com/b05c5de7233fd806f14001b3300581d732c85126/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f364a67306d77582e706e67

https://github.com/AdguardTeam/AdguardFilters/issues/40982

**Comment by ryanbr** [comment]
not sure what the screenshot shows, or even how to debug it.

**Comment by Khrin** [comment]
A menu button is missing on top left side in the screenshot, but I can see it correctly when opening the link...

**Comment by BlazDT** [comment]
It only happens on iOS, not on Android. As soon as the list is active in Safari iOS the menu button is hidden.

**Comment by Khrin** [comment]
Honestly, I'm unsure why ios should work differently to Android...

**Comment by BlazDT** [comment]
It is Safari API. E. g. a normal block rule like ||google.com is not allowing you to visit the website on iOS while on Android the HTML still opens if opened directly.

**Comment by ryanbr** [comment]
No way to debug this, If @BlazDT can supply a filter we can whitelist, I'll be happy to add it.

**Comment by BlazDT** [comment]
Can't reproduce on iOS anymore, strange. Maybe site behaved differently when some elements were hidden by mentioned filter list and then did not display the menu and site devs did fix it (it is normal the menu button is a bit delayed, but before it never showed with the filter list).
