### ISSUE TITLE
findthecompany.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#119]
anti adblock 

http://i.imgur.com/Cr9ybV4.png

on 

`http://401k-plans.findthecompany.com/`

filter

`@@||findthecompany.com/ad?$xmlhttprequest,domain=findthecompany.com`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/bd251e56bb13271c9236530149fb502befeab705
