### ISSUE TITLE
wikipedia.org [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [ryanbr/fanboy-adblock#1190]
### List the website(s) you're having issues:

`https://en.wikipedia.org/wiki/Wikipedia:Multiyear_ranking_of_most_viewed_pages`
`https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%9F%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%B5_%D1%81%D1%82%D0%B0%D1%82%D1%8C%D0%B8/2017`

### What happens?

Part of content is hidden by `Fanboy's Social Blocking List`

### List Subscriptions you're using:

EasyList, Fanboy's Social Blocking List

### Your settings

- OS/version: Win7
- Browser/version:  Chrome 76
- Adblock Extension/version: ABP 3.6.6 / AdGuard 3.2.1

### Other details:

<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/65682469-b1bf5000-e063-11e9-8986-01d992804ff8.png)

 </details>

Problematic rules:
```
##a[title="Facebook"]
##a[title="YouTube"]
```

<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/65682640-ff3bbd00-e063-11e9-9653-9d7bf49f377e.png)

![image](https://user-images.githubusercontent.com/8361299/65682847-7b360500-e064-11e9-9d47-bc133afc9923.png)

 </details>

Problematic rules:
```
##a[title="Facebook"]
##a[title="YouTube"]
##a[title="ВКонтакте"]
##a[title="Instagram"]
```

**Comment by THEtomaso** [comment]
**EasyList** has had a `$generichide` rule in place for `wikipedia.org` for half a year, so those problematic rules, which you refer to, really shouldn't pose a problem.

**Comment by ryanbr** [comment]
I don't see Adguard having a generichide for wikipedia.org

https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/whitelist.txt

**Comment by THEtomaso** [comment]
I said **EasyList** (which Alex-302 pointed out that he's using):
https://github.com/easylist/easylist/blob/0451700cd9c98a40a94865b197d7a3fc4e4fc3ed/easylist/easylist_whitelist.txt#L262

**Comment by ryanbr** [comment]
I was just pointing it out, thats all.

**Comment by Alex-302** [comment]
Ok, got it. It seems a problem with AdGuard app.
