### ISSUE TITLE
weather.com - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1192]
### List the website(s) you're having issues:

`https://weather.com`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.1
- Adblock Extension/version: Ublock Origin 1.22.2

### Other details:

General rule can be made:

`###consent_blackbar`

**Comment by ryanbr** [comment]
```
fanboy@Ubuntu$ grep -r \#consent_blackbar fanboy_cookie_general_hide.txt
###consent_blackbar
```

Already have it.

**Comment by peace2000** [comment]
Hi, oh, yes that rule seems to be there after all but it doesn't get blocked. I noticed now that this site is whitelisted for some reason (I could not find any topic relating to this). These rules are applied to this site:

`@@||consent.trustarc.com^$image`
`@@||consent.trustarc.com/asset/$script`
@@||consent.truste.com/notice$script
