### ISSUE TITLE
www.forbes.com - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1193]
### List the website(s) you're having issues:

`www.forbes.com`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.1
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:
-

**Comment by ryanbr** [comment]
filter suggestion? I'm not seeing it.

**Comment by peace2000** [comment]
![Näyttökuva (70)](https://user-images.githubusercontent.com/17256841/67509315-68324700-f69b-11e9-9276-7b8b370a302d.png)

Have you removed your cookies?

I noticed that this site has whitelist rules, it has `consent.trustarc.com` based cookie notice system.

**Comment by ryanbr** [comment]
Yeah, attempting to remove the message it will cause breakage. `trustarc.com` is problematic

**Comment by soshial** [comment]
Sad news. Interestingly though, if I block `trustarc.com` domain completely, the cocckie notice disappears after click outside of it.
