### ISSUE TITLE
www.talotarvike.com - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1196]
### List the website(s) you're having issues:

`https://www.talotarvike.com`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.1
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

A general blocking rule can be made:

`##.cookieReminder`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/db8cb423b921a3d2fe3e2d6a3b57c69c497d27c0
