### ISSUE TITLE
www.f-secure.com - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1198]
### List the website(s) you're having issues:

`https://www.f-secure.com/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.1
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

Recommended blocking rule (works for all language regions):

`www.f-secure.com##.fs-consent`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4ea3a19562e0681d468415b439b1e035bb354377
