### ISSUE TITLE
teamquest.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1199]
### List the website(s) you're having issues:

`https://teamquest.pl/blog`

### What happens?

Fanboy's Social Blocking list hides article's image.

### List Subscriptions you're using:

Default, Fanboy's Social

### Your settings

- OS/version: Manjaro 18.1.0 Juhraya
- Browser/version: Vivaldi 2.8.1664.40
- Adblock Extension/version: Nano Adblocker v1.0.0.127

### Other details:

![Screenshot_20191005_134136](https://user-images.githubusercontent.com/19818572/66254406-2e45e300-e776-11e9-84ec-d3d8da734b9c.png)
Problematic filter => `/img/*youtube.jpg`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/66d71805698ade75531de0880f09d22f812ba0c3
