### ISSUE TITLE
Fake-News List

### ISSUE THREAD

**Issue by Bri-an** [ryanbr/fanboy-adblock#120]
fakenewswatch.com lists DrudgeReport.com.co, but your subscription list has it as drudgereport.com

**Comment by klonipins** [comment]
Thank you.  That list will provide a good deal of amusement and/or gullibility testing this semester.

**Comment by Bri-an** [comment]
Is this list abandoned?  The last updated was in April. 
If not, will the above error be fixed in the next update?

**Comment by ryanbr** [comment]
The list was more like a trial/test-sub, never listed on the main site. It might be worked on the future if given the time.
