### ISSUE TITLE
wishpost parcel tracking broken

### ISSUE THREAD

**Issue by fabianfrz** [ryanbr/fanboy-adblock#1200]
### List the website(s) you're having issues:

<code>https://www.wishpost.cn/tracking?tracking_id=TrackingId</code>

### What happens?

Frontend does not list the tracking history of the parcel because the request to the backend is blocked by the advanced tracking protection list.

### List Subscriptions you're using:

![grafik](https://user-images.githubusercontent.com/3713914/66267066-2301be80-e82d-11e9-8c68-53bb275b8540.png)

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 69.0 (64-Bit)
- Adblock Extension/version: uBlock Origin/1.22.4

### Other details:

Fixed using the following whitelist rule:
```
@@||www.wishpost.cn/api/tracking/search$xmlhttprequest,domain=www.wishpost.cn
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f9ebab338ef1c7ca649f9d13ac8a20fdbc8b556e
