### ISSUE TITLE
www.quora.com - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1202]
### List the website(s) you're having issues:

`https://www.quora.com/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.2
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

Can be blocked by a general rule:

`##.EUCookieBanner`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f02bba2deef7fea0b4e29ad6a03e77681e045e78
