### ISSUE TITLE
hellenicbank.com top menu bar is gone

### ISSUE THREAD

**Issue by nicexe** [ryanbr/fanboy-adblock#1203]
### List the website(s) you're having issues:

`https://www.hellenicbank.com/portalserver/hb-en-portal/en/personal-banking`

### What happens?

The top menu bar that includes the login button isn't shown.

### List Subscriptions you're using:

- Fanboy's Cookie List
- Fanboy’s Annoyance List

### Your settings

- OS/version: Windows 10 Pro, Version 10.0.18362, Build 18362
- Browser/version: Firefox Quantum 69.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin v1.22.4

### Other details:

![image](https://user-images.githubusercontent.com/867535/66378709-bc130f80-e9bc-11e9-8740-6f780345f6f2.png)
![image](https://user-images.githubusercontent.com/867535/66378722-c33a1d80-e9bc-11e9-9249-536b1095ec28.png)

Changing the display property of this element at least makes the elements show up. No real text in the elements, just placeholders.
`body > div.pageContainer > div#main.bp-page.bp-portal-area > div.lp-page-children.bp-area.--area > div.bp-widget.bp-ui-dragRoot > div.bp-widget-body > div.widget-hb-header-and-megamenu`
Clicking on the login button does nothing.

**Comment by nicexe** [comment]
Same issue described here: [uBlockOrigin/uAssets: Hellenic Bank personal banking. Top menu bar isn't shown.](https://github.com/uBlockOrigin/uAssets/issues/6415)

**Comment by krystian3w** [comment]
> `@@||hellenicbank.com/portalserver/*/cookies-consent.js$script`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/820c1d0014d17f235c382c8d761fff6c0d90d35d
