### ISSUE TITLE
uploadvr.com [social] [breakage]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1204]
Hidden article: `https://uploadvr.com/resolution-games-multiple/`

`uploadvr.com#@#.share-container` [](https://github.com/AdguardTeam/AdguardFilters/issues/41990)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9247eac5a5788f9d4c66ab9a1cd4993d00e659ce
