### ISSUE TITLE
janssenmed.pl [social] [possible breakage]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1205]
URL: `https://www.janssenmed.pl/`

`www.janssenmed.pl#@#.footer-social`

cut too many elements...

this is not social image in footer:

![obraz](https://user-images.githubusercontent.com/35370833/66417047-775c9800-e9ff-11e9-924c-50a20714c8d7.png) |
--- |

**Comment by ryanbr** [comment]
Probably not worth it? got the cookie instead.

https://github.com/easylist/easylist/commit/bf62bde45f9f5809caddf5b2844bec2749b598db
