### ISSUE TITLE
www.budgetsport.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1206]
### List the website(s) you're having issues:

`https://www.budgetsport.fi/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.2
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

Can be blocked by a general rule:

`###cookie-notice-popup`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2f7df3df1002e3f6ed91f9f549007284b27fa6a8
