### ISSUE TITLE
kuriertczewski.pl [social] [breakage]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1207]
http://kuriertczewski.pl/

Incorrect blocked element in header by:

`##.social_header`

before | after 
--- | ---
![obraz](https://user-images.githubusercontent.com/35370833/66586314-b4a06180-eb88-11e9-89b0-b0db60f079c6.png) | ![obraz](https://user-images.githubusercontent.com/35370833/66586408-d699e400-eb88-11e9-999b-331e555bc0ac.png)
`##.social_header` |  `#@#.social_header` [](https://github.com/MajkiIT/polish-ads-filter/issues/14872)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b7602821a51e6afa88a3816c415ecb2fb3d18363
