### ISSUE TITLE
Hurtigruten.no - Modal backdrop (Fanboy's Annoyance List / Fanboy's Cookie List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1208]
### Affected site:
`https://www.hurtigruten.no/`

### Issue:
A modal backdrop covers the page, because of a blocked cookie consent.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rules:
```
##.consent-dialog
##.consent-container
```

### Possible fix (successfully blocking the cookie consent and backdrop):
`hurtigruten.no##.el-cookie-consent`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/da32d057d3123be6f1d0923022ab466d809b346c
