### ISSUE TITLE
xxl.fi - cookie notification not blocked correctly

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1209]
### List the website(s) you're having issues:

`https://www.xxl.fi/`

### What happens?

Cookie notification not blocked correctly. When it's blocked, it causes breakages to the top navigation bar.

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.3
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

The problematic rule that causes breakages:

`##.cookiewarning:not(body):not(html)`

The problem isn't acute as the Finnish Easylist has a whitelist rule for this site https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/98a732c275c2b18de9c97eb6aef9366db741c438, but it would be glad to find a good and working solution for this. :)

**Comment by ryanbr** [comment]
Seems very minor, worth have the cookie message? I'll only whitelist if the breakage causes page blanking (from the main site)

**Comment by peace2000** [comment]
xxl.fi have changed their notification so this is not relevant anymore.
