### ISSUE TITLE
searchstorage.techtarget.com - cookie notification not blocked correctly

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1210]
### List the website(s) you're having issues:

`https://searchstorage.techtarget.com/`

### What happens?

Cookie notification not blocked.

### List Subscriptions you're using:

Fanboy cookie list

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.3
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

-

**Comment by ryanbr** [comment]
Didn't see it, does manually adding `||consent.techtarget.com^` help?

**Comment by peace2000** [comment]
![Näyttökuva (35)](https://user-images.githubusercontent.com/17256841/67152066-4ff7ac00-f2d8-11e9-93c5-0366d4516c85.png)

It´s on the top. But yes your rule blocks it.

**Comment by ryanbr** [comment]
This should be better. re-open if it doesn't help.

**Comment by peace2000** [comment]
Works fine.
