### ISSUE TITLE
Cookie banner not blocked: researchgate.net

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1211]
### List the website(s) you're having issues:
`https://www.researchgate.net/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.22.4

**Comment by krystian3w** [comment]
Locked scrolling. IMO better no risk with breakage site with simple filters.

@mapx-?

**Comment by zertrin** [comment]
I think this is too aggressive, as it breaks some functionality. For example, I am unable to see the full paper request dialog now. Maybe it uses the same type of modals.

**Comment by mapx-** [comment]
Well, it's just a cookie, page needing account, I'll just remove the filters.

**Comment by krystian3w** [comment]
No better add `has/has-text` construction? If account is free I try create similar to: https://github.com/uBlockOrigin/uAssets/commit/6b78f437aeedcee01df6c17e3630a63ea366b84c

**Comment by krystian3w** [comment]
Hmm... site removed modal completely.
