### ISSUE TITLE
zive.aktuality.sk [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [ryanbr/fanboy-adblock#1212]
### List the website(s) you're having issues:

`https://zive.aktuality.sk/clanok/142793/huawei-ma-chystat-5nm-cipset-pre-mobily/`

### What happens?

Comment button is hidden by `Fanboy's Social Blocking List`

### List Subscriptions you're using:

EasyList, Fanboy's Social Blocking List, Fanboy's Annoyances

### Your settings

- OS/version: Win7
- Browser/version:  Chrome 76
- Adblock Extension/version: ABP 3.6.6 / AdGuard 3.2.1

### Other details:

<details><summary>Screenshot with ad blocker:</summary> 

![image](https://user-images.githubusercontent.com/8361299/66937481-33454500-f048-11e9-9e82-3cc4e687a48f.png)

 </details>

<details><summary>Screenshot without ad blcoker:</summary> 

![image](https://user-images.githubusercontent.com/8361299/66937291-df3a6080-f047-11e9-90d0-08d859d7b2fd.png)

 </details>

Can be fixed by:
```
zive.aktuality.sk#@#.socials-link
zive.aktuality.sk#@#.socials-wrapper
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/52ae6a3695947777b4457981a837ab9c0809b417
