### ISSUE TITLE
www.selly.pl

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1213]
`https://www.selly.pl/integracje/`

incorrect cut element on site:

![obraz](https://user-images.githubusercontent.com/35370833/67032241-76b8b580-f113-11e9-8e2f-57c78c89cf5a.png)

center is not real social FB.

```
www.selly.pl#@#img[alt="Facebook"]
||www.selly.pl/wp-content/themes/flatsome-child/img/logo/logo-facebook.png$image,domain=www.selly.pl
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/027e944a05d8b79804b6d3f23efc9ba987ccdb72
