### ISSUE TITLE
www.kitchentime.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1214]
### List the website(s) you're having issues:

`https://www.kitchentime.fi/`

### What happens?

Cookie notification not blocked.

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 69.0.3
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

A general blocking rule can be made:

`##.cookie`

I was surprised that this rule was not found on the list. `##.Cookie` was there but these rules are case sensitive.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/70ed70be9673c0c7f96e76c8ca988594237fd7a6

**Comment by krystian3w** [comment]
many have locked scrolling, specific is better.
