### ISSUE TITLE
ParadoxPlaza.com - Site broken (Fanboy's Annoyance List / Fanboy's Cookie List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1215]
### Affected site:
`https://www.paradoxplaza.com/`

### Issue:
Nothing can be clicked, because of a blocked cookie consent, which needs to be accepted!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rules:
```
###cookies-info
paradoxplaza.com###disablingDiv
```
(The first rule is the real culprit)

### Possible fix:
Delete the second rule and add the following exception:
```
paradoxplaza.com#@##cookies-info
```

### Other problem filters:
* AdGuard Annoyances filter _(reported)_ https://github.com/AdguardTeam/AdguardFilters/issues/42666/
* I don't care about cookies _(reported)_

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by krystian3w** [comment]
very old: https://github.com/MajkiIT/polish-ads-filter/issues/9383
