### ISSUE TITLE
ecoustics.com broken by Fanboy’s list

### ISSUE THREAD

**Issue by monterrr** [ryanbr/fanboy-adblock#1216]
List the website(s) you're having issues:

`https://www.ecoustics.com/products/edifier-s760d-51-multimedia-system/`

### What happens?

It doesn't load the full page.

### List Subscriptions you're using:

Peter Lowe’s Ad and tracking server list
Malware Domain
EasyPrivacy
EasyList
Fanboy’s Annoyance List
Fanboy’s Social Blocking List

### Your settings

- OS/version: Fedora 30
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock origin 1.22.4

### Other details:

Fanboy’s Annoyance List
Fanboy’s Social Blocking List

**Comment by THEtomaso** [comment]
### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule
`##.social-bottom`

### Possible fix:
`ecoustics.com#@#.social-bottom`

### Note:
There's some leftovers from an ad-bar on the right side too, which should be removed:
`ecoustics.com###sidebar-contain`
