### ISSUE TITLE
Cookie notice on https://www.bilesuserviss.lv/

### ISSUE THREAD

**Issue by soshial** [ryanbr/fanboy-adblock#1217]
### List the website(s) you're having issues:
`https://www.bilesuserviss.lv/`

### What happens?
Cookie banner in the top.

### List Subscriptions you're using:
Fanboy's Cookie List

### Your settings
- OS/version: MacOS Mojave 10.14.6 (18G103)
- Browser/version: Firefox 69.0.3 (64-bit)
- Adblock Extension/version: uBlock Origin 1.22.4

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4db07aa64342ec5bfbc183334a2f618a17ff6638
