### ISSUE TITLE
labanquepostale.fr If you are connected to the online bank, the button is removed

### ISSUE THREAD

**Issue by milklineep** [ryanbr/fanboy-adblock#1220]
### List the website(s) you're having issues:
```labanquepostale.fr```

### What happens?
1. Sign in to the online banking system
2. Open `labanquepostale.fr`
3. The button to connect to the online bank is removed by DOM rule

### List Subscriptions you're using:
A lot, but the two relevant ones are:
* Fanboy's Cookie List 
* Fanboy’s Annoyance List 

### Your settings

- OS/version: Ubuntu 19.04 64-bit
- Browser/version: Firefox 70.0b14
- Adblock Extension/version: uBlock Origin 1.22.4 

### Other details:

The problematic filter is: `##.cookie-on`

The relevant button HTML is:
```html
<a class="lbpaccount-link navbar-btn cookie-on" id="verifStatAccountLink" onclick="javascript:return tc_events_global(this, &quot;CLICK&quot;, {&quot;titre_section&quot;:&quot;Comptes&quot;,&quot;url_cible&quot;:&quot;https://voscomptesenligne.labanquepostale.fr/voscomptes/canalXHTML/identif.ea?origin=particuliers&quot;,&quot;id_composant&quot;:&quot;/apps/labanquepostale/particuliers/components/navigationComp&quot;});" style="display: block;" href="https://voscomptesenligne.labanquepostale.fr/voscomptes/canalXHTML/identif.ea?origin=particuliers" data-url-account="https://voscomptesenligne.labanquepostale.fr/voscomptes/canalXHTML/identif.ea?origin=particuliers" data-label-connect="CONNECTÉ" data-label-no-connect="ME CONNECTER" data-title-no-connect="" data-title-connect="">
<i id="account-icon-connect" class="icon-advisor"></i>
<span class="sr-only-xs" id="accountTextLink">CONNECTÉ</span>
<span class="focus-style"></span>
</a>
```

**Comment by krystian3w** [comment]
I suppose nobody create free account.

**Comment by ryanbr** [comment]
Sure, i'll take your word for it.
