### ISSUE TITLE
[Fanboy's Cookie List] "0 used out of 15,989" General issue

### ISSUE THREAD

**Issue by Radiac93** [ryanbr/fanboy-adblock#1228]
### List the website(s) you're having issues:

General issue with the list, not a specific site.

### What happens?

I got tired of having the GDPR cookie pop-ups, so I enabled the " Fanboy's Cookie List". However, I was still getting the pop-ups. When I go to my Ublock Origin settings, I find that there 0 out of 15,989 rules are used, but I cannot seem to find out why.
I tried to purge all caches, update, disable the "Block-EU-Cookie-Shit-List" to see whether there aren't any conflicts, etc. but all to no avail.

What can I do to fix this? I'm sure it must be something simple.

Thanks for the help!

Cheers

### List Subscriptions you're using:

Built-in (6/7):
+ uBlock filters17,943 used out of 18,302
+ uBlock filters – Annoyances2,682 used out of 2,695
+ uBlock filters – Badware risks345 used out of 348
+ uBlock filters – Privacy150 used out of 163
+ uBlock filters – Resource abuse104 used out of 112
+ uBlock filters – Unbreak1,104 used out of 1,152
Ads (1/4):
+ EasyList89,443 used out of 89,640
Privacy (2/3):
+ EasyPrivacy17,213 used out of 17,914
+ Fanboy’s Enhanced Tracking List3,313 used out of 3,388
Malware domains (2/4):
+ Malware Domain List1,105 used out of 1,105
+ Malware domains26,848 used out of 26,865
Annoyances (2/6):
+ Fanboy's Cookie List0 used out of 15,989
+ Fanboy’s Annoyance List54,628 used out of 55,354
Multi-purpose (1/4):
+ Peter Lowe’s Ad and tracking server list2,954 used out of 3,061
Regions, 
languages (4/35):
+ FRA: EasyList Liste FR22,631 used out of 22,650
+ NLD: EasyList Dutch1,430 used out of 1,432
+ POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda6,331 used out of 6,467+ POL: Oficjalne polskie filtry przeciwko alertom o Adblocku955 used out of 976
Custom (1/1):
+ Block-EU-Cookie-Shit-List1,251 used out of 1,252

### Your settings
Enabled: (by default, as far as I'm aware)
+ Hide placeholders of blocked elements
+ Show the number of blocked requests on the icon
+ Make use of context menu where appropriate
+ Disable pre-fetching (to prevent any connection for blocked network requests) 
+ Disable hyperlink auditing

- OS/version: Windows 10, version 1903
- Browser/version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Adblock Extension/version: Ublock Origin 1.23.0

**Comment by ryanbr** [comment]
Because Annoyances list includes the cookie list, just remove the cookie list and use Annoyances.
