### ISSUE TITLE
www.valio.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#1229]
### List the website(s) you're having issues:

`https://www.valio.fi/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy cookie list

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 70.0
- Adblock Extension/version: Ublock Origin 1.23.0

### Other details:

A general blocking rule can be made:

`##[class*="CookieBarWrapper"]`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5c9a8f1ae26aeeac50c51d8741946b85ccbea9a5
