### ISSUE TITLE
theguardian.com contribution request on every article

### ISSUE THREAD

**Issue by fivefilters** [ryanbr/fanboy-adblock#1230]
### List the website(s) you're having issues:

* `theguardian.com`

### What happens?

Every article on the site displays a long message at the end asking for contributions.

### List Subscriptions you're using:

* uBlock filters
* uBlock filters Annoyances
* Easylist
* Fanboy's Annoyance List

### Your settings

- Browser/version: Firefox 70
- Adblock Extension/version: uBlock Origin 1.23

### Other details:

If possible, please add a filter for this to the Annoyance list. HTML element has class attribute value `contributions__epic`. 

Screenshot:

![Screenshot_2019-11-02 US effort to curb fentanyl behind brief arrest of El Chapo’s son, says minister](https://user-images.githubusercontent.com/3708988/68063405-0adc6c80-fd11-11e9-8b29-ae193204c097.png)

HTML snippet:

    <div class="contributions__epic contributions__epic--2019-10-14_moment_climate_pledge" data-link-name="epic">
      <div class="">
        <div>
          <h2 class="contributions__title">Since we published our pledge...</h2>
          <p>... focused on the escalating climate crisis,...

**Comment by krystian3w** [comment]
Nano Defender Integration block by:

`theguardian.com##.contributions__epic`


- https://github.com/NanoAdblocker/NanoFilters/blob/e32c3125a4736ce1801648baaf495153f2a87b0e/NanoMirror/NanoDefender.txt#L404
- https://github.com/NanoAdblocker/NanoFilters/blob/e32c3125a4736ce1801648baaf495153f2a87b0e/NanoMirror/NanoDefender.txt#L405

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/aec69ee3d54ef133a3b438833cc7141bfbfadaea
