### ISSUE TITLE
Cookie banner not blocked: bundeskanzleramt.gv.at

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1232]
### List the website(s) you're having issues:
`https://www.bundeskanzleramt.gv.at/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.23.0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/48e1a65be80479a1ecdbc173ebee86dea2218ad6
