### ISSUE TITLE
TheWireCutter.com top menu positioning broken Annoyances list

### ISSUE THREAD

**Issue by GoWithitRoger** [ryanbr/fanboy-adblock#1239]
### List the website(s) you're having issues: 
The Wire Cutter, `https://thewirecutter.com`

### What happens?
Top menu bar is positioned 1/4 way down the screen, instead of fixed at the top. 

### List Subscriptions you're using:
Fanboy's Annoyances

### Your settings
Nothing else enabled on mobile Safari, iOS 13.2.3

- OS/version: iOS 13.2.3
- Browser/version: Safari mobile
- Adblock Extension/version: iOS (iPhone) Adguard 3.1.2

### Other details:

![IMG_1620](https://user-images.githubusercontent.com/11821868/69392236-fef22380-0c9a-11ea-8224-e75a9d7087e4.jpg)

**Comment by ryanbr** [comment]
Actually expected. because of the cookie message.  and it won't callapse, just the design of the site
