### ISSUE TITLE
nungmovies-hd.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#124]
```
-728x90px-
||blogspot.com^*.gif$domain=nungmovies-hd.com

+ popads
```
`https://www.nungmovies-hd.com/` (Non English)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b47c76991772aae6c4e8561558f8073d4fc92365

The rest can be taken care of by a regional list
