### ISSUE TITLE
SchonMagazine.com - Blocked elements (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1240]
### Affected site:
`https://schonmagazine.com/`

### Issue:
Most elements are blocked!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.addthis_toolbox
`
### Possible fix:
`schonmagazine.com#@#.addthis_toolbox`

### Other problem filters:
* AdGuard Social Media filter https://github.com/AdguardTeam/AdguardFilters/issues/44556/
* uBlock filters - Privacy https://github.com/uBlockOrigin/uAssets/issues/6608/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by ryanbr** [comment]
already fixed?

**Comment by THEtomaso** [comment]
Yeah, things have changed server-side.
