### ISSUE TITLE
Nettavisen.no - Blocked scoreboards (Fanboy's Annoyance List / Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1241]
### Affected page:
`https://live.nettavisen.no/`

### Issue:
The scoreboards are blocked!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`nettavisen.no##.active > div`

### Possible fix:
The problem rule is too generic, and should be removed!
To block the cookie consent popup, this generic rule can be used instead (works for all Amedia sites):
`##amedia-privacybox`

### Temporary fix (for anyone who may need it):
```
##amedia-privacybox
nettavisen.no#@#.active > div
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by DandelionSprout** [comment]
My proposal for a fix: Adding `live.nettavisen.no#@#.active > div`.

**Comment by THEtomaso** [comment]
The following rule (found in **Fanboy's Annoyance List** / **Fanboy's Cookie List**) should be completely removed!:
`ba.no,ifinnmark.no,nettavisen.no,op.no##.active > div`

For one thing, the rule is way too generic, and has the potential to cause various breakage issues (like demonstrated in the first post)!
Also, the new, recently added rule `##amedia-privacybox` (which is much more specific), effectivelly blocks the cookie popups for all of those sites, thereby making the problem rule totally redundant!

**Comment by peace2000** [comment]
@THEtomaso this change is merged now!
