### ISSUE TITLE
epicdrama.pl [social] [breakage]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1244]
Incorect hiden element - search icon:

`http://epicdrama.pl/`

![obraz](https://user-images.githubusercontent.com/35370833/69660652-09d4fb80-1081-11ea-8897-77bb2cab13ce.png) |
--- |

bad:

`##.menu-social`

fix:

```
epicdrama.pl#@#.menu-social
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/776a89432a8f06e7b42c66c0e22efba1ddfd4d40
