### ISSUE TITLE
Cookie banner not blocked: play.google.com/store?hl=de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1245]
### List the website(s) you're having issues:
`https://play.google.com/store?hl=de`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c8837e50c47f751f61f02a4cf55e686ee1cd3c47
