### ISSUE TITLE
kostenlose-urteile.de unblocked newsletter

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1246]
### List the website(s) you're having issues:

`https://www.kostenlose-urteile.de/`
### What happens?
Newsletter popup
<img width="600" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/69769133-d038e900-1183-11ea-8c23-1c7d9fa6f14b.PNG">

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3899320/Settings.txt)

### Your settings

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3899319/Settings.txt)

- OS/version: Windows 10
- Browser/version: Firefox 70.0.1
- Adblock Extension/version: uBlock Origin v1.24.2

**Comment by krystian3w** [comment]
`kostenlose-urteile.de###raoKLUibSNL_overlay`
`kostenlose-urteile.de###raoKLUibSNL_container`

or generic:

```
##.simplemodal-container
##.simplemodal-overlay
```

simple suppose no support lock scrolling.
