### ISSUE TITLE
letyshops.com

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1248]
hidden icon on social **login**/register button:

`https://letyshops.com/uk`

![obraz](https://user-images.githubusercontent.com/35370833/69894336-b253bb80-131e-11ea-8e26-da7c0359d17f.png) |
--- |

Fix:

```
@@||letyshops.com/build/core/images/fb-white.*.png$image
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b4e5d33e4ef23108c1cdf0604733af54fb70dcef
