### ISSUE TITLE
pioneer-iot.com broken by Fanboy’s Annoyance List

### ISSUE THREAD

**Issue by monterrr** [ryanbr/fanboy-adblock#1249]
### List the website(s) you're having issues:

` https://pioneer-iot.com/product/internal-ssd/internal-ssd-aps-se20g/`

### What happens?

Doesn't load the full page.

### List Subscriptions you're using:

Fanboy’s Annoyance List

### Your settings

- OS/version: Fedora 31
- Browser/version: Firefox 70
- Adblock Extension/version: uBlock Origin v1.24.2

### Other details:

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.social-circle`

### Possible fix:
`pioneer-iot.com#@#.social-circle`
