### ISSUE TITLE
False positive adcore.ch

### ISSUE THREAD

**Issue by slartibartfass** [ryanbr/fanboy-adblock#125]
IsraelList.txt
/adcore.

The Domain adcore.ch (Website still in development) from one of our customers is not related to adcore.com (SEM, Adwords) and needs a whitelisting like adcore.com.au in easylist.

Otherwise visitors have problems with missing graphics, css and js

**Comment by ryanbr** [comment]
I no longer maintain "IsraelList.txt", and /adcore doesn't seem to interfere from what I see.

**Comment by slartibartfass** [comment]
Problem still exists

![adcore-ch](https://user-images.githubusercontent.com/1481796/29485888-b0e37e72-84da-11e7-9910-8c2ccc11b982.jpg)

**Comment by SMed79** [comment]
> Problem still exists

if you disagree with the [strict block](https://github.com/gorhill/uBlock/wiki/Strict-blocking) of uBo you have to click the "Permanently" button.
read https://github.com/uBlockOrigin/uAssets/issues/454#issuecomment-308433572

**Comment by slartibartfass** [comment]
Thanks, I know how to "Whitelist" the site permanently. :-) My wish is that the site *.adcore.ch will be added to the permanently whitelist because it has nothing to do with the "adcore" that should be blocked by the list.
