### ISSUE TITLE
Cookie banner not blocked: krimi-couch.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1250]
### List the website(s) you're having issues:
`https://www.krimi-couch.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4344cb0feea6db826f8244698193bbc6014b21a2
