### ISSUE TITLE
instalki.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1251]
### List the website(s) you're having issues:
`https://www.instalki.pl/aktualnosci/bezpieczenstwo/38884-cyber-monday-trwa-uwaga-na-oszustow-na-olx.html`

### What happens?

Hidden image in article.

### List Subscriptions you're using:
Fanboy's Social

### Your settings

- OS/version: Manjaro 18.1.3 Juhraya
- Browser/version: Vivaldi 2.9.1705.41
- Adblock Extension/version: Nano Adblocker 1.0.0.130

### Other details:

![Screenshot_20191202_160305](https://user-images.githubusercontent.com/19818572/69969717-3e333680-151d-11ea-9488-27fb4b2dcec2.png)

Fix => `@@_facebook.png$domain=instalki.pl`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7c7d3330ca8d111fdbf350b03d3372d4c6f6636d
