### ISSUE TITLE
support.gearbest.com submitting a ticket doesn't work

### ISSUE THREAD

**Issue by monterrr** [ryanbr/fanboy-adblock#1252]
### List the website(s) you're having issues:
`support.gearbest.com`

 
### What happens?

Clicking on submitting ticket doesn't do anything.

### List Subscriptions you're using:
Easy List
Easy Privacy
Peter Lowe’s Ad and tracking server list
AdGuard Annoyances​​​​​
AdGuard Social Media​
​Anti-Facebook List​
Fanboy’s Annoyance List​
Fanboy’s Social Blocking List

### Your settings

- OS/version: Fedora 31
- Browser/version: Firefox 70
- Adblock Extension/version: uBlock Origin v1.24.2

### Other details:

Unfortunately due to the nature of the bug I'm unable to pinpoint the exact list causing the problem but I can leave here the source code for the page:

[https _support.gearbest.com_ticket_ticket_index?cat_id=16.html.txt](https://github.com/ryanbr/fanboy-adblock/files/3923211/https._support.gearbest.com_ticket_ticket_index.cat_id.16.html.txt)

Screenshot of the page:

![Screenshot_2019-12-07 https support gearbest com](https://user-images.githubusercontent.com/56444382/70368208-ea6b7900-189f-11ea-8d0c-45f01a253165.png)

**Comment by ryanbr** [comment]
Can you screenshot the blocked items window on the site?

**Comment by monterrr** [comment]
I've added a screenshot, and just to be clear I removed the email address from the source code of the page before uploading.

**Comment by THEtomaso** [comment]
Does this help?:
`@@||gearbest.com/static/dist/minjs/jcookie.js`

**Comment by monterrr** [comment]
@THEtomaso I've put that line on my filters and that indeed worked!

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`/jcookie.js`

### Blocked script:
`https://support.gearbest.com/static/dist/minjs/jcookie.js`

### Screenshot (from uBO's logger):
![filterissue-gearbest](https://user-images.githubusercontent.com/9382674/71096791-375c2300-21af-11ea-8cca-eacbc29d582a.jpg)

### Possible fix:
`@@||gearbest.com/static/dist/minjs/jcookie.js`

**Comment by krystian3w** [comment]
cookies list has new name (again):

`! Title: EasyList Cookie List`
