### ISSUE TITLE
Cookie banner not blocked: support.microsoft.com/de-de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1257]
### List the website(s) you're having issues:
`https://support.microsoft.com/de-de`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by peace2000** [comment]
It is blocked already, I don't see cookie notifications without disabling my adblocker. Sometimes blocked cookie notifications may appear and when you refresh the page it's gone.

What is the date of your list?

**Comment by krystian3w** [comment]
```
support.microsoft.com###uhfCookieAlert
support.microsoft.com###msccBanner:not(body):not(html)
```

**Comment by ryanbr** [comment]
is `:not(body):not(html)` really needed?

**Comment by krystian3w** [comment]
IMO nope, IDCAC use this for almost all cosmetic filters.

**Comment by ryanbr** [comment]
Should be resolved,  not sure when I fixed this. but its fixed
