### ISSUE TITLE
Major false positive

### ISSUE THREAD

**Issue by Mr-Dead** [ryanbr/fanboy-adblock#126]
Hello and thank you for your service towards a safer and more elegant internet.  Please be advised that "Fanboy's Annoyances" list renders [this ](thadenschool.org)website unusable.

**Comment by Mr-Dead** [comment]
Apparently your link device does not work as intended.  Here is the website blocked by the above noted list: thadenschool.org

**Comment by klonipins** [comment]
Works for me with the mentioned subscription (alone or in addition to my defaults)

**Comment by Mr-Dead** [comment]
Sorry for delay, good folks.  The site in question is free from barriers now.  This ticket can be closed.  Merry Christmas and/or Happy Holidays!
