### ISSUE TITLE
Tidssonen.no - Blocked article contents (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1260]
### Affected site:
`https://www.tidssonen.no/`

### Issue:
Article content is blocked.

### Example:
`https://www.tidssonen.no/bell-ross-lanserer-br-03-92-full-lum/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.post-share-container`

### Possible fix:
`tidssonen.no#@#.post-share-container`

### Note:
There are plenty of social crap that needs to be cleaned up too, and scroll floaters in their forum.

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout:
How about a temp fix for the NOR filter?
Also, there's an empty, labeled ad box:
`tidssonen.no##[id^="custom_html"]:-abp-contains(Annonse)`

**Comment by DandelionSprout** [comment]
Well, this went pretty fast. I presume the temp-fix won't be needed in my lists after all.
