### ISSUE TITLE
DeGuleSider.dk / GuleSider.no / Krak.dk - Broken search results / maps (Fanboy's Annoyance List / Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1261]
### Affected sites:
```
https://www.degulesider.dk/
https://www.gulesider.no/
https://www.krak.dk/
```

### Issue:
Search results / maps are blocked.

### Examples:
```
https://kort.degulesider.dk/
https://kart.gulesider.no/
https://map.krak.dk/
```

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`||cookieinformation.com^$third-party`

### Possible fix:
```
- @@||policy.app.cookieinformation.com^$script,domain=eniro.se
+ @@||policy.app.cookieinformation.com^$script,domain=degulesider.dk|eniro.se|gulesider.no|krak.dk
```
`+ ||cookieinformation.com/cookiesharingiframe$important`
(Needed to block the cookie popups)

### Other problem filters:
* Frellwit's Swedish Filter https://github.com/lassekongo83/Frellwits-filter-lists/issues/68/
* I don't care about cookies *(reported)*

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
As the problem spans 2 lists, and I am unable to figure out what IDCAC's extension-version-exclusive problem rule is in a hurry, I wouldn't be able to certify or properly write any whitelisting entries to cover both lists. So I'll hold out on adding anything to my list as it currently stands.

**Comment by THEtomaso** [comment]
IDCAC's filter list problem rule is this one:
`policy.app.cookieinformation.com$domain=~kartor.eniro.se`
How is its potential "extension-version-exclusive" rule is relevant, anyway?
Are whitelistings in uBO, or any other blocker for that matter, actually able to affect the extension version?

**Comment by DandelionSprout** [comment]
Ah, wait, no, I saw wrong previously. I *somehow* managed to mistake `policy.app.cookieinformation.com$domain=~kartor.eniro.se` for being a whitelist rule à la `@@||`.

I'm currently doing some late-night Ring Fit Adventure, but I'll add `@@||cookieinformation.com^$third-party,domain=gulesider.no` after I'm finished with it, plus I'll look into if Eniro have any other map domains as well.

**Comment by THEtomaso** [comment]
OK. :+1: 
Good luck with that weird Ring Fit stuff! (yes, I searched it up :) )

**Comment by DandelionSprout** [comment]
After having finished tonight's exercise, these four were the Eniro map sites I could find, and for which I propose that all three involved lists expand their whitelistings:

`@@||cookieinformation.com^$third-party,domain=kart.gulesider.no|map.krak.dk|kort.degulesider.dk|kartor.eniro.se`

**Comment by THEtomaso** [comment]
*First post updated*

**Comment by THEtomaso** [comment]
@DandelionSprout / @lassekongo83:
When whitelisting `policy.app.cookieinformation.com` an extra rule is needed to block the cookie popups (see first post).

**Comment by ryanbr** [comment]
Does this help?

**Comment by THEtomaso** [comment]
Yes, that works too, and does indeed appear to be the simplest solution! :)

**Comment by THEtomaso** [comment]
@DandelionSprout:
At all of the mentioned sites, there's an empty ad container, right below the search box (in the top left corner).
Possible fix: `degulesider.dk,gulesider.no,krak.dk##.e-banner`

**Comment by THEtomaso** [comment]
The sites are broken again.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
```
###CookieConsent
||cookieinformation.com/*/*.js
```

### Possible fix:
```
degulesider.dk,gulesider.no,krak.dk#@##CookieConsent
@@||cookieinformation.com/*/*.js$domain=degulesider.dk|gulesider.no|krak.dk
```

### Other problem filters:
* AdGuard Annoyances filter: `###CookieConsent` (@BlazDT)
* I don't care about cookies: `###CookieConsent` (@kiboke)

--

@DandelionSprout

**Comment by THEtomaso** [comment]
Sorry, I seem to have made a mistake when first testing this..
`###CookieConsent` doesn't break the pages, only `||cookieinformation.com/*/*.js` does!
*Previous post edited*

**Comment by spirillen** [comment]
hmmm weird as I have blocked `cookieinformation.com` entirely from my network, and I have no issues on either of those pages...

But just a thought
Why isn't `cookieinformation.com` blocked as `||cookieinformation.com^` ?

Personally I had no breakage by blocking that entirely....

**Comment by THEtomaso** [comment]
It's a GDPR issue.
Those type of issues are often highly region-dependent!

**Comment by spirillen** [comment]
You are actually right... If you try to access the maps directly there comes a problem, but when it is a integrated part of a search it's working

<details><summary>`https://www.krak.dk/hansen/firmaer`</summary>

![image](https://user-images.githubusercontent.com/44526987/74472799-ca10f980-4ea2-11ea-9f49-67c9135b953f.png)

</details>

<details><summary>`https://map.krak.dk/`</summary>

![image](https://user-images.githubusercontent.com/44526987/74472922-080e1d80-4ea3-11ea-9347-8262ec4d9d44.png)

</details>

PS: all three example url are owned by `eniro.se` :smiling_imp: 

<details><summary>`https://kartor.eniro.se/s/J%C3%B6nsson`</summary>

![image](https://user-images.githubusercontent.com/44526987/74473129-5fac8900-4ea3-11ea-8623-f6a7c8712ec2.png)

</details>

**Comment by THEtomaso** [comment]
> when it is a integrated part of a search it's working

That's certainly not the case for all of the affected sites, because I noticed this problem today, when using the search function at `gulesider.no`.

**Comment by spirillen** [comment]
@THEtomaso have you tried blocking `cookieinformation.com` on DNS/hosts level and tried again?  mostly because I'm curious of what is/would happen....

**Comment by THEtomaso** [comment]
I'll take your word for it, and assume that it will have a different effect! :)
