### ISSUE TITLE
mediaexpert.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1263]
### List the website(s) you're having issues:

`https://www.mediaexpert.pl/gazetka.html`

### What happens?

Hidden news-sheet.

### List Subscriptions you're using:

Fanboy's Social.

### Your settings

- OS/version: Manjaro 18.1.3 Juhraya
- Browser/version: Vivaldi 2.9.1705.41 (Stable channel)
- Adblock Extension/version: Nano Adblocker v1.0.0.130

### Other details:

![Screenshot_20191211_103311](https://user-images.githubusercontent.com/19818572/70609162-a52dab00-1c01-11ea-9508-d4fc33513cfe.png)

Fix:
```
mediaexpert.leszczynscy.pl#@#.fb-container
mediaexpert.leszczynscy.pl#@#.fb-page
```

**Comment by krystian3w** [comment]
`leszczynscy.pl`? IFRAME?

**Comment by hawkeye116477** [comment]
@krystian3w Yes
