### ISSUE TITLE
kiwibrowser.com

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1266]
### List the website(s) you're having issues:
`https://kiwibrowser.com/`

### What happens?

Social icons on footer.

### List Subscriptions you're using:

Fanboy's Social

### Your settings

- OS/version: Manjaro 18.1.4 Juhraya
- Browser/version: Waterfox Classic 2019.12
- Adblock Extension/version: uBlock Origin v1.24.2

**Comment by ryanbr** [comment]
Probably not worth it..

**Comment by krystian3w** [comment]
Nobody like  elementor builder page... 

`##.elementor-element-51b95a2`

`#?#section:-abp-has(~ footer) .elementor-element-51b95a2`

**Comment by krystian3w** [comment]
no based on classes:

```
##section:first-child:-abp-has(~ footer) > div:last-child:nth-of-type(2) > div > div:nth-child(3):nth-of-type(3) > div > div
```
