### ISSUE TITLE
epicgames.com

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#1268]
### List the website(s) you're having issues:

`https://www.epicgames.com/id/login`

### What happens?

Hidden social login methods.

### List Subscriptions you're using:

Fanboy's Social

### Your settings

- OS/version: Manjaro 18.1.4 Juhraya
- Browser/version: Vivaldi 2.10.1745.21
- Adblock Extension/version: Nano Adblocker v1.0.0.130

### Other details:

Fix:
```
epicgames.com#@#.SocialBar
epicgames.com#@#.SocialButton
epicgames.com#@#.google-btn
epicgames.com#@#.facebook-btn

```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a19f3a716eaeb062a7c91d7e0d06036aed202f58
