### ISSUE TITLE
Layout issue on ctvnews.ca

### ISSUE THREAD

**Issue by mica** [ryanbr/fanboy-adblock#1269]
Both the Annoyances and Social lists are causing the "More news from Canada" section title to jump up the page, appearing overtop text in the first paragraph of the article: 

https://i.imgur.com/0LAXp1j.png

https://www.ctvnews.ca/canada/canadian-workers-aren-t-entitled-to-bathroom-breaks-lawyer-says-1.4738922

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.StoryShareBottom`

### Possible fix:
`ctvnews.ca#@#.StoryShareBottom`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8368ffebfaf6e0962214b995332d6237968ac464
