### ISSUE TITLE
 distrowatch.com thumbnails are not visible

### ISSUE THREAD

**Issue by SuperPat45** [ryanbr/fanboy-adblock#127]
One  distrowatch.com, thumbnails are not visible on "DistroWatch Weekly, Issue" pages using uBlock Origin with the "Fanboy’s Enhanced Tracking List" due to rule:
`distrowatch.com##A[href] > IMG[src][alt]`

Example:
http://distrowatch.com/weekly.php?issue=20170814

It may be fixed by changing to:
`distrowatch.com##TD.News > A[href] > IMG[src][alt]`
or maybe with:
`distrowatch.com##A[href] > IMG[src][alt]:not([title])`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/b00da1a9cea53af73a48e3b548a52170140f64a6
