### ISSUE TITLE
Cookie banner not blocked: antiquariat.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1270]
### List the website(s) you're having issues:
`https://www.antiquariat.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by THEtomaso** [comment]
`antiquariat.de##.confirm-cookie`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/38836862d112cb1d8bab6f40cbd71e2b80b0a675
