### ISSUE TITLE
Fanboy Annoyance List causing issues with Gfycat.com

### ISSUE THREAD

**Issue by thinkpad4** [ryanbr/fanboy-adblock#1271]
### List the website(s) you're having issues:

 `https://gfycat.com/misguidedinsidiousjay-jon-hamm` Any `gfycat.com` link it happens on, using that one as a example

### What happens?

Fanboy's Social Blocking List 
Fanboy's Annoyance List 
have either annoyance list and/or social blocking list enabled causes `gfycat.com` to show a blank screen.  I tracked down the cause of the issue to `##.share-page` in both Annoyance List and Social Blocking List. When I manually entered `gfycat.com#@#.share-page` in My Filters gfycat loaded correctly 
### List Subscriptions you're using:

Only running Fanboy's Social Blocking List 
Fanboy's Annoyance List 

### Your settings

 I am

- OS/version: win7 64bit
- Browser/version: FF 71
- Adblock Extension/version: uBlock Origin v1.24.2

**Comment by ryanbr** [comment]
We already have it for gfycat.com:

`fanboy_social_whitelist_general_hide.txt:dropbox.com,ge.tt,gfycat.com,recite.com#@#.share-page`

**Comment by thinkpad4** [comment]
That fixed it, thank you
