### ISSUE TITLE
Cookie banner not blocked: din.one

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1272]
### List the website(s) you're having issues:
`https://din.one/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1a6db7b6d8957a8e49c561c9b533c69cc21f86b9
