### ISSUE TITLE
Cookie banner not blocked: din.de/de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1273]
### List the website(s) you're having issues:
`https://www.din.de/de`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by ryanbr** [comment]
Not seeing this. Do have in the list: can you re-check?
`##.cookie-banner__cnt`
`##.cookie-banner:not(body):not(html)`
