### ISSUE TITLE
zeit.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1275]
### List the website(s) you're having issues:

`https://www.zeit.de`

### What happens?

unblocked cookie banner

### List Subscriptions you're using:

[settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3999339/settings.txt)

### Your settings

[settings.txt](https://github.com/ryanbr/fanboy-adblock/files/3999341/settings.txt)

- OS/version: Windows 10
- Browser/version:  Firefox 71
- Adblock Extension/version: uBlock Origin v1.24.2

**Comment by krystian3w** [comment]
@kiboke:

`###data-protection-overlay`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3c7642342cd8ce6e4e2bb6e5f58d22efc1403a1f
