### ISSUE TITLE
HerbRitts.com - Blank page (Fanboy's Annoyance List / Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1277]
### Affected site:
`http://www.herbritts.com/`

### Issue:
Everything is blocked (blank page)!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rule:
`##.mod_cookies`

### Possible fix:
`herbritts.com#@#.mod_cookies`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.12 (XUL)

**Comment by llacb47** [comment]
That whole rule should just be removed, that class is used by Modernizr I believe.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1c237af85a0a64b83e1b9ef0763f5587167169bb
