### ISSUE TITLE
Cookie banner not blocked: dumont.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1278]
### List the website(s) you're having issues:
`https://www.dumont.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by krystian3w** [comment]
generic...

`###sp_message_id1577474904287.sp_message_container1577474904287`

**Comment by krystian3w** [comment]
#1145  - @llacb47  you see "CMP" subdomain to block?

**Comment by krystian3w** [comment]
@kiboke:

```css
##footer ~ div[id^="sp_messeage"][style="display: block;"]
```

❓

**Comment by llacb47** [comment]
`||consent.dumont.de^`

**Comment by krystian3w** [comment]
ABP no support `first-party`.

**Comment by llacb47** [comment]
`~third-party`

**Comment by kiboke** [comment]
I'll just block messaging.js in IDCAC

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ab06200b6e72eaf440307a55473f5ea43a02b8b0
