### ISSUE TITLE
lazienkaplus.pl [cookies] [breakage]

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1279]
`https://www.lazienkaplus.pl/pl/kompakty-wc,8,88,c/` 

blank page. [](https://github.com/MajkiIT/polish-ads-filter/issues/15452)

![obraz](https://user-images.githubusercontent.com/35370833/71549175-4619b580-29b9-11ea-9e1d-f043625b6bbf.png) |
--- |

## Fix:

```
lazienkaplus.pl#@#.cookies-policy
```

or add into generic filter:

```
:not(body):not(html)
```

**Comment by ryanbr** [comment]
Done.
