### ISSUE TITLE
[Add] The subscription checking Poool.fr to Enhanced Tracking List

### ISSUE THREAD

**Issue by iscreamcoke** [ryanbr/fanboy-adblock#1280]
Add `||assets.poool.fr` to `! ---------- Cookie/Subscription Checking ------` in order to block the scripts of [poool.fr](https://poool.fr/) from loading in websites (e.g., valeursactuelles.fr, challenges.fr, etc.)

### List Subscriptions you're using:

Fanboy's Enhanced Tracking List

**Comment by ryanbr** [comment]
Done. Tracker in EP the rest in Enhanced trackers.
