### ISSUE TITLE
sozialleistungen.info

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1285]
### List the website(s) you're having issues:

`https://www.sozialleistungen.info/hartz-iv/`

### What happens?

unblocked cookie banner

### List Subscriptions you're using:

[settings.txt](https://github.com/ryanbr/fanboy-adblock/files/4019668/settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 71
- Adblock Extension/version: uBlock Origin v1.24.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cb138e17fe355ae70bb5e1d88b4dc6287e550f43
