### ISSUE TITLE
moebelmarkt.com [breakage]

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1288]
### List the website(s) you're having issues:

`moebelmarkt.com`

### What happens?

Bad filter/unblocked cookie banner

### List Subscriptions you're using:

[settings.txt](https://github.com/ryanbr/fanboy-adblock/files/4030194/settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 71
- Adblock Extension/version: uBlock Origin v1.24.2

### Other details:

<img width="856" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/71890001-ae982d80-3143-11ea-8a16-a3d250bd433d.PNG">

**Comment by krystian3w** [comment]
`###BorlabsCookieBox`
