### ISSUE TITLE
www.gp.se

### ISSUE THREAD

**Issue by gtfs0** [ryanbr/fanboy-adblock#129]
Could you please fix Adblock for www.gp.se. There are two problems if you use Adblock. First, when you scroll down to the next article you will automatically return to the previous article. Second, in slideshows only the first, second and last image works, the others are black. None of these problems occur if you turn off Adblock.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c0a006d28fcd84648868b2fab09eb0674d72fa03
https://github.com/ryanbr/fanboy-adblock/commit/7264a41ba9c338503448ec09caf34acf049adbb8

Hopefully this resolves it.
