### ISSUE TITLE
Online.no / Telenor.no - Frozen pages (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1290]
### Affected sites:
```
https://www.online.no/
https://www.telenor.no/
```

### Issue:
Blocked cookie consent results in frozen pages, with modal overlays.

### Screenshots:
Not needed, as the problem is obvious.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
```
##.privacy_prompt
###__tealiumGDPRcpPrefs
###__tealiumGDPRecModal
```

### Possible fix (allowing the cookie consent popups):
```
online.no,telenor.no#@#.privacy_prompt
online.no,telenor.no#@##__tealiumGDPRcpPrefs
online.no,telenor.no#@##__tealiumGDPRecModal
```

### Note:
The second problem rule only becomes apparent when clicking on "Endre instillinger" (Change preferences).

### Other problem filters:
* I don't care about cookies (`###__tealiumGDPRcpPrefs`) @kiboke

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.13 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by kiboke** [comment]
@THEtomaso I don't see the problem with IDCAC filter list. The cookie warning appears and waits to be accepted on both sites. Once accepted, the websites work fine.

**Comment by THEtomaso** [comment]
@kiboke:
In the first post, read what I wrote under "**Note:**".
