### ISSUE TITLE
Multimedia carousel freezes on *.sputnik.* sites

### ISSUE THREAD

**Issue by simurq** [ryanbr/fanboy-adblock#1291]
### List the website(s) you're having issues:

Some of the *.sputnik.* websites, such as `az.sputniknews.ru/photo` but not `fr.sputniknews.com/photos` (!) and so on.

### What happens?

Multimedia carousel freezes when I click on or try to scroll the photos, for example, on `https://az.sputniknews.ru/photo/20200107/422798473/kak-ispolzovat-tsvet-2020-goda.html`
The problem is gone when I untick the filter and refresh the page, so I don't think it's the adblocker problem.

### List Subscriptions you're using:

Fanboy's Ultimate List on uBlock Origin.

### Your settings

- OS/version: Windows 7 Ultimate 64-bit
- Browser/version: Chrome 79.0.3945.117 (official stable build)
- Adblock Extension/version: uBlock Origin v1.24.2

### Other details:

I first thought that the filter blocks all sputnik* websites but at a closer look it turned out that mostly **az.sputniknews.ru** domain suffers. For example, `https://fr.sputniknews.com/photos/201912231042634362-roscosmos-calendrier-2020/` works well with filter ON but this one fails: `https://az.sputniknews.ru/photo/20191230/422765424/samye-gromkie-svadby-2019-goda.html`, i. e. webpage loads well but doesn't react on interaction like clicking on page elements.

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`/plugins/social-$~stylesheet`

### Blocked script:
`https://cdn1.img.sputnik.az/min/js/plugins/social-likes.min.js`

### Possible fix:
```
- @@/social-likes.min.js$script,~third-party,domain=armeniasputnik.am|sputnik-abkhazia.info|sputnik-abkhazia.ru|sputnik-georgia.com|sputnik-georgia.ru|sputnik-news.ee|sputnik-ossetia.com|sputnik-ossetia.ru|sputnik-tj.com|sputnik.az|sputnik.by|sputnik.kg|sputnik.md|sputniknews-uz.com|sputniknews.cn|sputniknews.com|sputniknews.gr|sputniknews.kz|sputniknews.lt|sputniknewslv.com

+ @@/social-likes.min.js$script,~third-party,domain=armeniasputnik.am|sputnik-abkhazia.info|sputnik-abkhazia.ru|sputnik-georgia.com|sputnik-georgia.ru|sputnik-news.ee|sputnik-ossetia.com|sputnik-ossetia.ru|sputnik-tj.com|sputnik.az|sputnik.by|sputnik.kg|sputnik.md|sputniknews-uz.com|sputniknews.cn|sputniknews.com|sputniknews.gr|sputniknews.kz|sputniknews.lt|sputniknews.ru|sputniknewslv.com
```

### Temporary fix:
`@@||sputnik.az/min/js/plugins/social-likes.min.js$domain=sputniknews.ru`

### Other problem filters:
* AdGuard Social Media filter (@BlazDT)
`/social-likes.min.js$domain=~animego.org|~zastenchivosti.net|~gorod-812.ru|~sputnik.by|~sputnik-news.ee|~animalreader.ru|~ichip.ru|~keddr.com|~kino-max.com|~kino24x7.com|~make-3d.ru|~miuipro.ru|~omelchuck.ru|~podfm.ru|~serial-online.com|~sputniknews.com|~trinixy.ru|~kinogo-kinopoisk.net|~bobfilm-online.ru|~westernfilm.ru|~bobfilm.tv|~kinokrik.net|~kinogo720.net|~kinogo-net-co.ru|~kinoklad.net|~intex-press.by|~kino-max.org|~farming-simulator15.ru|~trikky.ru|~trv-science.ru|~unzensuriert.at|~lizaalert.beeline.ru|~megapolisonline.ru`

**Comment by BlazDT** [comment]
Fixed for AdGuard, thank you.

**Comment by krystian3w** [comment]
`@@||sputnik.*^/min/js/plugins/social-likes.min.js$script,~third-party`

❓

**Comment by THEtomaso** [comment]
> @@||sputnik.*^/min/js/plugins/social-likes.min.js$script,~third-party

That won't work, because even if you use an asterisk (*), blockers will still detect `sputnik.az` as being a third party site for `sputniknews.ru`.

**Comment by krystian3w** [comment]
So your `Possible fix:` also do not fix it all troubles (only repair orange header).

**Comment by THEtomaso** [comment]
Oh, I hadn't even noticed it.
Thanks for pointing it out!
I've edited it now. :)

**Comment by simurq** [comment]
I cannot replicate the issue with the updated versions of Fanboy's list. So, the issue may be closed. Thank you!
