### ISSUE TITLE
Techopedia.com - Frozen page (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1295]
### Affected site:
`https://www.techopedia.com/`

### Issue:
After about 5 seconds, a blocked newsletter popup results in a disappearing scrollbar, and the page is covered by a backdrop modal!

### Screenshots:

* Screenshot 1 (Fanboy's Annoyance List enabled):

![filterissue-techopedia-1](https://user-images.githubusercontent.com/9382674/72673035-a1910d80-3a64-11ea-84f3-4a664e5b4415.jpg)

* Screenshot 2 (Fanboy's Annoyance List disabled):

![filterissue-techopedia-2](https://user-images.githubusercontent.com/9382674/72681876-1d707180-3ac8-11ea-9f57-b6ad53b87220.jpg)

* Screenshot 3 (After successfully having closed the newsletter popup, with Fanboy's Annoyance List disabled):

![filterissue-techopedia-2](https://user-images.githubusercontent.com/9382674/72673036-abb30c00-3a64-11ea-88cb-b749571c8992.jpg)

### Problem filter:
* Fanboy's Annoyance List

### Problem rules:
```
##.subscriptionForm
###subscriptionModal
/newsletterpopup.
```

### Possible fix (allowing the newsletter popup):
```
techopedia.com#@#.subscriptionForm
techopedia.com#@##subscriptionModal
@@||techopedia.com/support/newsletterpopup.
```

### Note:
As a simple workaround, simply refreshing the page unlockes it, but it should be fixed in the filter list regardlessly!

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.14b2 (XUL)

**Comment by THEtomaso** [comment]
> krystian3w reacted with thumbs down emoji

@krystian3w:
Are you unable to reproduce this issue at your end?
I've updated the first post with screenshots.

**Comment by spirillen** [comment]
Adding :-1:  Without a comment for why is bad style in my book.

I don't care if people disagree, but at least take your time to give a argument for why. Everything else is rather childish and making you appear like a 5 yo.

**Comment by krystian3w** [comment]
Second screen is created to late, you should clear cookies, refresh page and now create screenshot with newsletter "pop-up".

**Comment by THEtomaso** [comment]
> Second screen is created too late

Fixed.
But that still doesn't explain why you gave it a thumbs down, before I had added any screenshots.

**Comment by THEtomaso** [comment]
Thanks, krystian3w:
`https://github.com/uBlockOrigin/uAssets/issues/6843/` :+1:
