### ISSUE TITLE
Cookie banner not blocked: de.reuters.com

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1298]
### List the website(s) you're having issues:
`https://de.reuters.com/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by krystian3w** [comment]
evidon - so can't block for Moldavians 🇲🇩 and Norwegians 🇳🇴 .

**Comment by ryanbr** [comment]
yeah, unfortantly cant block without causing other issues @bestoernesto
