### ISSUE TITLE
vdk.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1299]
### List the website(s) you're having issues:
`
https://www.vdk.de/deutschland/`

### What happens?

unblocked cookie banner

### List Subscriptions you're using:

[settings.txt](https://github.com/ryanbr/fanboy-adblock/files/4090484/settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 72.0.2
- Adblock Extension/version: uBlock Origin v1.24.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7f8a1552d0d24b495ed9e0f7e970689ec8482e65
