### ISSUE TITLE
Slate.com images and videos (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by rpodric** [ryanbr/fanboy-adblock#13]
Hi. I've noticed for some weeks or maybe months on slate.com that certain pictures and videos are missing, but only when this particular filter is enabled. The examples I'll list below all happen to be Twitter-related, but I don't know if it's limited to Twitter. If I come across some non-Twitter examples I'll post back. Thanks.

[Missing a Twitter insert a few pages down](http://www.slate.com/articles/sports/sports_nut/2016/04/leicester_city_is_now_a_virtual_lock_to_win_the_premier_league_it_happened.html)

[Missing two Twitter videos](http://www.slate.com/blogs/the_slatest/2016/05/05/hillary_clinton_s_trump_attack_ads_hit_him_from_both_sides.html)

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/39a3f24061a6
