### ISSUE TITLE
Yahoo consent rules needs to be updated (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1304]
### Affected sites:
All sites which uses Yahoo's cookie consent service.

### Issue:
Sites can't be accessed, because the cookie consent popups are blocked, thereby preventing users from accepting the terms.

### Examples:
```
https://www.yahoo.com/
https://www.engadget.com/
```

### Screenshots:
Not needed, as the problem is obvious.

### Problem filters:
* EasyList Cookie List
* Fanboy's Annoyance List

### Problem rules:
```
##.consent-wrapper
###consent.consent
```

### Possible fix (allowing the cookie consent popups):
```
consent.yahoo.com#@#.consent-wrapper
consent.yahoo.com#@##consent.consent
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.16 (XUL)

**Comment by ryanbr** [comment]
Okay, what about `https://www.engadget.com/` @THEtomaso ?

**Comment by THEtomaso** [comment]
> what about `https://www.engadget.com/` ?

It uses Yahoo's GDPR consent.
When accessing engadget.com from my end, I'm redirected to consent.yahoo.com, to approve it.
