### ISSUE TITLE
minecraft.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1307]
### List the website(s) you're having issues:

`https://www.minecraft.net`

### What happens?

When i click on "sign in" i need to accept cookies but its not possible

### List Subscriptions you're using:

[settings.txt](https://github.com/ryanbr/fanboy-adblock/files/4151530/settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 72.02
- Adblock Extension/version: uBlock Origin v1.24.2

### Other details:

`@@/cookie-consent.$script,domain=minecraft.net` works for me

**Comment by THEtomaso** [comment]
More info:

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rule:
`/cookie-consent.`

### Other filters, containing the same problem rule:
* AdGuard Annoyances filter (@BlazDT)

**Comment by BlazDT** [comment]
Thank you, fixed in AdGuard filter.
