### ISSUE TITLE
New Common Cookie warning

### ISSUE THREAD

**Issue by spirillen** [ryanbr/fanboy-adblock#1309]
### List the website(s) you're having issues:

Hi @ryanbr @AnonymousPoster have submitted some "global" cookie warning to my private blocklist.

https://github.com/spirillen/ublockorigin-rules/pull/2/files#diff-91086c487b2f3500d215ad85d9132b91R5-R31 

Have a look, I believe these should go into the broader public list of yours.

Cheers

**Comment by ryanbr** [comment]
Should be taken care of in Easylist Cookie, can you confirm? @spirillen

**Comment by spirillen** [comment]
Not really :unamused: 

1. `https://www.fuglsangvvs.dk` -> `###cookie_box`

![image](https://user-images.githubusercontent.com/44526987/74078780-e2aa8b00-4a2e-11ea-8be2-bb14a913a877.png)

2. `https://bornholm.info` -> ##.cookie-box

![image](https://user-images.githubusercontent.com/44526987/74078802-0ff73900-4a2f-11ea-9753-22a0ece74872.png)

And of curse with a fresh update of filters

uBlock Origin v1.24.2
FF 
![image](https://user-images.githubusercontent.com/44526987/74078825-45038b80-4a2f-11ea-814b-f363ce0b452b.png)

**Comment by ryanbr** [comment]
We have `###cookie_box` and `##.cookie-box` generic so it should be taken care of

**Comment by spirillen** [comment]
Found the reason..... the `EasyList Cookie` wasn't enabled on that computer :thinking: but that is solved now :+1: and now I can of curse confirm.
