### ISSUE TITLE
NaturligLiv.no - Backdrop modal overlay (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1314]
### Affected site:
`https://naturligliv.no/`

### Issue:
Backdrop modal overlay covers the page.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
```
##.gdpr-popup
###gdpr-popup
```

### Possible fix (simply blocking the backdrop modal):
`naturligliv.no##.gdpr-overlay-container`

### Other problem filters:
* I don't care about cookies (@kiboke):
```
~totalcasino.pl##.gdpr-popup:not(body):not(html)
~tikkio.com,~pekao.com.pl###gdpr-popup
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.3 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.18 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by kiboke** [comment]
Thanks!
