### ISSUE TITLE
Cookie banner not blocked: aviationweek.com

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1317]
### List the website(s) you're having issues:
`https://aviationweek.com/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.24.4

**Comment by krystian3w** [comment]
`##.awn-cookie-compliance`
