### ISSUE TITLE
Website icon blocked: douban.com

### ISSUE THREAD

**Issue by sailfromhere** [ryanbr/fanboy-adblock#1318]
### List the website(s) you're having issues:

`douban.com`
`movie.douban.com`
`book.douban.com`
`music.douban.com`

### What happens?

Website icons for `douban.com` and all its subdomains are blocked/don't show up in Firefox. Unsubscribing from Fanboy’s Enhanced Tracking List or disabling uBlock Origin solves this issue.

### List Subscriptions you're using:

Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: macOS 10.15.3
- Browser/version: Firefox 73.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin v1.24.4

### Other details:

Icon for `douban.com` seems to come from `https://img9.doubanio.com/favicon.ico`

**Comment by krystian3w** [comment]
```
movie.douban.com
book.douban.com
music.douban.com
```

3-party but on home page is loaded as 1-party:

`||www.douban.com/favicon.ico$image,domain=www.douban.com`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cdcadd4f8fc971390742ba502157f1554829e81c
