### ISSUE TITLE
hartziv.org

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1319]
### List the website(s) you're having issues:
`https://www.hartziv.org/news/20200222-jobcenter-ueberweist-10-billionen-euro-leistungen-an-schule.html`

### What happens?

unblocked newsletter (after 20 seconds)

<img width="442" alt="newslttr456" src="https://user-images.githubusercontent.com/48647394/75119077-09e49780-5680-11ea-9d0e-85febc1f2615.PNG">

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/4242312/Settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 73.0.1
- Adblock Extension/version: uBlock Origin v1.24.4

**Comment by krystian3w** [comment]
`###cr_embeded_form`
