### ISSUE TITLE
PayPal Content Removed Incorrectly

### ISSUE THREAD

**Issue by bradandrews4** [ryanbr/fanboy-adblock#132]
https://forums.lanik.us/viewtopic.php?f=64&t=38045 
OP where I initially posted the issue.

One of the Moderator/Contributors of the forum provided this custom filter to try and resolve all the problems in my OP.

`@@||paypalobjects.com/*/opinionLab/$script,domain=paypal.com`

Upon adding this custom filter it seemingly rectified all problems that were being produced originally.

As such I am now providing the fix along with a link to my OP where you can see a full detailed description of what was being blocked on PayPal etc so that the fix can be applied to the next update.

Thanks for your time.
Brad

**Comment by ryanbr** [comment]
The forum post was removed, is it still happening?

**Comment by SMed79** [comment]
Not removed, merged here https://forums.lanik.us/viewtopic.php?p=123543#p123543

**Comment by bradandrews4** [comment]
yes sorry didn't see the notif @ryanbr however the thread was moved as pointed out above! Not sure if the issue is still happening as a member on the forum provided the custom filter which fixed it for me above... Was just providing the bug to the community for a fix for others as paypals a pretty widely used site and not having functionality over their Help system is the biggest pain!

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7efee2a7f75e338ce8613d1a6c408f6499882f57
