### ISSUE TITLE
lr-online.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1321]
### List the website(s) you're having issues:
`https://www.lr-online.de/`

### What happens?

unblocked cookie banner

### List Subscriptions you're using:

[Settings.txt](https://github.com/ryanbr/fanboy-adblock/files/4264835/Settings.txt)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 73.0.1
- Adblock Extension/version: uBlock Origin v1.25.0

### Other details:

`lr-online.de###dsgvo_info` blocks the cookie banner

**Comment by krystian3w** [comment]
maybe safe generic:

`###dsgvo_info`

**Comment by ryanbr** [comment]
Has been added as a generic. ^
