### ISSUE TITLE
Cookie banner not blocked: plu.mx

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#1324]
### List the website(s) you're having issues:
`https://plu.mx/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin 1.25.0

**Comment by krystian3w** [comment]
`###cookie-policy-bottom-banner`

**Comment by peace2000** [comment]
This is merged now, this can be closed
