### ISSUE TITLE
This line completely disables Mixer

### ISSUE THREAD

**Issue by NeoGanon** [ryanbr/fanboy-adblock#1325]
### List the website(s) you're having issues:
https://www.mixer.com
https://www.mixer.com/embed/player/

### What happens?
It makes mixer only open as a blank page even the embedded video players don't work

### List Subscriptions you're using:
Fanboy’s Enhanced Tracking List

### Your settings
Using just ublock and disabling all my other filters

- OS/version: Win7 & Win10 64 Bit
- Browser/version: Firefox Nightly 75.0a1 and Chrome 80.0.3987.132
- Adblock Extension/version: 1.24.4

### Other details:
narrowed it down to this filter messing it up 

mixer.com##+js(acis, gtag)

**Comment by ryanbr** [comment]
Was removed a while ago, closing
