### ISSUE TITLE
/foresee- rule breaks cdc.gov navigation

### ISSUE THREAD

**Issue by jawz101** [ryanbr/fanboy-adblock#1329]
### List the website(s) you're having issues:

`https://www.cdc.gov/coronavirus/2019-ncov/hcp/index.html
`
### What happens?

click on left-hand navigation menus.  nothing happens

### List Subscriptions you're using:

Fanboy's Enhanced Tracking Protection

### Your settings

uBlock Origin, Firefox, Windows

### Other details:
/foresee-
rule breaks navigation

**Comment by THEtomaso** [comment]
> `/foresee-`
> rule breaks navigation

Actually that's not the problem rule.

--

**Summary:**

### Problem filter:
* Fanboy's Enhanced Tracking List

### Problem rule:
`||cdc.gov/jscript/metrics/`

### Blocked script:
`https://www.cdc.gov/JScript/metrics/adobe/analytics_cdcgov.js`

### Possible fix:
`@@||cdc.gov/JScript/metrics/adobe/analytics_cdcgov.js$~third-party`

### Note:
Don't know this script's function, but it should probably be whitelisted too?:
`https://www.cdc.gov/JScript/metrics/topic_levels.js`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/ac92eff0b16939002e823e80f9f8a1fdd3c517f5
