### ISSUE TITLE
Annoyances list breaks cdc.gov

### ISSUE THREAD

**Issue by sumyungguy** [ryanbr/fanboy-adblock#133]
Hi, this page for example:
https://wwwnc.cdc.gov/eid/article/7/7/01-7705_article

Requires this to see the main content, which for some reason is inside a "share-bar" div:
wwwnc.cdc.gov#@##share-bar

Thanks.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ad4720dbd5973045479de2f719b39105f989cfc8
