### ISSUE TITLE
forbes.com ads placeholder with Fanboy's Enhanced Tracking List

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#1336]
### List the website(s) you're having issues:

https://www.forbes.com/sites/billybambrough/2020/04/09/billions-of-google-chrome-users-now-have-another-surprising-option/amp/
### What happens?

Empty ads placeholder with Fanboy's Enhanced Tracking List
### List Subscriptions you're using:

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media, Fanboy's Annoyances, Fanboy's Enhanced Tracking List
### Your settings
uBlock Origin

- OS/version: Windows 10 Pro 1909
- Browser/version: Chromium Edge Beta and Firefox 75
- Adblock Extension/version: uBlock Origin 1.24.4

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/2487e51b3eae69eb2e67047224da38287a35b8f4
