### ISSUE TITLE
gaming.youtube.com Cookie Not Filtered by Cookiemonster List

### ISSUE THREAD

**Issue by germaloney11** [ryanbr/fanboy-adblock#134]
Fanboy's Cookiemonster List isn't blocking the "Cookies help us deliver our services. By using our services, you agree to our use of cookies" message on gaming.youtube.com

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/05fb3c5768951d3f9a2630c3864a142ceadb7376
