### ISSUE TITLE
golem.de not blocked

### ISSUE THREAD

**Issue by C4R2T3N** [ryanbr/fanboy-adblock#135]
Cookie-Banner: `https://www.golem.de/`

This helps: `www.golem.de###golem-cookie-accept`

**Comment by ryanbr** [comment]
`###golem-cookie-accept`

Filter is generic, already in the list.

**Comment by SMed79** [comment]
Disabled by the `$generichide` filter in the **EasyList Germany**.
[#diff-5c13de32ac78af089fd2237d6774280fR3331](https://github.com/easylist/easylistgermany/commit/92fc2ca9ed824fa29450550ff845f49443588415#diff-5c13de32ac78af089fd2237d6774280fR3331)

**Comment by ryanbr** [comment]
Monzta will be editing EasyList Germany to fix this

**Comment by ryanbr** [comment]
Resolved.
