### ISSUE TITLE
AlternativeTo.net - Unable to report problems (EasyList Cookie List / Fanboy's Annoyance List) 

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1351]
### Affected site:
`https://alternativeto.net/`

### Issue:
Unable to report problems.

### How to reproduce:
1 - Go to `https://alternativeto.net/software/eset-internet-security/`
2 - Click on the big cogwheel button, and choose "Report a problem".
* Expected result: A report form should pop up at the bottom of the page.
* Actual result: Nothing happens (the form is blocked)!

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rule:
`alternativeto.net###bottomNotifier`

### Possible fix:
```
- alternativeto.net###bottomNotifier
+ alternativeto.net###iubenda-cs-banner
```

### Temporary fix:
```
alternativeto.net#@##bottomNotifier
alternativeto.net###iubenda-cs-banner
```

### Other problem filters:
* I don't care about cookies (same problem rule as the one mentioned above) @kiboke

### Reference (with screenshot):
`https://forum.palemoon.org/viewtopic.php?f=46&t=24308/`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by kiboke** [comment]
Thank you @THEtomaso !
Actually the problematic rule is old and not needed anymore, it's going to be removed from IDCAC.

**Comment by THEtomaso** [comment]
> Actually the problematic bottomNotifier rule is old and not needed anymore

Confirmed.
Each of these other rules (also present in IDCAC) both handles it on their own!:
```
###iubenda-cs-banner
||cdn.iubenda.com/cookie_solution$script,domain=~radiomontecarlo.net
```
