### ISSUE TITLE
Elring.* - Blurred pages (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1354]
### Affected sites:
```
https://www.elring.ae/
https://www.elring.cn/
https://www.elring.com/
https://www.elring.com.tr/
https://www.elring.de/
https://www.elring.fr/
https://www.elring.it/
https://www.elring.pl/
https://www.elring.pt/
https://www.elring.ru/
```

### Issue:
Blurred pages, because of blocked cookie consent popup.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rule:
`##.modal-cookie`

### Possible fix (allowing the cookie consent popup):
`elring.ae,elring.cn,elring.com,elring.com.tr,elring.de,elring.fr,elring.it,elring.pl,elring.pt,elring.ru#@#.modal-cookie`

### Reference (with screenshot):
`https://forum.palemoon.org/viewtopic.php?f=3&t=24359/`

### Other problem filters:
* I don't care about cookies (`~gillet-baustoffe.de,~goetzmoriz.com,~moelders.de##.modal-cookie:not(body):not(html):not(.show)`)
@kiboke

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.3 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by kiboke** [comment]
Thank you @THEtomaso
