### ISSUE TITLE
aixFOAM.* - Blurred pages (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1355]
### Affected sites:
```
https://www.aixfoam.com/
https://www.aixfoam.de/
https://www.aixfoam.dk/
https://www.aixfoam.fi/
https://www.aixfoam.fr/
https://www.aixfoam.nl/
https://www.aixfoam.se/
```

### Issue:
Blurred pages, because of blocked cookie consent popup.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
```
###cc-notification
###cc-notification-wrapper
```

### Possible fix (allowing the cookie consent popup):
```
aixfoam.com,aixfoam.de,aixfoam.dk,aixfoam.fi,aixfoam.fr,aixfoam.nl,aixfoam.se#@##cc-notification
aixfoam.com,aixfoam.de,aixfoam.dk,aixfoam.fi,aixfoam.fr,aixfoam.nl,aixfoam.se#@##cc-notification-wrapper
```

### Reference (with screenshot):
`https://forum.palemoon.org/viewtopic.php?f=3&t=24359/`

### Other problem filters:
* AdGuard Annoyances filter (`###cc-notification`) https://github.com/AdguardTeam/AdguardFilters/issues/55182/
* I don't care about cookies (`###cc-notification / ###cc-notification-wrapper`) @kiboke

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.3 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by kiboke** [comment]
Thank you, @THEtomaso
