### ISSUE TITLE
Cookie notice on Reddit

### ISSUE THREAD

**Issue by Okamoi** [ryanbr/fanboy-adblock#136]
Hi,

I'm not sure this notice appears all the time, but it does regularly. It started to happen when uBlock Origin switched from the list "EU: Prebake - Filter Obtrusive Cookie Notices" to "Fanboy’s Cookiemonster List"

The filter that worked (tested and confirmed just now) in the former list was `reddit.com###eu-cookie-policy`. Could it be added to Cookiemonster list ?

Also, should Cookiemonster list absorb all filters from EU Obtrusive Cookie Notices ?

Info from that list:
Title: Prebake - Filter Obtrusive Cookie Notices
Last modified: 04 May 2016 20:17 UTC
Homepage: http://prebake.eu
https://github.com/liamja/Prebake

When both lists are in place, the latter has 559 rules used out of 862. Even assuming some of those 559 rules should be removed because no longer in useful (last updated 4 May 2016), most of them probably still apply.

**Comment by ryanbr** [comment]
`###eu-cookie-policy`

Its a generic filter already, just tested via my UK VPN.. seems to work here?

**Comment by Okamoi** [comment]
This filter indeed exists in the Cookiemonster list. Unless it has been added today, this is odd because it would mean I had that filter but it wasn't triggered. Since this can't be reproduced reliably I'll keep an eye out and next time it pops up I'll check if Reddit doesn't randomly use another ID for its cookie policy notice. It coincided exactly with uBlock Origin's switch from one list to the other though.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5e0bc0dd4

Exisited since 2015.
