### ISSUE TITLE
wetter.com (breakage)

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1366]
### List the website(s) you're having issues:

`https://www.wetter.com/hd-live-webcams/deutschland/cologne-media-park/5977288734b55/`

### What happens?

broken player because the site `usercentrics.eu` is blocked

### List Subscriptions you're using:
<img width="398" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/83876841-c1864c80-a739-11ea-9c22-255b4e43bcc7.PNG">

### Your settings

- OS/version:  win 10
- Browser/version: Firefox 67.0.1
- Adblock Extension/version: uBlock Origin v1.27.10

**Comment by ryanbr** [comment]
Okay removed. too problematic. force an update.
