### ISSUE TITLE
WitteTools.com - Blocked elements (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1368]
### Afected site:
`https://www.wittetools.com/`

### Issue:
Certain elements won't load, due to a cookie consent, which is only partially blocked.

### Screenshot:
Not needed, as the problem is obvious, even on the site's front page.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
```
##.CookieNote
###cookienote
```

### Possible fix:
`wittetools.com/cookienote/`

### Other problem filters:
* AdGuard Annoyances filter (`##.CookieNote` / `###cookienote`)
https://github.com/AdguardTeam/AdguardFilters/issues/57086/

* I don't care about cookies (`##.CookieNote:not(body):not(html)` / `###cookienote`) @kiboke

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.10.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by kiboke** [comment]
@THEtomaso Thanks! IDCAC will block URLs containing `/cookienote/` instead. Exceptions are not needed in that case.

**Comment by THEtomaso** [comment]
> IDCAC will block URLs containing `/cookienote/` instead. Exceptions are not needed in that case.

Confirmed.
I've updated the first post, to reflect this.
