### ISSUE TITLE
inverse.com

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#1369]
### List the website(s) you're having issues:
`https://www.inverse.com/entertainment/snowpiercer-star-steven-ogg-interview`

### What happens?

Multiple empty ads placeholders thought the page.
<details><summary>Screenshot:</summary>

![adg](https://user-images.githubusercontent.com/29574622/82947931-a8a3cb80-9fc2-11ea-84c9-4da0e1e5059a.jpg)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List 

uBlock Origin 

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: 1.27.10

**Comment by THEtomaso** [comment]
Same thing @ `bustle.com`.

A bit of a warning though..
When I first blocked those things some weeks ago, I first tried to simply use `##[id^="ad-"]`
This turned out to be a mistake, as it caused certain browsers (e.g. Pale Moon) to trip over something, and become unreponsive!
To fix this issue, I came up with these rules, which works just fine:
```
bustle.com,inverse.com##div[id^="ad-"]:before
bustle.com,inverse.com##div[id^="ad-"]:xpath(..)
```
..but of course, these rules are not ABP-compatible, so a different approach is needed for EasyList.

**Comment by SeriousHoax** [comment]
> Same thing @ `bustle.com`.
> 
> A bit of a warning though..
> When I blocked those things some weeks ago, I first tried to simply use `##[id^="ad-"]`
> This turned out to be a mistake, as it caused certain browsers (e.g. Pale Moon) to trip over something, and become unresponsive!
> To fix this issue, I came up with these rules, which works just fine:
> 
> ```
> bustle.com,inverse.com##div[id^="ad-"]:before
> bustle.com,inverse.com##div[id^="ad-"]:xpath(..)
> ```
> 
> ..but of course, this solution is not ABP-compatible, so a different approach is needed for EasyList.

I reported this to adguard filters as well 2 weeks ago and this is the approach they took. Are this going to work for EasyList too? Take a look 
https://github.com/AdguardTeam/AdguardFilters/commit/48028379b38104e5b46ce0489fac91a3da66c4ae

**Comment by THEtomaso** [comment]
> Are this going to work for EasyList too?

Probably not.
ryanbr or Khrin will have to investigate.

**Comment by THEtomaso** [comment]
> https://github.com/AdguardTeam/AdguardFilters/commit/48028379b38104e5b46ce0489fac91a3da66c4ae

@AdamWr:
Like I pointed out above, you might want to take a look at `bustle.com` too.

**Comment by krystian3w** [comment]
Why here? Why not in EasyList official repository report "placeholders"?

**Comment by SeriousHoax** [comment]
> 
> 
> Why here? Why not in EasyList official repository report "placeholders"?

Sorry for that. Having this two repo is kind of confusing. I only came to know about the EasyList repo few days ago. Should I close this one and create a new one on EasyList? Or maybe someone fix the reported issue anyway.

**Comment by THEtomaso** [comment]
> Should I close this one and create a new one on EasyList?

It's not really necessary, since both repos have the same moderators.
Just keep it mind, for future reports.

**Comment by SeriousHoax** [comment]
Looks like it has been fixed in EasyList. Closing the issue.

**Comment by krystian3w** [comment]
Yes, EasyList added:

`###ad-1`
`###ad-2`
`###ad-3`
`###ad-4`
`###ad-5`
`##.adWrapper`

Probably the same advertising system was on another site.
