### ISSUE TITLE
progeeksblog.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#137]
```
###tt-share-count
##.ssf.fpss[style]
```
- http://i.imgur.com/NixsAFy.png

`https://www.progeeksblog.com/best-external-hard-drives/`

**Comment by ryanbr** [comment]
Still applies? not seeing it

**Comment by SMed79** [comment]
You have to scroll down to see it 

https://i.imgur.com/G7XxNrg.gif
http://i.imgur.com/ZWaR4jf.png
http://i.imgur.com/DcROQTd.png

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5fc0bc5a4367367c8c966782f9120dc871ef48b7
