### ISSUE TITLE
stern.de (breakage)

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1370]
### List the website(s) you're having issues:

`https://www.stern.de/p/plus/politik-wirtschaft/noch-ist-geld-da--so-sichern-sie-sich-6250-euro-renovierungszuschuss-vom-staat-9301098.html`

### What happens?

blank screen

### List Subscriptions you're using:

<img width="397" alt="Unbenannt2" src="https://user-images.githubusercontent.com/48647394/84999277-3a7d9f00-b151-11ea-9cf6-aa06aa7d4849.PNG">

### Your settings

- OS/version: win 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin v1.27.10

### Other details:

i can unbreak this with the filter `stern.de#@##toTop`

**Comment by Khrin** [comment]
It's already listed: https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_annoyance_allowlist_general_hide.txt#L29

**Comment by JobcenterTycoon** [comment]
looks like a bug now it works
