### ISSUE TITLE
ZDNet.com - Videos blocked (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1375]
### Affected site:
`https://www.zdnet.com/`

### Issue:
Modal overlay, unclickable items and unplayable videos, due to a blocked cookie consent, which needs to be accepted!

### Examples:
`https://www.zdnet.com/video/no-ads-no-trackers-former-google-executives-launch-alternative-search-engine/`
`https://www.zdnet.com/article/samsung-blu-ray-players-are-rebooting-in-a-loop-and-nobody-knows-why/`

### Screenshots:
Not needed, as the the problem is obvious.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`
`/privacy/optanon/*`

### Possible fix:
```
zdnet.com#@##onetrust-banner-sdk
zdnet.com#@##onetrust-consent-sdk
@@||zdnet.com^*/privacy/optanon/*$script
```

### Other problem filters:
* ~~**AdGuard Annoyances filter**
`###onetrust-consent-sdk`
https://github.com/AdguardTeam/AdguardFilters/issues/58146/~~
_FIXED_

* ~~**Frellwit's Swedish Filter**
`||cookielaw.org^$third-party`
https://github.com/lassekongo83/Frellwits-filter-lists/issues/77/~~
_FIXED_

* ~~**I don't care about cookies** (@kiboke)
`###onetrust-consent-sdk`
`||cookielaw.org/scripttemplates$script,domain=~orckpapershotgun.com|~usgamer.net|~eurogamer.net|~eurogamer.pl|~vg247.com`~~ _FIXED_

~~btw, kiboke; there's a typo in one of your above rules:
`orckpapershotgun.com` should be `rockpapershotgun.com` :)~~

* **MVPS HOSTS**
`geolocation.onetrust.com`
_NOTIFIED_

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.2.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by spirillen** [comment]
You should add this domain by it's root... <https://gitlab.com/my-privacy-dns/matrix/matrix/-/issues/181>

I have been blocking the entire domain for over a year without any known issues, So I suggest this rule

```python
||onetrust.com^
```

|id|name|type|content|ttl|
|--|----|----|-------|---|
|6333947|onetrust.com.rpz.mypdns.cloud|CNAME|.|345600|
|6333948|*.onetrust.com.rpz.mypdns.cloud|CNAME|.|345600|

**Comment by THEtomaso** [comment]
> I suggest this rule
> `||onetrust.com^`

Without additional whitelisting rules, that will definitely break things!

As you can see from my first post, **MVPS HOSTS** even breaks the videos with the following rule:
`geolocation.onetrust.com`

Besides, **EasyList Cookie List** already contains this rule:
`||onetrust.com^$third-party`
..but also these whitelistings, to prevent breakage:
```
@@||geolocation.onetrust.com/cookieconsentpub/$script
@@||onetrust.com/request/$xmlhttprequest
```

I suspect that the reason why `||onetrust.com^` has worked for you, is that you've been taking advantage of whitelisting rules, found in other filters.
Try adding `$important` behind it, and see what happens! :)

**Comment by spirillen** [comment]
Hi @THEtomaso :rofl: 

Nope, no whitelisting beneficiary :+1: it's a NXDOMAIN, as you can see in this [rules guide](https://www.mypdns.org/w/rpz/#the-quot-nxdomain-quot-action) for RPZ


```
onetrust.com.rpz.mypdns.cloud CNAME . ; return NXDOMAIN
*.onetrust.com.rpz.mypdns.cloud CNAME . ; return NXDOMAIN
```

```bash
dig onetrust.com

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 63699
;onetrust.com.                  IN      A

;; Query time: 124 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
```

```bash
$ drill onetrust.com
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 19541
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; onetrust.com.        IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 155 msec
```

About the `MVPS` <https://www.mypdns.org/w/blacklists/mvps/#what-does-mvps-means>, I was reading it as you had suggested them to add it :unamused: 

Unfortunately I can't test the yt embed as yt is on the private `rcode 3` list, but as written earlier, nobody have been reporting any issues about it. Original report: <https://gitlab.com/my-privacy-dns/matrix/matrix/-/issues/181>.

And then there of curse the opinion on how strict rules should be :imp: EasyList is `We don't like to break` and mine... well... should be well known by now :smiley: 

At the end of writing all these letters, it crosses my mind... isn't there a `enhanced tracking protection` list? then your suggestion could make it to the general list and mine to the enhanced..., then only most users can those for them self...

**Comment by kiboke** [comment]
@THEtomaso thanks!

**Comment by THEtomaso** [comment]
The problem has gotten worse..
There's a modal overlay too now, which covers the page and make things unclickable!
_*First post updated*_

**Comment by THEtomaso** [comment]
_Yet another problem rule added to the first post._
(reported by stm-x here https://github.com/easylist/easylist/issues/9177 )

**Comment by THEtomaso** [comment]
Not fixed.
The two problem rules, which I originally posted 15 months ago, still prevents some videos fom being played.
_See first post._
