### ISSUE TITLE
vollmacht-muster.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1378]
### List the website(s) you're having issues:

`https://www.vollmacht-muster.de/gesundheitsvollmacht/`

### What happens?

i need to accept cookies (because scroll is blocked) but i cant

### List Subscriptions you're using:

<img width="343" alt="85469579-23eea200-b5ae-11ea-9dc9-3de335330852" src="https://user-images.githubusercontent.com/48647394/86028518-4101f580-ba32-11ea-87f6-c6fe43ad7f1d.PNG">

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin v1.27.10

**Comment by krystian3w** [comment]
`vollmacht-muster.de#@##cookie-law-info-bar`

`Datenschutzerklärung` - GDPR? If yes so not bolockable also in `uBlock Annoyance`.

**Comment by krystian3w** [comment]
Cookie script have randomized name: 

`https://www.vollmacht-muster.de/wp-content/cache/min/1/337ebe0bfa914414aaee7916e66c13c1.js` 

there's a chance it has other important codes in it - I see YouTube downstairs.
