### ISSUE TITLE
www.tygodniksiedlecki.com

### ISSUE THREAD

**Issue by gomoku** [ryanbr/fanboy-adblock#138]
One of Fanboyz Cookiemonster's filter breaks a header's slide-menu as seen on the screenshoot, you have to add the exception filter: 
`@@||tygodniksiedlecki.com/assets/mobile/cookiebar/jquery.cookiebar.js$script,first-party`
By the way the whole website has been found just right now, and has turned out to be extremely littered by ads & ads remaings & banners & sliders and is being cleaned at the moment by our polish teams in our PL filters lists:
https://github.com/azet12/PopupBlocker/issues/136 and https://github.com/MajkiIT/polish-ads-filter/issues/3776

![](https://s3.dodajfote.pl/2017/09/23/headermenudb6fc.png)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/4359626d082c7904ae2a58bf168754e5572acc2c
