### ISSUE TITLE
vioma.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1380]
### List the website(s) you're having issues:

`https://www.vioma.de/de/wiki/tools/html-sonderzeichen/`

### What happens?

unblocked cookie banner
<img width="344" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/86187403-fec4db00-bb3b-11ea-9ae5-ce5c9e887319.PNG">

### List Subscriptions you're using:

<img width="343" alt="86028518-4101f580-ba32-11ea-87f6-c6fe43ad7f1d" src="https://user-images.githubusercontent.com/48647394/86187373-ece33800-bb3b-11ea-9986-adf84df5544d.PNG">

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin v1.27.10

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/dfb417b8a362ef5868dca2ddeabe76dd59faeceb
