### ISSUE TITLE
Annoyance request: Ali Express

### ISSUE THREAD

**Issue by yokoffing** [ryanbr/fanboy-adblock#1381]
***Description***: AliExpress shows the same pop-up offering a coupon no matter despite viewing multiple products on their site.
* **Current behaviour**:  https://postimg.cc/GHtwVfpB

**Comment by krystian3w** [comment]
Blocked scroll, so not for AdBlock or ABP.

PS. Fixed in uBO after enable `uBlock filters – Annoyances`
