### ISSUE TITLE
DNBEiendom.no - Modal backdrop (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1382]
### Affected site:
`https://dnbeiendom.no/`

### Issue:
The page is covered by a modal backdrop, because of blocked cookie consent popup.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rule:
`###cookieConsentPopup`

### Possible fix:
`dnbeiendom.no##.modal-backdrop`

### Other problem filters:
* I don't care about cookies (`###cookieConsentPopup`) @kiboke

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.10.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.23b2 (XUL)

**Comment by kiboke** [comment]
@THEtomaso Thank you!
