### ISSUE TITLE
webutation.net blocked

### ISSUE THREAD

**Issue by JimLoose** [ryanbr/fanboy-adblock#1386]
### List the website(s) you're having issues:

https://www.webutation.net/

### What happens?

site is completely blocked

### List Subscriptions you're using:

Fanboys Enhanced Tracking List

### Your settings

no extensions only NextDNS

- OS/version: MacOS
- Browser/version: Firefox
- Adblock Extension/version: NextDNS

### Other details:

none

**Comment by spirillen** [comment]
Hmm doesn't seems like a big loss

![image](https://user-images.githubusercontent.com/44526987/88463534-b3d88200-ceb3-11ea-8f3d-cc4d5ddfcabf.png)

100 out of 100?? on a malicious spyware/tracking/adware site? not exactly what I consider trustworthy.

**Comment by krystian3w** [comment]
@nextdns why you convert this into "hosts" format?

https://github.com/ryanbr/fanboy-adblock/blob/7cd69e482b93f78dd5a91d55bd152fd768da2adf/enhancedstats-addon.txt#L816

`^$third-party ` is not same as:

```
||webutation.net^$document
||webutation.net^$all
||webutation.net^
```

```
0.0.0.0 webutation.net
127.0.0.1 webutation.net
```

**Comment by krystian3w** [comment]
https://github.com/nextdns/metadata/issues/368

**Comment by ryanbr** [comment]
Fixed
