### ISSUE TITLE
A: Add Apple's favicon to whitelist

### ISSUE THREAD

**Issue by DRSDavidSoft** [ryanbr/fanboy-adblock#1387]
### List the website(s) you're having issues:

- `https://appleid.apple.com/`

#### Fanboy’s Enhanced Tracking List 
```
/favicon.ico$image,3p,domain=~douban.com|~bahn.de|~winfuture.de|~bt.com|~ebay.com.au|~ebay.com|~ebay.co.uk|~go.com|~github.com|~stackexchange.com|~stackoverflow.com|~askubuntu.com|~reddit.com|~4chan.org|~twitter.com|~live.com|~espn.com|~yahoo.com
```

### Other details:

- **Context:** `appleid.apple.com`
- **Partyness:** (3) apple.com ⇒ cdn-apple.com
- **Type:** image
- **URL:** `https://appleid.cdn-apple.com/static/bin/cb3606853004/images/favicon.ico`

**Comment by krystian3w** [comment]
`cb3606853004` - stable not your PC "id"?

**Comment by llacb47** [comment]
> `cb3606853004` - stable? not your PC "id"?

`view-source:https://appleid.apple.com/#!&page=signin`

```
<link rel="shortcut icon" type="image/x-icon" href="https://appleid.cdn-apple.com/static/bin/cb3606853004/images/favicon.ico">
```

**Comment by DRSDavidSoft** [comment]
@krystian3w Of course, I checked from multiple sources before opening this issue.  However, if this part `cb3606853004` is somehow actually used to **track** the user, it should definitely _NOT_ be whitelisted according to the list's policy (Fanboy’s Enhanced Tracking List).

Can other people also please verify if this URL is being used for tracking purposes?
