### ISSUE TITLE
volkskrant.nl / dpgmedia.net

### ISSUE THREAD

**Issue by practik** [ryanbr/fanboy-adblock#1388]
When I try to access pages of the Dutch newspaper de Volkskrant, I am taken to a cookie notice on an entirely different site.  For example, if I try to go to this story:

`https://www.volkskrant.nl/cultuur-media/the-last-black-man-in-san-francisco-is-een-poetisch-droomdebuut~bf14b06c/`

I end up here instead:

`https://myprivacy.dpgmedia.net/?siteKey=PUBX2BuuZfEPJ6vF&callbackUrl=https%3a%2f%2fwww.volkskrant.nl%2fprivacy-wall%2faccept%3fredirectUri%3d%252fcultuur-media%252fthe-last-black-man-in-san-francisco-is-een-poetisch-droomdebuut%257ebf14b06c%252f`

![Screenshot_2020-07-30 Privacy settings](https://user-images.githubusercontent.com/12074235/88975098-e1884700-d276-11ea-84ba-dc3a3422f202.png)

Is there way to prevent or bypass this hijacking?

I'm using uB0 1.28.4 with all of its default filter lists plus EasyList Cookie, EasyPrivacy and uBlock Annoyances, on Firefox 78.0.2.

EDIT: I also tried installing the EasyList Dutch filter list but it didn't help with this.

**Comment by spirillen** [comment]
Find a trustworthy site and "news" media that is pro democracy

They are giving shit in your privacy and democratic rights

```
Cookies van onszelf en van derden kunnen worden gebruikt om advertenties te tonen en artikelen aan te bevelen op de websites en apps van DPG Media die aansluiten op uw interesses.
```
