### ISSUE TITLE
When using https://tweetdeck.twitter.com/, the User column doesn't display

### ISSUE THREAD

**Issue by bontchev** [ryanbr/fanboy-adblock#1389]
### List the website(s) you're having issues:

`https://tweetdeck.twitter.com/`

### What happens?

The contents of the User column is not displayed. Instead, a spinner is shown, suggesting that the column is constantly (but futilely) tried to be updated.

In addition, when displaying someone's profile (even your own), the button that normally reads Edit profile/Follow/Following is shown the same spinner and no text.

### List Subscriptions you're using:

I'm using uBlock Origin. There is no point enumerating all my subscriptions, because I know which particular list is causing the problem and even which particular rule in this list is causing it; see below.

### Your settings

- OS/version: Windows 7 Pro
- Browser/version: Opera Portable 69.0.3686.81
- Adblock Extension/version: uBlock Origin version 1.28.4

### Other details:

The problem is caused by the Fanboy's Annoyance list. The offending rule is

`||api.twitter.com^*/user_timeline/$third-party`

If I disable the Fanboy's Annoyance list, TweetDeck works correctly. Among the list of blocked elements displayed by uBlock Origin, the above rule is the only one which results in blocked elements and comes only from the Fanboy's Annoyance list. All the other blocked elements are blocked by rules present on other lists too.

**Comment by ryanbr** [comment]
I'm  not seeing this @bontchev  is it still applicable?

**Comment by bontchev** [comment]
It is not. Turning on Fanboy's Annoyance list no longer blocks TweetDeck's User column. I don't know what has changed - the list contents (I updated it before testing) or TweetDeck. Closing the issue, then.
