### ISSUE TITLE
rp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#139]
@ryanbr RSS icon on left side is blocked. So can you add whitelist to Social list?
`@@||www.rp.pl/public/img/generic/toolbar/social_toolbar_all.png`

**Comment by ryanbr** [comment]
what is exactly is the false positive?

**Comment by hawkeye116477** [comment]
@ryanbr Yes, it's false positive.
It looks so ![82460e9c-b7c0-4d4d-a7ef-a7af5b7a89b7](https://user-images.githubusercontent.com/19818572/30777437-be73a8fe-a0ba-11e7-86c9-d8db450fb283.png)
Should look so ![6b505dbc-33fb-463b-8dc8-1301a9e90462](https://user-images.githubusercontent.com/19818572/30777436-bd65a8d6-a0ba-11e7-8e27-36dc2f60f4ae.png)

**Comment by ryanbr** [comment]
What I see;

![rppl](https://user-images.githubusercontent.com/1659004/30777520-9e8e6124-a118-11e7-9f1a-c42ccefdf69a.png)

**Comment by ryanbr** [comment]
If I whitelist it, the element doesn't show

**Comment by hawkeye116477** [comment]
@ryanbr This icon maybe not visible on some resolutions, I saw it when I closed Vivaldi's sidebar. Try with maximised window.

**Comment by ryanbr** [comment]
Ah yes, This should be better?

`##.toolbar-linkedin
##.toolbar-facebook
##.toolbar-twitter

@@||rp.pl/img/generic/toolbar/social_toolbar_all.png`

**Comment by hawkeye116477** [comment]
@ryanbr Yes, that's right.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/60759e46974d49bd394299767c1176ba89cc43f0

**Comment by hawkeye116477** [comment]
Thanks
