### ISSUE TITLE
Stabila.com - Blank page / broken page scrolling (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1390]
### Affected site:
`https://www.stabila.com/`

### Issues:
Unable to access site (blank page), and broken page scrolling!

### Example:
`https://www.stabila.com/en-US/products-553/list/standard-spirit-levels.html`

### Screenshot:
Not needed, as the the problem is obvious.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
```
##.cookie-bar-visible
/cookie-bar.
```

### Possible fix:
```
stabila.com#@#.cookie-bar-visible
@@||stabila.com/bundles/marketingsuite/css/cookie-bar.css
```

### Other problem filters:
* AdGuard Annoyances filter (`/cookie-bar.`)
https://github.com/AdguardTeam/AdguardFilters/issues/60633/

* I don't care about cookies (`##.cookie-bar-visible .mod_cms_accept_tags`) @kiboke

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.11.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.24 (XUL)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/fedd2b71f993c929b8ba39b35f8e1adf82919259

**Comment by kiboke** [comment]
Thank you @THEtomaso, it will be fixed in IDCAC.
