### ISSUE TITLE
picnic.app (breakage)

### ISSUE THREAD

**Issue by JobcenterTycoon** [ryanbr/fanboy-adblock#1391]
### List the website(s) you're having issues:

`https://www.picnic.app`

### What happens?

the black background is unblocked
<img width="519" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/89189646-95077900-d5a0-11ea-85c2-aa8501da9aaa.PNG">

### List Subscriptions you're using:

<img width="348" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/89189585-799c6e00-d5a0-11ea-92e2-991118e67c0e.PNG">

### Your settings

- OS/version: win 10
- Browser/version: Firefox 79
- Adblock Extension/version: uBlock Origin v1.28.4

**Comment by krystian3w** [comment]
`picnic.app#?##modal:-abp-has(~ #cookie-modal)`

IDK maybe EasyList add without use `:-abp-has(~ #cookie-modal)` (IMO can break many other modals).

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/85f27c364edb18cad8f42898b0db63fa4a900b62
