### ISSUE TITLE
Amazon.* - Unable to fetch return labels (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1393]
### Affected sites:
```
https://www.amazon.ae/
https://www.amazon.ca/
https://www.amazon.cn/
https://www.amazon.co.jp/
https://www.amazon.co.uk/
https://www.amazon.com/
https://www.amazon.com.au/
https://www.amazon.com.br/
https://www.amazon.com.mx/
https://www.amazon.com.tr/
https://www.amazon.de/
https://www.amazon.es/
https://www.amazon.fr/
https://www.amazon.in/
https://www.amazon.it/
https://www.amazon.nl/
https://www.amazon.sg/
```

### Issue:
When returning items at Amazon, users are unable to fetch the return labels, because of a missing button!

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`###button-share`

### Screenshot (problem rule whitelisted):
![filterissue-amazon](https://user-images.githubusercontent.com/9382674/89765756-39387500-daf7-11ea-9339-00a5e8d98482.jpg)

### Possible fix:
`amazon.ae,amazon.ca,amazon.cn,amazon.co.jp,amazon.co.uk,amazon.com,amazon.com.au,amazon.com.br,amazon.com.mx,amazon.com.tr,amazon.de,amazon.es,amazon.fr,amazon.in,amazon.it,amazon.nl,amazon.sg#@##button-share`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.12.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.24 (XUL)

**Comment by krystian3w** [comment]
e-mail = social on `Fanboy Annoyance` / `Fanboy social`

I guess politics is gonna force the pop-ups `Send copy of label` out there?

**Comment by THEtomaso** [comment]
Alternatively, this will fix the issue too:
- ###button-share
+ ###button-share:not(.a-button)

![filterissue-amazon2](https://user-images.githubusercontent.com/9382674/90321584-6350c380-df4b-11ea-8a09-f561310eb587.jpg)
