### ISSUE TITLE
CRFashionBook.com - Embedded videos blocked (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1395]
### Affected site:
`https://www.crfashionbook.com/`

### Issue:
Embedded videos are missing, because of a blocked cookie consent, which needs to be accepted!

### Example:
`https://www.crfashionbook.com/culture/a33406305/`

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rules:
```
###onetrust-consent-sdk
||cookielaw.org^$third-party
||onetrust.mgr.consensu.org^$third-party
```

### Screenshot:
Not needed, as the problem is obvious.

### Possible fix:
```
crfashionbook.com#@##onetrust-consent-sdk
@@||cookielaw.org^$third-party,domain=crfashionbook.com
@@||onetrust.mgr.consensu.org^$third-party,domain=crfashionbook.com
```

### Other problem filters:
* ~~AdGuard Annoyances filter https://github.com/AdguardTeam/AdguardFilters/issues/61278/~~ _(FIXED)_
~~`###onetrust-consent-sdk`
`||consensu.org^$third-party`
`||cookielaw.org^$third-party`~~

* ~~Frellwit's Swedish Filter https://github.com/lassekongo83/Frellwits-filter-lists/issues/80/~~ _(FIXED)_
~~`||consensu.org^$third-party,domain=~joe.ie|~mirror.co.uk|~sourceforge.net|~sportsjoe.ie|~vi.nl`
`||cookielaw.org/scripttemplates$script,domain=~eurogamer.net|~eurogamer.pl|~rockpapershotgun.com|~usgamer.net|~vg247.com|~zdnet.com`~~

* I don't care about cookies (@kiboke)
`~vg247.com,~usgamer.net,~rockpapershotgun.com,~eurogamer.net,~eurogamer.pl,~zdnet.com###onetrust-consent-sdk`

* MVPS HOSTS _(NOTIFIED)_
`geolocation.onetrust.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.12.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.24 (XUL)

**Comment by spirillen** [comment]
<details><summary>Own note</summary>

<https://www.mypdns.org/T943>

</details>

**Comment by THEtomaso** [comment]
We all understand that it's used for tracking, spirillen, so you don't have to point it out at every turn.
With the exception of **MVPS HOSTS** however, all of the filters which I mentioned in my first post will prioritize functionality in these matters.
As you very well know, whitelistings are easely overriden by `$badfilter` rules and such, which belongs in more strict filters (like your own).
All I'm saying is that there's no need for all of these references that you keep on posting!

Don't get me wrong though..
If you need any help with creating such strict rules, I'm still willing to lend a hand, every now and then. :)

**Comment by spirillen** [comment]
> We all understand that it's used for tracking, spirillen, so you don't have to point it out at every turn.

Why do you think I made the note "hidden" :wink: : it is for personal cross reference `no mo, no less` (the when, where, why)

> Try adding these rules to your anti-whitelist filter

As I recalls it, there was a reason it was preferably to do it the other way as some `@@` rules actually did overrule these

> Of course, this will also cause various types of breakage, on a huuuge amount of websites, but as I've understood it, this would be preferable to you?

Njaa, I would prefer the internet wasn't weaponized against democracy and privacy = freedom

**Yes**, I for sure have no issue disabling such sites by blocking there malicious spyware.

> will prioritize functionality

You'll for sure opens a debate with this, but I'm going to leave that for another place, as it would turn this issue into a derailed debate to the OP

>  I'm still willing to lend a hand, every now and then. :)

Thanks, I'm very appreciative for that :+1:

**Comment by THEtomaso** [comment]
@Khrin:
> https://github.com/easylist/easylist/commit/65f79240117e330fc8a9fab7cd6940c08974565f

Unkfortunately, these whitelistings aren't sufficient.
`https://cdn.cookielaw.org/vendorlist/iab2Data.json` is still blocked by `||cookielaw.org^$third-party`.
As a result, the cookie consent is still prevented from loading, and the embedded videos remains blocked!

**Comment by Khrin** [comment]
Sorry, now should be correctly fixed. https://github.com/easylist/easylist/commit/fc492bf418d0d0d40bf12b2f479433a2789f8ca8

**Comment by kiboke** [comment]
@THEtomaso thank you, it will be fixed in IDCAC!
