### ISSUE TITLE
TheTechSutra.com - Missing scrollbar (EasyList Cookie List / Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1397]
### Affected site:
`https://thetechsutra.com/`

### Issue:
The page appears to be frozen (missing scrollbar), because of a blocked newsletter popup, which appears after about 3 seconds.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* EasyList Cookie List (a.k.a. Fanboy's Cookie List)
* Fanboy's Annoyance List

### Problem rule:
`##.cp-overlay`

### Possible fix:
`thetechsutra.com#@#.cp-overlay`

### Other problem filters:
* ~~**AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/61850/~~ _FIXED_
~~`/wp-content/plugins/convertplug/*`~~

* ~~**Frellwit's Swedish Filter** https://github.com/lassekongo83/Frellwits-filter-lists/issues/83/~~ _FIXED_
~~`/plugins/convertplug/*`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.12.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.25b2 (XUL)

**Comment by spirillen** [comment]
I've added these two rules for testing, and now the site is at least to be browsed (read)

```
! 2020-08-20 thetechsutra.com
||thetechsutra.com/wp-content/cache/*$script,important
||thetechsutra.com/cdn-cgi/scripts/*/cloudflare-static/email-decode.min.js$script,important
```

**Comment by THEtomaso** [comment]
They also break embedded videos.
Example:
`https://thetechsutra.com/16-inch-macbook-pro/`

I've told you before, spirillen..
Please stop posting/refering to those strict rules of yours.
They only cause breakage!

**Comment by spirillen** [comment]
I don't see the breakage in my end...

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/90764723-0f4a3400-e2e9-11ea-89ef-1c41de690c78.png)

</details>

And sorry, was just trying to give you a suggestion to workaround your issue

PS: I wasn't linking to my rules, but I DO keep history and ref links to where I got info from in the commit message as it keeps the repo transferable with full history

**Comment by THEtomaso** [comment]
Then please put your GitHub links in a code box, and stop mentioning my name.
I appreciate that you're creating a strict block list, but I don't want to be notified every time that you decide to override a whitelisting that is related to any of my reports.
