### ISSUE TITLE
mod-cookiepolicy

### ISSUE THREAD

**Issue by mapx-** [ryanbr/fanboy-adblock#140]
new cookie element on:
`http://www.mirror.co.uk/tv/tv-news/simon-cowell-just-out-louis-11227330`

mirror.co.uk##.mod-cookiepolicy

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/5b3692ad7672eb2b0cf8a3d27b113b7be8aac87e
