### ISSUE TITLE
GoFugYourself.com - Disappearing navbar (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1400]
### Affected site:
`https://www.gofugyourself.com/`

### Issue:
Disappearing navbar on subpages.

### Example:
`https://www.gofugyourself.com/picard-has-premiered-01-2020/`
(Scroll down, then back up again)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rules:
```
##.social-container
##.social-holder
##.social-icons
```

### Possible fix:
```
- cheezburger.com,epicgames.com#@#.social-container
- deathandtaxesmag.com,hostinger.ae,hostinger.com.br,hostinger.com.ua,hostinger.fr,hostinger.in.th,hostinger.it,hostinger.kr,hostinger.lt,hostinger.my,hostinger.ph,hostinger.pl,hostinger.pt,hostinger.ro,hostinger.ru,hostinger.vn,hostinger.web.tr,spin.com,stereogum.com,vibe.com#@#.social-holder
- deathandtaxesmag.com,ourweigh.in,spin.com,stereogum.com,vibe.com,viewbug.com#@#.social-icons

+ cheezburger.com,epicgames.com,gofugyourself.com#@#.social-container
+ deathandtaxesmag.com,gofugyourself.com,hostinger.ae,hostinger.com.br,hostinger.com.ua,hostinger.fr,hostinger.in.th,hostinger.it,hostinger.kr,hostinger.lt,hostinger.my,hostinger.ph,hostinger.pl,hostinger.pt,hostinger.ro,hostinger.ru,hostinger.vn,hostinger.web.tr,spin.com,stereogum.com,vibe.com#@#.social-holder
+ deathandtaxesmag.com,gofugyourself.com,ourweigh.in,spin.com,stereogum.com,vibe.com,viewbug.com#@#.social-icons
```

### Temporary fix:
```
gofugyourself.com#@#.social-container
gofugyourself.com#@#.social-holder
gofugyourself.com#@#.social-icons
```

### Other problem filters:
* ~~**AdGuard Social Media filter** https://github.com/AdguardTeam/AdguardFilters/issues/62008/~~ _FIXED_
~~`~meditopia.com,~nippononline.ru,~onitsukatiger.com,~symfonycasts.com,~blog.avast.com,~slovnyk.ua,~obserwatorgospodarczy.pl,~militarytimes.com,~adn.com,~programmingwithmosh.com,~ctc.ru,~theweathernetwork.com,~gardenista.com,~kino.de,~theatlantic.com,~cont.ws,~ispo.com,~petri.com,~howtogeek.com,~diatribe.org,~acura.com,~avito.ru,~gamingbolt.com,~vanion.eu,~willdev.in,~am-play.de##.social-icons`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.12.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.25b2 (XUL)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/15b115419388a1ef4f3d43af15b2629f82997967
