### ISSUE TITLE
chip.de incorrectly removed content

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [ryanbr/fanboy-adblock#142]
fanboys annoyances list blocks images from loading at: 
http://www.chip.de/video/software

<img width="790" alt="chip de" src="https://user-images.githubusercontent.com/23087597/30815133-89f78592-a212-11e7-9d6c-e4b4ace38296.png">

**Comment by sdfasdfgawe456h4356** [comment]
works. 👍 @SMed79

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4361b6956a934c7d54e7f936ff1bc18c49b93136
