### ISSUE TITLE
Fanboy's Enhanced Tracking List is blocking reCAPTCHA on Last.fm

### ISSUE THREAD

**Issue by Palf994** [ryanbr/fanboy-adblock#143]
When trying to reset a forgotten password on Last.fm, having Fanboy's Enhanced Tracking List enabled in uBlock Origin prevents the reCAPTCHA from loading properly. The Last.fm##div[style*="visibility:"] filter seems to be the problem.

Thanks for your hard work maintaining this project.

**Comment by ryanbr** [comment]
Through the signup process? I get the tickbox reCaptcha fine?

**Comment by Palf994** [comment]
No, during the process for retrieving and resetting a forgotten password. It worked fine for me during the sign-up procedure too.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/2cda9e6c5a4bfd048b54ba0033c6aab149c53914

Disabled for the time being, will look at a better filter when I get a chance.
