### ISSUE TITLE
nextdoor.com broken authorisation

### ISSUE THREAD

**Issue by Sergey-Lyapin** [ryanbr/fanboy-adblock#1431]
Fanboy's Annoyances (most likely rule `||nextdoor.com^$third-party`) breaks authorisation on nextdoor.com in Safari (mobile and desktop). For example this `@@||nextdoor.com^$domain=nextdoor.com` helps.

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/67077

**Comment by Khrin** [comment]
no exact url, if any?

**Comment by Sergey-Lyapin** [comment]
> no exact url, if any?

@Khrin click "Log in" at the american version of nextdoor.com and try to authorise
