### ISSUE TITLE
Nytimes.com/wirecutter newsletter banner

### ISSUE THREAD

**Issue by rpodric** [ryanbr/fanboy-adblock#1432]
### List the website(s) you're having issues:

`https://www.nytimes.com/wirecutter`

### What happens?

Newsletter banner is on essentially every page. 

### List Subscriptions you're using:
Default uBO + Fanboy's Annoyance

### Your settings

- OS/version: Win10
- Browser/version: Chrome 86
- Adblock Extension/version: uBO 1.30.6

### Other details:

1) The element name changes on each page, so it may not be straightforward to do.
2) An attempt was made at it before [here](https://github.com/ryanbr/fanboy-adblock/issues/1124), but those two changes refer to an obsolete URL (thewirecutter.com) and should now be removed (I don't think those particular fixes would apply now anyway).

**Comment by ryanbr** [comment]
Picked the cookie message, not seeing the newsletter tho.

**Comment by Yuki2718** [comment]
@ryanbr Don't you see this blue banner?

![nytimes](https://user-images.githubusercontent.com/58900598/99668285-df115d80-2ab0-11eb-8b47-745c9ac3d9e1.png)

Apparently randomly named class names, maybe `nytimes.com###__next > div[class][aria-hidden="false"]` or `nytimes.com###__next > #main[aria-live="assertive"] + div[class][aria-hidden="false"]` if you mind false positive.

**Comment by rpodric** [comment]
Thanks, I'll run with the first one you mentioned and see if it causes any problems. It looks like it's working so far though.

BTW, there are numerous references to thewirecutter.com in Fanboy's Annoyance that can go since that domain is just a redirect now. Always good when we can reduce.
