### ISSUE TITLE
digital.aakash.ac.in Broken favicons on some websites, other websites as well.

### ISSUE THREAD

**Issue by ectoanonymous** [ryanbr/fanboy-adblock#1433]
**### List the website(s) you're having issues:**
https://digital.aakash.ac.in/
https://techcommunity.microsoft.com/t5/discussions/

**### What happens?**
Favicons of these websites are not loading (or loading properly)

**### List Subscriptions you're using:**
I checked with all others filters and this one _(Fanboy’s Enhanced Tracking List)_ was the reason for such behavior. 

**### Your settings**
- OS/version: Window 10 20H2
- Browser/version: Microsoft edge (chromium)
- Adblock Extension/version: 1.30.6

**### Other details:**
I've checked by enabling and disabling the extensions and each and every filter lists, and this one _(Fanboy’s Enhanced Tracking List)_ was the reason for such behavior.

**Comment by ryanbr** [comment]
Its expected, we block 3rd-party favicons due to privacy issues.
