### ISSUE TITLE
svenskhalsokost.se - broken website

### ISSUE THREAD

**Issue by BourbonCrow** [ryanbr/fanboy-adblock#1436]
`svenskhalsokost.se` is breaking and only shows a blank page when using EasyList Cookie List or the combined variant Fanboy's Annoyances (i tried all filters 1 by 1 and it only breaks using this specific filters)

[Gallery](https://imgur.com/a/gkYul47)  with filter ON and OFF to showcase the issue

- OS/version: Windows 10 Enterprice LTSC 1809 OS build 17763.1577
- Browser/version: Firefox 83.0
- Adblock Extension/version: AdGuard for Windows 7.6 nightly 3

**Comment by BourbonCrow** [comment]
`<body class="default mobile-open-search mobile-sticky-search cookie-accept">` that row is the problem if you remove `cookie-accept` from it and make it only `<body class="default mobile-open-search mobile-sticky-search">` i would do it my self but i have no idea how to

**Comment by THEtomaso** [comment]
### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`##.cookie-accept`

### Possible fix:
`svenskhalsokost.se#@#.cookie-accept`
