### ISSUE TITLE
Fanboy's Cookiemonster List - Twitch.tv

### ISSUE THREAD

**Issue by aroboto** [ryanbr/fanboy-adblock#144]
On Twitch.tv the `twitch.tv##.alert` filter is blocking the delete text of a box on the sites channel feed feature.

With the filter
![mohm9m7 1](https://user-images.githubusercontent.com/22084203/31155113-c39d03e8-a8a3-11e7-868a-4b7ea8d061eb.png)

Without the filter 
![spt127u 1](https://user-images.githubusercontent.com/22084203/31155133-e61b32c8-a8a3-11e7-83b5-c9a72c8635fb.png)

**Comment by ryanbr** [comment]
Can you check if any of these filters cause false positives?

twitch.tv###noty_bottomCenter_layout_container
twitch.tv##.noty_type_alert
twitch.tv##.noty_message

**header for "free trial:"**
twitch.tv##.header-announcement__wrapper

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/2c467af8accf687a4376656ec3d64cc5155334fb

May fix it.
