### ISSUE TITLE
google.fr

### ISSUE THREAD

**Issue by KaKi87** [ryanbr/fanboy-adblock#1447]
### List the website(s) you're having issues:

`google.fr`

### What happens?

An unbypassable cookie consent modal appears

### List Subscriptions you're using:

`fanboy-cookiemonster.txt`

### Your settings

- OS/version: Elementary OS 5
- Browser/version: Brave 1.18
- Adblock Extension/version: uBlock Origin 1.31

### Other details:

None

---

Thanks !

**Comment by krystian3w** [comment]
Try:

`google.*##+js(aeld, DOMContentLoaded, CONSENT)`

No works too in Firefox 85+ and Chrome 88+

**Comment by KaKi87** [comment]
Hello, sorry I never saw your reply, would you have an update on this ? It doesn't work today. Thanks

**Comment by krystian3w** [comment]
So try these:

```
www.google.*##^script:has-text(consentCookiePayload)
www.google.*##+js(acis, document.cookie, YES+)
```

First no work in Chromium.

Source: https://old.reddit.com/r/uBlockOrigin/wiki/solutions#wiki_consent_dialog_popup

**Comment by KaKi87** [comment]
Thanks ! Why didn't any blocklist added those filters ?

**Comment by krystian3w** [comment]
No one can guarantee that something rare function is not damaged. 

Acis also have race condition (rare run too late so pop-up still prompt) in Chromium (Firefox 57+ can use html filtering, Firefox legacy a little too).

**Comment by KaKi87** [comment]
Alright, thanks.
