### ISSUE TITLE
https://twitter.com/settings/add_muted_keyword: overblocking

### ISSUE THREAD

**Issue by lol768** [ryanbr/fanboy-adblock#1452]
### List the website(s) you're having issues:

```
https://twitter.com/settings/add_muted_keyword
```

### What happens?

Save button blocked, impossible to add new muted keywords

### List Subscriptions you're using:

Other subscriptions don't matter, the rule that caused the problem is `twitter.com##.r-13qz1uu.r-1w50u8q` and it originates from Fanboy’s Annoyance list:

```
[Adblock Plus 2.0]
! Checksum: 3MoPnJF/Gh9r09QLWdbcTA
! Version: 202011060931
! Title: Fanboy's Annoyance List
! Last modified: 06 Nov 2020 09:31 UTC
! Expires: 4 days (update frequency)
! Homepage: https://easylist.to/
! License: http://creativecommons.org/licenses/by/3.0/
!
! Please report any unblocked content or problems by email or in our forums
! Email: easylist@protonmail.com
! Forums: https://forums.lanik.us/
!
!--------------------------General blocking rules-----------------------------!
```

### Your settings

- OS/version: Ubuntu 20.04
- Browser/version: FF 86
- Adblock Extension/version: uBlock Origin v1.32.4

### Other details:

![image](https://user-images.githubusercontent.com/2552726/104622790-98dc1300-5689-11eb-8736-456a9c93dd6b.png)

**Comment by ryanbr** [comment]
Was resolved @lol768  force an update, reopen ticket if it still occurs
