### ISSUE TITLE
Suscribe buttons hidden on skeptikon.fr (PeerTube)

### ISSUE THREAD

**Issue by funkypou** [ryanbr/fanboy-adblock#1453]
### List the website(s) you're having issues:

`https://skeptikon.fr`

### What happens?

Go to an account or a channel page. The buttons "Subscribe" (to a channel) and "Subscribe to all channels" are hidden.

### List Subscriptions you're using:

    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "urlhaus-1",
    "fanboy-annoyance",
    "plowe-0",
    "FRA-0"

On the request log, the filter causing the issue seems to be ##.subscribe-button from Fanboy’s Annoyance.

### Your settings

- OS/version: Kubuntu 20.04
- Browser/version: Firefox 84.0.2
- Adblock Extension/version: uBlock Origin v1.32.4

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* **Fanboy's Annoyance List**
* **Fanboy's Social Blocking List**

### Problem rule:
`##.subscribe-button`

### Possible fix:
`skeptikon.fr#@#.subscribe-button`
