### ISSUE TITLE
Third-Party Fonts Service: typesquare.com

### ISSUE THREAD

**Issue by piquark6046** [ryanbr/fanboy-adblock#1454]
### What happens?
This website requests getting fonts from `wf.typesquare.com`.

### List Subscriptions you're using:
`AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Turkish filter, AdGuard French filter, AdGuard Russia filter, AdGuard Chinese filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Dutch filter, AdGuard Spanish/Portuguese filter and List-KR`

### Your settings

- OS/version: `Microsoft Windows 10`
- Browser/version: `Mozilla Firefox Developer Edition 85.0b9`
- Adblock Extension/version: `AdGuard for Windows 7.5.3
`
### Other details:

Recommended Rule: `||wf.typesquare.com^`, `||webfonts.sakura.ne.jp^` and `||typesquare.com/*/script/*/typesquare.js`

**Comment by piquark6046** [comment]
AdguardTeam/AdguardFilters#72973

**Comment by piquark6046** [comment]
https://sinsyakai.or.jp
This website requests getting fonts from `webfonts.sakura.ne.jp`.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/beb530144c50967a2978db27c6420b83a1db0539
