### ISSUE TITLE
mydealz.de seems to be broken with FanBoy's Annoyance list.

### ISSUE THREAD

**Issue by le0mil** [ryanbr/fanboy-adblock#1458]
### List the website(s) you're having issues:

mydealz.de

### What happens?

Annoyances list blocks the cookie window but transparent overlay remains. You can't click on the site at all and the only solution is to disable the list or to whitelist the whole domain (not nice).

### List Subscriptions you're using:

uBlock Origin defaults + Fanboy's Annoyance list.

### Your settings

I don't use any other extensions.

- OS/version:  Win10
- Browser/version: Chrome
- Adblock Extension/version: latest uBlock Origin

**Comment by iMonZ** [comment]
> ### List the website(s) you're having issues:
> 
> mydealz.de
> ### What happens?
> 
> Annoyances list blocks the cookie window but transparent overlay remains. You can't click on the site at all and the only solution is to disable the list or to whitelist the whole domain (not nice).
> ### List Subscriptions you're using:
> 
> uBlock Origin defaults + Fanboy's Annoyance list.
> ### Your settings
> 
> I don't use any other extensions.
> 
>     * OS/version:  Win10
> 
>     * Browser/version: Chrome
> 
>     * Adblock Extension/version: latest uBlock Origin
> 
> 
> ### Other details:

Hey,

just a quick disclaimer:

"Windows 10" is the OS name
the 10 is inside the name and not the version

You can find your "Windows 10" OS version inside the Settings/Info About
