### ISSUE TITLE
Certain shields.io badges are blocked

### ISSUE THREAD

**Issue by amyspark** [ryanbr/fanboy-adblock#146]
https://github.com/ryanbr/fanboy-adblock/blob/e4b73d005667642b266b23efe0d3de612b89ba3f/enhancedstats-addon.txt#L1101-L1102

The line above blocks Shields.io's Github issues, pull requests, stars and Appveyor status badges.
I think this is because of github's caching feature:
```
(from)
https://ci.appveyor.com/api/projects/status/8v8u6lnc8krqxkuu?svg=true
(to)
https://camo.githubusercontent.com/3bcca0d0ae387738310f824a04d4b0a5196f090c/68747470733a2f2f63692e6170707665796f722e636f6d2f6170692f70726f6a656374732f7374617475732f38763875366c6e63386b7271786b75753f7376673d74727565
```

**Comment by ryanbr** [comment]
Has been resolved, just force update.
