### ISSUE TITLE
Unable to complete payment at certain webshops (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#1469]
### Example site:
`https://webshop.harddisk.no/`

### Issue:
Unable to complete payment (authentication failure).

### Problem filter:
* **Fanboy's Annoyance List**

### Problem rule:
`||service.signalr.net^$third-party`

### Screenshots:
* **Screenshot 1 (Payment stuck in infinite loading loop):**

![filterissue-harddisk no-1](https://user-images.githubusercontent.com/9382674/112869049-04e0eb80-90bd-11eb-90f4-cf17536c6109.jpg)

* **Screenshot 2 (Payment went through, after disabling the problem rule):**

![filterissue-harddisk no-2](https://user-images.githubusercontent.com/9382674/112869103-11fdda80-90bd-11eb-990f-d2d6d129e041.jpg)

### Possible fix:
Remove the problem rule!

### Temporary fix:
For ABP-based blockers:
`@@||service.signalr.net^$third-party`

For uBO / AdGuard:
`||service.signalr.net^$third-party,badfilter`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.1.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by rmihael** [comment]
I also was hit by it. Azure SignalR (https://azure.microsoft.com/en-us/services/signalr-service/) is a generic service for real-time message passing and should not be considered as harmful.

**Comment by rhamnett** [comment]
+1 for removing this from the list. Signalr is a communications framework library and is not malicious. Please remove

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1c1e6e8bdd7cfd01f97a7855b5402ab65ef47d82

**Comment by rhamnett** [comment]
Thank you @ryanbr
