### ISSUE TITLE
Annoyance List breaks page navigation @ yr.no

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#147]
This rule (in' Fanboy's Annoyance List') completely breaks the page navigation menu at yr.no:
**yr.no##.yr-stickynav**

Example URL:
https://www.yr.no/place/Norway/Oslo/Oslo/Oslo/hour_by_hour.html?spr=eng
(The menu is supposed to be located on the left side of the screen)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/575821854fa7d8246824b0a4ae8014bcbe23d433
