### ISSUE TITLE
Box.com download links being blocked

### ISSUE THREAD

**Issue by twiz-ahk** [ryanbr/fanboy-adblock#148]
A filter is blocking the download link from either Box.com, or one or more subdomains

Example Url:
> https://notredame.app.box.com/s/26a4bygh9vbaw7jjq08xr5evomvaw5ww/folder/3332706778

Problematic Filter:
> ! "DANESCO TRADING"
> /\.com\/[\w\/\-.+]{320,}/$subdocument,third-party

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=38544

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/b50eb870377fbefaa3c3a5d17a9309138484d20f
