### ISSUE TITLE
Unable to login to any soundcloud.com account 

### ISSUE THREAD

**Issue by 0x192** [ryanbr/fanboy-adblock#1481]
### List the website(s) you're having issues:

```
https://soundcloud.com
```

### What happens?

All login attempt fail with the `Our robots think you're a robot` error.

### List Subscriptions you're using:

A lot but **Fanboy's Enhanced Tracking List** is the problematic one here.

### Your settings

Firefox 88 with ublock Origin v1.35.2

### Fix

The script [pagespeed.js](https://pwt.soundcloud.com/static/sc/4.80.9/pagespeed.js) needs to run in order to successfully login : 

```
@@||pwt.soundcloud.com/static/sc/*/pagespeed.js$script,domain=secure.soundcloud.com
```

EDIT: pull request :  #1482

**Comment by ryanbr** [comment]
fixed
