### ISSUE TITLE
Translation badge blocked on uBlock repo

### ISSUE THREAD

**Issue by gwarser** [ryanbr/fanboy-adblock#149]
On https://github.com/gorhill/uBlock
Crowdin translation badge
![image](https://user-images.githubusercontent.com/886325/31584968-66ef2ec2-b1b9-11e7-881a-e3b38ada4a4b.png)

https://camo.githubusercontent.com/4022bd3dd5a7e8be9b3758773c386b5b5c12937f/68747470733a2f2f64333232637174353834626f346f2e636c6f756466726f6e742e6e65742f75626c6f636b2f6c6f63616c697a65642e737667 

is blocked by

Static filter `/\.com\/.*[a-f0-9]{110}/$third-party,image` found in: Fanboy’s Enhanced Tracking List

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/ce358b142d9c8de13527de1dbf24e41d13d8891b
