### ISSUE TITLE
docs.qq.com don't show the share button

### ISSUE THREAD

**Issue by redleafnew** [ryanbr/fanboy-adblock#1499]
### List the website(s) you're having issues:
https://docs.qq.com/sheet/DUktPSUNHRGVTcHN5?tab=BB08J2

### What happens?
the share （分享）button don't appear

### List Subscriptions you're using:
Fanboy's Social Blocking List

### Your settings

- OS/version: Win 10
- Browser/version: EDGE the latest
- Adblock Extension/version: AdGuard
### Other details:

please see this issue 
https://github.com/AdguardTeam/AdguardFilters/issues/94075#issuecomment-920905106

**Comment by shenzhiming88** [comment]
`Fanboy's Social Blocking List`就是用来屏蔽分享按钮的
另外经过测试，不会屏蔽分享按钮，影响文档权限的修改功能
![image](https://user-images.githubusercontent.com/66902050/133922823-f6b5d0bf-fb4a-4877-869b-443254ca0e7b.png)

**Comment by redleafnew** [comment]
> `Fanboy's Social Blocking List`就是用来屏蔽分享功能的
> 另外经过测试，不会屏蔽分享按钮，影响文档权限的修改功能
> ![image](https://user-images.githubusercontent.com/66902050/133922823-f6b5d0bf-fb4a-4877-869b-443254ca0e7b.png)

我不明白。

屏蔽分享功能，但不屏蔽按钮是什么意思。

现在我的屏蔽了分享按钮，但实际上这个按钮和分享功能都是有用了，在线文档分享给别人一块编辑也是经常用到的。

**Comment by redleafnew** [comment]
现在我的把分享按钮给屏蔽了。
分享功能也不知道如何调出来。

**Comment by shenzhiming88** [comment]
> 现在我的把分享按钮给屏蔽了。
> 分享功能也不知道如何调出来。

你就订阅了那一个规则吗？我这里测试的话，那个按钮应该是存在的，我用的是uBO

> 我不明白。
>
> 屏蔽分享功能，但不屏蔽按钮是什么意思。

> Fanboy's Social Blocking List solely removes Social Media content on web pages such as the Facebook like button and other widgets.

我没说清楚，我觉得这个列表就是用来屏蔽分享功能的，但是那个分享按钮里面还可以调整权限，所以按钮就还存在

**Comment by redleafnew** [comment]
我用了AdGuard，社交插件中有Fanboy's Social Blocking List，启用后分享按钮消失，无法分享。

**Comment by shenzhiming88** [comment]
> 启用后分享按钮消失，无法分享。

我刚刚看了一下，你那个链接里面的确会把分享按钮屏蔽。但是这就达到了`Fanboy's Social Blocking List`的目的——移除社交媒体按钮。因为这个分享按钮仅有分享的功能，而没有其他功能。

**Comment by redleafnew** [comment]
所以要使用分享功能只能把Fanboy's Social Blocking List先禁用了吗？

**Comment by shenzhiming88** [comment]
> 所以要使用分享功能只能把Fanboy's Social Blocking List先禁用了吗？

是的，因为这个过滤规则旨在禁用分享功能和各种社交媒体小部件……但是表格里面的那个分享按钮好像还有修改文档权限的作用，所以这一个按钮不应该被禁用。我也不是官方人员，只能去反馈一下了

**Comment by redleafnew** [comment]
那就等官方了。

**Comment by shenzhiming88** [comment]
其实在这里也可以修改文档的权限，所以那个按钮屏不屏蔽也无所谓了
![image](https://user-images.githubusercontent.com/66902050/133929835-9a82d661-4890-459a-99c2-2ce6794f0c91.png)

**Comment by shenzhiming88** [comment]
@redleafnew 即使允许了那个按钮，也无法分享内容，下面的“分享到”也同样会被屏蔽。我只是为了能够在那里面修改文档的权限

**Comment by redleafnew** [comment]
是的，我也发现了，无法分享了。

**Comment by shenzhiming88** [comment]
> 是的，我也发现了，无法分享了。

这是正常的。如果要用分享功能的话，就把那个过滤规则禁用吧
另外对EasyList规则，最好到 https://github.com/easylist/easylist/issues 反馈吧

**Comment by spirillen** [comment]
Do you have another keyboard... :smile: I'm kind a feeling [lost in translation](https://www.themoviedb.org/movie/153) here

**Comment by shenzhiming88** [comment]
> Do you have another keyboard... 😄 I'm kind a feeling [lost in translation](https://www.themoviedb.org/movie/153) here

In short, he wants to share web content, but at the same time he enable `Fanboy's Social Blocking List`

**Comment by shenzhiming88** [comment]
@redleafnew 您最好将这个issue关闭，因为这就是`Fanboy's Social Blocking List`应该做的

You'd better close this issue, because that's what `Fanboy's Social Blocking List` is supposed to do

**Comment by spirillen** [comment]
Thanks @shenzhiming88

**Comment by redleafnew** [comment]
@shenzhiming88 ok
