### ISSUE TITLE
Ezoworld.hu incorrect appearance by Cookie Monster

### ISSUE THREAD

**Issue by kovacsattila-hun** [ryanbr/fanboy-adblock#15]
Incorrect appearance on the website's bottom!

Please add the whitelist:

`@@||ezoworld.hu^*/cookielawinfo.js`

Thanks!

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/39be3d0540d94fb6312970c7ad980e5a795e72c3
