### ISSUE TITLE
"Snackbar" components are blocked.

### ISSUE THREAD

**Issue by Serubin** [ryanbr/fanboy-adblock#150]
Material Design Lite's Snackbar component are being hidden. Although in some cases these are annoying, in most cases they provide valuable information, particularly in web apps.

**Comment by ryanbr** [comment]
From committ: https://github.com/easylist/easylist/commit/febf68642

Seems fine here? https://imgur.com/a/2It03  Its blocking the cookie message.

**Comment by Serubin** [comment]
Are you saying that it's warranted, or that it doesn't block anything?

It's in the file and does block snackbar items. The parent element that's used to provide info, particularly of a popular design framework, shouldn't be blocked.

**Comment by ryanbr** [comment]
I say its warranted until proven otherwise, you haven't given any examples where its broken. 

When people submit issues here they'll give me example sites etc, you haven't given enough details

**Comment by Serubin** [comment]
messenger.klinkerapps.com, pulse.serubin.net both use it for error/info reporting as well as a few other things.

It's a design component of a popular framework, it seems overly aggressive to block it for all sites. It's a very useful part of the material design specification.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d5d6c95c5a5314939f64e2e8c19eedfbbf990015

**Comment by Serubin** [comment]
Thank you
