### ISSUE TITLE
goibibo.com incorrect blocking

### ISSUE THREAD

**Issue by im3or** [ryanbr/fanboy-adblock#151]
See the issue here - https://github.com/AdguardTeam/AdguardFilters/issues/7132
Can confirm, caused by Enhanced Tracking List.

**Comment by Alex-302** [comment]
Can be fixed by:
```
@@||googletagservices.com/tag/js/gpt.js$domain=goibibo.com
```

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/36f43bef64954ba079a92e15f21845b10efb3b84
