### ISSUE TITLE
||gelbooru.com^$first-party,image

### ISSUE THREAD

**Issue by UserNaem** [ryanbr/fanboy-adblock#152]
Found in "Fanboy's Enhanced Tracking List":
`||gelbooru.com^$first-party,image`

This breaks all thumbnails on https://gelbooru.com/index.php?page=post&s=list. Disabling this filter list will un-break the thumbnails. (How can first-party images be used for tracking, anyways?)
![image](https://user-images.githubusercontent.com/21028464/31862462-8a1a243a-b757-11e7-9a1b-3e895dbe59ef.png)

**Comment by gwarser** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/117
