### ISSUE TITLE
http://dizinow.is/

### ISSUE THREAD

**Issue by ririmyhoe** [ryanbr/fanboy-adblock#153]
This site have a Javascript popup ad 
Turkish site

**Comment by ririmyhoe** [comment]
! 24.10.2017 20:01:39 http://www.mp3indirdur.org/turkce-mp3ler.asp
||www.mp3indirdur.org/mp3indirdur.png$image

! 24.10.2017 20:27:20 http://dizinow.is/
||dizinow.is/ads/pageskin3.jpg$image

! 24.10.2017 20:27:28 http://dizinow.is/
dizinow.is##a[href^="https://www.grand-ads.com/ads/click"]
its ublock filter code i think it would help

**Comment by ririmyhoe** [comment]
! 24.10.2017 20:01:39 http://www.mp3indirdur.org/turkce-mp3ler.asp
||www.mp3indirdur.org/mp3indirdur.png$image

this site have a ad too

**Comment by SMed79** [comment]
add
```
/ads/click?$popup
/ads/banner?
/ads/header.
##a[href*="/ads/click?"]
##a[href*="/earn.php?zone="]
||grand-ads.com^$popup,third-party
||moon-ads.com^$popup,third-party

```

**Comment by ryanbr** [comment]
Add some generic filters as suggested, seem pretty safe.

https://github.com/easylist/easylist/commit/2bd98317c6677abcf94c5c7356fe4c2b73da5a62
