### ISSUE TITLE
facebook.com $popup - false positive

### ISSUE THREAD

**Issue by gwarser** [ryanbr/fanboy-adblock#154]
`/\.com\/.*[0-9]{6,9}\/\?/$popup` from "Fanboy’s Enhanced Tracking List" may cause false positives when browsing images in Facebook Groups.

![image](https://user-images.githubusercontent.com/886325/31970111-402cd9dc-b917-11e7-9a3e-ddd621c49a9e.png)

**Comment by ryanbr** [comment]
Filter was disabled.
