### ISSUE TITLE
fanboy-anti-facebook "shaking" facebook posts :)

### ISSUE THREAD

**Issue by survivor303** [ryanbr/fanboy-adblock#1547]
Something from antifacebook make facebook shaking ;)

**Comment by jkam007** [comment]
> Something from antifacebook make facebook shaking ;)

do you try to turn it off?

**Comment by survivor303** [comment]
@jkam007 yes, and it is fixed.. the problem was on the other list (finnish blocklist) too and i investigate more, found the error line. and now the site works after removing the line form the finnish blocklist and enabling anti-facebook too.

odd mix of problems but all is fine now and this can be close.
