### ISSUE TITLE
comparic.pl

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#155]
Hi,

Issue displaying thumbnails of articles

```
@@||comparic.pl^*/eu-cookie-law.js
```
- https://user-images.githubusercontent.com/5884000/32003117-8199e432-b99e-11e7-8fb0-1338a8f72524.png
- `https://comparic.pl/`

(https://github.com/uBlockOrigin/uAssets/issues/783)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/fbb4da3749f9bdb110e22c6dac2581b1c98e3631
