### ISSUE TITLE
yahoo.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#156]
Hi,
cookies notice 

(mobile user agent)

- https://i.imgur.com/D2DQ1KO.png
- https://i.imgur.com/pOgiUaj.png
- https://i.imgur.com/I3mgZ2m.png

<span>https://</span>fr.yahoo.com/?p=dnr
<span>https://</span>de.yahoo.com/?p=dnr
<span>https://</span>es.yahoo.com/?p=dnr

replace:
```
uk.yahoo.com##div.js-applet-view-container-main > div[style^="background:"]
```
by:
```
yahoo.com##div.js-applet-view-container-main > div.fixed-win[style^="background:"]
```

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/4380271b35b436af4264440c18d56ab941e850f6
