### ISSUE TITLE
arnaudfrichphoto.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#157]
```
/pinterest-1.
/pinterest-2.
/facebook-1.
/facebook-2.
/instagram-1.
/instagram-2.
```
<span>https://</span>www.arnaudfrichphoto.com/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/83616a88334cd8477c9ca9ffd30355464c123e4d
