### ISSUE TITLE
developpement-personnel-club.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#158]
privacy
```
.gif?membreid=
```
annoyance
```
||sg-autorepondeur.com^$third-party
```
- http://i.imgur.com/0oy89cs.png
- `https://developpement-personnel-club.com/`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/64078b616713a30960b0b152967353ca42133b3c
