### ISSUE TITLE
whatsappblogger.js

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#160]
```
/whatsappblogger.js
```

<span>http://</span>www.saadantar.com/
<span>http://</span>www.wisatabdg.com/
<span>http://</span>www.teacher4us.com/
<span>http://</span>www.seputarbandungraya.com/
<span>http://</span>www.tteachers.in/
<span>http://</span>www.kerjabatam.com/
<span>http://</span>www.galerikitabkuning.com/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/dd0995b68cc2cad7d90dfd49391907838ad521ad
