### ISSUE TITLE
Problem With Tweets On 411mania.com Using Fanboy's Ultimate List

### ISSUE THREAD

**Issue by ddn2003** [ryanbr/fanboy-adblock#163]
I have added Fanboy's Ultimate List to Adguard. When it is enabled all tweets come in as text, instead of as proper tweet format with pictures, etc.

With the help of one of the Adguard developers we narrowed down the issue to:

@@||ads.ayads.co/ajs.php?zid=$domain=411mania.com

Please add this to the Fanboy Ultimate List.

Thank you in advance!

**Comment by ryanbr** [comment]
I'll need a decent example, I browsed the site didn't see any Tweets.

**Comment by ddn2003** [comment]
https://411mania.com/wrestling/rusev-wants-wwe-survivor-series-spot/

**Comment by ddn2003** [comment]
Any update?

**Comment by ryanbr** [comment]
I don't think there is an issue. And even if I whitelisted it, the page looks the same.

Without whitelist: https://screenshots.firefox.com/4LlhiiomiYOPsQb1/411mania.com
With whitelist: https://screenshots.firefox.com/x37AP3kZ5h8mC4Q4/411mania.com

I would consult Adguard devs imo.

**Comment by ddn2003** [comment]
What about this page?
https://411mania.com/wrestling/ember-moon-reacts-takeover-title-win/
Screenshot: http://easycaptures.com/fs/uploaded/1223/4039953213.png

**Comment by ryanbr** [comment]
Loaded fine here? Disable Adguard and re-test in Firefox or Chrome with ABP or uBo (which is what I'm testing in)

**Comment by ddn2003** [comment]
All I have to do to get them to work fine is to disable Fanboy's Ultimate List in Adguard, but I'll try ABP and Fanboy's Ultimate List.

**Comment by ddn2003** [comment]
I'm just thinking, could the HTTPS Everywhere extension play a part in blocking the tweets format?

**Comment by ryanbr** [comment]
I don't use this extension. Before creating reports be sure no extensions are causing it.

**Comment by ryanbr** [comment]
Closed, re-tested, no issues still seen.
