### ISSUE TITLE
sentry.io and docs.sentry.io cookie banner

### ISSUE THREAD

**Issue by jody-frankowski** [ryanbr/fanboy-adblock#164]
```
##.privacy-shield-banner
```
[https://sentry.io/welcome/](https://sentry.io/welcome/)
[https://docs.sentry.io/server/installation/](https://docs.sentry.io/server/installation/)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/181bd815641f6f6d4c56d61de4fff83885011bd3
