### ISSUE TITLE
Fanboy Enhanced Tracking List blocks Expedia

### ISSUE THREAD

**Issue by Palf994** [ryanbr/fanboy-adblock#166]
Fanboy Enhanced Tracking List blocking sign in on Expedia.ca

To replicate:
1. Go to [expedia.ca](https://www.expedia.ca/)
2. Search for hotel
3. Click to reserve
4. When you get to the "Sign up" stage, click "Sign in" instead and try to log in (nothing will happen)

This appears to be blocking:

https://a.travel-assets.com/bundles/expweb/siteanalytics/omniture-89beb87ff1fd1cec20c90b50cd893ee8-min.js

with the "/omniture-" filter

Thanks for your hard work on this project.

Edit: This also blocks sign-in on the other Expedia domains (.fr, .com, .at, .co.uk...)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/002897b10f853b5ca532fb987b20f3c94e244664
