### ISSUE TITLE
Fanboy's Enhanced Tracking List - Filter Typo

### ISSUE THREAD

**Issue by SkeletalDemise** [ryanbr/fanboy-adblock#167]
Fanboy's Enhanced Tracking List has a small typo on one of the filters in it causing it not to be used/applied. 
Filter: @@/mbox-configuration.$sccript

Screenshot of uBlock Origin not using the filter because it's invalid:
![invalid filter screenshot](https://user-images.githubusercontent.com/29117662/32300658-cbaf2298-bf17-11e7-933b-65178a6502af.png)

~Thanks

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/8d8206273693a1c08c0111763e8155ed3c6e828a
