### ISSUE TITLE
Fanboy's Cookiemonster List - Redundant Filters

### ISSUE THREAD

**Issue by SkeletalDemise** [ryanbr/fanboy-adblock#168]
There are a couple filters in Fanboy's Cookiemonster List that are redundant and should be deleted/fixed.

_**Redundant Filters:**_
**[|1|]** `calciomercato.com###ca_banner` **_(is redundant by)_** `###ca_banner`

**[|2|]** `thesimsresource.com###eucookie` **_(is redundant by)_** `###eucookie`

**[|3|]** `iubenda.com###iubenda-cs-banner` **_(is redundant by)_** `###iubenda-cs-banner`

**[|4|]** `wccftech.com##.cc_banner` **_(is redundant by)_** `##.cc_banner` [Remove from `publicleech.xyz,thebarchive.com,wccftech.com##.cc_banner`]

**[|5|]** `theatlantic.com##.cookie-disclaimer` **_(is redundant by)_** `##.cookie-disclaimer`

**[|6|]** `lacajachina.fi##.cp-curtain-container` **_(is redundant by)_** `##.cp-curtain-container` _[And the website no longer exists.]_

~Thanks

**Comment by mapx-** [comment]
You have to check if for the domains listed above there are $generichide filters
For example mirror.co.uk has such filter in easylist (so the generic filter wont help)

`@@||mirror.co.uk^$generichide`

**Comment by SkeletalDemise** [comment]
Ah yes, you're correct. I'll do that.

**Comment by SkeletalDemise** [comment]
Actually, wait no. For some reason, `##.mod-cookiepolicy` from Fanboy's Cookiemonster List gets applied on mirror.co.uk for me even with `@@||mirror.co.uk^$generichide`...

**Comment by mapx-** [comment]
in uBo probably is a bug, see:
https://github.com/gorhill/uBlock/issues/2763

in the last legacy ABP in firefox, it works well

in ABP for chrome probably is a similar bug as in uBo

**Comment by SkeletalDemise** [comment]
Hmm, I just downloaded and tested ABP and did a test. It didn't apply the global filter `##.mod-cookiepolicy` with `@@||mirror.co.uk^$generichide` in place. But uBo for some reason does. So it's a bug I guess. And since this filter list needs to work with both, then still need to think about any $generichide filters then.

**Comment by SkeletalDemise** [comment]
OK, finished sorting through all of the them. Just left with 7 filters that are redundant and can be removed.

**Comment by mapx-** [comment]
in the polish list  ( Homepage: https://www.certyficate.it/ ) in cluded in uBo, there is:
`@@||filmweb.pl^$generichide`

`lacajachina.fi` seems to not exist anymore

**Comment by SkeletalDemise** [comment]
Ok... Still need to get rid of the `lacajachina.fi` then still, if it's useless.

**Comment by mapx-** [comment]
The Polish list is part of the standard setup for the polish people, so it should remain as it is now.

**Comment by SkeletalDemise** [comment]
Ok, that then leaves a final 6 redundant filters that can be removed.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/b5307b9eb55003a6fa34f2513bf51518330f6db4

Given the use of generichide, there will be some dubes. But If I missed any legit request re-open this.
