### ISSUE TITLE
Fanboy's Enhanced Tracking List - Redundant Filters

### ISSUE THREAD

**Issue by SkeletalDemise** [ryanbr/fanboy-adblock#169]
Found some redundant filters in Fanboy's Enhanced Tracking List. Please remove/fix.

**_Redundant Filters:_**
**[|1|]** `@@||wired.com/assets/load?$script` **_(is redundant by)_** `@@||wired.com/assets/load?$script`

**[|2|]** `bournemouthecho.co.uk##.custom-sharing` **_(is redundant by)_** `bournemouthecho.co.uk##.custom-sharing`

**[|3|]** `||contributor.google.com^*/loader.js$third-party` **_(is redundant by)_**
`||contributor.google.com^*/loader.js$third-party`

**[|4|]** `@@||geo.de^*/advertisement.js` **_(is redundant by)_** `@@||geo.de^*/advertisement.js`

**[|5|]** `@@||geo.de^$generichide` **_(is redundant by)_** `@@||geo.de^$generichide`

**[|6|]** `redtube.com###slidePanelContainerAB` **_(is redundant by)_** `redtube.com###slidePanelContainerAB`

**[|7|]** `pornhub.com###abAlert` **_(is redundant by)_** `pornhub.com###abAlert`

**[|8|]** `||seal.websecurity.norton.com^$third-party` **_(is redundant by)_** `||websecurity.norton.com^$third-party`

**[|9|]** `@@||marinetraffic.com/js/inc/adframe.js` **_(is redundant by)_** `@@/inc/adframe.js`

**[|10|]** `@@||roguest.com^*/advert.js$domain=allmusic.com` **_(is redundant by)_** `@@||roguest.com^*/advert$domain=allmusic.com`

~Thanks

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/f7b4b15e7ca1f9d4bc356920b69c8382c0ea11fa
