### ISSUE TITLE
bitcoin faucet sites with a lot of ads

### ISSUE THREAD

**Issue by phant** [ryanbr/fanboy-adblock#17]
```
http://bitcoinspace.net/freebitcoins/
http://freebtc.click/
```
With enabled filter that contains EasyList rules these sites show warning "... disable your ad-blocking browser plugin ...".

Adding this hosts and disabling EasyList removes adds and adblocks warnings.
```
http://app.cointraffic.in/
http://coinad.com/
https://coinad.com/
```

**Comment by SMed79** [comment]
Anti adblock add:
```
@@||freebtc.click/display_ads.js
@@||bitcoinspace.net/freebitcoins/display_ads.js
```

**Comment by ryanbr** [comment]
Force an update of the subscriptions. (note, dont post links. Use the Insert code button <>)
