### ISSUE TITLE
Fanboy’s Social Blocking List removes ability to answer to tweets on twitter.com

### ISSUE THREAD

**Issue by therealmarv** [ryanbr/fanboy-adblock#171]
Affects fanboy_social_general_block.txt in ublock:

1. Go and login to twitter.com
2. select a tweet of your choice and try to answer

Answer button and character counter is not visible with this list.

**Comment by therealmarv** [comment]
workaround for now: Ctrl+Enter to answer (Windows&Linux) or Cmd+Enter (Mac)

**Comment by ryanbr** [comment]
Is this still broken, can you update and retest?

**Comment by ryanbr** [comment]
No response, closing.

**Comment by therealmarv** [comment]
@ryanbr no it's not broken anymore. Thanks for fixing. Have not seen your December 1st message.
