### ISSUE TITLE
Fanboy+Easylist-Merged Ultimate List breaks "Where to buy" pages

### ISSUE THREAD

**Issue by ps-cody-buller** [ryanbr/fanboy-adblock#172]
Enabling Fanboy+Easylist-Merged Ultimate List breaks "Buy Now" functionality on some pages. 

Example:
https://www.callofduty.com/wwii/buy

Behavior:
While enabled, Fanboy+Easylist-Merged Ultimate List prevents you from clicking the "Buy Now" page.

**Comment by ryanbr** [comment]
No longer an issue? can you confirm?

**Comment by ps-cody-buller** [comment]
Looks to still be an issue.
I checked it on the same page: https://www.callofduty.com/wwii/buy

It seems to work for the Season-pass edition but it prevents the clicking of Buy Now for any other edition of the game (for example the Digital Deluxe)

Thanks

**Comment by ps-cody-buller** [comment]
It also seems to hide the "Where to buy" functionality on some other webpages entirely. For example:
https://www.lg.com/us/products/wtb?modelId=MD05129480

**Comment by mapx-** [comment]
try
`@@||pricespider.com^$script,domain=lg.com`

**Comment by ps-cody-buller** [comment]
I tried this but it seems to block all of the pictures and the map functionality. 
Screenshot: [link](https://imgur.com/a/7p3cW)

The filter blocks more than just LG and Call of Duty though, it seems to break all of the where to buys on manufacturer pages.
Some random examples:
https://recip.skilsaw.com/
https://www.dynacraftwheels.com/monster-high-18-bike-black-087876094739
https://www.drscholls.com/products/product-by-type/insoles-inserts-orthotics/
https://www.mccormick.com/simply-asia/products/noodles-and-broth/vietnamese-inspired-pho-beef-broth

**Comment by mapx-** [comment]
it should be completely removed

add
`@@||pricespider.com^$script,stylesheet`
