### ISSUE TITLE
paypal-communication.com

### ISSUE THREAD

**Issue by Salamander3** [ryanbr/fanboy-adblock#173]
https://epl.paypal-communication.com/T/v40000015f95bfb8f1ba3978f4bbcf76f8/1a320584304e47a80000021ef3a0bcce/1a320584-304e-47a8-a782-a84b3ba7fe09
Because of the following filter
||epl.paypal-communication.com^
Found in: EasyPrivacy

paypal-communication.com is owned by paypal to send notifications, it's not a fake or an ad.

**Comment by ryanbr** [comment]
We deemed it be a tracker, what type of notifications does it send?

**Comment by Salamander3** [comment]
It is about my paypal account activity, recent transactions.

**Comment by ryanbr** [comment]
Logged into my paypal account, viewed my transaction history, works fine as I suspected.

**Comment by Salamander3** [comment]
Nobody is saying you can't use paypal site. What is said was that link was blocked (4 months ago)...

**Comment by SMed79** [comment]
@Salamander3 Describe exactly the issue and how to reproduce.
