### ISSUE TITLE
underverse.su, underverse.me

### ISSUE THREAD

**Issue by slikkkk** [ryanbr/fanboy-adblock#176]
Hi there.
http://underverse.me/viewtopic.php?t=10588
when Adblock Plus is enabled, java script is blocked - https://i.imgur.com/tVXEAb0.jpg
Images aren't displayed, spoilers aren't working, the counter of peers isn't displayed.
Also, the buttons in the "quick response" box don't work - https://i.imgur.com/eqHFM0Y.jpg

found that the problem is with recording in the fanboy-social list
https://easylist-downloads.adblockplus.org/fanboy-social.txt

`@@||underverse.su/min/index.php*/js/share42.js`

if disable the list, then everything works. this script is "share in social networks" button. it isn't advertising or spamming.
can you remove it? or make a line for mirror site, please.

`@@||underverse.me/min/index.php*/js/share42.js`

P.S. also created here https://forums.lanik.us/viewtopic.php?f=64&t=39008

**Comment by slikkkk** [comment]
Update.

There is no more 'share42.js' at our site.

**Comment by ryanbr** [comment]
All good.

**Comment by slikkkk** [comment]
> All good.
but why rule
`@@||underverse.su/min/index.php*/js/share42.js`
is still present in the list?
