### ISSUE TITLE
kliknijwzdrowie.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#177]
![2017-11-17 00_38_02-zdrowie - choroby porady leczenie odzywianie zdrowie i uroda](https://user-images.githubusercontent.com/5884000/32921873-a862d180-cb2f-11e7-860f-bebc8453c1fe.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4488

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`@@||s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js$script,domain=kliknijwzdrowie.pl`
