### ISSUE TITLE
bing.com/translator

### ISSUE THREAD

**Issue by userOperaFF** [ryanbr/fanboy-adblock#178]
## Blank page:
<ul>

![image](https://user-images.githubusercontent.com/33114475/33014489-c9e99f5e-cde7-11e7-81dc-f1de7e089f4e.png)

</ul>

## uBlock logger:
<ul>

| time     |   | filter            |   | element | website                           |
|----------|---|-------------------|---|---------|-----------------------------------|
| 11:29:10 |   | `##.no-cookies`   |   | dom     | `https://www.bing.com/translator` |
| 11:29:10 |   | `##.cc-container` |   | dom     | `https://www.bing.com/translator` |
| 11:29:10 |   | `##.cc-banner`    |   | dom     | `https://www.bing.com/translator` |

</ul>

## Guilty:
<ul>

 `##.no-cookies` <sup> [fanboy-cookiemonster.txt#L2166](https://github.com/ryanbr/fanboy-adblock/blob/fe33d299aaf9368725a879b30e76595f7a051a62/fanboy-cookiemonster.txt#L2166) </sup>

</ul>

**Comment by ryanbr** [comment]
Can you update, and confirm if this helps?

https://github.com/ryanbr/fanboy-adblock/commit/f749f56b1c3abfc4c3db009ecdef16eac61203b5

**Comment by Khrin** [comment]
I can confirm you the issue, but sadly this doesn't help to fix... i think is necessary to allow this domain.

**Comment by mapx-** [comment]
`bing.com#@#.no-cookies:not(body)`

**Comment by mapx-** [comment]
same for thenextweb
`thenextweb.com#@#.no-cookies:not(body)`

**Comment by userOperaFF** [comment]
@mapx-  good.

@ryanbr `Updated: 24 Nov 2017`/`Updated: 25 Nov 2017`  does not fix.

**Comment by userOperaFF** [comment]
I can not create Checksums and no edit date update.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/07ad4c81d4aa0c82f606403ef1b332d23b1ab923
