### ISSUE TITLE
easycoin.pl

### ISSUE THREAD

**Issue by mat41997** [ryanbr/fanboy-adblock#179]
![2017-11-20 20_54_52-gielda bitcoin polcoin](https://user-images.githubusercontent.com/5884000/33038554-56ab3694-ce35-11e7-892e-ea65d630295b.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4527#issuecomment-346338011

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.89
chrome 62.0.3202.94

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f067c2bbfe85b8b6d33db95d74d29d45166223c4
