### ISSUE TITLE
Failed checksum on some lists

### ISSUE THREAD

**Issue by dezhavu** [ryanbr/fanboy-adblock#18]
Please check
https://github.com/ryanbr/fanboy-adblock/tree/master/firefox-regional

at least these 2 have checksum mistmatch:
https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-rus-v2.txt
https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-rus.txt

Thanks

**Comment by ryanbr** [comment]
Just to note, they haven't been updated for a while (Updated: 23 Apr 2010) and (2 Feb 2013)

Someone actually using them?
