### ISSUE TITLE
ps.bahn.de

### ISSUE THREAD

**Issue by fa23** [ryanbr/fanboy-adblock#182]
### Time sliders are broken:
https://ps.bahn.de/preissuche/preissuche/psc_start.post

With blocking:
![screen shot 2017-11-28 at 15 22 54-fullpage](https://user-images.githubusercontent.com/34067024/33328391-2cacf4ec-d45a-11e7-9dcd-beecf73efa7e.png)

Without blocking:
![screen shot 2017-11-28 at 15 23 10-fullpage](https://user-images.githubusercontent.com/34067024/33328408-3b1dacf6-d45a-11e7-8f64-6eb9f545901d.png)

This is not a cosmetic issue:
Blocking these elements causes a 404 error when clicking on "Suchen" ("Search").

### uBlock logger:
| Time |   | Element | | Type | URL |
|---|---|---|---|---|---|
| 15:00:00 |   | `/s_code.` | -- | script | https://www.img-bahn.de/es/v1710/js/s_code.js

### Cause:
`ps.bahn.de` is not in whitelist entry for `/s_code.` in [Enhanced Tracking List](https://github.com/ryanbr/fanboy-adblock/blob/66344ba551838a4235ed8c2fb0b3df26c804f1c7/enhancedstats-addon.txt#L2309)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/ed01cf215f5a9a0f6f3499b9f98bc80e333a19be
