### ISSUE TITLE
liggoo.com

### ISSUE THREAD

**Issue by Zorrototo** [ryanbr/fanboy-adblock#186]
Lot of the site functionalities are blocked (images, ordering, and so on). Blocked by fanboy annoyance or social blocking list.

images not showing in details pages: https://www.liggoo.com/fr/boutique/accessoires/etui-de-protection-l/
create your kit: https://www.liggoo.com/fr/boutique/produit/creer-mon-kit-liggoo/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/39eb3ae048d92b59e306880e3542ba1892caf649
