### ISSUE TITLE
Annoyance List‎ blocks bootstrap alert warnings

### ISSUE THREAD

**Issue by Brottweiler** [ryanbr/fanboy-adblock#19]
I noticed that when using `Fanboy’s Annoyance List‎` and `Fanboy+Easylist-Merged Ultimate List‎`, which both have the filter `##.alert.alert-warning`, it blocks [Bootstrap Alert](https://getbootstrap.com/components/#alerts) Warnings.

I see no reason why this list need to block important bootstrap features like the alert warning.

**Comment by ryanbr** [comment]
the element is often used to hide privacy/cookie notices. Is there a sample page where it causes issues?

**Comment by Brottweiler** [comment]
I administer a minecraft server, and we have a website for players to file appeals if they have gotten banned. Inside these appeals, administrators can view from what IP the user filed the appeal, and from what IP they were last playing from. This box is using the Bootstrap Alert Warning.

**Comment by tomsommer** [comment]
This has to be an error, please remove the block. It breaks normal alerts on all Bootstrap sites.

**Comment by Brottweiler** [comment]
In my mind, these warning alerts should usually be used for important messages, not annoying things.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1851be7f117272bd13e0b1ed995f872e819538ef

**Comment by Parnassius** [comment]
`##.alert.alert-warning` is still present in [fanboy-cookiemoster.txt](https://github.com/ryanbr/fanboy-adblock/blob/283b30867549e0c1f21bbe363c5ad2d06cb2099a/fanboy-cookiemonster.txt#L1317)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/5a5023dff1dfafd34f8bb47be9ff88f6b3475e19
