### ISSUE TITLE
cdiscount.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#191]
annoyance 
```
###cookiesNoticeId
```

privacy
```
/ghostery_light.js
||cdiscount.com/dtagent_
```
* `https://www.cdiscount.com/telephonie/r-pack+playstation+4+pro.html`

**Comment by ryanbr** [comment]
https://www.cdiscount.com/telephonie/r-pack+playstation+4+pro.html#_his_

**Comment by SMed79** [comment]
https://github.com/easylist/easylist/commit/76c878298c523b4f5032473c6eee0358a03c36d3
