### ISSUE TITLE
[Feature Request] Merge With Privacy Badger Cookie Block List

### ISSUE THREAD

**Issue by zero77** [ryanbr/fanboy-adblock#194]
Can you please merge your cookie block list with privacy badger cookie block list, because their list is very extensive and regularly updated.
Thanks

https://github.com/EFForg/privacybadger

**Comment by ryanbr** [comment]
Is that more of an extension rather than a adblock list?

**Comment by zero77** [comment]
yes it is but, they maintain a cookie block list as part of it.

**Comment by ryanbr** [comment]
they achieve different goals in different ways. so you can't really "lets merge" here.

**Comment by zero77** [comment]
Ok, thanks anyway
