### ISSUE TITLE
rmf24.pl

### ISSUE THREAD

**Issue by mat41997** [ryanbr/fanboy-adblock#195]
![2017-12-06 05_49_20-rmf 24 - najblizej faktow](https://user-images.githubusercontent.com/5884000/33645075-41c42946-da49-11e7-9f60-dada54ab080a.png)
`http://www.rmf24.pl/`

Fanboy’s Annoyance List

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bafc640a0c0c7493cbfea9ab4994948b2f6784c2
