### ISSUE TITLE
passport.bilibili.com

### ISSUE THREAD

**Issue by Franinc** [ryanbr/fanboy-adblock#196]
CAPTCHA error on https://passport.bilibili.com/login

Fanboy’s Enhanced Tracking List:
`/\.com/.*[a-f0-9]{110}/$script,image,third-party`

**Comment by ryanbr** [comment]
Apologies for the delay;

https://github.com/ryanbr/fanboy-adblock/commit/b155c6579e815bde75de9fbf9db4c865a9a2b399
