### ISSUE TITLE
bilesuparadize.lv

### ISSUE THREAD

**Issue by anonymous74100** [ryanbr/fanboy-adblock#197]
`https://www.bilesuparadize.lv/en/events/event/59240`

When clicking "BUY" can't see available seats and buy tickets.

Problematic filter from "**Fanboy's Annoyance List**":

```
.cookiesdirective.
```

Fix:
```
@@||bilesuparadize.lv/js/jquery.cookiesdirective.js
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2eb26a719580c812ff6604adad32b05dbff44a25
