### ISSUE TITLE
Font Awesome RSS icon is hidden.

### ISSUE THREAD

**Issue by AdamPerkins** [ryanbr/fanboy-adblock#198]
Fanboy's Annoyances filter hides Font Awesome RSS icon.

Example:
```
<span class="fa fa-rss-square" style="color:#f26522"></span>
```

**Comment by userOperaFF** [comment]
And many other rss elements / links.

Maybe wrong place for this issue:
```
! Please report any unblocked content or problems by email or in our forums
! Email: easylist.subscription@gmail.com 
! Homepage: https://easylist.to/ 
! Forums: https://forums.lanik.us/
````

**Comment by userOperaFF** [comment]
And many other rss elements / links.

<code>Maybe wrong place for this issue:<pre>! ⚠️ **Please report any unblocked content or problems by email or in our forums** ⚠️ 
! Email: ✉️  **easylist.subscription@gmail.com** ✉️ 
! Homepage: https://easylist.to/ 
! Forums:  🌐 **https://forums.lanik.us/** 🌐  </pre></code>

**Comment by userOperaFF** [comment]
And many other rss elements / links.

<code>Maybe wrong place for this issue:<pre>! ⚠️ **Please report any unblocked content or problems by email or in our forums** ⚠️ 
! Email: ✉️  **easylist.subscription@gmail.com** ✉️ 
! Homepage: https://easylist.to/ 
! Forums:  🌐 **https://forums.lanik.us/** 🌐  </pre></code>

**Comment by AdamPerkins** [comment]
Maybe this is done on purpose on this list. Than it's not an issue.

However RSS feeds are for me normally no advertising nor social nonsens like Twitter and FB. RSS Feeds normally are part of the site owner content.

For me I have renamed the RSS icon and that fixed the problem.

**Comment by LArtCrime** [comment]
You can try to explain that blocking rss is meaningless on [forums.lanik.us](https://forums.lanik.us/) and may remove it from the list over time.

**Comment by ryanbr** [comment]
It was intentional in the Annoyances list, We've removed the social stuff re: Font Awesome, but haven't touched Annoyances.  It'll block rss stuff (mainly the icons here) by default.
