### ISSUE TITLE
​​​​​ Fanboy’s Annoyance List, Fanboy’s Social Blocking List (and Fanboy+Easylist-Merged Ultimate List) hides Solidopinion commments subscribe link

### ISSUE THREAD

**Issue by mzso** [ryanbr/fanboy-adblock#199]
As such I can't subscribe to notifications for comments when I have any of these list enabled.

Example website: nextbigfuture.com

**Comment by Atavic** [comment]
Specifically I don't know Solidopinion, but comments sections on many sites are a gray zone for tracking/fingerprinting: e.g. Disqus - a comment hosting service - tracks users across different websites, even if they aren't posting any comment.

**Comment by ryanbr** [comment]
Not sure if this is fixable, Solidopinion probably needs to fix this

**Comment by mzso** [comment]
[**@ryanbr**](https://github.com/ryanbr) commented on [2017. dec. 24. 02:01 CET](https://github.com/ryanbr/fanboy-adblock/issues/199#issuecomment-353758360 "2017-12-24T01:01:28Z - Replied by Github Reply Comments"):
> Not sure if this is fixable, Solidopinion probably needs to fix this

How come? Can't you just whitelist the element? Or tweak the filter that hides it?

**Comment by ryanbr** [comment]
I couldn't find the filter causing it, and even we managed to whitelist the affected filters it would only apply the main site and not all sites using Solidopinion.

**Comment by ryanbr** [comment]
Closing this, if its still an issue, point Solidopinion to this thread.
