### ISSUE TITLE
fanboy-adblocklist-swe.txt - tv4play.se

### ISSUE THREAD

**Issue by flyingzebras** [ryanbr/fanboy-adblock#20]
I have succefully used [tv4play.se](http://www.tv4play.se/) with these domains blocked:

com.s3.amazonaws.com
conviva.com
schneevonmorgen.com
stat-api-prod.herokuapp.com
video-annotator-api-prod.herokuapp.com
videoplaza.tv

Can you please add them?

**Comment by ryanbr** [comment]
Even if you block them, Those don't seem to be ads.

**Comment by flyingzebras** [comment]
@ryanbr They need to be blocked so we can rule out where the ads come from. These spagetti domains is useless for the video user.

**Comment by ryanbr** [comment]
Only blocking ad/tracking scripts or popups, the site is very clean. No further work needed from me

**Comment by flyingzebras** [comment]
This filter will remove the video ads:
>||videoplaza1.tv^$third-party

Can you please add it?

**Comment by SMed79** [comment]
If you block 'videoplaza' the video won't play.

**Comment by flyingzebras** [comment]
@SMed79 1) I wrote "videoplaza1.tv" (note the extra "1") 2) Also, "videoplaza.tv" can be blocked these days but that won't remove any ads.

**Comment by flyingzebras** [comment]
@ryanbr Erm, can you please have a look. Having one person look for all ads of all countries in the world is very inconvenient.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by flyingzebras** [comment]
https://github.com/reek/anti-adblock-killer/issues/1464
