### ISSUE TITLE
css blocked on uky-sb.peopleadmin.com

### ISSUE THREAD

**Issue by mapx-** [ryanbr/fanboy-adblock#200]
wrong filter

`/\.(accountant|bid|click|club|com|cricket|date|download|faith|link|loan|lol|men|online|party|racing|review|science|site|space|stream|top|trade|webcam|website|win|xyz|com)\/(([0-9]{2,9})(\.|\/)(css)?)$/$script,stylesheet,third-party,xmlhttprequest`

see
https://adblockplus.org/forum/viewtopic.php?f=10&t=54710&p=173368#p173368

**Comment by j-allen** [comment]
Not sure this came through correctly when I pasted it 


STYLESHEET | Block item

https://pa-hrsuite-production.s3.amazonaws.com/1391.css

 /\.(accountant\|bid\|click\|club\|com\|cricket\|date\|download\|faith\|link\|loan\|lol\|men\|online\|party\|racing\|review\|science\|site\|space\|stream\|top\|trade\|webcam\|website\|win\|xyz\|com)\/(([0-9]{2,9})(\.\|\/)(css)?)$/$script,stylesheet,third-party,xmlhttprequestEasyList

**Comment by mapx-** [comment]
fixed
https://github.com/easylist/easylist/commit/112b38c4753227fd4d0d8c14533e0bc4182e2438
