### ISSUE TITLE
Fanboy's Annoyance List: DHL Tracking blocked

### ISSUE THREAD

**Issue by stdedos** [ryanbr/fanboy-adblock#204]
I can provide a testing link - although I prefer not to post it publically

|Document domain | Type | FilterOrigin|
|-- | -- | --|
|  | ELEMHIDE | ###toTop|
|www.dhl.fi | -- |Fanboy's Annoyance List|

**Comment by SMed79** [comment]
> I prefer not to post it publically

send an e-mail to [fanboy](http://scr.im/fanboy) (the annoyance list author).

**Comment by stdedos** [comment]
@SMed79 Good call! E-mail sent

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7b82355f2c0d49c174563825b8c6f7e0bba7b5e8

**Comment by stdedos** [comment]
@ryanbr Ahem, would you kindly remove the tracking number from the commit?

> although I prefer not to post it publically

**Comment by ryanbr** [comment]
Not sure how to change a commit message, though it was just a "testing url" as you stated?

**Comment by stdedos** [comment]
`git commit --amend && git push origin -f`

> although I prefer not to post it **publically**

Why I would go all the trouble to send it with e-mail, if you simply post it in public commits?

**Comment by ryanbr** [comment]
That command will only modify the master/newest commit.

**Comment by stdedos** [comment]
```
git rebase -i 7b82355^
# edit `p 7b82355` with `e 7b82355`, save and exit the used editor
git commit --amend
# obsfucate link
git rebase --continue
git push origin -f
```

**Comment by stdedos** [comment]
Thank you. Now kindly edit the comment with the correct reference (https://github.com/easylist/easylist/commit/b26381cb8d939a948023f3f97835aaccb3d4805a)

**Comment by SMed79** [comment]
> How to change your commit messages in Git?
> https://gist.github.com/nepsilon/156387acf9e1e72d48fa35c4fabef0b4
