### ISSUE TITLE
[Incorrect blocking] kizlarsoruyor.com [Fanboy's Social Blocking List]

### ISSUE THREAD

**Issue by Alex-302** [ryanbr/fanboy-adblock#207]
URL:
https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.kizlarsoruyor.com%2Fdiger%2Fq5784129-neden-asyali-kizlar-bile-turk-kizlarindan-guzel

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://s18.postimg.org/74m13fyzt/image.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://s18.postimg.org/xpojz092x/image.png)
</details>

Caused by
```
##.fb-content
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5c40d7aa30976563455c6ed586e60ae60eb3e56b
