### ISSUE TITLE
particuliers.engie.fr broken by fanboy's annoyances

### ISSUE THREAD

**Issue by mapx-** [ryanbr/fanboy-adblock#208]
example page:
`https://particuliers.engie.fr/electricite/chauffage-electrique/conseils/chauffage-electrique-intelligent.html`

fix
`particuliers.engie.fr#@##backToTop`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4468fbf8f241dee5d86492d9c4ed419d593e01b8
