### ISSUE TITLE
 fanboy-adblocklist-swe.txt - aftonbladet.se

### ISSUE THREAD

**Issue by flyingzebras** [ryanbr/fanboy-adblock#21]
These domains can safely be blocked.

ab-web-notifications.herokuapp.com
blocket.com
blocket.se
d1nf1ogr7o23z7.cloudfront.net
omni-cdn.se
schibsted.com

**Comment by ryanbr** [comment]
again, no ads seen on the site. Blocking random scripts?

**Comment by flyingzebras** [comment]
@ryanbr Yes.

**Comment by ryanbr** [comment]
Only blocking ad/tracking scripts or popups, the site is very clean. No further work needed from me
