### ISSUE TITLE
Fanboy’s Annoyance and Social Blocking List break b.hatena.ne.jp

### ISSUE THREAD

**Issue by tauxeta** [ryanbr/fanboy-adblock#211]
Disabling each one of these lists the page loads fine.
uBlockOrigin 1.14.22
Chrome  63.0.3239.108 
Firefox  57.0.2

`||st-hatena.com^$third-party`

**Comment by ryanbr** [comment]
Whats broken on the site?

**Comment by tauxeta** [comment]
Before the deletion It was looking like this https://imgur.com/I1Rz7kS
But it is fixed now in both filter lists https://github.com/easylist/easylist/commit/4eb86b12ba96bb06743d0260c34af01dcf5383e3
