### ISSUE TITLE
chillitorun.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#212]
![2017-12-29 11_50_28-zabytkowy budynek przy szumana sprzedany _ chillitorun](https://user-images.githubusercontent.com/5884000/34435502-7d9839a6-ec8e-11e7-8b71-84945f13d103.png)
`http://www.chillitorun.pl/miasto/zabytkowy-budynek-przy-szumana-sprzedany/`

`Fanboy’s Social Blocking List`

https://github.com/MajkiIT/polish-ads-filter/issues/5316

my filters
easylist + polish filters

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/da2c60176099c5f4d8ff8cafec4b391dec02286e
