### ISSUE TITLE
dealabs.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#213]
`/let-it-snow_`

`##.btn--move-to-top`
http://i.imgur.com/3N4h3A6.png

`dealabs.com###softMessages-list`
http://i.imgur.com/oU6iqxI.png

* https\://www.dealabs.com/bons-plans/m-1146665

see also https://forums.lanik.us/viewtopic.php?f=62&t=30537

**Comment by raphaelh** [comment]
CookieMonster list breaks dealabs.com

It hides the navigation bar at the top:

`<div class="nav-content page2-center tGrid tGrid--auto space--r-2 space--fromW3-l-2">`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d74d5f60cf0d893205ea3beacc6027a2ebbefb48
https://github.com/easylist/easylist/commit/665f228e59df6c0759128ff48b60789155489346

**Comment by raphaelh** [comment]
Thanks! Your commits fixed the problem
