### ISSUE TITLE
mercotte.fr

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#214]
```
##.socials-label
##.socials-icons
```
* http://i.imgur.com/9xkJoj5.png

```
mercotte.fr###abonnements-widget
```
* http://i.imgur.com/3LoPuEc.png

https\://www.mercotte.fr/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7c922aadf8a1dc8fe00fa4a0f06e713f1b7b8daf
