### ISSUE TITLE
hyperpc.ru

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#216]
```
/goodshare.
```
* `https://hyperpc.ru/media/jui/js/goodshare.min.js`
* `https://cdnjs.cloudflare.com/ajax/libs/goodshare.js/4.0.6/goodshare.min.js`

https\://hyperpc.ru/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/54a24236b41dae7f46b202a038c19992a08a2409
