### ISSUE TITLE
Fanboy annoyance list blocks morningstar tax comparison with ##.cc_container

### ISSUE THREAD

**Issue by shuhaowu** [ryanbr/fanboy-adblock#217]
The problem url is:

http://quote.morningstar.ca/QuickTakes/ETF/etf_taxanalysis.aspx?t=HXT&region=CAN&culture=en-CA

You can't open the compare tab with fanboy annoyance list enabled as shown below:

![screenshot from 2018-01-01 15-21-12](https://user-images.githubusercontent.com/338100/34470795-b16921d4-ef07-11e7-9157-0fac4e3b269f.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/733b3a5855443b94609ab13563098f660b406ec2
