### ISSUE TITLE
mva.microsoft.com

### ISSUE THREAD

**Issue by GoodGuyNick** [ryanbr/fanboy-adblock#218]
Using **Fanboy’s Enhanced Tracking List** in **uBlock Origin**.
On a https://mva.microsoft.com videos are not loading.
[Example](https://mva.microsoft.com/en-us/training-courses/creating-flappy-bird-using-reactjs-18124)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/186c3071e3304fdbb1b21a59719494fa4b3a40b1
