### ISSUE TITLE
linkis.com (Force Twitter auth annoyance)

### ISSUE THREAD

**Issue by kowith337** [ryanbr/fanboy-adblock#22]
I'm work on my filter to stop most overlay that force users to like pages or follow brand account(s), include Linkis site that do the worst thing.

Many peoples on twitter was infected by Linkis.com, a twitter app that automatically wrapped links and force users who open links that wrapped by it to authorize app to see content, users who fall to this trap will do the same thing without notice due to that app can delete tweet that have URLs and repost with linkis.com or ln.is wrapped links. _(do the loop)_

This rules below isn't block access linkis.com, but to prevent linkis.com attempt users who open links from linkis forced to authorize to see content*
_Note: some links from linkis cannot load framed content and show the force twitter app authorize page (mostly appear when open in mobile browser, e.g. Firefox for Android)_

> Filters and rules below are pull from my filter and issue.
> kowith337/ThaiAntiForceLike#2
### Must be blocked

**Network Filtering**

```
||linkis.com/ajax/get-popup-html?
||linkis.com/ajax/update-click?*force_auth
||linkis.com/index/ln-event?*force-auth
```

To prevent "authorize twitter to see content" popup request (I didn't insert `$ request type` tag because It's request as image instead of XHR, logged with uBlock)

**Element Hiding**

```
linkis.com##.deeper-overlay
linkis.com##.js-forceAuth-popup-light
linkis.com##.popup_force-auth
```

Mainly to block overlay popup

```
linkis.com##.js-modal-popup
linkis.com##.js-popups-html
```

Don't sure about these rules, it does to hide overlay popup, but sometime it's affect to top panel.
### Excluded

`linkis.com#@#.social-panel` to unhide top bar (Fanboy Ultimate/Annoyance is hide ##.socialpanel)
`@@||amazonaws.com/user_photos$image,domain=linkis.com` to allow user icon (maybe useless)

**Comment by ryanbr** [comment]
Is there a 3rd-party site where this is used? I don't want to prevent people from logging in at all, though I hate forced logins to read content.

**Comment by kowith337** [comment]
Interest third party sites that linkis used.
- AddThis widget for share/export link to other SNS, Mail, etc.
- Google Analytics for tracking visitors.
- DoubleClick (Google ads) to show ads banner over iframe.
- Amazon AWS to show linkis user's avatar.
But some third party sites above will be present or not present, depend on generated links or what sites was generated because it have various overlay theme they've created.

> - All wrapped contents seems counted as third-party too, because it wrapped page as iframe, the front mask is have additional appearance to show who shared through that, also made some request to bring overlay popup for try force visitor authorize twitter app.
> - Some sites was changed appearance by Linkis and show content as embed-like instead. (e.g. Instagram, YouTube)

**Comment by ryanbr** [comment]
I could only fix/reproduce the social panel issue. 

https://github.com/easylist/easylist/commit/83f2d076d458775fd5539d042569b5613cebfddc

**Comment by kowith337** [comment]
Sorry for very late respond due to cannot use laptop for a while.
It seems hard to tell, but after quick test on Mobile device (Fennec F-droid 48 + uBO 1.90) it still show popup in first time (when no cookies from `linkis.com` was created before OR open in private tab) because it made `/ajax/get-popup-html` XHR to call lightbox, but it seems doesn't make same request when visit another one.
Also, I think this element rule (`##.js-forceAuth-popup-light`) might be blocked along with.

**Comment by ryanbr** [comment]
Test on the desktop since I can't reproduce this.

**Comment by kowith337** [comment]
1. Above quick test also have "Request desktop site" checked.
2. [also forget my previous comment above] Can't confirm right now, it's sometime show, and sometime aren't, or just a random chance.
3. confirmed it will use `/ajax/get-popup-html` XHR and `##.js-forceAuth-popup-light` to call and show lightbox.

[screenshot 2](https://cloud.githubusercontent.com/assets/16535467/18277656/730c5596-7479-11e6-9984-6bcf41f8d75e.jpg)
[screenshot 3](https://cloud.githubusercontent.com/assets/16535467/18277661/7375cd1e-7479-11e6-83b3-5ccddb488e3c.jpg)
[screenshot 4](https://cloud.githubusercontent.com/assets/16535467/18277666/7385ac02-7479-11e6-99ab-882c45b26492.jpg)

**Comment by ryanbr** [comment]
Might help? 

https://github.com/easylist/easylist/commit/adc3502cc8ab79ace98d70f445754d54afa2fda8

**Comment by kowith337** [comment]
Test with social blocking list, worked!
