### ISSUE TITLE
Annoyance List & Cookiemonster list blocking Sandisk.com

### ISSUE THREAD

**Issue by Palf994** [ryanbr/fanboy-adblock#220]
The following filters seem to prevent anything from loading at [https://www.sandisk.com/home/ssd](https://www.sandisk.com/home/ssd):
1. ##.back-top in Fanboy's Annoyance List
2. ###consent_blackbar in Fanboy's Cookiemonster List

I was using uBlock Origin.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/8cb09725e43c2cdb91ed48762c6b09da1b499048

I didn't see issues with ##.back-top, but fixed the non-display.
