### ISSUE TITLE
Cookie warnings present on these sites

### ISSUE THREAD

**Issue by Alfinger** [ryanbr/fanboy-adblock#221]
I still can see a cookie warnings on this site and don't know how to fix it myself:
https://www.onlinetvrecorder.com/v2/

I'm using the Fanboy’s Cookiemonster List. Can someone post me a link to a guide how to add this under my filters myself?
Sorry if this quation is too basic. I'm just new to this. Thanks!

**Comment by ryanbr** [comment]
Not an easy fix, if you add this, does this filter work?

`onlinetvrecorder.com##div[id^="d1"]`

**Comment by Alfinger** [comment]
Yes, perfect. Thanks a lot for the quick reply!

**Comment by ryanbr** [comment]
I'll add to the list later, thanks for the confirmation

**Comment by ronjouch** [comment]
@ryanbr one more addition proposal to the Cookiemonster list: on https://unity3d.com/learn/tutorials/projects/roll-ball-tutorial/setting-play-area?playlist=17141 I see a typical cookie div, using class `cookies-dialog`

**Comment by ryanbr** [comment]
Seems to be blocked already with ##.cookies-dialog ?

**Comment by ryanbr** [comment]
onlinetvrecorder.com added;

https://github.com/ryanbr/fanboy-adblock/commit/4e983200fcdb05976aec216ece5af54cdc054640

**Comment by ronjouch** [comment]
> *Seems to be blocked already with `##.cookies-dialog` ?*

@ryanbr hmmmm indeed, should be. But it's not; no idea why.

**Comment by ronjouch** [comment]
> *Seems to be blocked already with `##.cookies-dialog` ?*

@ryanbr hmmmm indeed, it is. It wasn't, because it looks like uBlock filtering is not applied on displaying pages after a browser restart. Must be a known issue. Thanks for the fast response 👍.
