### ISSUE TITLE
Twitter embeds not working

### ISSUE THREAD

**Issue by shapiro125** [ryanbr/fanboy-adblock#222]
Twitter embeds on sites aren't working due to rule `||platform.twitter.com*/widgets/$third-party` in Fanboy Annoyances.

This can be seen on sites such as https://sploid.gizmodo.com/google-can-now-tell-you-which-works-of-art-you-look-lik-1822074643

Thanks!

**Comment by ryanbr** [comment]
Part of the social list, I added a whitelist previously. Force an update and retest

**Comment by shapiro125** [comment]
Forced update worked, thanks

For anybody searching later -- it showed me that it was being whitelisted, but didn't work until i allowed platform.twitter.com as a 3rd party cookie.
