### ISSUE TITLE
Facebook is full of ads

### ISSUE THREAD

**Issue by WalrusInAnus** [ryanbr/fanboy-adblock#225]
I am not even sure whether the "Anti-Facebook List" blocks anything anymore.
My Facebook wall is full of suggested groups, posts, etc.

**Comment by ryanbr** [comment]
Anti-Facebook List isn't blocking the ads, its blocking 3rd-party facebook requests. Basically if you care about your privacy, without facebook tracking your every movement. then this list is for you.

**Comment by WalrusInAnus** [comment]
Oh, ok. That's good to know.
Do you suggest I use it with uBlock as well? - because I am not entirely sure how differently it works compared to Adblock.

**Comment by ryanbr** [comment]
It'll work fine. just keep in mind some sites that use Facebook comments won't work (comments won't show).
