### ISSUE TITLE
Weatherdotcom

### ISSUE THREAD

**Issue by rpodric** [ryanbr/fanboy-adblock#226]
Hi, I noticed "Fanboy Problematic websites List" and added it to uBO, but this periodic popup on weatherdotcom is not handled. I see that domain is mentioned in the filter though, but it's unclear what it's supposed to do. If it's meant to handle this, it no longer is. Could it be handled?

https://imgur.com/a/c7qfd

**Comment by ryanbr** [comment]
Good to see someone using it :) 

https://github.com/ryanbr/fanboy-adblock/commit/f394f65f21251d60bd8b4b54c05e3ee8a5d4115d

Should be in the list in the next 45mins.

**Comment by rpodric** [comment]
Looks great, thanks!
