### ISSUE TITLE
techgyd.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#227]
social
```
##.thesocialbar
##.thesocialbartext
##.thesocialbarform
###menu-herald-social
```

* http://i.imgur.com/gUp6gI1.png
* http://i.imgur.com/YuBtHkE.png
* http\://www.techgyd.com/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1c129d10de52ae2b639d67be77e96214b93c5515
