### ISSUE TITLE
hyperdebrid.net

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#228]
Cookie notice on the bottom of the page with Fanboy’s Cookiemonster List: https://hyperdebrid.net/

**Comment by ryanbr** [comment]
I'm not seeing this, can you share the coookie element (using the picker in uBo, or element hider in ADP)

**Comment by SMed79** [comment]
`$generichide` filter in the **Liste FR** / Removed here [678ce8c91260#l1.50](https://hg.adblockplus.org/listefr/rev/678ce8c91260#l1.50).

@adranger Update your filter lists and test again.

**Comment by adranger** [comment]
Actually, I had disabled cosmetic filtering manually for it before because EasyList was breaking something, and  didn't remember it. Now it works as expected.

At least this false report wasn't in vain, and you fixed the French list.
