### ISSUE TITLE
using similar ad strings to other sites

### ISSUE THREAD

**Issue by rajatmathurs** [ryanbr/fanboy-adblock#23]
`http://bossmp3.in/category/3844/Tere_Bina_(Shorgul)_Arijit_Singh.html`

using similar ad strings to other sites.
`https://forums.lanik.us/viewtopic.php?f=62&t=31072`

add this general filter 
`##a[href*=":80/key/"] `

which blocks ads and banners for all below mentioned sites and many more which is not mentioned.

`heromaza.in`
`songmix.in`

Thank you for your time and support

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/326acf4119f52ad8a866119c27bcd0bed4c60c24
https://github.com/easylist/easylist/commit/e4974b92236e2f89a252a0d1dc9ee14720268069
https://github.com/easylist/easylist/commit/38514236e207125c00872effcb51a959501b8445
