### ISSUE TITLE
Unable to get far in https://getsupport.apple.com/.

### ISSUE THREAD

**Issue by antdude** [ryanbr/fanboy-adblock#230]
Hello.

1. Go to https://getsupport.apple.com/.
2. I clicked on its iPhone and its Battery Replacement.

Highlighted "Battery Replacement", but it doesn't continue onto more options.

/omniture/ | -- | xhr | https://getsupport.apple.com/lib/internal/omniture/v3/appleSatelliteLib.min.packager-201601026A.dt
-- | -- | -- | --

I was using SeaMonkey v2.49.1 web browser and UO v1.13.8 extension's Fanboy’s Enhanced Tracking List subscription.

Thank you in advance. :)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/db7307a575ef0bdf858ae70b100d76e3639b2a3e

**Comment by antdude** [comment]
When will this fix be released? I cleared and downloaded the subscription, but still saw the same issue.

**Comment by ryanbr** [comment]
Was fixed a while ago, I limited it to scripts only and not (as you reported) xmlrequests.
