### ISSUE TITLE
radiogra.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#231]
![2018-01-21-radio gra wroclaw](https://user-images.githubusercontent.com/5884000/35195383-e6a451dc-fec2-11e7-8f99-fba902ecc890.png)
`https://radiogra.pl/`

site don't work

Fanboy’s Annoyance List

https://github.com/MajkiIT/polish-ads-filter/issues/5658

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.27
Nano Defender 13.22
Chrome 63.0.3239.132

**Comment by SMed79** [comment]
add
```
radiogra.pl#@##to-top
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7b4619883c447e30d5ba0c0dbf697642271d69ac
