### ISSUE TITLE
Blocked videos

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#232]
This rule (found in '**Fanboy’s Anti-Thirdparty Social**') breaks video playback for some sites:
**||connect.facebook.com^$third-party,domain=~facebook.net|~fb.com**

Example:
https://screenrant.com/video/10-new-star-wars-theories-that-actually-make-sense/

I'm aware of the warning for this particular filter, I just wanted to let you know, in case the behaviour isn't intended. :)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/088187f3f9154584e3aa99b58addcb77b51f7404
