### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#233]
![2018-01-21-mbank podwoi wszystkie wplaty na wosp 7 000 000 zlotych - wykop pl](https://user-images.githubusercontent.com/5884000/35198836-f08e59d6-fef4-11e7-8f38-7bc88d6c75ad.png)
`https://www.wykop.pl/link/4111221/mbank-podwoi-wszystkie-wplaty-na-wosp-7-000-000-zlotych/`

Fanboy's Social Blocking List

https://github.com/MajkiIT/polish-ads-filter/issues/5655

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.27
Nano Defender 13.22
Chrome 63.0.3239.132

**Comment by hawkeye116477** [comment]
`wykop.pl#@#.social-list`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/77cd25ef0fe4619e983e1a069d26e96b07d7ffe1
