### ISSUE TITLE
.alert-dismissible class

### ISSUE THREAD

**Issue by giorgiopagnoni** [ryanbr/fanboy-adblock#235]
Why is the bootstrap class `alert-dismissible` blocked? It's a normal class often used to style Symonfy flashbags, among other things.

**Comment by karolyi** [comment]
+1

I use it at a lot of places, to tell important notifications to users. Please unblock. I was wondering why we get a lot of feedback from people not understanding what's happening on the site while they're navigating around.

`.alert-dismissible` is part of an essential twitter bootstrap alert.

https://github.com/twbs/bootstrap/issues/25433

**Comment by karolyi** [comment]
Examples (blocked with this list):
https://getbootstrap.com/docs/4.0/components/alerts/#dismissing

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cc380a8064060c962989a288a57cd3793e1ed73c
