### ISSUE TITLE
Fanboy's Cookiemonster List breaks website

### ISSUE THREAD

**Issue by WalrusInAnus** [ryanbr/fanboy-adblock#236]
When using uBlock with the above mentioned filter, this [page](http://www.samsung.com/semiconductor/minisite/ssd/product/consumer/ssd960/) (along with probably anything besides Samsung's main site) doesn't open at all. I just see blank page.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/5097e8ebe0271dae7b7c98d34a3061dc3bf63d37
