### ISSUE TITLE
kdnuggets.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#237]
![2018-01-24-machine learning data science big data analytics ai](https://user-images.githubusercontent.com/5884000/35315323-1ec175b2-00cc-11e8-93af-a6b4e235b622.png)
`https://www.kdnuggets.com/`

social

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.24
Chrome 63.0.3239.132

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ae8fb424db928a27817c218b3c2180e24e55ad9e
