### ISSUE TITLE
superbiznes.se.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#238]
![2018-01-24-superbiznes](https://user-images.githubusercontent.com/5884000/35316513-53486e0c-00d2-11e8-8726-126eb7060547.png)
`http://superbiznes.se.pl/`

broken site

Fanboy’s Annoyance List

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.24
Chrome 63.0.3239.132

**Comment by hawkeye116477** [comment]
@ryanbr Can you add this -> `superbiznes.se.pl#@##fbContainer` ?
