### ISSUE TITLE
ShareLaTeX share button is blocked leading to users being unable to share projects

### ISSUE THREAD

**Issue by casselt** [ryanbr/fanboy-adblock#240]
In ShareLaTeX the share button has id="shareButton" which leads to being blocked by the list. Problem: It is not enough to whitelist sharelatex.com since there exists lots of private installation, some huge like ours at a university.

**Comment by ryanbr** [comment]
Best to take it up with ShareLaTeX, they could change the element

**Comment by casselt** [comment]
Already did that, they will look at it.
