### ISSUE TITLE
freecodecamp.org overblocking

### ISSUE THREAD

**Issue by stonecrusher** [ryanbr/fanboy-adblock#243]
Fanboy's Annoyance List and Fanboy's Social Blocking List hide the signup and login buttons on
```
https://www.freecodecamp.org/signin
```
caused by `##.btn-social`.

Something like `@@||freecodecamp.org^$generichide` helps, but is a bit too unspecific?

/edit
`@@||freecodecamp.org/signin^$generichide` should do it.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/903bd390e9813b192cb6b966c33b8349f9c730b7
