### ISSUE TITLE
zaufanatrzeciastrona.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#244]
@ryanbr Fanboy's Social Blocking List hides RSS icon on right. RSS icon should be under „Trzymaj rekę na pulsie" section.

Fix -> `@@||zaufanatrzeciastrona.pl/wp-content/plugins/subscribe-connect-follow-widget/images/32px/rss.png`

**Comment by ryanbr** [comment]
Leaving, it would counter the Annoyance filters use of blocking rss icons.
