### ISSUE TITLE
gwarek.com.pl

### ISSUE THREAD

**Issue by Ravizz** [ryanbr/fanboy-adblock#245]
@ryanbr : Fanboy's Social Blocking List hides comments section: https://github.com/MajkiIT/polish-ads-filter/issues/5763

<details>
  <summary>Should be:</summary>

![capture_043_28012018_200535](https://user-images.githubusercontent.com/35421792/35485928-be851f84-0466-11e8-994b-01093367b1df.png)

</details>

**Comment by ryanbr** [comment]
Its expected, it'll block Facebook comments
