### ISSUE TITLE
Breaking PrintFriendly & PDF Chrome Extension

### ISSUE THREAD

**Issue by taylor-n** [ryanbr/fanboy-adblock#246]
PrintFriendly.com is a legit service. It helps people save money and the environment when they print webpages. 

**Can you please remove PrintFriendly.com from the list?** It's breaking the Chrome Extension for our users.

**See we're legit:** https://chrome.google.com/webstore/detail/print-friendly-pdf/ohlencieiipommannpdfcmfdpjjmeolj?hl=en

![image](https://user-images.githubusercontent.com/10843733/35550676-8bf73988-05c6-11e8-9347-d15af38ed6a9.png)

**Comment by ryanbr** [comment]
Was resolved.
