### ISSUE TITLE
majkrafci.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#247]
![2018-01-31-majkrafci pl](https://user-images.githubusercontent.com/5884000/35616439-826dfe88-0675-11e8-8927-5dc9618f3a72.png)

please unblock, this is main content of this site

`##.fb-page`
`||facebook.com^*/plugins/page.php?$third-party`

**Comment by hawkeye116477** [comment]
@ryanbr I still have that problem. It's caused now also by `##.fb-xfbml-parse-ignore`.
