### ISSUE TITLE
nvidia.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#249]
@ryanbr On https://shield.nvidia.pl/blog Fanboy's Social Blocking List hides newsletter on right. On right should be „Zamów subskrycję biuletynu" just like in first image above. 
Also it hides newsletter on https://www.nvidia.pl/page/home.html (should be „ZAREJESTRUJ SIĘ, BY 
OTRZYMYWAĆ WIADOMOŚCI OD FIRMY NVIDIA" just like in screenshot number 2) .

Fixes:
 ```
nvidia.pl#@#.social-newsletter
nvidia.pl#@#.subscribe-text
nvidia.pl#@#.subscribe-container
```
![screenshot_20180201_135912](https://user-images.githubusercontent.com/19818572/35679663-37a7e06a-0758-11e8-9471-204fa5826a82.png)

![screenshot_20180201_140200](https://user-images.githubusercontent.com/19818572/35679786-92a538b4-0758-11e8-95c8-0ffa4e21e590.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2f07673c93a5abb72fa3028d6a6afca156e50065
