### ISSUE TITLE
fanboy-adblocklist-swe.txt - poporock.com

### ISSUE THREAD

**Issue by flyingzebras** [ryanbr/fanboy-adblock#25]
poporock.com domains

poporock.com ajax.googleapis.com
poporock.com facebook.com
poporock.com facebook.net
poporock.com fonts.googleapis.com
poporock.com gravatar.com
poporock.com wp.com

**Comment by ryanbr** [comment]
^ not helpful info. But the site is enough.

https://github.com/ryanbr/fanboy-adblock/commit/622078ce36023bb2846dbeb8a460ed4551f6f089
