### ISSUE TITLE
Accept cookies still showing in a website even with Cookie Monster & Annoyance list enabled

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#251]
The title said it all. 
So, this is the site I'm talking about. 

(https://www.dailystar.co.uk/real-life/679306/firefox-mozilla-new-logo-fox-or-red-panda/amp)

There's a screenshot (http://imgbox.com/ArvIp9AH)

I'm seeing accept cookies prompt. 
Browser: Firefox Nightly 60 on Android
Adblocker: Ublock Origin 1.15.4

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/c0f8e22f09f181bc7b5427592d4a4740389b9b21
