### ISSUE TITLE
laradiofm.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#252]
```
##a[href^="https://vk.com/share.php?url="]
##a[href="https://twitter.com/home/?status="]
```
http://i.imgur.com/QBWXJ1P.png

https\://laradiofm.com/Station-3017

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8ae6f0589ab5058821536aaca8123f8b665b27ed
