### ISSUE TITLE
telechargerunevideo.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#253]
[annoyance / social]

Click **Download** ==> http://imgur.com/wmHbcvKl.png

```
||telechargerunevideo.com/*/js/jquery.bpopup.min.js
```
https\://www.telechargerunevideo.com/en/finish?id=Ado1E3zahw

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a66811debd3a0792f634371f466d82dd8b2c7afc
