### ISSUE TITLE
flyordie.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#254]
cookies notice
```
flyordie.com###eucc
```
http://i.imgur.com/EsyNDJN.png

privacy
```
/log/error?
```
ads
```
||jokbon.com^
||dvdsm0rlx65fo.cloudfront.net^
||d38jqyqnm50w90.cloudfront.net^
```
or
```
|http://$script,xmlhttprequest,third-party,domain=flyordie.com
|https://$script,xmlhttprequest,third-party,domain=flyordie.com
```

http://i.imgur.com/XCFRZEe.png
http\://www.flyordie.com/8ballpool/

**Comment by SMed79** [comment]
@okiehsch fyi.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0605264178f5ea619a3c1813ea4e3ee4f32f7498 

should help?

**Comment by SMed79** [comment]
> should help?

Yes, thank you.
