### ISSUE TITLE
forbes.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#256]
@ryanbr Can you add this rule -> `@@||ocdn.eu/forbes/misc/fb_logo.png`, because rule `/fb_logo.` which is on Fanboy's Social and Annoyance lists, hides Forbes logo.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c49b8374c2821bf59b7672377deefa17c93b83d1
