### ISSUE TITLE
www.aftonbladet.se

### ISSUE THREAD

**Issue by Zawaq** [ryanbr/fanboy-adblock#257]
Hi, when opening an article on the website a "please inactivate adblock"-popup appears over article.
Is a fix possible?

**Comment by ryanbr** [comment]
Does this work?

`@@||ib.adnxs.com^$xmlhttprequest,domain=aftonbladet.se`
`@@||aftonbladet.se^$generichide`

**Comment by lalalandblabla** [comment]
I have the same issue. I dont know much about code... what am i supposed to try with the text you just shared?

**Comment by ryanbr** [comment]
Add it to your personal filters/Apply, refresh the site to see if it works.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/e13c7c828ac70fe545da6bae9728af94fc5253da
