### ISSUE TITLE
freep.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#259]
```
##.taboola-sidebar-title
```

https\://www.freep.com/

**Comment by ryanbr** [comment]
Didnt see this.

https://github.com/easylist/easylist/commit/20885559903b5f536325e4284c9d67ac13db5c6b

**Comment by SMed79** [comment]
\<section id="module-position-19" class="card-sidebar **taboola-module** **taboola-sidebar** primary-suspender-sidebar-page-sidebar-module">\<div class="sidebar-title-wrapper **taboola-sidebar-title-wrapper**">\<h6 class="sidebar-title **taboola-sidebar-title** home">
