### ISSUE TITLE
aliexpress-ad on putlockerTV

### ISSUE THREAD

**Issue by lalalandblabla** [ryanbr/fanboy-adblock#261]
`https://putlockertv.se/watch/show-me-love.wxo4/009vv7`

**Comment by SMed79** [comment]
add https://forums.lanik.us/search.php?keywords=dc5ig2fc8lg83.cloudfront.net

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b06bafec0dc48e33e714a63a5354779b3d1e8dd7
