### ISSUE TITLE
otakustream.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#262]
![2018-02-20-otakustream - watch anime online english subbed hd](https://user-images.githubusercontent.com/5884000/36425801-40754ddc-1648-11e8-9e64-e008c004007b.png)

`otakustream.tv##.show.fade.modal-backdrop`

Fanboy’s Annoyance List
Fanboy’s Social Blocking List

**Comment by ryanbr** [comment]
Just removed it, otherwise it'll kill the scrollbar.

https://github.com/easylist/easylist/commit/44371eed77e78732e1ae9724cefcb7594b483693

**Comment by SMed79** [comment]
this filter `###socialbox` is what kill the scrollbar.

test
```
otakustream.tv#@##socialbox
otakustream.tv##a[style]
```

**Comment by KonoromiHimaries** [comment]
please reopen this thread.
