### ISSUE TITLE
Breaks blogs.bing.com

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#264]
https://blogs.bing.com/webmaster/january-2018/Introducing-Social-Login-for-Bing-Webmaster-Tools

Doesn't work when Fanboy's Cookiemonster list is enabled, but works without it enabled.

Broken due to cookiemonster list is blocking `.cc-container`.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/370b5fd46c491c3082bd8ba43ec25c8f55d1bfd4
