### ISSUE TITLE
niedziela.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#265]
@ryanbr Fanboy's Social Blocking List hides article on this page.
Example link -> `http://niedziela.pl/artykul/34031/Wkrotce-duze-zmiany-w-Kurii-Rzymskiej`
Fix -> `niedziela.pl#@#.article-social-btn`

https://github.com/MajkiIT/polish-ads-filter/issues/6315

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/89c298fb1b01270bd504da21e060e8d888c336c9
