### ISSUE TITLE
trainline

### ISSUE THREAD

**Issue by ariasuni** [ryanbr/fanboy-adblock#266]
- `trainline.*##div:has(> div > div > .cookies.notification__message)` (`.eu`, `.fr`, `.de`, `.it`, `.es`, `.cn`, `.ch`, `.com.br`, etc.)
- `thetrainline.com##[data-test="cookie-banner"]`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/4787842f79e1f973bcf3bbd10f607d37e07dc92b

**Comment by ariasuni** [comment]
Please also block the banner in mobile version:

`www.thetrainline.com##div[data-test="cookie-policy-banner"]`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/6b0cf7bf1366df3b3e8af065233485f9af84bc57
