### ISSUE TITLE
bilasport.com

### ISSUE THREAD

**Issue by agadirian** [ryanbr/fanboy-adblock#267]
Hi,

AdBlocker Google Chrome plugin is blocking clappr player on two of my websites. this sites are: bilasport.com and bilasport.me. 
Could you please whitelist our domain?

Links : http://www.bilasport.com/p/test-adblock.html and http://bilasport.me/cana.html

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=133101#p133101

@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/066ba4cac288a08a63cf919e998a6bb1675a47b6

Remove the popads, and the filters will be removed.
