### ISSUE TITLE
adblockplus.org

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#268]
### List the website(s) you're having issues:

`https://adblockplus.org/en/`

### What happens?
Leftover after social.

### List Subscriptions you're using:
Fanboy's Social Blocking List

### Other details:

Solution -> `adblockplus.org###social-list`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e5b2482c90f2ea7d8e54a56e0f70b7d424500ae8
