### ISSUE TITLE
Signup prompt at the bottom of the screen at blog.bitwarden.com

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#269]
There's a popup about sign up to get more updates. 
CookieMonster should take care of it.

https://blog.bitwarden.com/bitwarden-desktop-app-released-for-windows-macos-and-linux-37de846ea421

**Comment by ryanbr** [comment]
Try the Annoyances list, CookieMonster is only targeting cookie messages.
