### ISSUE TITLE
Threatpost.com - Broken search function

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#271]
**Affected site:**
`https://threatpost.com/`

**Issue:**
The page's search function is broken (located in the top right corner)

**Filters causing the problem:**
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

**Rule causing the problem:**
`/social-share.`

**Possible fix:**
`@@/social-share.$domain=threatpost.com`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.7.2 (x64)
- Adblock Extension/version: uBlock Origin v1.15.10

**Comment by ryanbr** [comment]
Please use the code tag to wrap your url.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bbcba1d177716326f456125e46874829479d4683
