### ISSUE TITLE
MSN.com - Blocked Instagram images

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#272]
**Affected site**:
https://www.msn.com/

**Issue**:
Instagram images are blocked

**Filter causing the problem**:
Fanboys Enhanced Tracking List

**Rule causing the problem**:
`/:\/\/www\.([a-z]{6,16})\.com\/([a-z]{1,5})\.js$/$script,third-party`

**Example** (scroll down to the Instagram image):
https://www.msn.com/nb-no/nyheter/verden/arresterte-og-fengslet-eskortepike-som-var-p%C3%A5-%C2%ABhemmelig%C2%BB-b%C3%A5ttur-i-norge/ar-BBJJWq9/

**Possible fix**:
`@@/:\/\/www\.([a-z]{6,16})\.com\/([a-z]{1,5})\.js$/$script,third-party,domain=msn.com`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.7.2 (x64)
- Adblock Extension/version: uBlock Origin v1.15.10

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/612fa9afc943c8c4c6d0e551f1588d55b17f013d
