### ISSUE TITLE
Swappa login page's social login buttons are hidden

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#274]
### List the website(s) you're having issues:

* `https://swappa.com/login`

### What happens?

Social login buttons are hidden

### List Subscriptions you're using:
* Fanboy's Annoyance List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 59
- Adblock Extension/version: uBlock Origin

### Other details:

uBlock logger:
![image](https://user-images.githubusercontent.com/5832930/36909078-b9ed33c8-1e45-11e8-9267-4accced61df3.png)

Firefox dev tools:
![image](https://user-images.githubusercontent.com/5832930/36909082-c1234fc4-1e45-11e8-83c1-60696114b075.png)

**Comment by SMed79** [comment]
add 
```
swappa.com#@##social-buttons
swappa.com#@#.btn-social
swappa.com#@#.btn-facebook
@@||static.swappa.com/static/icons/social/login_google.png
```

**Comment by ryanbr** [comment]
Ta.

https://github.com/easylist/easylist/commit/cdd9f7700c5aadd490d2d251915b484f939608d9
