### ISSUE TITLE
IMPORTANT: Meta-data

### ISSUE THREAD

**Issue by davidhedlund** [ryanbr/fanboy-adblock#28]
@ryanbr 
I noticed that you added this to
* https://www.fanboy.co.nz/fanboy-antifacebook.txt
* https://www.fanboy.co.nz/fanboy-cookiemonster.txt

> ! Reporting Issues: https://github.com/ryanbr/fanboy-adblock/issues

Thank you for doing that. Can you add it to the rest of your subscription filters?

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
@ryanbr [said](https://github.com/ryanbr/fanboy-adblock/issues/46):
> Personally I only read the issues via my personal git repo and the forums. I can't say much for the emails. fanboyadblock@googlegroups.com is defunct.

**Comment by SMed79** [comment]
@davidhedlund Do not be ridiculous :chicken: and STOP flooding :umbrella:

**Comment by davidhedlund** [comment]
@SMed79 Please do't tell me what to do. It's been much more time consuming for me to submit the filter to the wrong source over and over again.

**Comment by davidhedlund** [comment]
@SMed79 So what do you propose, pretend that the contact network work as it should?

**Comment by davidhedlund** [comment]
@SMed79 Stop supporting incompetence.

**Comment by davidhedlund** [comment]
@SMed79 There are multiple contact issues and that is why I submitted several issues about it.

**Comment by davidhedlund** [comment]
This is interesting. There are social codes on GitHub saying that, you are annoying if you submit "too many" issues in a short time, like this was a chat channel. I don't know the exact formula, but people like SMed79 take it for granted to discourage people from helping out, instead of shut up.

**Comment by davidhedlund** [comment]
@SMed79 Thank you for removing you post here. Please don't forget to blacklist me too, so I don't get response from you if I'm stupid enough to contact you.

**Comment by ryanbr** [comment]
Please calm down. We do support without cost, and in our spare time.. and you'll prioritise other issues over other things. Note the issue isn't closed, and when I have a chance I'll get to it.

**Comment by davidhedlund** [comment]
@ryanbr Don't worry. I didn't say you should fix all my submitted issues right now. I'm only annoyed on SMed79's critisism, not you.

**Comment by SMed79** [comment]
@davidhedlund I have only said 'flooding will not help'.

Anyway, sorry.

**Comment by davidhedlund** [comment]
@SMed79 Please do not duck the real issue here. You said: "Don't be ridiculous :chicken: and STOP flooding :umbrella:."]

IMHO "Ridiculous :chicken:" is childish, and "STOP" is commanding, in this context because you are neither the owner or the repository nor did you subscribe to the issues, so I don't think I flooded you personally.

**Comment by SMed79** [comment]
You are absolutely right. Again, I apologize.

**Comment by davidhedlund** [comment]
I forgive you @SMed79.  Namaste :pray:

**Comment by SMed79** [comment]
Thank you  :cat:

**Comment by davidhedlund** [comment]
@SMed79 With that said I'm going to continue my plans as the were before this day; a few days back I wanted to ask if you were interested to beta-test a ad crawler script. It will find anything on certain networks and automatically generate new EasyList filters.

Do you use GNU/Linux?

Would you like to try it?

**Comment by davidhedlund** [comment]
@SMed79 Never mind. But this project is going to set a new standard.

**Comment by davidhedlund** [comment]
@ryanbr A friendly reminder:

Can you please add "Issues: https://github.com/ryanbr/fanboy-adblock/issues" to all subscription files (like https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-swe.txt) so people know where to submit them?

**Comment by ryanbr** [comment]
No. Because the filters are just mirrors of other subscriptions. Only ones that are actually hosted here.

**Comment by davidhedlund** [comment]
@ryanbr This is the meta-data of one of your filters:

> ! Version: 201703082020
> ! Title: Fanboy's Annoyance List
> ! Last modified: 08 Mar 2017 20:20 UTC
> ! Expires: 4 days (update frequency)
> ! License: http://creativecommons.org/licenses/by/3.0/
> ! Please report any unblocked content or problems by email or in our forums
> ! Email: easylist.subscription@gmail.com
> ! Homepage: https://easylist.to/
> ! Forums: https://forums.lanik.us/

I suggest that you add your repo to complete the meta-data like this:

> ! Repository: https://github.com/ryanbr/fanboy-adblock/

What do you think about it?

**Comment by ryanbr** [comment]
Annoyances isn't hosted here, it a mirror from the Easylist repo.

**Comment by davidhedlund** [comment]
@ryanbr I don't find Annoyances on https://github.com/easylist. Where is it?

**Comment by SMed79** [comment]
> I don't find Annoyances on ...

- template https://github.com/easylist/easylist/blob/master/fanboy-annoyance.template
- files https://github.com/easylist/easylist/tree/master/fanboy-addon

**Comment by davidhedlund** [comment]
@SMed79 Thanks.

@ryanbr 

> fanboyadblock@googlegroups.com is defunct.

I find the invalid email on
* https://www.fanboy.co.nz/fanboy-adblock.txt
* https://github.com/easylist/easylist/blob/master/easylistfanboy/other/tracking-intl.txt

Can you update them?

**Comment by davidhedlund** [comment]
@ryanbr 
I noticed that you added this to
* https://www.fanboy.co.nz/fanboy-antifacebook.txt
* https://www.fanboy.co.nz/fanboy-cookiemonster.txt

> ! Reporting Issues: https://github.com/ryanbr/fanboy-adblock/issues

Thanks.

**Comment by davidhedlund** [comment]
https://github.com/easylist/easylist/issues/304
