### ISSUE TITLE
otakustream.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#280]
![2018-02-20-otakustream - watch anime online english subbed hd](https://user-images.githubusercontent.com/5884000/36425801-40754ddc-1648-11e8-9e64-e008c004007b.png)

https://github.com/ryanbr/fanboy-adblock/issues/262

Fanboy’s Annoyance List
Fanboy’s Social Blocking List

**Comment by SMed79** [comment]
Do you think a duplicate thread is helpful? The repo owner will see your thread as a spam.

**Comment by KonoromiHimaries** [comment]
@SMed79 thread #262 it was closed
I thought he was overlooked

**Comment by SMed79** [comment]
> I thought he was overlooked

Always remember that this report is maintained by volunteers.
https://forums.lanik.us/rules#volunteers
https://forums.lanik.us/viewtopic.php?f=9&t=20881
