### ISSUE TITLE
Ferplast.com - Blocked cookies = no product images

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#282]
### List the website(s) you're having issues:
`Ferplast.com`
Example:
`https://www.ferplast.com/int/cat-supplies.html`

### What happens?
Product images are unable to load as a result of blocked cookies.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookiemonster List

### Problem rule:
`/cookiepolicy/*`

### Possible fix:
`@@ferplast.com/js/filoblu/cookiepolicy/jquery.cookie.js`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.0 (x64)
- Adblock Extension/version: uBlock Origin v1.15.10

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8802f9f90e88bc022999043c29c185ad4239e33d
