### ISSUE TITLE
imagefap.com

### ISSUE THREAD

**Issue by hubbathegit** [ryanbr/fanboy-adblock#284]
### List the website(s) you're having issues:

`imagefap.com`
### What happens?

The site seems to have changed its ad scripting (the filters were working fine a couple weeks ago); it now creates pop-ups and redirects mouse clicks, which are not working normally to open links either directly or via right mouse click to open in a different tab/window.
### List Subscriptions you're using:

Fanboy Ultimate List
### Your settings

- OS/version: Windows 7 64bit
- Browser/version: Firefox ESR 52.6.0
- Adblock Extension/version: uBlock Origin 1.15.10

### Other details:

I'm assuming the existing filters simply need an update to counteract the site's current ad scripts, but I'm not the expert. Thank you. :-)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/ffe4e48707566eabf17abb36608a320233caf978

Does this help? Seems to be an ad-detection script.

**Comment by hubbathegit** [comment]
The issue persists, I'm afraid. 

If I click on anything with the LEFT mouse button, it automatically redirects to marketing sites. 

If I use the RIGHT mouse button, it acts as if it was the left button (meaning, it opens the link or image directly, instead of opening the browser's context menu as it should).

**Comment by ryanbr** [comment]
Not sure if this will be resolved by this list, I'm closing this. If you have a filter suggestion, re-open it.
