### ISSUE TITLE
mixcloud.com

### ISSUE THREAD

**Issue by anewuser** [ryanbr/fanboy-adblock#285]
### List the website(s) you're having issues:

`https://www.mixcloud.com/DjKevinAnthony/`

### What happens?

`##.follow-text` in Fanboy’s Annoyance List hides the internal "Follow"/"Following" button for logged-in users on Mixcloud. That's an essential feature on Mixcloud.

![Screenshot](https://user-images.githubusercontent.com/6733770/37183735-50fc4e32-2316-11e8-9b6c-9817b575ba00.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2281445f586521a13506c748e1ced75aa0041e09
