### ISSUE TITLE
tourhebdo.com

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#287]
**website**:

http\://www.tourhebdo.com/

**What happens?**

Social sharing btn

**List Subscriptions you're using**:

EasyList
EasyPrivacy
Fanboy's Annoyance List
Adblock Warning Removal List

- OS/version: Manjaro 17.1.6
- Browser/version: FF 58
- Adblock Extension/version: ABP 3.0.2

**Other details**:

```
##a[title="linkedin"]
##a[onclick^="doSocialShare"]
tourhebdo.com##.social
tourhebdo.com##.resocs
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/fb9ab4ab39c4827161105f15d6480a8915977f30
