### ISSUE TITLE
Some email popups still coming through

### ISSUE THREAD

**Issue by Nateliason** [ryanbr/fanboy-adblock#29]
See example here: http://blog.teachable.com/

What's the best way for me to help with identifying these other email popup sources? Paste examples here, or submit changes?

**Comment by ryanbr** [comment]
Sure, though I couldn't see any popups on http://blog.teachable.com/

**Comment by ryanbr** [comment]
No further comments, I've close this. I re-checked it again,  no email popups still (Using Easylist + Easyprivacy and Annoyances).
