### ISSUE TITLE
Ahlsell.* - Sites won't load (Fanboy's Annoyance List + Fanboy's Cookiemonster List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#297]
**Affected sites**:
```
https://www.ahlsell.dk/
https://www.ahlsell.fi/
https://www.ahlsell.no/
https://www.ahlsell.se/
```

**Issue**:
The sites won't load

**Problem filters**:
* Fanboy's Annoyance List
* Fanboy's Cookiemonster List

**Problem rule**:
`##.accept-cookies`

**Possible fix**:
`ahlsell.*#@#.accept-cookies`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.1 (x64)
- Adblock Extension/version: uBlock Origin v1.15.18

**Comment by SMed79** [comment]
add `ahlsell.dk,ahlsell.fi,ahlsell.no,ahlsell.se#@#.accept-cookies`

@ryanbr
