### ISSUE TITLE
Regional Swe - I see video ad - nyheter24.se

### ISSUE THREAD

**Issue by JonasNo** [ryanbr/fanboy-adblock#3]
Link video starts to play at full volume. Browser: Chrome
The video ad do not show in Firefox. Is it another Chrome limitation?
[http://nyheter24.se/nyheter/inrikes/835650-nu-kan-du-se-hur-mycket-pengar-du-far-tillbaka-pa-skatten](http://nyheter24.se/nyheter/inrikes/835650-nu-kan-du-se-hur-mycket-pengar-du-far-tillbaka-pa-skatten)

**Comment by ryanbr** [comment]
I don't know if I can test it, the site is very slow atm even through a VPN.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/f9f05726241c1b14ab82517c8fb08ffd556c6b5e

See if this commit helps.

**Comment by JonasNo** [comment]
Yes that site is very slow. Incompetent coders and technicians. Seems to be getting worryingly common.

Just tested it with the link above and it appears to work for the moment.
Have tried a few other pages using the same flash player and it works. Thank you.

While searching the site I encountered another kind of flash player that shows ads:
[http://nyheter24.se/geddit/796472-vad-du-an-gor-i-dag-bli-inte-som-den-har-valborgsfiraren](http://nyheter24.se/geddit/796472-vad-du-an-gor-i-dag-bli-inte-som-den-har-valborgsfiraren)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/ae26d6f5c299e69021adf4cd5c5d446ec9393753

Probably as much as I can do for that site.

**Comment by JonasNo** [comment]
Okay. Thank you for spending time helping me. I appreciate it.
The good thing is that this TV4 plash player is rarely used.

Your kung fu is stronger than mine. You should write a wiki page of how you do it. Teach me, master.
