### ISSUE TITLE
[May NSFW] gelbooru.com (New ads elements)

### ISSUE THREAD

**Issue by kowith337** [ryanbr/fanboy-adblock#30]
## Subscribed: Fanboy Ultimate List
Some ads frame still show, regardless of using uBlock Origin to block all third party.

> ![newgel1](https://cloud.githubusercontent.com/assets/16535467/17394449/5449cef8-5a53-11e6-9ae6-bb219f2f1787.png)
> Sorry, it need to censor it out.

and seems their try to avoid blocking by made some change like this.
> ![ccbill_typo](https://cloud.githubusercontent.com/assets/16535467/17394476/80981ef6-5a53-11e6-9966-8bda97e3795d.png)
> - Framed ads that make hyperlink to `ccbill.com` (locate above page navigation), but need to look at that typo, their use `.Com` instead of `.com`
> - Their mirrored ads by hosted "webm" file in their domain, but before named as "b.webm", I see it named as "mnfclub.webm" before they change, probably to avoid blocking.
> - More think to see, their include ads from `exoclick.com` as iframe, too. but look closer, their avoid blocking again by change `.com` as `.cOm`

### Elements may should block.
`gelbooru.com##center div[style="width:1000px; overflow:hidden;"]`
to hide an element that contains 2-3 iframes (probably) that located above page navigation.

`gelbooru.com##.sidebar iframe`
to hide tall ads that show at left side (that frame contains image that was encoded as base64, also hyperlink when clicked that ads also encoded, too.)

### Network request that may should block
`||gelbooru.com/*_loader`
to block `frontend_loader.js` and `backend_loader.php` that loaded to use with or improvement of showing ads from `exoclick.com`
a file `backend_loader.php` is seems reference to tall ads banner that located at left side after end of tag lists.

`||gelbooru.com$media`
Currently I don't know any possible that their may to change file type, but it need to prevent video ads that their mirrored from "mnfclub" and self-hosted.
Just hiding element isn't prevent site load video file, so I need to use this rule for blocking it, but...

`@@||gelbooru.com/images^$media`
is needed to whitelisted to make sure content that uploaded by their users are viewable and not blocked by mistake for user side. (due to new update for that site was able to upload and see webm videos)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a59e1eddc7177c233b372b75575065d05793b231

**Comment by ryanbr** [comment]
Has been resolved, no more ads seen.

**Comment by kowith337** [comment]
WebM Video ads re-appear.
I'm look for some part of code, old code of `center div` is `<div style="width:1000px; overflow:hidden;">`
but for now is `<div style="display:block; overflow:hidden; width:1000px;">`
also they change `href` typo again by using `http://refer.Ccbill.cOM/...`

> for self-solution, I've added `gelbooru.com##center div[style*="width=1000px"]` to my filer to remove entire additional footer area.

![screenshot 10](https://cloud.githubusercontent.com/assets/16535467/18392818/70fbc762-76dd-11e6-8417-7edcf955f71b.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/369a824d69687d8cd856b5e261dfc8803f4088ef

**Comment by kowith337** [comment]
Sent from my HTC

----- Reply message -----

**Comment by kowith337** [comment]
It's OK for now.
*Tested on Fennec F-droid 48.0 + uBO 1.9.4

----- Reply message -----

**Comment by kowith337** [comment]
Can I Re-suggestion here? it seems your list was allowed some script from ExoClick ads. (Now seems gone?)
For my purpose, allow only this
`@@||gelbooru.com/script/application.js?$script`
Yes, strictly `application.js?` because it seems every request that called core script to load is have some numbers behind question mark, guess it's a script version.

`||gelbooru.com^$script,subdocument`
to block `application.js.php`, it's a script file that named as php file that their make it to fool whitelist rules in adblockers extensions, also I guess they will reuse old trick to bypass and keep serve ads and popunder that their created `frontend_loader.js` and `backend_loader.php` in the past to serving ads by add script code to first party server to bypass blocking because most blocking rules are focus to block third party.
