### ISSUE TITLE
Breakage at http://www.trevisoairport.it/en/flights/plan-your-journey.html by Fanboy’s Cookiemonster List

### ISSUE THREAD

**Issue by crssi** [ryanbr/fanboy-adblock#300]
### List the website(s) you're having issues:
`http://www.trevisoairport.it/en/flights/plan-your-journey.html`

### What happens?

Drop down selections does not work

### List Subscriptions you're using:

Fanboy’s Cookiemonster List

### Your settings

- OS/version: Wondows 10
- Browser/version: Firefox 59.0.1 x64
- Adblock Extension/version: uBlock Origin v 1.15.18

### Other details:

Rule `/divascookies_` and/or `.divascookies-` causes this breakage.

Thank you in advance
Cheers

**Comment by krystian3w** [comment]
**`.divascookies-`** block javascript (required to work website forms):

<ul>

```
@@||www.trevisoairport.it/assets/frontend-venice/ui/js/jquery.divascookies-0.3.min.js$script
```

</ul>

CSS blocked by **`/divascookies_`** may no required in me opinion - test when is unlocked:

<ul>

```
@@||www.trevisoairport.it/assets/frontend-venice/ui/css/divascookies_style_dark_top.css$stylesheet
```

</ul>

**Comment by ryanbr** [comment]
If I get more reports of .divacookies- I'll consider removing it.

https://github.com/ryanbr/fanboy-adblock/commit/9dc6e192c286d054f16c1d75c91796988540a5bf
