### ISSUE TITLE
Files that lack the "Reporting Issues" link

### ISSUE THREAD

**Issue by davidhedlund** [ryanbr/fanboy-adblock#302]
This text 
> ! Reporting Issues: https://github.com/ryanbr/fanboy-adblock/issues

Are found in these files:
* https://github.com/ryanbr/fanboy-adblock/blob/master/headers/header-problematic-sites.txt
* All *.txt files in the root directory of https://github.com/ryanbr/fanboy-adblock

Can you please also add
> ! Reporting Issues: https://github.com/ryanbr/fanboy-adblock/issues

to these files:
* https://github.com/ryanbr/fanboy-adblock/blob/master/fanboy-adblock/fanboy-header.txt
* https://github.com/ryanbr/fanboy-adblock/blob/master/fanboy-addon/fanboy-header.txt
* https://github.com/ryanbr/fanboy-adblock/blob/master/fanboy-tracking/fanboy-header.txt
* All files in https://github.com/ryanbr/fanboy-adblock/tree/master/firefox-regional
* All files in https://github.com/ryanbr/fanboy-adblock/tree/master/ie
* https://github.com/ryanbr/fanboy-adblock/blob/master/opera/opera-header.txt
* All files in https://github.com/ryanbr/fanboy-adblock/tree/master/other

**Comment by ryanbr** [comment]
Those are internal files used, or even formally used.  Most arent used now.
