### ISSUE TITLE
fanboy-adblocklist-swe.txt replaced with Frellwits-Swedish-Filter.txt in uBlock Origin

### ISSUE THREAD

**Issue by davidhedlund** [ryanbr/fanboy-adblock#303]
https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-swe.txt been replaced with https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt as the Swedish regional filter in uBlock Origin.

fanboy-adblocklist-swe.txt has been merged to Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt, see https://github.com/lassekongo83/Frellwits-filter-lists/issues/10

fanboy-adblocklist-swe.txt is obsolete. Thank you for all your historical contribution, it will be useful to the new maintainer.

# Suggestion 1

https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-cz.txt has this line:
> ! Redirect: https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt 

Should this line be added to https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-swe.txt to make it consistent (I have no idea, this is just a pure guess)?:
> ! Redirect: https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt

# Suggestion 2

If Suggestion 1 is irrelevant, should this lines:

> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !!!!!!!!!!!!!!!! Officially unsupported !!!!!!!!!!!!!!
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

be replaced with something like this?:

> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !!!!!!!!!!!!!!!! Merged to https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt !!!!!!!!!!!!!!
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by davidhedlund** [comment]
https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-cz.txt has this line:
> ! Redirect: https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt 

Should this line be added to https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-swe.txt to make it consistent?:
> ! Redirect: https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt

**Comment by davidhedlund** [comment]
I suggested the new author to give you some credit here: https://github.com/lassekongo83/Frellwits-filter-lists/issues/10#issuecomment-374926740

**Comment by ryanbr** [comment]
The regional lists haven't been on the main site for quite sometime, not sure if its needs to be suggested. And not touched for a year, I happy to leave given the unlikeliness of someone actually using it.

**Comment by davidhedlund** [comment]
https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-cz.txt has this line:

> ! Redirect: https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt


When is ! Redirect: used?
