### ISSUE TITLE
Fanboy’s Enhanced Tracking List breaks RES never-ending-reddit feature

### ISSUE THREAD

**Issue by BovixTrix** [ryanbr/fanboy-adblock#305]
### List the website(s) you're having issues:
reddit.com using reddit enhancement suite.

### What happens?
Fanboy’s Enhanced Tracking List breaks RES's never-ending-reddit feature
Get an error that states: Could not load the next page: Failed to fetch

### List Subscriptions you're using:
uBlock filters
uBlock filters – Annoyances​​​
uBlock filters – Badware risks
uBlock filters – Experimental
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List
Adguard Base Filters
Adguard Mobile Filters
EasyList​​​​​

Adguard Spyware Filters
EasyPrivacy

Malvertising filter list by Disconnect
Malware Domain List
Malware domains
Malware filter list by Disconnect​​​​​
Spam404​​​​​

Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social
Fanboy’s Cookiemonster List​​​​​
Fanboy’s Social Blocking List

Dan Pollock’s hosts file​​​​​
hpHosts’ Ad and tracking servers
MVPS HOSTS
Peter Lowe’s Ad and tracking server list​​​​​

Normally would also use Fanboy’s Enhanced Tracking List, but have it disabled because of this issue.

### Your settings

- OS/version: Win 7 Pro 64-bit
- Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin v1.15.18

### Other details:

With 
![with](https://user-images.githubusercontent.com/15334935/37873501-593a95e6-2fdb-11e8-9b26-f19748342b07.PNG)

Without
![without](https://user-images.githubusercontent.com/15334935/37873505-613da0bc-2fdb-11e8-8007-7d34c6df29d0.PNG)

**Comment by narcolepticinsomniac** [comment]
`@@||reddit.com/*app=res$xmlhttprequest,domain=reddit.com`

**Comment by ryanbr** [comment]
Sure, fixed.
