### ISSUE TITLE
Filter list breaking Reddit.com as well as Reddit browser extensions.

### ISSUE THREAD

**Issue by BenMcGarry** [ryanbr/fanboy-adblock#306]
### List the website(s) you're having issues:

https://alpha.reddit.com/
https://reddit.com/

### What happens?

With the latest filter updates which include https://github.com/ryanbr/fanboy-adblock/commit/60a4a73cf177b26ab54f746e992d40d3ba867c5e, the [Reddit redesign ](https://redditblog.com/2017/11/08/an-update-on-reddits-redesign/) as well as existing features on reddit.com no longer correctly function due to XHRs being blocked. Disabling the filter or adding an exception for reddit.com resolves the issue.

Browser extensions that utilise reddit such as [Moderator toolbox for Reddit](https://www.reddit.com/r/toolbox/) are also having requests blocked. I can see an exception was added for Reddit Enhancement Suite https://github.com/ryanbr/fanboy-adblock/commit/b8415b591760fa15671cdcb6bacd866e36f39e0b.

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

EasyList

EasyPrivacy​​​​​
Fanboy’s Enhanced Tracking List​​​​​

Malware Domain List​​​​​
Malware domains

Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version: Windows 10 16299.309
- Browser/version: Google Chrome 65.0.3325.181 (64-bit)
- Adblock Extension/version: uBlock Origin v1.15.18

### Other details:

![](https://i.imgur.com/dvTQJC8.png)

![](https://i.imgur.com/m0inFp6.png)

**Comment by creesch** [comment]
As a contributor to one of the extensions affected, any url on reddit is also an api endpoint as you can add ` .json` to every url and get the json formatted equivalent. We make heavy use of that in the moderator toolbox of that functionality meaning that this heavily impacts us.

**Comment by milosvvv** [comment]
I am unable to save a wiki page on reddit due to this filter : 



Static filter ||reddit.com^$xmlhttprequest,domain=reddit.com found in:

    Fanboy’s Enhanced Tracking List

**Comment by creesch** [comment]
@ryanbr Uhm I have been following your commits and at this point you have added so many exceptions that you might as well remove the entire xhr block or start filtering something specific instead of this blanket thing. 

Can I ask you what you are attempting to do? Also possibly respond in here, that would be appreciated.

**Comment by ryanbr** [comment]
Update your subscriptions then report back first

**Comment by KrakenZ** [comment]
This is still the case.

**Comment by LewisTehMinerz** [comment]
If anyone needs to get around this, add this to your filters (under My Filters):
```
@@reddit.com^$xmlhttprequest,domain=reddit.com
```
It will override the filter that blocks Reddit requests while still letting you use the list.

**Comment by ryanbr** [comment]
Was fixed a while ago, with an additional `reddit.com/?`  But have have removed the filters in question.
