### ISSUE TITLE
Unblock and exclude error monitoring services

### ISSUE THREAD

**Issue by toddhgardner** [ryanbr/fanboy-adblock#308]
### List the website(s) you're having issues:

`trackjs.com`
`cdn.trackjs.com`
`capture.trackjs.com`
`usage.trackjs.com`

### What happens?

`||capture.trackjs.com^` is specifically blocked, preventing errors from being recorded from our customer sites. Example site: `https://www.3m.com/`.

`||trackjs.com^*/tracker.js$third-party` is specifically blocked, preventing our customers that use our CDN from loading the agent.

TrackJS is an error monitoring service that records errors from user sessions and sends the data back to the developers of the web site. We do not aggregate data, sell data, or provide advertisements. We do not track users between customers either.

Similar tools in our market (Sentry, BugSnag, Raygun, New Relic) are not blocked.

Would it be possible to be added to the exclusion list for our domains?

### List Subscriptions you're using:

"Enhanced Trackers List"

### Your settings

- OS/version: MacOS 10.12.6
- Browser/version: Chrome 64.0.3282.186
- Adblock Extension/version: uBlock Origin 1.15.18

### Other details:

![Excerpt from uBlock Origin log](https://user-images.githubusercontent.com/672168/37990597-610fcae6-31cc-11e8-9913-3265a142a6fe.png)

Thank you!

**Comment by ryanbr** [comment]
Its removed in the Easylist section, but given we stop trackers no matter how much helpfulness in this specific list. I'll leave it.

**Comment by five23** [comment]
Consider that it is pathological to block error reporting tools.
