### ISSUE TITLE
crnotairesouest-dz.org

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#309]
**social links**:

```
##.soc-icon-circle
##.zozo-social-icons
##.zozo_social_link_widget
###zozo_social_link_widget-widget-3
```

**url e.g.**
https\://www.crnotairesouest-dz.org/wp-content/themes/themes/crnouest/profilenotaires.php?q=15

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/70c850a2b19b9e5fb9769eb60883c063e1d57be6
