### ISSUE TITLE
[Annoyance List] Google home page and search results page nag messages

### ISSUE THREAD

**Issue by phusseirr** [ryanbr/fanboy-adblock#31]
Alright, so the following messages keep coming back for users who delete cookies:
"Get to Google faster. Switch your default search engine to Google."
"Come here often? Make Google your homepage."

Annoyance list has blocked these in the past, but the method seems to be unreliable, and they haven't been blocked in months. It looks like these are the rules that are set on the list currently (these don't work):
```
! Google default search switch nag
###searchform > #gb > #gbw .gb_Mc[aria-label="promo"] > .gb_ea
! Google default homepage nag
###searchform > #gb > #gbw .gb_Vc[aria-label="promo"] > .gb_ga
```

The classes gb_Mc, gb_ea, gb_Vc, and gb_ga aren't currently set on the elements the above assumes. These classes seem to get changed all the time and cannot be relied upon.

I believe you should be able to simply remove the classes which appear in front of the aria-label attributes (replacing with a generic reference to a div) (sorry, I'm not clear about the syntax), and then remove the classes which appear at the end of the filter.

**Comment by ryanbr** [comment]
Does this help?

https://github.com/easylist/easylist/commit/293bd6f4fc1624bb88ca4ded92a37cc4bfc54818

**Comment by phusseirr** [comment]
That's doing the trick! :-)

**Comment by ks1322** [comment]
Now it is 100% reproducible for me in Firefox private mode, see https://superuser.com/q/1211130/105108. I have Fanboy's Annoyance List added to Adblock Plus. Can it be blocked again ?

**Comment by ryanbr** [comment]
Unless you've configured adblock plus not to work in private mode, it should be blocked.

**Comment by ks1322** [comment]
I have just tested it once again with "Allow some non-intrusive advertising" checkbox unchecked and it worked! Previously this checkbox was checked.

So popup is blocked only with "Allow some non-intrusive advertising" checkbox unchecked.
