### ISSUE TITLE
Remove block from Medium follow button

### ISSUE THREAD

**Issue by gueldner** [ryanbr/fanboy-adblock#310]
### List the website(s) you're having issues:
https://medium.com/

### What happens?

The "follow" button is being disabled by the blocker

### List Subscriptions you're using:

Fanboy's Social Blocking List

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

Medium.com does not have ads. There is strong feedback that this block is causing a bad experience of the core functionality for your list subscribers.

**Comment by ryanbr** [comment]
That follow button seems to part of the site? rather than a generic social (like twitter/facebook) its fine imo
