### ISSUE TITLE
Cookiemonster issue

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#311]
Cookie notice shows up, 

Website: https://www.deepl.com/translator

Screenshot: https://postimg.org/image/db7bw17bx/399304ea/

Browser: Firfox for Android Beta 60

Adblocker: uBlock Origin

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/7d01fe6c890628d2869ceac9faca5dc7b4108fe0
