### ISSUE TITLE
https://www.merriam-webster.com/dictionary/gauge

### ISSUE THREAD

**Issue by DrFritzA** [ryanbr/fanboy-adblock#312]
Hello,

I've got the annoyance filter added, but still get all kinds of in-page pop-ups, e.g., for newsletters.  For example, here:  `https://www.merriam-webster.com/dictionary/gauge.  `

Could you please let me know whether these *should* be blocked by the filter and, if so, what I should do?  As I read the description, the Annoyance Filter seeks to block these.  

Many thanks for this, and the hard work maintaining this important project.

Mac OS High Sierra 10.13.3.  Chrome 65.0.3325.181.

Thanks,
Fritz

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by SMed79** [comment]
Hi, 
add
```
merriam-webster.com###subscribe-overlay
merriam-webster.com##.subscribe-modal
```
- http://i.imgur.com/XMyDB9s.png

**Comment by SMed79** [comment]
No general solution, just report those pages at easylist forum http://forums.lanik.us/
... and sure, someone will help you.

**Comment by ryanbr** [comment]
Sorted.
