### ISSUE TITLE
Missing social / share buttons from Ultimate List

### ISSUE THREAD

**Issue by runboy93** [ryanbr/fanboy-adblock#314]
https://otaku-streamers.com/watch/6844/ep1-Slow_Start (need log in, but I share codes which cause those buttons appear)

`<a href="//www.furl.net/store?s=f&amp;to=0&amp;u=//otaku-streamers.com/info/6844/Slow_Start" target="_blank" title="Share this media on furl"><img src="//static.otaku-streamers.com/community/music/furl.gif" border="0"></a>`

`<a href="//reddit.com/submit?url=//otaku-streamers.com/info/6844/Slow_Start" target="_blank" title="Share this media on Reddit"><img src="//static.otaku-streamers.com/community/music/reddit.gif" border="0"></a>`

**Comment by SMed79** [comment]
* **Fanboy's Annoyances List** 
----includes----> **Fanboy's Social Blocking List**

* **Fanboy Ultimate List**
----includes----> **Easylist**, **Easyprivacy**, **Enhanced Trackers List** and **Annoyances List**

If you don't want to block/hide social media stuff remove this list and subscribe to the 
* Enhanced Trackers List (from https://fanboy.co.nz/filters.html)
* EasyList (from https://adblockplus.org/subscriptions#type_ads)
* EasyPrivacy (from https://adblockplus.org/subscriptions#type_privacy)

**Comment by SMed79** [comment]
... if i **misunderstand** you and you want to block/hide the social links/icons... add
```
/furl.gif
/reddit.gif
##a[title^="Share this media on"]
##a[href^="//www.facebook.com/share.php?"]
##a[href^="//del.icio.us/post?"]
##a[href^="//digg.com/submit?"]
##a[href^="//www.furl.net/store?"]
##a[href^="//www.stumbleupon.com/submit?"]
##a[href^="//reddit.com/submit?"]
```
https\://static.otaku-streamers.com/community/music/furl.gif
https\://static.otaku-streamers.com/community/music/reddit.gif
https://pastebin.com/raw/cnCXNvpK

**Comment by ryanbr** [comment]
I expect social elements to be blocked in the Ultimate list :)

**Comment by runboy93** [comment]
What I did mean, is those buttons should be blocked, but they aren't.

**Comment by SMed79** [comment]
Add the filters that i given to you.
