### ISSUE TITLE
fanfox.net facebook like button not blocked

### ISSUE THREAD

**Issue by runboy93** [ryanbr/fanboy-adblock#316]
`http://fanfox.net`

`<iframe src="//www.facebook.com/plugins/like.php?locale=en_US&amp;href=http%3A%2F%2Fwww.facebook.com%2Fmangafoxgo&amp;send=false&amp;layout=button_count&amp;width=100&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=141149349292130" scrolling="no" frameborder="0" style="float:left;border:none;overflow:hidden;width:100px;height:21px;margin-top:22px;margin-left:10px;margin-top:30px" allowTransparency="true"></iframe>`

Using Ultimate list, should be blocked like on most other websites.

**Comment by ryanbr** [comment]
Please wrap your url's in the code, to stop tracking.

**Comment by ryanbr** [comment]
Not seeing this. Atleast under Firefox Nightly/uBo.

**Comment by SMed79** [comment]
Already blocked

![abp](http://i.imgur.com/mBzHWom.png)
