### ISSUE TITLE
cnetfrance.fr

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#317]
social icons
```
/socialcore-$image
/social-core-$image
```
* http\://www.cnetfrance.fr/images/sprites/socialCore/social-core-sa9d6301746.png

* http\://www.cnetfrance.fr/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a2be8dc6c0a76d2806ec8d8f4c63497e094d071e
