### ISSUE TITLE
www.verisign.com

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#319]
### List the website(s) you're having issues:

`https://www.verisign.com/`
`https://www.verisign.com/en_US/security-services/public-dns/index.xhtml`

### What happens?

Blank website

### List Subscriptions you're using:

Default uBO / Adblock Plus + Fanboy's Cookiemonster List

No use two in same time.

### Your settings

- OS/version:   **Windows 7** Profesional x64 (PL)
- Browser/version:   **Opera 52** x64 (PL)
- Adblock Extension/version:  **uBO 1.15.2** / **Adblock Plus 1.13.5**

### Other details:

1. No possible reprocude in Firefox or Chrome (**maybe bug to report Opera developers**). 

2. Maybe required is Windows with Polish language +/- Polish regional settings (or other European).

3. Install Opera in Polish language (or other European).
    - you can use protable form https://www.opera.com/pl/computer/portable (I can reproduce in this version)
    - no works with PortableApps Opera <del>`https://portableapps.com/apps/internet/opera_portable`</del>

4. no change prefere languages / browser language in Opera settings (this is may exclude reproduce - bar from `5.` step will no show)

5. Open website, if show bar:

   > This website uses cookies to distinguish you from other users of our website. The use of cookies helps us to provide you with a specific service, to facilitate website use, to understand our visitors and to advertise to you. By continuing to browse the site you are giving consent to our use of cookies. Learn more in our Privacy Statement. 
    >
    > ![image](https://user-images.githubusercontent.com/35370833/38415930-50602dde-3993-11e8-956e-93e545eee373.png) |
    > --- |

   `##.cookie-warning` form Cookiemonster List hide `<body>` element (because website add `class` to `<body>` element)
   
6. If no work maybe remove Opera profile:
  
    * <code>Opera Software &gt; <b>Opera Stable</b></code>

    * <code>Opera &gt; profile &gt; <b>data</b></code>
    
    or refresh:
    * _**`opera://settings/resetOpera`**_
    
7. May not work with vpn / proxy (in my opinion this is not geo-lock), clear browser data is not effective.

---

```html
<body class="cookie-warning locale-suggester">
...
</body>
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ec626b6b0df3e69e74efc8ebe7e5842991ebf13f
