### ISSUE TITLE
[Social Blocking List] "share" button in google results

### ISSUE THREAD

**Issue by phusseirr** [ryanbr/fanboy-adblock#32]
Google results pages now sometimes include a "share" button in the knowledge graph. For example, on https://www.google.com/#q=Firefox -- to the right is info about Firefox from Wikipedia, and a share button next to the logo.

Here's how the element starts:
`<div class="_czk"><kno-share-button>`

**Comment by SMed79** [comment]
`##KNO-SHARE-BUTTON`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/097b07fa119f60580b60c57b94f3d2acb28ceb30
