### ISSUE TITLE
ricola.com

### ISSUE THREAD

**Issue by SkeletalDemise** [ryanbr/fanboy-adblock#324]
### List the website(s) you're having issues:
`http://www2.ricola.com/en-us`

### What happens?
A cookie notice displays.

### List Subscriptions you're using:
Default + Fanboy’s Cookiemonster List

### Your settings
- OS/version: Windows 10 1709 (64-bit)
- Browser/version: Chrome 65.0.3325.181 (64-bit)
- Adblock Extension/version: Nano Adblocker 1.0.0.40

### Other details:
Screenshot of cookie notice:
![ricola com cookie](https://user-images.githubusercontent.com/29117662/38408994-87644c16-3934-11e8-858c-bedbb526c8ca.png)

**Comment by krystian3w** [comment]
`ricola.com##.ricola-cookie-info`
