### ISSUE TITLE
Cookie Notice

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#327]
Cookie Notice on this site with Cookiemonster enabled. 

Website: https://uk.practicallaw.thomsonreuters.com/6-502-1481?transitionType=Default&contextData=(sc.Default)&firstPage=true&bhcp=1

Screenshot: https://imgbox.com/eXkaM5It

**Comment by krystian3w** [comment]
`###CookieConsentMessage`
