### ISSUE TITLE
minecraft.curseforge.com

### ISSUE THREAD

**Issue by RikoDEV** [ryanbr/fanboy-adblock#328]
![screenshot-2018-4-10 mods - projects - minecraft curseforge](https://user-images.githubusercontent.com/18230443/38564389-558bc74c-3cdf-11e8-84b1-54dec746b74d.png)

### List the website(s) you're having issues:

**https://minecraft.curseforge.com/**

### What happens?

Social icons in footer

### List Subscriptions you're using:

EasyList
EasyPrivacy
Fanboy’s Cookiemonster List​​​​​
​​Fanboy’s Social Blocking List​

### Your settings

- OS/version: Windows 10 Pro - 1709 (64 bit)
- Browser/version: Firefox 61.0a1 (64 bit)
- Adblock Extension/version: uBlock Origin v1.15.25b4

**Comment by SMed79** [comment]
Non-significant element... however, add:
```
minecraft.curseforge.com##.social
```

**Comment by ryanbr** [comment]
I guess if it bothers you...
