### ISSUE TITLE
Several popups on sperry.com

### ISSUE THREAD

**Issue by cletus** [ryanbr/fanboy-adblock#33]
I have the annoyances list and these are getting by. Thanks!

**Comment by SMed79** [comment]
Add: 
`sperry.com/on/demandware.store/Sites-sperry_us-Site/default/Promotion-Popup`
or 
`sperry.com##[class*="ui-widget-"]`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c5f2815279b4e90bf9fef5d4cf14e9520b691b99
