### ISSUE TITLE
cookie-bar.eu

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#330]
### List the website(s) you're having issues:

`https://cookie-bar.eu/`

### What happens?

the site is blocked by cookie monster list

### List Subscriptions you're using:

cookiemonster

### Your settings

- OS/version: kubuntu 17.10
- Browser/version: firefox 59
- Adblock Extension/version: ublock origin 

### Other details:

![image](https://user-images.githubusercontent.com/5832930/38598618-cb285688-3d65-11e8-843d-bdbac90f517f.png)

**Comment by ryanbr** [comment]
To be honest I expect this to be blocked, I haven't whitelisted cookie-bar sites, or even cookie sub-directorys of sites.

**Comment by SMed79** [comment]
@theel0ja Tthe strict-blocking is specific for uBo **ONLY** and it is not an insurmountable difficulty. 
Click the "**Permanently**" button and you will continue your surfing.

see
https\://github.com/uBlockOrigin/uAssets/issues/454
https\://github.com/uBlockOrigin/uAssets/issues/1535
