### ISSUE TITLE
Merge custom-prebake with cookiemonster list?

### ISSUE THREAD

**Issue by IsaakGroepT** [ryanbr/fanboy-adblock#331]
Since the form your provide doesn't have effect on the issue that I'm about to discuss, I'm skipping it.

I've been maintaining the Custom-Prebake cookie message filter list (see: https://gitlab.com/isaakm/Custom-Prebake) for a long time after the original maintainer stopped working on it and didn't reply to messages. But I have the idea that my efforts have mostly been for my own benefit since there has never been around my project from other people. Your list has more usage and there seems to be quite some differences between both, so I'm thinking of merging my list with you by creating pull requests.

How I would do these things:
- I would first remove all the duplicates from my list
- Remove the global identifiers that don't link to one specific website to avoid old and outdated ones being included in your list and to minimize the risk of corrupting websites
- Check if specific website identifiers are included in your list of global ones and remove them if it's the case 
- I'm going to see if it's possible to efficiently check whether the specific identifiers are still present on the websites
- For the ones that are still in use, I would PR them as one list

Just FYI, I've already created a script to remove the literal duplicates and these are the results:

Doubles:
https://paste.d0wn.biz/4651269115ad3b60.txt

Differences:
https://paste.d0wn.biz/56041805ad3b6268.txt

Are you interested in this?

**Comment by ryanbr** [comment]
Seems the Doubles and differences files are the same?

**Comment by ryanbr** [comment]
Regarding the differences,  If you have list of sites that aren't covered by Cookiemonster by any existing filters I use, I'll happy to include them. Just to avoid some dubes.

**Comment by ryanbr** [comment]
Looked at the first 700lines; from the domains listed; The rest seemed to blocked fine

```
airbnb.be##._puzpiop
duf.dk###cw
/cookie_header.js$script,domain=www.eventbrite.nl
forums.freebsd.org##.js-notices.notices--block.notices
fz.se##.blck-info
gosc.pl##div[style="box-shadow: rgba(255, 255, 255, 0.5) 0px 0px 10px 0px; background-color: rgb(158, 159, 161); padding: 20px 16px 16px; position: fixed; z-index: 99999; right: 20px; bottom: 20px; width: 300px; max-width: 90%;"]
ing.es##.cookies
```

**Comment by IsaakGroepT** [comment]
You're right, there was an issue in the script so I fixed that and updated the links. I will have a check which records are interesting to PR to your list and do that

**Comment by ryanbr** [comment]
Checked out the list through [redundancy checker](https://arestwo.org/famlam/redundantRuleChecker.html)

Just needs to be checked, https://pastebin.com/raw/iaSb8EPw

**Comment by ryanbr** [comment]
Went through these websites, most are either already covered, or they changed since.

I'll consider this ticket closed, if there is any missing filters, just create standard issue reports.
