### ISSUE TITLE
vr.fi cookie notification 

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#332]
### List the website(s) you're having issues:

`https://www.vr.fi/cs/vr/fi/etusivu`

### What happens?

That cookie notification:

![image](https://user-images.githubusercontent.com/5832930/38770059-a0ab313e-4015-11e8-8339-2853033e304c.png)

### List Subscriptions you're using:

cookiemonster list

### Your settings

- OS/version: kubuntu 17.10
- Browser/version: firefox 59
- Adblock Extension/version: ublock origin

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ca2a0de8d29376c69314dbb8c78558c1f5eac9ad

**Comment by theel0ja** [comment]
I think that `#.infoMessages` blocks some other elements too..

**Comment by theel0ja** [comment]
![image](https://user-images.githubusercontent.com/5832930/38778685-0fc37d78-40c6-11e8-9dfd-e05008590d55.png)

With latest version, that another blue message is blocked.

**Comment by ryanbr** [comment]
If you have alternative filter, do suggest.

**Comment by theel0ja** [comment]
```
vr.fi#@#.infoMessages

! 11/2/2018, 8:47:59 PM https://www.vr.fi/cs/vr/fi/etusivu
www.vr.fi##.headerContents > .infoMessages
```

This seems to block only the cookie notification.

**Comment by theel0ja** [comment]
<img width="1175" alt="screen shot 2018-11-02 at 20 50 22" src="https://user-images.githubusercontent.com/5832930/47934759-efae0580-dee0-11e8-9891-8d2e47f098d8.png">
