### ISSUE TITLE
Paperblog.com - Blocked images (Fanboy's Annoyance List / Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#333]
### List the website(s) you're having issues:
`paperblog.com`

### What happens?:
Full size image popups are blocked

### Example:
`https://en.paperblog.com/blade-runner-behind-the-scenes-459465/`

### How to reproduce:
Left-click on one of the images

### Screenshot:
![filterissue-paperblog](https://user-images.githubusercontent.com/9382674/38776934-dffef95a-408e-11e8-89d5-04c224708ccc.jpg)

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.social-inline`

### Possible fix:
`paperblog.com#@#.social-inline`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.3 (x64)
- Adblock Extension/version: uBlock Origin v1.15.24

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/539c71176e9f29051446b53aec4aff193d3e8a62

**Comment by THEtomaso** [comment]
I just noticed that there's a French version of the same site, which uses a different TLD:
`https://www.paperblog.FR/`
Therefore, the fix should be altered to this:
`paperblog.*#@#.social-inline`
