### ISSUE TITLE
deutsche-vogelstimmen.de

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#335]
```
www.deutsche-vogelstimmen.de###CookiePopup
```

https://github.com/liamja/Prebake/issues/545

Global filter no block in **Chrome 65 + uBlock**.

**Comment by ryanbr** [comment]
Already have it?

`fanboy-cookiemonster.txt:###CookiePopup`
`fanboy_annoyance_general_hide.txt:###CookiePopup`

**Comment by ryanbr** [comment]
To cover the Anti-adblock;

https://github.com/ryanbr/fanboy-adblock/commit/8513c8ec5764ad13bf261f4d645dbce4b1108f50
