### ISSUE TITLE
Prestigia.com - Broken sign up function (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#336]
### List the website(s) you're having issues:
`https://www.prestigia.com/`

### What happens?:
Sign up function is broken.

### How to reproduce:
1) Click on the Login button, at the top right side of the screen.
2) Click on "Sign up".

### Screenshot:
![filterissue-prestigia](https://user-images.githubusercontent.com/9382674/38781967-89235e20-40dc-11e8-92d8-af7cec5eade9.jpg)

### Problem filter:
Fanboy's Annoyance List

### Problem rule:
`###signupForm`

### Possible fix:
`prestigia.com#@##signupForm`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.3 (x64)
- Adblock Extension/version: uBlock Origin v1.15.24

**Comment by ryanbr** [comment]
Removed.
