### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#337]
![2018-02-23-ogloszenia - sprzedam kupie na olx pl](https://user-images.githubusercontent.com/5884000/36611319-55980564-18d3-11e8-94ee-b9d5b9152893.png)
`https://www.olx.pl/`

click not work

https://github.com/uBlockOrigin/uAssets/issues/1610

ubo default set + `Fanboy's Enhanced Tracking List`

**Comment by ryanbr** [comment]
What doesn't work? I click on the link, it works?

**Comment by KonoromiHimaries** [comment]
@ryanbr on my end not work

**Comment by ryanbr** [comment]
I've tested Easylist, Easyprivacy, Fanboy Annoyances and Enhanced Trackers list. Works fine here. Havent tested other filters. The site renders fine, links click fine. It'll be another filter I suspect and not related to me list.

**Comment by KonoromiHimaries** [comment]
@ryanbr add these rule `||static-olxeu.akamaized.net/static/olxpl/naspersclassifieds-regional/olxeu-atlas-web/static/js/advertising.js$important`
