### ISSUE TITLE
Cookie warning on doodle.com

### ISSUE THREAD

**Issue by pcworld** [ryanbr/fanboy-adblock#339]
### List the website(s) you're having issues:

`https://doodle.com/poll/msff7cpid276zf99`

### What happens?

![selection_711](https://user-images.githubusercontent.com/1506734/38935005-81fb22b6-431d-11e8-9c47-1921da1ad6d8.png)

### List Subscriptions you're using:

Fanboy’s Cookiemonster List​​​​​

### Your settings

- OS/version: Ubuntu 14.04
- Browser/version: Chromium 65.0.3325.181
- Adblock Extension/version: uBlock Origin 1.15.24

### Other details:

`doodle.com###d-cookiesWarningAdsLayout` should work.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/30d9e17457ae68674d35fddd9d13c2a50980a351
