### ISSUE TITLE
Fanboy's Social Blocking List - arstechnica.co.uk

### ISSUE THREAD

**Issue by JonasNo** [ryanbr/fanboy-adblock#34]
This needs to be updated:
`arstechnica.com,mozilla.org#@##social-footer
`
to:
`arstechnica.com,arstechnica.co.uk,mozilla.org#@##social-footer
`
To enable the "READ COMMENTS" link at the bottom of the article pages.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4a80b1fce72f1db4268b4f2bda43f1d8245ff74c
