### ISSUE TITLE
Enhanced Tracking List - zalando.co.uk

### ISSUE THREAD

**Issue by svk112** [ryanbr/fanboy-adblock#341]
The Enhanced Tracking List hides the buttons to get in contact with the zalando customer service on this site: https://www.zalando.co.uk/faq/Contact/77166764/Contact-and-Help-Information.htm
Below the headline "Get in touch" should be the buttons "Helpline", "EMail" etc. but with the enhanced tracking list activated I can't see those buttons. When I deactivate the list everything is fine again. Can you fix this?

**Comment by ryanbr** [comment]
Haven't tested on other zalando regional sites, but, see how this works

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/fa80160c5a8374b095c8fbcabe151a7cd611f6c9
