### ISSUE TITLE
factoriadeficcion.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#343]
**Website:**

https\://www.factoriadeficcion.com/

**What happens?**

social icons

**Filter:**

```
##div[class^="article__shared_bar"]
##div[class^="shareButton_"]
##div[class^="shareBar_"]
##div[class^="numberShares_"]
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/553277a7c8b969a61b5f248b89719687a4f74ff1
