### ISSUE TITLE
kayak.com

### ISSUE THREAD

**Issue by toddhgardner** [ryanbr/fanboy-adblock#345]
### List the website(s) you're having issues:

<code>kayak.com</code>

### What happens?

Site loads a tracking agent from `https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.3.9/rollbar.min.js`. This tracking agent can be loaded from other CDNs, so recommend blocking it by name `rollbar`.

If a JavaScript error is generated, a report with user tracking data is sent to `https://api.rollbar.com/api/1/item/`. Should be blocked in case the tracking script is bundled with other scripts.

You can recreate this by generating a false error `document.body.addEventListener('click', function() { window.x(); })` and clicking anywhere on the page.

### List Subscriptions you're using:

Enhanced Tracking List

### Your settings

- OS/version: OSX 10.12.6
- Browser/version: Chrome 66
- Adblock Extension/version: uBlock Origin 1.15.24

### Other details:

As recommended by #323

**Comment by toddhgardner** [comment]
[346]

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=117329#p117329

**Comment by ryanbr** [comment]
Won't add it to easyprivacy, atleast yet.
