### ISSUE TITLE
Annoyances list - .privacy-container selector

### ISSUE THREAD

**Issue by vhmth** [ryanbr/fanboy-adblock#347]
### List the website(s) you're having issues:

`https://www.useloom.com/privacy`

### What happens?

The content of our privacy page is wrapped in a div like this `<div class="privacy-container">`. This page is, somewhat ironically, meant to give users a peek into what personal information we collect about them and where it goes (and how to be forgotten per GDPR coming up).

### List Subscriptions you're using:

The following lists cause this (`.privacy-container` is explicitly listed here).

* Fanboy's Annoyance List
* Fanboy's Cookiemonster List

### Your settings=

- OS/version: `OSX 10.13.4`
- Browser/version: `Chrome 66.0.3359.117 (Official build) (64-bit)`
- Adblock Extension/version: `uBlock Origin 1.16.0`

### Other details:

I went through and deselected all other options/filters and these cause our container to be hidden:

* Fanboy's Annoyance List
* Fanboy's Cookiemonster List

**Comment by SMed79** [comment]
Just fyi, the purpose of this filter `##privacy-container` is to hide a cookies notice.
- e.g http://i.imgur.com/zPjlezf.png (kpmg.com)

**Comment by ryanbr** [comment]
Note, I do expect cookie/privacy sub dirs I expect to break. Will only fix main pages here. So if `https://www.useloom.com/` broke, then it'd be fixed.
