### ISSUE TITLE
Cookiemonster list blocks squarespace announcement bar

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#349]
### List the website(s) you're having issues:

* `https://www.blackboat.com/`

### What happens?

the announcement bar is blocked

### List Subscriptions you're using:

cookiemonster list

### Your settings

- OS/version: windows 10
- Browser/version: firefox 60
- Adblock Extension/version: ublock origin

### Other details:

it being disabled:
![image](https://user-images.githubusercontent.com/5832930/39265306-a077d948-48cf-11e8-96dc-e171e0cc81ae.png)

when enabled:
![image](https://user-images.githubusercontent.com/5832930/39265329-aec116c2-48cf-11e8-81ad-c1d14ceaba9c.png)

ublock origin logger:
![image](https://user-images.githubusercontent.com/5832930/39265386-ccfe6fea-48cf-11e8-907c-2f2cb62d77dc.png)

**Comment by ryanbr** [comment]
Should be fixed, just update.
