### ISSUE TITLE
craigslist.* - Broken reply function (Fanboy's Annoyance List + Fanboy's Cookiemonster List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#353]
### List the website(s) you're having issues:
`craigslist.*`

### What happens?:
Reply function is broken.

### Example:
`https://abbotsford.craigslist.ca/cto/d/2013-jeep-rubicon-2dr/6573975868.html`

### How to reproduce:
Click on the yellow Reply button, at the top.

### Screenshot:
![filterissue-craigslist](https://user-images.githubusercontent.com/9382674/39417520-4dd49ac8-4c44-11e8-894a-db43d21d87e8.jpg)

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookiemonster List

### Problem rule:
`##.grecaptcha-badge`

### Possible fix:
`craigslist.*#@#.grecaptcha-badge`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4 (XUL)

**Comment by THEtomaso** [comment]
Guess this report can be disregarded closed.
Reference:
`https://forum.palemoon.org/viewtopic.php?f=3&t=19010&p=140168#p140168`

**Comment by ryanbr** [comment]
All good.
