### ISSUE TITLE
webgate.ec.europa.eu cookie notification

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#354]
### List the website(s) you're having issues:

`https://webgate.ec.europa.eu/cas/login`

### What happens?

cookiebanner

### List Subscriptions you're using:

cookiemonster

### Your settings

- OS/version: windows 10
- Browser/version: firefox 60 beta
- Adblock Extension/version: ublock origin

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/862745ba7e5da8c2d7913bd199eef267e150d6fa
