### ISSUE TITLE
Yahoo Mail / guce.oath.com

### ISSUE THREAD

**Issue by anewuser** [ryanbr/fanboy-adblock#355]
### List the website(s) you're having issues:

`https://yahoo.com/`

### What happens?

After entering my email and password to access "Yahoo Mail", the login form takes me to `https://guce.oath.com/collectConsent?ccSessionId=xxxxxxxxxxxxxxxxx&lang=&inline=false&jsVersion=null&experiment=null`, which is blocked by the rule `||guce.oath.com^` in  `Fanboy’s Cookiemonster List`.

Oath has acquired Yahoo and that's a page about their new privacy policy.

### List Subscriptions you're using:

Fanboy’s Cookiemonster List

**Comment by ryanbr** [comment]
removed.
