### ISSUE TITLE
tabletowo.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#356]
### List the website(s) you're having issues:
`https://www.tabletowo.pl/page/2/`

### What happens?

Fanboy's Social Blocking List hides article image.

### List Subscriptions you're using:
Fanboy's Social Blocking List

### Your settings

- OS/version: Manjaro Linux Hakoila
- Browser/version: Waterfox 56.1.0
- Adblock Extension/version: Nano Adblocker 1.0.0.42

### Other details:

Fix => `@@||www.tabletowo.pl/wp-content/uploads/thumbs_dir/youtube-logo$image`
![screenshot_20180501_105056](https://user-images.githubusercontent.com/19818572/39467274-8c1426a2-4d2d-11e8-8146-168dffaea710.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3d440531e17ac56fc431e5588041aeca30edc6a7
