### ISSUE TITLE
openclassrooms.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#359]
### Website:

`https://openclassrooms.com/`

### What happens?

Social incons at the footer of the page.

### filters:

```
##.footer__socialButtons
##.footer__socialNetwork
##.footer__socialNetworkItem
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f7bdac06fca4dacf06090687af016913a07c77f4
