### ISSUE TITLE
Blocking social sign in?

### ISSUE THREAD

**Issue by benjamingr** [ryanbr/fanboy-adblock#36]
Hey, 

Is this list supposed to break social-sign-in (without tracking) or not?

Thanks,
Benjamin

**Comment by benjamingr** [comment]
www.tipranks.com - our social sign in is blocked, I don't mind making a modification on our end but I wanted to make sure I'm not blocking intended functionality.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3ddd56b2d3163dfc5848ec18a608a0e84c1cd246

Fixed, force an update in the next 30mins or so.

**Comment by benjamingr** [comment]
Awesome, thanks a lot!
