### ISSUE TITLE
gry-online.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#360]
### List the website(s) you're having issues:
`https://www.gry-online.pl/S013.asp?ID=109053`

### What happens?

Fanboy's Social Blocking List hides paws and comments icons.

### List Subscriptions you're using:
Fanboy's Social Blocking List

### Your settings

- OS/version: Manjaro Linux Hakoila
- Browser/version: Vivaldi 1.15.1147.36 (Stable channel) (64-bit)
- Adblock Extension/version: Nano Adblocker 1.0.0.46

### Other details:

Fix => `gry-online.pl#@#.social-16`
https://github.com/MajkiIT/polish-ads-filter/issues/7411
<img src="https://user-images.githubusercontent.com/36385327/39476688-28ece8d6-4d5d-11e8-873e-f01aaac1e564.png">

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/14c2d497521d51eb0106b02ee4af312969d327d1

**Comment by krystian3w** [comment]
<pre><code>gry-online.pl,<b>tvgry.pl</b>#@#.social-16</code></pre>

@ryanbr 

https://github.com/MajkiIT/polish-ads-filter/issues/7521
