### ISSUE TITLE
viz.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#361]
*Website:**

`https://www.viz.com/read/manga/product/kaguya-sama-love-is-war-volume-2/13195`

**What happens?**

Social incons.

**Ss:**

- http://i.imgur.com/ELb1HKt.png

**filters:**

```
##a[href="javascript:fbShare();"]
##a[href="javascript:tumblrShare();"]
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f4fc7a93101768447c2b2b0ae81aeacdd9a9021e
