### ISSUE TITLE
cleanlivinlife.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#364]
*Website:**

```
http://cleanlivinlife.com/
http://theshootonline.com/
```

**What happens?**

Social / pop-in

**filters:**

```
/facebook-popup-
/facebookpopup.
```

**Comment by ryanbr** [comment]
Should consider using github pull requests, might be easier/quicker? just saying.

https://github.com/easylist/easylist/commit/5b139dadc93c760301b534310dfd3f8114fe60a1

**Comment by smed79** [comment]
I open a issue if I have a doubt.
