### ISSUE TITLE
inquirer.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#365]
### List the website(s) you're having issues:

![2018-05-04-inquirer net _ philippine news for filipinos](https://user-images.githubusercontent.com/5884000/39621780-33d2ea4a-4f90-11e8-8baa-56f71a5c9025.png)

### What happens?

social buttons

### List Subscriptions you're using:

https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

### Your settings

- OS/version: w10 
- Browser/version: chr 66.0.3359.139
- Adblock Extension/version: ubo 1.16.2

**Comment by smed79** [comment]
add
```
inquirer.net###sm_follow_us
```
or
```
###sm_follow_us
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/418e6e10208d87f9cfca67c68987b39bd3b39135
