### ISSUE TITLE
Block images in namu.wiki

### ISSUE THREAD

**Issue by alexkoala** [ryanbr/fanboy-adblock#367]
### List the website(s) you're having issues:
All pages in `https://namu.wiki` except logo.
(Example: `namu.wiki/w/uBlock Origin`
### What happens?
Fanboy is blocking all images in namu.wiki.
The image is comming from [cdn.namuwikiusercontent.com](https://cdn.namuwikiusercontent.com)
### List Subscriptions you're using:
Fanboy’s Enhanced Tracking List
### Your settings
- OS/version: Windows 10/1803(17134.1)
- Browser/version: Chrome/66.0.3359.139
- Adblock Extension/version: uBlock Origin/1.16.2

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/92c0b4a2e5f09f6dd8f6a960b58ae6042f867960
