### ISSUE TITLE
iptvbuzz.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#369]
### List the website(s) you're having issues:

`http://www.iptvbuzz.com/`

### What happens?

social annoyance http://i.imgur.com/F4JXAAr.png

### filters
```
##.fbbox-wrapper
###fbOnscroll
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/00fcff8241d0697a7002300d11eb8bc077659796
