### ISSUE TITLE
Fanboy's Enhanced Tracking List: problem with bahn.de

### ISSUE THREAD

**Issue by martin54** [ryanbr/fanboy-adblock#37]
Filterlist:
- URL: https://www.fanboy.co.nz/enhancedstats.txt
- Title: Fanboy's Enhanced Tracking List

The rule "/s_code." from the above list is blocking scripts like:
- https://www.img-bahn.de/es/v1610/js/s_code.js
- https://www.img-bahn.de/es/v1608/js/s_code.js  (a few weeks ago)

which are needed by the following web page:
- https://ps.bahn.de/preissuche/preissuche/psc_angebotssuche.refresh?&countrylang=USA_en#no-back

If the script is blocked, then there are no drop down lists if you enter Departure or Destination (try Berlin or Bonn), and ticket search is not possible.

If I add the following exception rule to my own filters it's working again:
- @@||www.img-bahn.de/es/v*/js/s_code.js$script,domain=ps.bahn.de

Please modify your  filterlist, so that bahn.de is working w/o user-defined exceptions.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/c538db4425af904bc0d319d94226166a4d1d0294

**Comment by martin54** [comment]
Seems to work fine now, thanks :-)
