### ISSUE TITLE
pissedconsumer.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#370]
### Website:

`https://aliexpress.pissedconsumer.com/r-20150914699492.html`

### What happens?

Annoying fixed navigation bottom.

### Ss

http://i.imgur.com/wyi1fuF.png

### filters:

```
pissedconsumer.com##.nav-bottom
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/98a96977d6867477ba30c6076482fc4ac233b104
