### ISSUE TITLE
nalaweb.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#377]
**Website:**

`https://nalaweb.com/web/`

**What happens?**

social icons

**Ss**:
- http://i.imgur.com/ix0ojDe.png

**filters**:
```
/social-warfare/*
##.swp_social_panel
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0d181bfed93bcf6f057596d2c94293d171a57e2d
