### ISSUE TITLE
vpnmentor.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#379]
Social icons 
```
##div[id^="sl_share_"]
```
or
```
##div[id^="sl_share_fb"]
##div[id^="sl_share_tw"]
##div[id^="sl_share_gp"]
```
* http://i.imgur.com/KT4kjxD.png
* http://i.imgur.com/fYQ9xRJ.png

`https://fr.vpnmentor.com/blog/les-meilleures-series-de-netflix/` ([viewtopic.php?f=62&t=39602](https://forums.lanik.us/viewtopic.php?f=62&t=39602))

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f701b0ed1de3a431249269baba66d695a773236a
