### ISSUE TITLE
DiziLab - Ads appear when video stopped and the bottom of video

### ISSUE THREAD

**Issue by denizjcan** [ryanbr/fanboy-adblock#38]
I also checked in firefox as stated in the help page.
www.dizilab.com
for example:
![s](https://cloud.githubusercontent.com/assets/22716602/19215558/2ef949f0-8daa-11e6-8133-40b31073f6ba.png)

**Comment by ryanbr** [comment]
Might help? 
https://github.com/ryanbr/fanboy-adblock/commit/a3d28c8f318726270cd8fdd1d5d31c6042db300b

**Comment by denizjcan** [comment]
Thanks :)
