### ISSUE TITLE
Would you like to add the easy China filler?

### ISSUE THREAD

**Issue by CHN-STUDENT** [ryanbr/fanboy-adblock#380]
Hi,i am i Chinese adblock and icab user, as we know the adblock can block the ads base the fillerlist. And i hope you can add the easy China filler for our Chinese. Would you like to add the easy China filler? Thanks!!!

https://easylist-downloads.adblockplus.org/easylistchina.txt

**Comment by CHN-STUDENT** [comment]
@ryanbr Sorry, i think it do not know how to do it , so could you give me some help or advice? Thanks!!!

**Comment by smed79** [comment]
@CHN-STUDENT 
Install **Adblock Plus** https://adblockplus.org/
Go to the page **Known ABP subscriptions** https://adblockplus.org/subscriptions#type_ads
Subscribe to **EasyList China** (just click the link http://i.imgur.com/gIGrOJH.png)

**Comment by CHN-STUDENT** [comment]
@smed79 Thanks,but i mean i want to block the ads on my iphone. I downloaded the iCabmobile(http://www.icab-mobile.de/), this website show me they can use your list. 

And i want to know how to use the China list on it,also i asked this question by email. The author say i can download it and add it!

![tim 20180516072715](https://user-images.githubusercontent.com/21209416/40088678-9be3ee56-58da-11e8-8ed3-a17dac583ab0.png)

![img_7966](https://user-images.githubusercontent.com/21209416/40088727-d31159cc-58da-11e8-950e-ddfe1af53554.PNG)


It is good news!! And glad to get your help @ryanbr @smed79 !

Thanks!!!

**Comment by CHN-STUDENT** [comment]
Ok,Thanks!
