### ISSUE TITLE
yesstyle.com/

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#382]
**website**

`https://www.yesstyle.com/`

**cookie notice**
```
##div[data-privacy-consent]
```
**Ss** 

http://i.imgur.com/4p5P4Ew.png

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/7403c3cafd9c4c8a4049e3e4e952ef97f5c89601
