### ISSUE TITLE
Expires directives in filter lists are invalid

### ISSUE THREAD

**Issue by gwarser** [ryanbr/fanboy-adblock#384]
Valid format can be seen here https://adblockplus.org/filters#special-comments
Example:
`! Expires: 5 days`

You have now:
`! This list expires after 6 days`
This will not be parsed by ABP or UBO.

Discussion https://github.com/gorhill/uBlock/pull/3723#issuecomment-389575146

**Comment by smed79** [comment]
https://github.com/ryanbr/fanboy-adblock/blob/master/headers/header-problematic-sites.txt#L5

https://www.fanboy.co.nz/fanboy-antifacebook.txt
https://www.fanboy.co.nz/fanboy-cookiemonster.txt
https://www.fanboy.co.nz/fanboy-problematic-sites.txt
https://www.fanboy.co.nz/enhancedstats.txt
https://www.fanboy.co.nz/fanboy-antifonts.txt

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/786e83772bf9e270cd67a16bfefd28c2ba8036c7
https://github.com/ryanbr/fanboy-adblock/commit/ce2645e7a4ec2f8797d1b6b1bf4e2341a0770177

**Comment by mikhaelkh** [comment]
@ryanbr, fake-news.txt and popads-domains-list.txt still have invalid expires header.

**Comment by ryanbr** [comment]
neither list is used/maintained.
