### ISSUE TITLE
plautz.at

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#387]
### List the website(s) you're having issues:
plautz.at

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
Fanboy’s Cookiemonster List

### Your settings

- OS/version:  Win 7 prof.
- Browser/version:  firefox 56.0.2 (64-Bit)
- Adblock Extension/version:  uBlock Origin 1.16.6

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/7403c3cafd9c4c8a4049e3e4e952ef97f5c89601
