### ISSUE TITLE
nytimes.com cookie

### ISSUE THREAD

**Issue by pcworld** [ryanbr/fanboy-adblock#388]
### List the website(s) you're having issues:

`https://www.nytimes.com/2015/06/24/us/james-horner-whose-soaring-film-scores-included-titanic-dies-at-61.html`

### What happens?

![selection_721](https://user-images.githubusercontent.com/1506734/40262243-321899f8-5b06-11e8-9544-d890f6a8bd68.png)

### List Subscriptions you're using:

cookiemonster

### Your settings

- OS/version: Ubuntu 14.04
- Browser/version: Chromium 65
- Adblock Extension/version: uBlock Origin 1.16.6

**Comment by ryanbr** [comment]
Wrap the url in a code to prevent tracking please.

https://github.com/ryanbr/fanboy-adblock/commit/f8669f7794feb352cb1a6d340722805795fad191

**Comment by isaacl** [comment]
This change whitelists nyt ads that would have been blocked with other lists :-\

**Comment by isaacl** [comment]
It didn't break the site.

I was inspecting requests and saw XHRs pass because `@@||nyt.com/ads/$script` is [whitelisted by the enhanced list](https://github.com/ryanbr/fanboy-adblock/commit/f8669f7794feb352cb1a6d340722805795fad191#diff-d88786646d8d046cb375ba7ae71d71eaR890).

**Comment by ryanbr** [comment]
Only whitelisted to stop tracking/Anti-adblock.
