### ISSUE TITLE
onlinelibrary.wiley.com

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#389]
### List the website(s) you're having issues:
onlinelibrary.wiley.com

### What happens?
cookie banner not blocked

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by bestoernesto** [comment]
Oh, that's was a mistake by my own, forget this issue

**Comment by smed79** [comment]
@bestoernesto 

> forget this issue

![cls](https://user-images.githubusercontent.com/1873139/40265214-f39b5b5e-5b2b-11e8-9325-5df4c66a86cf.png)
