### ISSUE TITLE
https://www.gatesnotes.com

### ISSUE THREAD

**Issue by radusw** [ryanbr/fanboy-adblock#390]
### List the website(s) you're having issues:
https://www.gatesnotes.com
### What happens?
Blank page
### List Subscriptions you're using:
uBlock Origin
### Your settings

- OS/version: MacOs
- Browser/version: FF 60
- Adblock Extension/version: 1.16.6

### Other details:
`https://www.gatesnotes.com/TGN/js/TGN_v50_s_code.js`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/1b3b372942cf40c74d74d00371ab07902d9e68b6
