### ISSUE TITLE
toffeeweb.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#391]
![2018-05-19-pop-up scams _ suspicious ads](https://user-images.githubusercontent.com/5884000/40271066-60a747b4-5b98-11e8-9070-c8bcb6dbbd11.png)
`https://toffeeweb.com/season/17-18/comment/general/36682.html`

cookie

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.6
 ND 14.33
 Chr 66.0.3359.181
</details>

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/5a5677aad7f090c68ab9e6176cacebfcadf2fe2a
