### ISSUE TITLE
rtp.pt/play/ cookie bar

### ISSUE THREAD

**Issue by celsoazevedo** [ryanbr/fanboy-adblock#392]
### List the website(s) you're having issues:
`https://www.rtp.pt/play/`

### What happens?
Cookie "bar" is displayed. Can be hidden with the following rule:

`www.rtp.pt###rtpgeralcookiecontent`

### List Subscriptions you're using:
Fanboy’s Cookiemonster List

### Other details:

<img width="1440" alt="screen shot 2018-05-20 at 21 38 38" src="https://user-images.githubusercontent.com/4492221/40283453-60cb63fe-5c76-11e8-81fb-be978176a2d6.png">

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/45a829908aa87da33d625239664328aedc4d5355
