### ISSUE TITLE
ted.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#393]
![2018-05-22-tom wujec_ got a wicked problem_ first tell me how you make toast _ ted talk](https://user-images.githubusercontent.com/5884000/40337322-4792c27a-5d6f-11e8-8408-4c8880b78d8e.png)
`https://www.ted.com/talks/tom_wujec_got_a_wicked_problem_first_tell_me_how_you_make_toast`

social

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.6
 ND 14.36
 Chr 66.0.3359.181
</details>

**Comment by ryanbr** [comment]
I cant see this, can you use the element picker, see what element its using?

**Comment by ryanbr** [comment]
Given the non-response, closing.
