### ISSUE TITLE
europarl.europa.eu

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#395]
![2018-05-22-schedule of video broadcasts _ multimedia centre _ european parliament](https://user-images.githubusercontent.com/5884000/40376722-527b6356-5def-11e8-961f-d866cad43d8d.png)
`http://www.europarl.europa.eu/ep-live/en/schedule/`

newsletter

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.6
 ND 14.36
 Chr 66.0.3359.181
</details>

**Comment by ryanbr** [comment]
probably won't be blocked, will cause issues elsewhere.
