### ISSUE TITLE
askubuntu.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#396]
**website**

`https://askubuntu.com/questions/591733/`

https://twitter.com/Nick_Craver/status/998634207634165761

**What happens?**

cookies notice

**Ss**

* http://i.imgur.com/OkyyMi9.png

**filter**

```
###js-gdpr-consent-banner
```

**Comment by pcworld** [comment]
Seems to affect all Stack Exchange sites.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/1486a31310c749aa1c7d3c2ac904751de1bff961
