### ISSUE TITLE
srf.ch/play/

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#397]
### What happens?
Cookie banner not blocked

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by smed79** [comment]
```
srf.ch##.personalizationMessageWrapper
```

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/1486a31310c749aa1c7d3c2ac904751de1bff961
