### ISSUE TITLE
e-biznes.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#399]
### List the website(s) you're having issues:
`https://e-biznes.pl/nazwa-pl-wycofuje-oferty-sklepy-internetowe/`

### What happens?

Locked blurred content, maybe message about that we need to like FB/TW should be visible.

### List Subscriptions you're using:
EasyList, Fanboy's Social Blocking, Polish Social and others `https://gist.github.com/hawkeye116477/c19a440599c62cf50dd8f200c2030627` :smile:

### Your settings

- OS/version: Manjaro Linux
- Browser/version: Waterfox 56.2.0
- Adblock Extension/version: uBlock Origin 1.16.6

### Other details:
It's Fanboy's Social Blocking issue.
Before
![screenshot_20180525_110701](https://user-images.githubusercontent.com/19818572/40536240-c954a2da-600b-11e8-81f5-50dd4f7162e0.png)

After
![screenshot_20180525_110126](https://user-images.githubusercontent.com/19818572/40535985-00685aa6-600b-11e8-99b2-15b55cb90e8c.png)

Fix:
```
@@||e-biznes.pl/3/wp-content/plugins/sociallocker-next-premium/*
@@||www.facebook.com/v2.0/plugins/like.php$subdocument,domain=e-biznes.pl
@@||platform.twitter.com/js/button.*.js$script,domain=e-biznes.pl
@@||platform.twitter.com/widgets/follow_button.*.en.html$subdocument,domain=e-biznes.pl
e-biznes.pl#@#.fb-like
e-biznes.pl#@#.twitter-follow-button
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/158e38df6e6cc045f452b330b9eab08d46ce1668
