### ISSUE TITLE
[annoyance list] realclearpolitics.com newsletter nag

### ISSUE THREAD

**Issue by oophicci** [ryanbr/fanboy-adblock#40]
if you go to e.g. http://www.realclearpolitics.com/epolls/2016/president/2016_elections_electoral_college_map.html and then scroll down a little ways, an overlay will nag you to join their newsletters lists (see screen capture below).

The elements which need to be hidden have the following id's:
facebox
facebox_overlay

![newsletter-nag](https://cloud.githubusercontent.com/assets/22837922/19387531/c25cd7f6-91e8-11e6-89d6-0e4388f3f101.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9677e4e82f12f57fc1b7cd05cac2f147d0d84ce5

**Comment by oophicci** [comment]
thanks!
