### ISSUE TITLE
sw.js

### ISSUE THREAD

**Issue by hannes-k** [ryanbr/fanboy-adblock#401]
### List the website(s) you're having issues:
`https://thesis.baqend.com/` or any other website that uses a service worker or script with the name `sw.js`

### What happens?

The website is unable to register the service worker, because the `sw.js` is blocked by Fanboy’s Enhanced Tracking List

### List Subscriptions you're using:

Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 10 Build 1803
- Browser/version: Chrome  66.0.3359.181
- Adblock Extension/version: uBlock Origin 1.16.6

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/1753043fe3eda428152a3044f1d8dd2c04b3e0d6

**Comment by anantoghosh** [comment]
@ryanbr this is blocking **all** the service workers with the name sw.js which is a common name for the service worker file, not just for baqend.com

**Comment by reef-actor** [comment]
The `/sw.js|$script` rule seems to be untargeted, as @anantoghosh mentioned it is a common name given to service workers (even used in [google's example](https://developers.google.com/web/fundamentals/primers/service-workers/#register_a_service_worker)).
I suggest removing `/sw.js|$script` and `@@||baqend.com/sw.js`.  Any known bad script using this name should be more precisely targeted in the rules as this will be catching mostly useful/harmless service workers that serve to improve the user experience.  This would be more maintainable than adding exclusions for reported false positives.
