### ISSUE TITLE
lightningmaps.org

### ISSUE THREAD

**Issue by RikoDEV** [ryanbr/fanboy-adblock#403]
### List the website(s) you're having issues:

https://www.lightningmaps.org/

### What happens?

Fanboy’s lists destroy the page css and js, the page without the lists works normally.

### List Subscriptions you're using:

Fanboy’s Cookiemonster List
Fanboy’s Annoyance List
EasyList
Easy Privacy

### Your settings

- OS/version: Windows 10
- Browser/version: Chromium 66.0.3359.170
- Adblock Extension/version: uBlock Origin v1.16.9b0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7eb72f17e7f349230752a0f8064a575963ae53c3
