### ISSUE TITLE
Cookie Monster issue

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#405]
Cookie notice showing with Cookie Monster list enabled. 

Adblocker: uBlock Origin

Browser: Firefox Beta 61 Android

**Comment by ryanbr** [comment]
wat? which site? details? please use the template, else I will just close this report.

**Comment by SeriousHoax** [comment]
Sorry sorry. Somehow I forgot to paste the link, 
This is the link,

https://www.dailystar.co.uk/sport/football/705543/Liverpool-Mohamed-Salah-injury-news-Real-Madrid-Champions-League-World-Cup-Egypt-Klopp/amp

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/5314540690b1b6f648b6f3780d0aaf6bda684605
