### ISSUE TITLE
bleepingcomputer.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#407]
![2018-05-27-firefox 63 to get improved tracking protection that blocks in-browser miners](https://user-images.githubusercontent.com/5884000/40590163-7a289f04-61fa-11e8-9e99-e61f3d5b4e77.png)
`https://www.bleepingcomputer.com/news/software/firefox-63-to-get-improved-tracking-protection-that-blocks-in-browser-miners/`

arrow up

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.6
 ND 14.39
 Chr 66.0.3359.181
</details>

**Comment by KonoromiHimaries** [comment]
`##.bc_goto_top > [href="#"]`

**Comment by krystian3w** [comment]
Yes, should block by `Fanboy’s Annoyance List`?

`bleepingcomputer.com##.bc_goto_top`

**Comment by smed79** [comment]
https://forums.lanik.us/viewtopic.php?p=92213#p92213
