### ISSUE TITLE
wavesplatform.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#409]
![2018-05-29-waves platform](https://user-images.githubusercontent.com/5884000/40674347-d5c0825c-6374-11e8-893b-6a2a16338865.png)

popup

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.6
 ND 14.39
 Chr 66.0.3359.181
</details>

**Comment by ryanbr** [comment]
Not seeing this.
