### ISSUE TITLE
pop-up Filter not working on this site

### ISSUE THREAD

**Issue by yvestch** [ryanbr/fanboy-adblock#412]
`https://www.productmanagerhq.com/2014/12/product-manager-interview-the-favorite-product-question/`

I used fanboy popup filter hoping to get rid of the annoying popup that appears a few seconds after accessing the website abote, prompting users to join a newsletter. But it doesn't block it. 

Can you please help?

**Comment by smed79** [comment]
> I used fanboy popup filter

You mean [Fanboy Annoyances List](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt&title=Fanboy%20Annoyances%20List) ?

**Comment by ryanbr** [comment]
If you add this filter,

`||sumo.b-cdn.net^$script,domain=productmanagerhq.com`

Does it help?

**Comment by ryanbr** [comment]
Given the non-response, closing ticket.
