### ISSUE TITLE
brigitte.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#413]
### List the website(s) you're having issues: 
brigitte.de

### What happens?
Cookie banner not blocked

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by smed79** [comment]
add
```
brigitte.de##.guj-cb
```
or
```
##.guj-cb
```

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/06ce528cb443b17e6f045d70af8a651a4ea1a9d2
