### ISSUE TITLE
sourceforge.net

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#414]
### List the website(s) you're having issues:

<ul>

`https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20P.E.%20Test/Mozilla%20Firefox%2C%20Portable%20Edition%2061.0%20Beta%203/FirefoxPortableTest_61.0_Beta_3_English.paf.exe/download`

</ul>

### What happens?

<ul>

Cookiemonster block download files - cookiewall?

</ul>

### List Subscriptions you're using:

<ul>

uBO default + Cookiemonster

</ul>

### Your settings

<ul>

- OS/version: Windows 10 Pro build 1803
- Browser/version:  FX 61.0b10
- Adblock Extension/version:  uBO 1.6.8

</ul>

### Other details:

<ul>

I can download when unlock pop-up privacy

<ul>

```
@@||quantcast.mgr.consensu.org^$script,domain=sourceforge.net
@@||vendorlist.consensu.org^$xmlhttprequest,domain=sourceforge.net
```

or simpler

```
@@||consensu.org^$third-party,domain=sourceforge.net
```

</ul>

 and click "`I DO NOT ACCEPT`".

</ul>

**Comment by ryanbr** [comment]
Adjusted filter; https://github.com/easylist/easylist/commit/420504bc2386b580478a79bdfe25328265675c5e   Let me know if causes any false positives.

**Comment by krystian3w** [comment]
From my side this does not work for `sourceforge.net`, download still waiting for GDPR decision and I do not see Pop-up to click:

<ul>

 `I do not accept` / `I accept`, 

`more options` :left_right_arrow:    `Enable all purposes` / `save and exit`.

</ul>

to start / unlock download.

Maybe file `config.js` changed name or something.

**Comment by ryanbr** [comment]
I re-looked at this, I don't see consensu.org being used by sourceforge anymore

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/42413604-1080fb42-8224-11e8-8f5b-a05d1616467c.png)

I still see website use script: Powered by **Quantcast** - GDPR Consent Solution. 

If cut pop-up / script I must use button "Problems Downloading?" > direct "link".
