### ISSUE TITLE
stern.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#415]
### List the website(s) you're having issues:
stern.de

### What happens?
Cookie banner not blocked

### Your settings

- OS/version: Win7 64bit
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.8

**Comment by ryanbr** [comment]
Update your subs? it was fixed yesterday

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/35822cc30ad27a20bbd3081750f89a96bc84c62f
