### ISSUE TITLE
sonyentertainmentnetwork.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#421]
### List the website(s) you're having issues:

`https://id.sonyentertainmentnetwork.com/signin/?`

### What happens?

cookies notice

### Ss

http://i.imgur.com/UdEc8C2.png

### List Subscriptions you're using:

Easylist, EasyPrivacy & Fanboy Annoyance.

### Your settings

- OS/version: Arch 64
- Browser/version: FF 60
- Adblock Extension/version: Adblock Plus 3.1

**Comment by ryanbr** [comment]
Couldnt see the element, would need a suggestion to be added.

**Comment by smed79** [comment]
```
sonyentertainmentnetwork.com###js-SIEWS1lib-header
```
or
```
##div[data-components="pdr-ws1lib-header"]
```

http://i.imgur.com/CaBpLF3.png

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7dba8eb32d4506a95a869123b8fb28f80ea49361
