### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT when importing Firebase in service worker

### ISSUE THREAD

**Issue by rejhgadellaa** [ryanbr/fanboy-adblock#423]
### List the website(s) you're having issues:

`mobile.twitter.com`
`feedlr2.rejh.nl`

### What happens?

I'm getting errors on a variety of sites if I have the Fanboy's Enhanced Tracking List enabled for uBlock Origin:

> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

This prevents the service worker from starting:

> Uncaught (in promise) DOMException: Failed to update a ServiceWorker: ServiceWorker cannot be started

In the case of `feedlr2.rejh.nl` I suspect the import of the Firebase script causes the error. I'm not sure but suspect the same problem for mobile.twitter.com.

An example of the CDN-hosted firebase script:
https://www.gstatic.com/firebasejs/4.8.1/firebase-app.js

If I disable the list in uBlock Origin the error disappears.

### List Subscriptions you're using:

uBlock Origin: Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome v67
- Adblock Extension/version: uBlock Origin

### Other details:

None

**Comment by ryanbr** [comment]
just force update
