### ISSUE TITLE
dustinhome.fi cookie notification

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#424]
### List the website(s) you're having issues:
* `https://www.dustinhome.fi/product/5011071530/xps-13-9370-4k-touch-ubuntu`
* `https://www.dustin.fi/product/5011071530/xps-13-9370-4k-touch-ubuntu`

### What happens?
cookie notification (class `cookiebanner__container`)

### List Subscriptions you're using:
cookiemonster

### Your settings

- OS/version: windows 10
- Browser/version: firefox beta
- Adblock Extension/version: ublock origin

**Comment by krystian3w** [comment]
Workaround uBlock Origin / AdGuard Adblocker:

```
dustinhome.fi,dustin.fi###site-selector
dustinhome.fi,dustin.fi##.modal-backdrop
dustinhome.fi,dustin.fi##.modal-open:style(overflow-y:auto !important)
```

I can not see script / stylesheet to block, to unlock scroll (without break website) for AdBlock / Adblock Plus users.

**Comment by ryanbr** [comment]
Tested with uBo, I don't see an issue? site seems to display fine

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/41183920-711a759a-6b7d-11e8-90dc-016bb1d146c0.png)

Maybe this Annoyace Pop-up is affected.

> ![Imgur](https://i.imgur.com/2NVTFog.png)
> Select the business or consumer
> <kbd>Company</kbd> <kbd>Costumer</kbd>

**Comment by theel0ja** [comment]
@krystian3w I wouldn't probably block that selector

**Comment by krystian3w** [comment]
`###site-selector` or `##.modal-backdrop`?  If no find other unlock scroll this rules is bad for AdBlock / Adblock Plus.

I did not check whether declaring whether we are a Company / Costumer changing something in the store.

**Comment by ryanbr** [comment]
Happy to leave the check for "Valitse yritys tai kuluttaja"
