### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by tortugaverde98** [ryanbr/fanboy-adblock#425]
Thank you for your work blocking ads. I would like to support your work with a donation. Please post your btc address on a readme. for fanboy-adblock.

**Comment by ryanbr** [comment]
Unfortunately I don't do btc, you're free to use Paypal :)

**Comment by smed79** [comment]
Paypal to `mp3geek@gmail.com`

**Comment by ryanbr** [comment]
Not ideal for some people (paypal), but every bit helps.
