### ISSUE TITLE
welcome.adguard.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#427]
![2018-06-05-dziekujemy za instalacje adguard](https://user-images.githubusercontent.com/5884000/40975577-b9c2b8e8-68cb-11e8-9a70-98861d20645b.png)
`https://welcome.adguard.com/v2/thankyou.html?`

social icons

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.8
 ND 14.44
 Chr 67.0.3396.62
</details>

**Comment by smed79** [comment]
```
adguard.com##.icon--google
```
```
##.community__social
##.community__social-ico
##.community__social-ico--facebook
##.community__social-ico--twitter
##.community__social-ico--instagram
##.community__social-ico--google
##.community__social-item
##.community__social-desc
##.icon--facebook-simple
```
