### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#428]
### List the website(s) you're having issues:
`https://naekranie.pl/aktualnosci/red-dead-redemption-2-z-edycjami-specjalnym-zobacz-ich-wyglad-poznaj-zawartosc-3231539`

### What happens?

Fanboy Social hides  „Skomentuj" buton („Comment").

### List Subscriptions you're using:
Fanboy Social

### Your settings

- OS/version: Manjaro Linux
- Browser/version: Waterfox 56.2.0
- Adblock Extension/version: 1.16.8

### Other details:
https://github.com/MajkiIT/polish-ads-filter/issues/7894
Fix => `naekranie.pl#@#.share-buttons`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/13f03a778be623ecb2edb497822eaf2605da7baf

**Comment by krystian3w** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/1077
