### ISSUE TITLE
www.fastmailusercontent.com Remote Image Load Blocked

### ISSUE THREAD

**Issue by grahamjpark** [ryanbr/fanboy-adblock#429]
### List the website(s) you're having issues:
Swapped out some number just to be safe:
`https://www.fastmailusercontent.com/proxy/f8853249f8a9ebf00754a235c55a960344c9734ef6ed93f06105573088adb355/8647470737a3f2f25763836363330303e23647e23756e64676279646e2e65647f27766f2f60756e6f35707e6d334e486f483852763552476e45635d2232443134787237744656394c4f436945687a685d22364c60746d4b403c4d4078424a607b637f405a6266553e66653c4370797935666e4967627a74563447656a7a427964666268383c44395a5f45385334557a6564467c6a424943377b61436d6b4c4e6a64636c6871595961743a5a56713070575c4d22324470715653765958764d2236486755594458795d6a46334f6e6c403674653642403c6367545750774d223648526057783c613574376b6c476d68243d223646345436374e4c613b6a7a686d455647703e46403772324578385a644a4871435326685d223645603d607a4545394461653756747543565873473a673f614244713265535348687b436b437e686c4a5a492b61627d22324d2236454b4a67685d2232436b4745487370724841763f64794970703679663a444d22364f5d6a465d223236383f6860515b447d685a526865407e66557470375a5f45645e176935766278666633627d12324137617965403d223642735361433d427333384739544e666d43705264717175467b43365d696d2232446238434d4a713d22364d223649556358566b40546433527855685c437078537a6d223643334c66566d22324c4365747059546a5d22364435325a7d614774633577403750385b6f41397b6b66513e6e61514476415c4f4171444465543d614a79543a6953614d23344d23344/open`
and
`https://www.fastmailusercontent.com/proxy/3f9c743516001487781dc049b858972ca4b28c4bd8b649727082140af1400860/8647470626a3f2f2d61627b6564796e676d296d6167656d20727f64657364796f6e6e23733e216d616a7f5e6167737e236f6d6f25707c6f6164637f25623366363333353838383669366735346630333335333035633165663835366235313632646262316663343462626249363931256630313139313465656734323536363543626732615435393835123433646634656463693423283262346137366733393263603160336261323438303431303361366460316738313566373e2a60776/e2c66335888f9f75d6033530e3ae685f2516bdb3af34dbbb9692e601191dee7425668cb7ba5598ef6cd6dedc9438b2d17f639bc0a0cb12480410c1fd0a781e67.jpg`

### What happens?
When trying to load an a remote image while using fastmail, the image is blocked and does not load. When I opened uBlock Origin's logger it said the request was being blocked based on the following rule from "Fanboy’s Enhanced Tracking List" :
`/\.com\/.*[a-f0-9]{110}/$third-party,image,domain=~bilibili.com|~namu.wiki`

### List Subscriptions you're using:
Fanboy’s Enhanced Tracking List

- OS/version: Windows 10 version 1803
- Browser/version: Chrome Version 66.0.3359.181
- Adblock Extension/version: uBlock Origin v1.16.8

### Other details:
Happens after i click the "Load Image" in the "Remote images blocked to protect your privacy. Load images." notification in fastmail.

**Comment by ryanbr** [comment]
See if this helps; https://github.com/ryanbr/fanboy-adblock/commit/7dcc4065d53708acd5662264059145c4cf816005
