### ISSUE TITLE
Sometimes images are not shown in Google image search

### ISSUE THREAD

**Issue by wooque** [ryanbr/fanboy-adblock#43]
![screenshot_2016-10-21_18-45-58](https://cloud.githubusercontent.com/assets/1936195/19605936/bf88b9d8-97be-11e6-8266-634b9a322d91.png)
uBlock Origin logs says it's because Fanboy’s Annoyance List and/or Fanboy’s Social Blocking List rule:
![screenshot_2016-10-21_18-48-25](https://cloud.githubusercontent.com/assets/1936195/19605973/02167e8e-97bf-11e6-955d-7c389810b6d2.png)

**Comment by ryanbr** [comment]
Link/URL to the issues would be helpful, just so I can reproduce it

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/ce1a57747173f30a1a8ed6ffccaebb3ab2ab5de1

**Comment by wooque** [comment]
Whitelist that you added helped but it's not fixed entirely. 
It just happen randomly during image search, I noticed it's more often if image search is probably to include "pinterestic" images. 
Some more blocked urls:
```
||pinimg.com^$third-party,domain=~pinterest.com	--	image	http://media-cache-ak0.pinimg.com/736x/04/31/05/043105860ae4b412ae0ba6913184abb5.jpg
||pinterest.com^$third-party,image	--	image	http://media-cache3.pinterest.com/upload/47358233551432682_HTfPAPHE_c.jpg
/uploads/*pinterest.jpg	--	image	http://www.closetfulofclothes.com/wp-content/uploads/2014/12/sienna-miller-grey-jeans-blazer-beanie-red-ankle-boots-via-pinterest.jpg
```

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/0836bf44ea86ecba23f45ff9ce741f99e18eecba

**Comment by wooque** [comment]
Thank you for your swift response. This helped a lot.
Unfortunately I think it's just a tip of the iceberg because there is a lot of rules that can be problematic and block images on Google image search.

**Comment by ryanbr** [comment]
Should be fine currently, its generic enough to pick most of the false positives.
