### ISSUE TITLE
Dailymotion cookie notification

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#431]
### List the website(s) you're having issues:
`https://www.dailymotion.com/us`

### What happens?

cookie notification isn't blocked

### List Subscriptions you're using:

cookiemonster

### Your settings

- OS/version: windows 10
- Browser/version: firefox beta
- Adblock Extension/version: ublock origin

**Comment by krystian3w** [comment]
Blocked in EasyPrivacy:

`-dspcookiematching.`

**Comment by krystian3w** [comment]
My misteake - https://www.fanboy.co.nz/fanboy-cookiemonster.txt have:

`dailymotion.com##div[class^="CookieGdpr_"]`

**Comment by ryanbr** [comment]
all good, closed
