### ISSUE TITLE
qvc.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#433]
### List the website(s) you're having issues: 
qvc.de

### What happens?
Cookie banner not blocked

### Your settings

- OS/version: Win 7 (64bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.8

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/89331aa3ed255bf8df45e169a8e25e552e2a97de
