### ISSUE TITLE
belitsoft.com cookie notification

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#435]
### List the website(s) you're having issues:
`https://belitsoft.com/`

### What happens?
cookie notification isn't blocked

### List Subscriptions you're using:
cookiemonster

### Your settings

- OS/version: windows 10 
- Browser/version: ff 60
- Adblock Extension/version: ubo

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f5099b11b650597ec1372f881ac00aea5800ae25
