### ISSUE TITLE
racketboy.com

### ISSUE THREAD

**Issue by anewuser** [ryanbr/fanboy-adblock#437]
### List the website(s) you're having issues:

`http://www.racketboy.com/retro/games-that-defined-sega-32x`

### What happens?

Large newsletter subscription bar at the bottom of the page.

### List Subscriptions you're using:

Fanboy’s Annoyance List

**Comment by ryanbr** [comment]
Didn't merge pull request, because it was isnt the right subsection.

https://github.com/easylist/easylist/commit/09370a69c8384562beab2f070ce32d0c14b976b3
