### ISSUE TITLE
livecoinwatch.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#438]
![2018-06-11-live coin watch_ cryptocurrency prices market cap list](https://user-images.githubusercontent.com/5884000/41218220-a3e4a390-6d5a-11e8-8c54-0fc70eea6bda.png)

newsletter

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.8
 ND 14.51
 Chr 67.0.3396.79
</details>

**Comment by ryanbr** [comment]
site doesn't load.

**Comment by smed79** [comment]
@ryanbr load here http://i.imgur.com/yKwcIfI.png

@KonoromiHimaries test 
```
livecoinwatch.com##div.ui.message.top.attached
```
