### ISSUE TITLE
 Custom Redirector

### ISSUE THREAD

**Issue by redirectads** [ryanbr/fanboy-adblock#44]
### URL(s) where the issue occurs

`http://vaughnlive.tv/newzviewz`
### Describe the issue

this is what appears in the video and it can be blocked http://vaughnlive.tv/abvs.php but it removes the play/ pause and volume so please resolve this thanks but after 5 seconds you can click on the [X] and close it manually here is the website http://vaughnlive.tv/newzviewz.

Works perfectly with Google Chrome Extension but the media controls does not show up
Using Google Chrome i can use this Switcheroo RedirectorPlus
https://github.com/jkischel/SwitcherooPlus
Here is the original Switcheroo Redirector 
https://github.com/ranjez/Switcheroo

So my wish is can you Fanboy-adblock implement this so we can a custom redirect if can't block ads we can just redirect it.
The only way is to redirect it like this from http://vaughnlive.tv/abvs.php to http://google.com
### Screenshot(s)

Switcheroo Redirector Plus
<a href='https://postimg.org/image/589c0n97n/' target='_blank'><img src='https://s21.postimg.org/589c0n97n/redirect1.png' border='0' alt="redirect1"/></a><br/><br/> Switcheroo Redirector Plus
<a href='https://postimg.org/image/p45bg6q8z/' target='_blank'><img src='https://s21.postimg.org/p45bg6q8z/redirect2.png' border='0' alt="redirect2"/></a><br Switcheroo RedirectorPlus/><br/> Switcheroo Redirector Plus
<a href='https://postimg.org/image/fxn0swl0j/' target='_blank'><img src='https://s21.postimg.org/fxn0swl0j/redirect3.png' border='0' alt="redirect3"/></a><br/><br/> Shows With Ads and http://vaughnlive.tv/abvs.php are not blocked
<a href='https://postimg.org/image/anmnfcq5f/' target='_blank'><img src='https://s21.postimg.org/anmnfcq5f/withads1.png' border='0' alt="withads1"/></a><br/><br/> Shows Without Ads the Video Controls are gone and http://vaughnlive.tv/abvs.php are blocked
<a href='https://postimg.org/image/s26vnmnab/' target='_blank'><img src='https://s21.postimg.org/s26vnmnab/withoutads2.png' border='0' alt="withoutads2"/></a><br/><br/> 
### Versions
- Browser/version: Firefox 49.0.2
- uBlock Origin version: 1.9.12
### Settings

None.
### Notes

None.

**Comment by ryanbr** [comment]
Not sure if this list can get around it

**Comment by redirectads** [comment]
Ok Thank you if you added this to the filter list at least give it a try with Easylist. Because all that should happen is for uBO to read the filter list to that rule should be apply to site and redirect video ad away.  
Kinda hard since Google Chrome it's the browser with that option but i prefer Firefox over Google any day.

**Comment by ryanbr** [comment]
Keep in mind Easylist is a Adblock Plus subscription, I have the greatest respect with uBo and other adblocking tools re-using our work, but to keep compatibility with ABP is priority.
