### ISSUE TITLE
certum.eu cookie notification

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#445]
### List the website(s) you're having issues:

`https://www.certum.eu/en/`

### What happens?
cookieconsent isn't blocked

### List Subscriptions you're using:
cookie monster

### Your settings

- OS/version: windows 10
- Browser/version: firefox
- Adblock Extension/version: ublock origin

### Other details:

![image](https://user-images.githubusercontent.com/5832930/41509443-f499efae-7253-11e8-8f7b-d5e18d4035dc.png)

**Comment by smed79** [comment]
```
##div[data-nconvert-cookie]
```
```
certum.eu##.spu-bg
certum.eu##.spu-box
```
