### ISSUE TITLE
twitch.tv gdpr

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#446]
### List the website(s) you're having issues:

`https://www.twitch.tv/`

### What happens?
unblocked cookie notification

### List Subscriptions you're using:
cookie monster

### Your settings

- OS/version: windows 10
- Browser/version: firefox stable
- Adblock Extension/version: ublock origin

### Other details:

![image](https://user-images.githubusercontent.com/5832930/41509470-83f400c2-7254-11e8-9a35-3e82338e74c0.png)

**Comment by ryanbr** [comment]
force update, does it help?

**Comment by theel0ja** [comment]
it's gone after that
