### ISSUE TITLE
forum not allow registration. and really bad easylist filter

### ISSUE THREAD

**Issue by iltaren** [ryanbr/fanboy-adblock#448]
First your forums not allow registration because of opening remote url at server config closed. 

Second i love to read manga but your adblock lists has some unimaginable regexp like 

Static filter /^https?:\/\/([0-9a-z\-]+\.)?(9anime|animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime|gogoanime|igg-games|kimcartoon|mangapanda|mangareader|memecenter|readcomiconline|toonget|toonova|watchcartoononline)\.[a-z]{2,4}\/(?!([Ss]cripts|[Uu]ploads|[Ii]mages|assets|combined|content|cover|img|static|thumbs|wp-content|wp-includes))(.*)/$first-party,script found in:
www.mangareader.net 
www.mangapanda.com 

did you ever test site work or not after that regexp ? 
you closed all images and pages and scripts everything. 
that site use ad.mangareader.net ad.mangapanda.com for advertisement also
bebi.com or some place for javascript advertisement. that kind of regex just closing site for usage.

**Comment by smed79** [comment]
> First your forums not allow registration because of opening remote url at server config closed.

https://forums.lanik.us/viewtopic.php?f=9&t=41033

**Comment by iltaren** [comment]
thank you but last update not fix the real problem unfortunately. problem is regexp is so much global.

**Comment by iltaren** [comment]
full regexp is
^https?://([0-9a-z-]+.)?(9anime|animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime|gogoanime|igg-games|kimcartoon|mangapanda|mangareader|memecenter|readcomiconline|toonget|toonova|watchcartoononline).[a-z]{2,4}/(?!([Ee]xternal|[Ii]mages|[Ss]cripts|[Uu]ploads|assets|combined|content|cover|img|static|thumbs|wp-content|wp-includes))(.*)

sorry but problem is about last (.*) when start up is ([0-9a-z-]+.)?
if it need to be blocked ad. domain like that i can understand. but you block every subdomain and every page inside of it .

(?!([Ee]xternal|[Ii]mages|[Ss]cripts|[Uu]ploads|assets|combined|content|cover|img|static|thumbs|wp-content|wp-includes))
regexp like that becausse of question mark at start even if not found. not important . so that regexp block everything inside that sites.
which banning that domains completely. please solve regexp . making mangareader or mangapanda exit kinda solve my problem but situation continue for other sites which domain name.
that regexp intended of block every javascript image xhr request covers everything from that sites. its not normal.

adblockers need to block ads
not sites.

**Comment by smed79** [comment]
If you are the webmaster, you should know for what reason this filter has been added.
... and if you complain without knowing the why, remember that your adblocker still give you the total control (one/two clicks whitelist your favorite sites).

**Comment by iltaren** [comment]
About webmaster. yes i agree. i have some work stuff with that site. but i dont know why people try to block all site? adblocker i respect. who use adblock dont want to see ads. but closing site completely can you explain this why ? and why you delete patch ?

**Comment by iltaren** [comment]
and instead of block site. like i said we respect who adblock us. we can help for right adblock regexp. otherwise we push our users for not use easylist. you push your users for not use our sites. what sense ?

**Comment by smed79** [comment]
We can not hide the sun with a sieve 
[https://www.mangareader.net/h7gp/H4kXhpo/Gl5vis/TaTD4SvN/B8YHZMA.js](https://forums.lanik.us/viewtopic.php?f=62&t=40165)

Remove the bebi.com **revolving ad script** and the **anti adblock** then come back to report again. I am sure the Easylist author @ryanbr will be happy to remove "mangareader" from the regex filter.

**Comment by iltaren** [comment]
ok i talk with our advertisement company. today i asked them too. now they said they removed already after i ask . can you check ?

**Comment by iltaren** [comment]
mangareader and mangapanda same that scripts removed.

**Comment by smed79** [comment]
Wait for @ryanbr to push a fix.

**Comment by iltaren** [comment]
thank you. by the way. not always advertisement work under website control. if something particular happen we can contact each other and solve problem.

**Comment by smed79** [comment]
> not always advertisement work under website control

We are going to blame who when you give your advertising company the control of your site in order to bypass adblockers then push [adwares, malwares, scams & spams](https://blog.malwarebytes.com/cybercrime/2017/05/roughted-the-anti-ad-blocker-malvertiser/) to users who trusted you?

**Comment by ryanbr** [comment]
have all the other sites listed in the regex been fixed also?

**Comment by iltaren** [comment]
mangareader and mangapanda at my control. others currently no i think

**Comment by iltaren** [comment]
@smed79 unfortunately true and false. they promise for no virus and malwares, and hard to be selective about how they put their advertisements in that case unless it is really bad for user. and hard to check which tricks they use for tricking adblockers, and as you can agree, it is kinda game between each other. publishers try to put advertisements for users see even with adblockers, adblockers try to make their product better to not show users advertisements. 

It is not about who right , who wrong. Showing users advertisements when they use adblocker kinda wrong. because it is for sure they don't want. also sites using resources for serve. so they need to earn money. long story. in my opinion, even if users not see advertisements they could be use site. but not same for everyone.

**Comment by ryanbr** [comment]
If someone uses an adblock, just show a non-intrusive div warning, letting the user know you rely on ads. Anyways, removed mangareader and mangapanda

**Comment by iltaren** [comment]
@ryanbr thank you for commit. after updates happen mostly at adblockers  will remove warning div anyway. quite annoying to eyes.

**Comment by ryanbr** [comment]
btw, the main Easylist won't hide warnings.

**Comment by iltaren** [comment]
@ryanbr its nice. but still unfortunately if users use adblocker they less likely open it for see advertisements just for website can earn money :) i think best way is advertisement companies making non intrusive advertisements option , like users can close themselves . also advertisments companies which agreements with adblockers so will not need to block. otherwise that warnings just annoying at site and make design worse.
