### ISSUE TITLE
PostNL Verhuisservce

### ISSUE THREAD

**Issue by bnbaz** [ryanbr/fanboy-adblock#45]
Step 2 on https://www.postnl.nl/ontvangen/doorsturen-en-bewaren/verhuisservice/ doesn't work. This is the address change service of the Dutch national post company.

Logger shows the following blocks:
https://www.postnl.nl/voorthuis/_administration/include/omniture.js (Fanboy's Enhanced Tracking List)
https://tol.postnl.nl/content/toljs/oranje (Fanboy's Annoyance List)

Also, I'd like to use this opportunity to thank you for the excellent lists!

**Comment by ryanbr** [comment]
Just to confirm, does whitelisting it fix it? 

`@@||postnl.nl/voorthuis/_administration/include/omniture.js`

**Comment by bnbaz** [comment]
Yes it does

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/c0ed6a761d462f5f2b9679212965a4b193c94513
