### ISSUE TITLE
Ultimate List is completely borked

### ISSUE THREAD

**Issue by narcolepticinsomniac** [ryanbr/fanboy-adblock#450]
Guessing it's a syntax error, because it's blocking everything and saying there's a rule that's just a wildcard:

![ultimate](https://user-images.githubusercontent.com/14100003/41636298-95200652-741b-11e8-8eb4-2789a62b0348.png)

Selecting all the same lists it contains individually seems fine, so probably a typo or something.

**Comment by ryanbr** [comment]
I can't see "*" in https://secure.fanboy.co.nz/r/fanboy-ultimate.txt  ?

**Comment by narcolepticinsomniac** [comment]
Can you repro, or am I losing my mind?

**Comment by ryanbr** [comment]
just remove/clear cache, and re-added.

**Comment by narcolepticinsomniac** [comment]
Yeah, that worked, thanks. Thought I had already tried that, but must not have in the right order. The rule actually prevented all lists from updating. Any idea what happened?

**Comment by ryanbr** [comment]
corruption? dunno. Not sure if uBo checks checksum, should report it to uBo devs.

**Comment by Mr6686** [comment]
Same problem with version 201806200240, no problem with newest 201806200340.
Only changes i can see related to this: 2 empty lines and one | line.

**Comment by narcolepticinsomniac** [comment]
Hmm. Guess I'll wait and see if it becomes a constant PITA first. Big fan of uBO, but I'd rather slam my head against a wall repeatedly than deal with gorhill. Thanks ryan.

**Comment by ryanbr** [comment]
which mirror is being used secure.fanboy.co.nz or easylist?  and which lines does it show on?

**Comment by ryanbr** [comment]
reported here also; https://www.reddit.com/r/uBlockOrigin/comments/8sewas/fanboys_annoyance_list_blocking_most_websites/

**Comment by narcolepticinsomniac** [comment]
`https://www.fanboy.co.nz/r/fanboy-ultimate.txt`

**Comment by ryanbr** [comment]
This is fix, (just purge and update filters). It probably missmerged, not sure what caused it.

I'm reviewing and fine tuning the script, and hopefully minimise any potential false positives in future.
