### ISSUE TITLE
heroku cookie notification

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#451]
### List the website(s) you're having issues:

`https://devcenter.heroku.com/articles/ssl-endpoint`

### What happens?
unblocked cookieconsent

### List Subscriptions you're using:
cookiemonster

```
##.heroku-cookie-banner
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9b06f4f24a7432bda3dd1579e465cc9ba3fff7e8
