### ISSUE TITLE
Twitch Realm Royale Adds

### ISSUE THREAD

**Issue by Twitchers** [ryanbr/fanboy-adblock#454]
![problem](https://user-images.githubusercontent.com/40476447/41748212-8ad4853e-75b9-11e8-9e57-0a75e2417d9e.jpg)

List the website(s) you're having issues:
https://www.twitch.tv

What happens?
I see this Realm Royale Ad all the time

List Subscriptions you're using:
Adblock

Your settings
OS/version: Windows 10 / 1709
Browser/version: Chrome 67.0.3396.87 (64 bit)
Adblock Extension/version: Adblock  3.31.2

**Comment by ryanbr** [comment]
I don't think this will be ever fixed tbo.
