### ISSUE TITLE
expressen.se cookie notification

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#455]
### List the website(s) you're having issues:
`https://www.expressen.se/`

### What happens?
Unblocked cookieconsent

### List Subscriptions you're using:
Cookiemonster

### Your settings

- OS/version: android
- Browser/version: ff mobile
- Adblock Extension/version: ubo

### Other details:

[![Screenshot_20180623-114342_Firefox.jpg](https://s22.postimg.cc/5onaiymyp/Screenshot_20180623-114342_Firefox.jpg)](https://postimg.cc/image/du5ch4b7h/)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/84e843885a4b2d4194a4e915d652684727e163dc
