### ISSUE TITLE
Cookie banner not blocked: moebel-und-garten.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#456]
### List the website(s) you're having issues:
`https://www.moebel-und-garten.de`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:

cookie monster
### Your settings

- OS/version: win7 (64bit)
- Browser/version: firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.10

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/712a04bd0b8d4612d52447b5e920ca9467677ef8
