### ISSUE TITLE
raymond.cc

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#458]
![2018-06-25-raymond cc blog computers made easy](https://user-images.githubusercontent.com/5884000/41868064-3f32d1b8-78b5-11e8-8dea-bafafa892ed8.png)
`https://www.raymond.cc/blog/`

social section

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.10
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by smed79** [comment]
add
```
raymond.cc###aa_wpfs_wrap
```
