### ISSUE TITLE
.tealium. breaks dominos.com

### ISSUE THREAD

**Issue by vith** [ryanbr/fanboy-adblock#459]
https://github.com/ryanbr/fanboy-adblock/blob/3b1ebbf502a62461be3826c781be10e32adf8a88/enhancedstats-addon.txt#L42

Breaks https://www.dominos.com/en/ when logged in: the page just has a loading overlay forever. Also the login process doesn't work.

After creating an exception for https://cache.dominos.com/olo/5_35_6/assets/build/js/modules/dpz.tealium.js both problems go away.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/0a3385226451e54f5dfdc97ff8641dfc22950064
