### ISSUE TITLE
How can you have missed my messages?

### ISSUE THREAD

**Issue by flyingzebras** [ryanbr/fanboy-adblock#46]
I've been trying to report EasyList issues from my Gmail to:
- easylist.subscription+khrin@gmail.com
- easylist.subscription+fanboy@gmail.com
- fanboyadblock@googlegroups.com

No one did anything with them despite that the filters were correct and for some top sites. Have you blocked my email address or something?

**Comment by ryanbr** [comment]
Personally I only read the issues via my personal git repo and the forums. I can't say much for the emails. fanboyadblock@googlegroups.com is defunct.

**Comment by davidhedlund** [comment]
@ryanbr Is easylist.subscription+fanboy@gmail.com defunct too?

**Comment by davidhedlund** [comment]
"author fanboynz <easylist.subscription+fanboy@gmail.com>" appear on hd.adblockplus.org, for example https://hg.adblockplus.org/easylist/rev/ec5112596c17

You have to expect that people are going to report filters to your email.
