### ISSUE TITLE
Icons blocked on Bitbucket

### ISSUE THREAD

**Issue by ariasuni** [ryanbr/fanboy-adblock#462]
### List the website(s) you're having issues:

`https://bitbucket.org/ariya/phantomjs/src/master/`

### What happens?

Icons used by Bitbucket coming from `https://bitbucket-connect-icons.s3.amazonaws.com/`, which are used in their interface, are blocked.

### List Subscriptions you're using:

It’s blocked because of the `-connect-icons.` filter that comes from Fanboy’s Annoyance List.

**Comment by smed79** [comment]
add
```
@@||bitbucket-connect-icons.s3.amazonaws.com/add-on/icons/$image,domain=bitbucket.org
```

**Comment by ariasuni** [comment]
I confirm it’s working with this rule.
