### ISSUE TITLE
Pages on lepotcommun.fr totally hidden

### ISSUE THREAD

**Issue by ariasuni** [ryanbr/fanboy-adblock#463]
### List the website(s) you're having issues:

For example: `https://www.lepotcommun.fr/pot/f0tqqlyf`

### What happens?

Website completely hidden.

### List Subscriptions you're using:

The website works when disabling Fanboy’s Annoyance List.

**Comment by smed79** [comment]
Test
```
@@||lepotcommun.fr/static/js/libs/angular-cookie.min.js$script
```

**Comment by ariasuni** [comment]
I confirm it’s working with this filter.

**Comment by ryanbr** [comment]
removed
