### ISSUE TITLE
ems.dz

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#465]
### List the website(s) you're having issues:

`http://ems.dz/`

### What happens?

social icons

### screenshot:

http://i.imgur.com/hZcGRdf.png

### Filter:

```
##.home__social__item
##.home__social__item--facebook
##.home__social__item--twitter
##.home__social__item--youtube
##.home__social__item--google-plus
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/022b8b1d6452fa3807c2aabfaa6ec17d35612b79
