### ISSUE TITLE
timeanddate.com

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#466]
### List the website(s) you're having issues:
`https://www.timeanddate.com/`

### What happens?

unblocked cookienotification

### List Subscriptions you're using:

cookiemonster

### Your settings

- OS/version: w10 
- Browser/version: ff stable 
- Adblock Extension/version: ubo 

### Other details:

`||timeanddate.com/custom/privacyframe.php` works with me

**Comment by ryanbr** [comment]
shouldnt be blocked by ###privacybanner already?

**Comment by theel0ja** [comment]
No. It blocks `#privacybanner` (uBO logger) but it's not hidden.
