### ISSUE TITLE
truste filter breaks spring.io

### ISSUE THREAD

**Issue by IsaakGroepT** [ryanbr/fanboy-adblock#467]
### List the website(s) you're having issues:
Happens on `spring.io` but I assume also other websites because I've noticed many issues with being able to click on links recently.

### What happens?
Visiting this website (and some others) works but I'm not able to click on the links on that website. I'm also not able to allow everything on that website because the spring.io record in the list of accepted and blocked urls is showing as green. Allowing it anyway doesn't solve the issue.

### List Subscriptions you're using:

Default uBlock + yours

### Your settings

- OS/version:  Antergos Linux 4.17
- Browser/version: Waterfox 56.2.1
- Adblock Extension/version: 1.16.12

### Other details:

 ##.truste_overlay |   | dom | http://spring.io/
 ##.truste_box_overlay |   | dom | http://spring.io/

**Comment by ryanbr** [comment]
I see a different domain, "http://consent.trustarc.com/"  If you block this, does it help:?

`||trustarc.com^`

**Comment by ryanbr** [comment]
All good, has been added to the list.
