### ISSUE TITLE
ETOnline.com - Required user action blocked (Fanboy's Annoyance List + 'Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#469]
### Affected site:
`https://www.etonline.com/`

### Issue:
Required user action (cookie consent) is blocked, preventing video playback.

### Example:
`https://www.etonline.com/mila-kunis-addresses-divorce-and-pregnancy-rumors-and-the-stress-it-causes-family-105330/`

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rules:
```
/evidon-banner.
##.evidon-banner
###_evidon_banner
```

### Possible fix:
```
@@/evidon-banner.$domain=etonline.com
etonline.com#@#.evidon-banner
etonline.com#@##_evidon_banner
```
..but of course, if possible, bypassing this annoyance would be preferable.

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.3 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.2 (XUL)

**Comment by ryanbr** [comment]
replace those whitelists and test with;

`@@||evidon.com/geo/country.js$script,domain=etonline.com`

let me know if it helps

**Comment by THEtomaso** [comment]
No, it doesn't work.

**Comment by ryanbr** [comment]
etonline.com#@##_evidon_banner

Is this enough?

**Comment by THEtomaso** [comment]
No, I tested the whitelistings thoroughly.
All of them needs to be present, for the cookie consent message to appear!
In fact, for my particular setup, I actually need to add a couple more, but I've reported those to other filter authors, and they aren't needed for the Fanboy filters.

**Comment by ryanbr** [comment]
is @@/evidon-banner.$domain=etonline.com needed? whats the full url being whitelisted here?

**Comment by ryanbr** [comment]
```
image | https://c.evidon.com/pub/icong1.png
script | https://c.evidon.com/sitenotice/425/etonline/settings.js
script | https://c.evidon.com/sitenotice/425/translations/en.js
script | https://c.evidon.com/sitenotice/425/etonline/settings.js
script | https://c.evidon.com/sitenotice/425/snthemes.js
script | https://c.evidon.com/geo/country.js
script | https://c.evidon.com/sitenotice/evidon-sitenotice-tag.js
```

This is what I'm seeing (none are actually blocked (if I disable Easyprivacy)

**Comment by THEtomaso** [comment]
> is `@@/evidon-banner.$domain=etonline.com` needed?

Yes, it's needed.
Otherwise, this script gets blocked:
`https://c.evidon.com/sitenotice/evidon-banner.js`
