### ISSUE TITLE
[social blocking list] google image search "Share" button

### ISSUE THREAD

**Issue by twioflieggeu** [ryanbr/fanboy-adblock#47]
if you do an image search and then select an image, a box will come up for that image and it will contain a "Share" button like follows:

`<a class="irc_fsl irc_but i17628" jsaction="irc.sh" tabindex="0" data-ved="0ahUKEwjhksSk8fbPAhWIz4MKHQkrCHcQ3IkBCAs">
    <span class="_qyj irc_but_t _wtf _Rtf" style="height:14px;line-height:14px;width:14px">
        <svg focusable="false" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z"/>
        </svg>
    </span>
    <span class="irc_but_t irc_but_t_pad">Share</span>
</a>`

**Comment by SMed79** [comment]
- https://goo.gl/images/WhkdJK
- https://www.google.com/search?q=adblock+plus&tbm=isch#imgrc=PYjAeQz6Y86TxM%3A

```
/social/fb_
##.irc_butc > .irc_but_r A[jsaction="irc.sh"]
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/407f3affba46fe8abdaa4839937c1e79955c87bf

**Comment by twioflieggeu** [comment]
https://github.com/easylist/easylist/commit/407f3affba46fe8abdaa4839937c1e79955c87bf doesn't seem to block it

**Comment by ryanbr** [comment]
Happy to probably leave it, not that imposing anyways. Even now.
