### ISSUE TITLE
qrdesign.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#470]
![2018-07-07-qd _ generate visual qr code](https://user-images.githubusercontent.com/5884000/42411739-710b9bb6-8201-11e8-9954-179ec30815f0.png)
`https://www.qrdesign.net/en/generate`

broken social icon

Fanboy’s Annoyance List
Fanboy’s Social Blocking List

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.12
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by HybridDog** [comment]
It is shown if I disable "Parse and enforce cosmetic filters".
If I re-enable this setting, the icon is not shown.
I think the blocked thing is called "##.fa-share-alt.fa-4x.fa".

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0c02f1ace1870f068b761f08e5b156db0668e490
