### ISSUE TITLE
Privacy Policy Banner

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#471]
### List the website(s) you're having issues: 
`https://secure.avaaz.org/page/en/`, `https://avaaz.org/page/de/`, `https://avaaz.org/page/fr/`, `https://avaaz.org/page/po/`, `https://avaaz.org/page/nl/`, `https://avaaz.org/page/it/`, `https://avaaz.org/page/tr/`, `https://avaaz.org/page/pl/`, `https://avaaz.org/page/ro/`, `https://avaaz.org/page/el/`, `https://avaaz.org/page/ru/`, `https://avaaz.org/page/ar/`, `https://avaaz.org/page/jp/`, `https://avaaz.org/page/kr/`, `https://avaaz.org/page/kr/`, `https://avaaz.org/page/ct/`

### What happens? 
Hello, 
Since the entry into force of the General Data Protection Regulation (GDPR) (EU) 2016/679 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, some websites have started to publish a banner similar to the cookie banner on their site. (Example: "By continuing you accept Avaaz's Privacy Policy which explains how your data can be used and how it is secured") These Privacy Policy Banners are as annoying as the Cookie Banners. Wouldn't it be a good idea to introduce filters for this as well? Either integrated into the "Fanboy's Cookiemonster List" or into a separate list, for example "Fanboy's Privacy Policy Monster List". To get started, here are some examples from avaaz.org above

Greetings Ernesto (Translated with www.DeepL.com)

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.12

**Comment by ryanbr** [comment]
Applicable for the Cookie list. Added.
