### ISSUE TITLE
Express.co.uk - Login/Registration dialogs blocked (Fanboy's Annoyance List + 'Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#472]
### Affected site pages:
```
https://www.express.co.uk/users/login/
https://www.express.co.uk/users/register/
```

### Issue:
The login and registration popup dialogs are blocked.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`||consent.cmp.oath.com^`

### Blocked script:
`https://consent.cmp.oath.com/cmp3p.js`

### Possible fixes:
`@@||consent.cmp.oath.com^$domain=express.co.uk`
or
`@@||consent.cmp.oath.com/cmp*p.js$domain=express.co.uk`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.3 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.2 (XUL)

**Comment by ryanbr** [comment]
That should work, if it affects other sites with other false positives, might be removed
