### ISSUE TITLE
MSI.com - Required user action blocked (Fanboy's Annoyance List + Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#475]
### Affected site:
`https://www.msi.com/`

### Example:
`https://www.msi.com/Motherboard/support/Z170A-PC-MATE.html#down-bios`

### Issue:
Required user action (cookie consent) is blocked, preventing downloading of files.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`/cookiecontrol-`

### Possible fix:
`@@/cookiecontrol-$domain=msi.com`
..but of course, if possible, bypassing this annoyance would be preferable.

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.3 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.2 (XUL)

**Comment by ryanbr** [comment]
Post the full /cookiecontrol- url that's being blocked

**Comment by THEtomaso** [comment]
> Post the full /cookiecontrol- url that's being blocked

Here you go:
`https://cc.cdn.civiccomputing.com/8.0/cookieControl-8.0.min.js`

Perhaps a fix like this then, just in case the script version changes?:
`@@||cdn.civiccomputing.com/*/cookieControl-*.min.js$domain=msi.com`
