### ISSUE TITLE
tempr.email:  block not hide ##.af-table-wrapper

### ISSUE THREAD

**Issue by BigGiantHeadsHighCommander** [ryanbr/fanboy-adblock#478]
### List the website(s) you're having issues:

`tempr.email`

sneaky content difficult to discern source

### What happens?

load site
create DEA mailbox
cruft after blocking with these

`! 7/9/2018, 1:15:26 AM https://tempr.email/inbox.htm
||images-eu.ssl-images-amazon.com/*$image,domain=tempr.email
||tempr.email/www.amazon.de/*
||www.tempr.email/www.amazon.de/*
||produkte.appfield.net/*
||nur.gratis/*
||tempr.email/inbox.htm$inline-script,first-party
`

### List Subscriptions you're using:

most of them

### Your settings

- OS/version:  windows 10
- Browser/version:  current waterfox and iridium
- Adblock Extension/version:  uBlock Origin, and Nano AdBlock, respectively

### Other details:

I do not want to hide the remnant.  I want to prevent its generation

`class="af-table-wrapper"`

![not hide do block generation](https://user-images.githubusercontent.com/40991806/42445788-0f8659e8-8329-11e8-8e1a-a30dafe53a6c.png)

**Comment by smed79** [comment]
https://forums.lanik.us/viewtopic.php?p=139285#p139285

**Comment by smed79** [comment]
> So what exactly is that element showing?

https://i.imgur.com/lxclw8v.png
https://i.imgur.com/RD0Zsm2.png
