### ISSUE TITLE
Back/skip to top of page button gets blocked on ebay.com

### ISSUE THREAD

**Issue by mieiko** [ryanbr/fanboy-adblock#48]
1.Visiting ebay.com
2. Searching for items
3. Scrolling

There should be a button with an arrow on it on the right hand side on the site which allows you to skip back to top of the page.
"Skip to top of page"-button gets blocked by this filter. (Via adblock customer service who asked me to leave this info here).

**Comment by ryanbr** [comment]
Its intentionally blocked

**Comment by SMed79** [comment]
@mieiko Add to your customer filters:
```
ebay.com#@##gh-bt
ebay.com#@#img[alt="Scroll to top"]
```
