### ISSUE TITLE
instalnet.pl

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#481]
### List the website(s) you're having issues:

`http://www.instalnet.pl/instalnet/`

### What happens?

Rule `##div[data-cookie]` cuts warning about possible data theft by impersonating the subject instalNET company.

_https://github.com/MajkiIT/polish-ads-filter/issues/8350#issuecomment-404462121_

### List Subscriptions you're using:

uBO default +  Fanboy’s Annoyance List / Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 10 Pro
- Browser/version:  Firefox 61.0.1
- Adblock Extension/version: uBO 1.16.12

### Other details:

`##div[data-cookie]` cuts warning: 

>![obraz](https://user-images.githubusercontent.com/35370833/42627423-4fc844ac-85cd-11e8-9451-d99c4f2e4717.png)

> **Warning! False contests and surveys**  
>   
>  on the internet appear to be false contests and surveys, suggesting that the organizer is the operator **Instalnet sp.j.**
> 
> **Company Instalnet sp.j. does not run contests and surveys of this type and in this form.**  
> False messages about the contest or survey may appear on various websites.  
> Fraudsters display information that the client receives one of several prizes.  
> In addition, they used false information, suggesting an association with recognizable companies
> 
> **Note the redirection to another page where fraudsters can fool our data.**
> 
> Protect your personal information, security is a minimum of a full blown anti-virus program.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9c38f19329e41e7c4a10c729b4b5f7267b4812c1
