### ISSUE TITLE
NYTimes.com - Required user action blocked (Fanboy's Annoyance List + 'Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#483]
### Affected site:
`https://www.nytimes.com/`

### Issue:
Required user action (cookie consent) is blocked, preventing video playback.

### Example:
`https://www.nytimes.com/2018/05/18/us/dimitrios-pagourtzis-gunman-texas-shooting.html`

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`nytimes.com##.expanded`

### Possible fix (commit):
`-nytimes.com##.expanded`

### Note:
The page needs to be refreshed, after having accepted the cookie consent (site issue).

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.3 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.2 (XUL)

**Comment by ryanbr** [comment]
video played fine here?

**Comment by THEtomaso** [comment]
Yeah, turns out that the the cookie warning doesn't need to be accpeted after all.

Here's what happens at my end..

When loading the page, the video is shown as a black frame, which threw me off:

![filterissue-nytimes](https://user-images.githubusercontent.com/9382674/42672924-629f8bd6-8658-11e8-8f13-56f19a6d25ae.jpg)

If I whitelist the cosmetic rule, accept the cookie consent, and reload the page, then the video plays.

However, I've now discovered that simply clicking on the black frame makes the video play too! :)

**Comment by ryanbr** [comment]
retested it from other regions just in case, seems fine here.

**Comment by THEtomaso** [comment]
Simply clicking on the black frame doesn't work anymore.
Now the problem rule in my first post really needs to be removed!

Example:
`https://www.nytimes.com/2018/09/24/style/robot-furniture-beep-beep-boop.html`

**Comment by ryanbr** [comment]
Worked fine here. again

**Comment by THEtomaso** [comment]
It's a regional GDPR thing then, like those notorious "Evidon" consents.

Looks like these files might be invovled in sniffing the visitors locations, and determining which cookie consent to serve: 
```
https://content.api.nytimes.com/svc/location/v1/current.json
https://www.nytimes.com/vi-assets/static-assets/main-b94b3ee5a848b10d9c28.js
```

**Comment by THEtomaso** [comment]
The video in the article that I linked to in the first post still plays when the cookie consent is blocked, simply by clicking on the black frame.
However, the video that I posted a link to here doesn't (at least not from my location):
https://github.com/ryanbr/fanboy-adblock/issues/483#issuecomment-424276252

This is the problem rule (found in Fanboy's Annoyance List and in 'Fanboy's Cookie List):
`nytimes.com##.shown.expanded`

I've troubleshooted this issue quite thoroughly..
The ONLY way that I can make the video play, is if I make an exception for the rule above, like this:
`nytimes.com#@#.shown.expanded`
Once this exception is in place, I'm able to accept the cookie consent, and the video plays after refreshing the page!

**Comment by THEtomaso** [comment]
This recently added rule simply made things worse:
`##.gdpr:not(body):not(html)`
I guess the idea is that it should accept the cookie consent automatically (like in the 'I don't care about cookies' filter)?
However, from my location, this doesn't work at all.
Instead, the consent dialog is denied, and I have to make yet another exception:
`#@#.gdpr:not(body):not(html)`

**Comment by ryanbr** [comment]
screenshot of the before an after with  #@#.gdpr:not(body):not(html)

**Comment by ryanbr** [comment]
Sure, I guess.

**Comment by THEtomaso** [comment]
The following rule (which I've pointed out before) still blocks it!:
`nytimes.com##.shown.expanded`

**Comment by THEtomaso** [comment]
@ryanbr:

Could you please remove the rule which I refered to in my previous post?
