### ISSUE TITLE
NYTimes articles' embedded tweets not displaying

### ISSUE THREAD

**Issue by lukeuser** [ryanbr/fanboy-adblock#485]
### List the website(s) you're having issues on:

`https://www.nytimes.com`

### What happens?

Visit any article page with an embedded tweet. The tweet doesn't display; the outline of the tweet box does appear, and in at least one case an image from the tweet does display, but nothing else. See `https://www.nytimes.com/2018/07/13/world/europe/donald-trump-uk-london-visit.html` for an example.

### List Subscriptions you're using:

Fanboy’s Cookiemonster List (issue occurred with every other list disabled, and was resolved by disabling this list)

### Your settings:

- OS/version: Windows 10
- Browser/version: Chrome 67 & 69
- Adblock Extension/version: uBlock Origin

### Notes:

Problem doesn't occur when cosmetic filtering (element hiding) is disabled, so the issue must be with such a rule. uBlock logger doesn't show anything relavent, perhaps because the rule is being applied inside a shadow root?

**Comment by lukeuser** [comment]
This is what appears when Cookiemonster list is enabled:
![image](https://user-images.githubusercontent.com/26203914/42724002-15474f80-8762-11e8-890e-679be68fac68.png)
And when it is disabled:
![image](https://user-images.githubusercontent.com/26203914/42724004-1d947348-8762-11e8-906c-3b3a15df7b5a.png)
I'm not getting the issue on Firefox (also with uBlock), so it seems to be specific to either Chrome, or the Chrome version of uBlock.

**Comment by ryanbr** [comment]
I did see it, when I vpn'd to the EU. It doesnt look like its filter related, server related maybe? tl;dr I tested with adblock completely disabled and the twitter bits didnt render properly.

**Comment by lukeuser** [comment]
Okay, thanks
