### ISSUE TITLE
Cookie banner not blocked: geo.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#487]
### List the website(s) you're having issues:

`https://www.geo.de/`

### What happens?

Cookie banner not blocked

### List Subscriptions you're using:
Fanboy's Cookiemonster List

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.12

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/29875b66d36119ea06cd962f90b335de6bfc9600
