### ISSUE TITLE
rosbank.ru content hidden by a cookie rule

### ISSUE THREAD

**Issue by mkr4** [ryanbr/fanboy-adblock#488]
### List the website(s) you're having issues:

- `https://www.rosbank.ru/`

### What happens?

Cookiemonster filter breaks this site with [rule](https://github.com/ryanbr/fanboy-adblock/blob/35822cc30ad27a20bbd3081750f89a96bc84c62f/fanboy-cookiemonster.txt#L5429) `##.cookie-on`

Site has this class attached to body tag:
`<body class=" cookie-on menu-opened p-home">`

### List Subscriptions you're using:

uBlock Origin with `Fanboy’s Annoyance List` and `Fanboy’s Cookiemonster List` on
### Your settings

Reproduces on windows 7 in chromium and firefox

**Comment by ryanbr** [comment]
Does this cover it? 
```
#@#.cookie-on
rosbank.ru###gray_overlay
```
