### ISSUE TITLE
borlabs-cookie on Fanboy's Annoyance List

### ISSUE THREAD

**Issue by opensourcecompany** [ryanbr/fanboy-adblock#489]
### List the website(s) you're having issues:
`https://oekologische-werbeartikel.de`
(and MANY others!)

### What happens?
The GDPR FORCES website owners to show a cookie consent.
In case of Wordpress, it is a good idea to use Borlabs Cookies plugin, since it allows the website visitor to finetune accepting cookies -> following GDPR standard.

Therefore: WHO is in charge for blocking:
/borlabs-cookie/*
Fanboy's Annoyance List

### List Subscriptions you're using:
Fanboy's Annoyance List

### Your settings
- OS/version: Windows 7
- Browser/version: Chrome latest
- Adblock Extension/version: latest

### Other details:
none

**Comment by ryanbr** [comment]
See if that works, I think it works? let me know.

**Comment by opensourcecompany** [comment]
Unfortunately not.
Yes, the slider is loading again, but it is a bad idea to block Borlabs Cookies since the visitor needs to see the Cookie agreement... :-/
Yes, Europe, strange things happen here... :-)

**Comment by krystian3w** [comment]
Disable thrid party cookies or first party isolation (if no break you most visited websites)?

`##body > div[data-borlabs-cookie-wrap="popup"]` if block network rule CSS fail?

**Comment by ryanbr** [comment]
I visited the site, seems fine (force list update), I don't get the popup, and the site seems to show correctly.

**Comment by ryanbr** [comment]
Picked up the cookie warning at the bottom, because the css was blocked.

https://github.com/easylist/easylist/commit/6df089688a52c98a29846eddf53796d7469a24cf

Closing ticket, site still renders fine.

**Comment by opensourcecompany** [comment]
It is STILL broken, since the cookie warning is not showing up...

**Comment by ryanbr** [comment]
Where on these screenshots is it broken? 

https://imgur.com/a/vlcjI0Y

**Comment by ryanbr** [comment]
Erm, okay. Its intentional. Don't install the Annoyances list if you like getting all those cookie warning ads. 

Regarding legality, using adblock subs is client side. Technically the site is showing the cookie warnings as per the requirements. What ever you do on your own PC is up to you, including hiding cookie elements.

**Comment by opensourcecompany** [comment]
Well, it is a difference between annoying anti-adblock and neccessary cookie warnings :-/
But okay, i agree with you, it is a client-side problem, the website technically delivers the content.

Hope that the bureaucrats from Brussels also follow this idea... ;-)

**Comment by krystian3w** [comment]
For yourself, you can always add a message to the exception as you like in a specific click.
