### ISSUE TITLE
dreamfilmhd.bz crazy popup

### ISSUE THREAD

**Issue by BourbonCrow** [ryanbr/fanboy-adblock#49]
dreamfilmhd.bz

This website have done it again and worse then ever.. like just when you click the search bar it closes it self and opens an ad window instead with like a cooldown of.. 15ish.. mins or so its some kind of js that is REALLY annoying hope you can block it

cant really give any details on how to cause i have no idea just wanted to report it

**Comment by SMed79** [comment]
add these filters:
```
||psma02.com.^
|blob:$script,domain=dreamfilmhd.bz
dreamfilmhd.bz##a[target="_blank"] > img
```

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/f73e7c7bf190133b5e0b2a676b04c11eb1858caa
