### ISSUE TITLE
Cookie banner not blocked: gira.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#492]
### List the website(s) you're having issues:
`https://www.gira.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:

Fanboy's Cookiemonster List

### Your settings

- OS/version: Win7 (64Bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.14

**Comment by krystian3w** [comment]
`gira.de###ac_frame` - cookies banner

`gira.de###navmaintop > div > a:nth-child(-n+5) > img` - social media, mabye better is network rules.

**Comment by smed79** [comment]
for the social icons https://github.com/easylist/easylist/pull/1568
