### ISSUE TITLE
olx.ua

### ISSUE THREAD

**Issue by GoodGuyNick** [ryanbr/fanboy-adblock#493]
### List the website(s) you're having issues:
    https://www.olx.ua

### What happens?
Contact button not working in any advert.
Open any advert and try to press contact button.
Registration is not required for testing.

### List Subscriptions you're using:
Using uBlock Origin with **Fanboy’s Enhanced Tracking List** and **uBlock filters – Privacy**

### Your settings

- OS/version: Xubuntu 16.04.4
- Browser/version: Firefox 61.0.1, Chromium 66.0.3359.181
- Adblock Extension/version: uBlock Origin v1.16.14 in Firefox, uBlock Origin v1.16.12 in Chromium

### Other details:
If you disable **uBlock filters – Privacy** or **Fanboy’s Enhanced Tracking List** the button will work.

**Comment by adranger** [comment]
Problems with "uBlock filters – Privacy" should be reported to https://github.com/uBlockOrigin/uAssets/issues

**Comment by krystian3w** [comment]
Now works fine - maybe fixed and nobody pinned PR for this issue.

**Comment by krystian3w** [comment]
`@@||www.googletagmanager.com/gtm.js$script,domain=olx.ua`

**Comment by mapx-** [comment]
```
@@||googletagmanager.com/gtm.js$script,domain=olx.ua
@@||ninja.onap.io/ninja-cee.js$script,domain=olx.ua
```

**Comment by adranger** [comment]
@GoodGuyNick  If this is supposed to be added to this list after all, please reopen this issue.
