### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#496]
`github.com##.js-notice`  is bad filter:

Cut info about edit reply / issue post / Pull requests posts:

> ![obraz](https://user-images.githubusercontent.com/35370833/43045707-d89a2c12-8dbd-11e8-84a4-a4a1863240bd.png)

`https://github.com/Aris-t2/CustomCSSforFx/issues/133#issuecomment-406709015` = demo

---

uBO 1.16.14 Default filters +  Fanboy Cookiemonster List, On Windows 10, in Firefox 61.0.1.

**Comment by ryanbr** [comment]
okay, removed.
