### ISSUE TITLE
Incorrect domain in your blacklist

### ISSUE THREAD

**Issue by ronkol** [ryanbr/fanboy-adblock#497]
https://github.com/ryanbr/fanboy-adblock/blob/5c6a0de2b6aef75ffc9d5963e01d5e9d4e863741/fanboy-problematic-sites.txt#L83

My name is Ron Kol, VP R&D of Hola Spark http://holaspark.com. We are a worldwide service provider of CDN and Video experience enhancements and have top tier customers as you can see on our site.

In this commit you added player.h-cdn.com to your blacklist. I have no idea why but this is hurting our reputation and business. 

Please remove us from this list or tell me why we are on it so we can get it resolved.

Thanks,

**Comment by smed79** [comment]
@ronkol 

> you added player.h-cdn.com to your blacklist

The filters above that your are refer to does not block your domain (see [#whitelist](https://adblockplus.org/en/filters#whitelist))

> this is hurting our reputation and business

What is the issue & how to reproduce?

@ZeroDot1 

> :+1:

Did you understand something that I missed ?

**Comment by ZeroDot1** [comment]
@smed79 It's a false positive.
I already removed it from the CoinBlockerLists.
https://gitlab.com/ZeroDot1/CoinBlockerLists/commit/c944dbdf825391047c0cda4d08ed5e21b9039dc1

**Comment by ronkol** [comment]
Thanks @ZeroDot1 , i appreciate it.

@smed79 please remove it as well and we can close this issue.

**Comment by yvestch** [comment]
How do I completely unsubscribe from this plz?

Cheers,

Yves (version 2.7) 🤗  
  Product Manager, Customer Obsessed & Data Driven + Certified Salesforce Developer & Administrator 

 <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/> <https://www.linkedin.com/in/yvestch/>/in/yvestch <https://www.linkedin.com/in/yvestch> | yvestch <https://twitter.com/Yvestch>@gmail.com |  <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch> <https://twitter.com/Yvestch>@yvestch <https://twitter.com/Yvestch>  |  650-999-0121  |  415-528-8904 |  San Francisco , CA

**Comment by krystian3w** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/497 - login and click "unsubscribe" on site:

> ![image](https://user-images.githubusercontent.com/35370833/43310009-ac039f86-9186-11e8-9c10-89da981a8475.png)

:question:

**Comment by ryanbr** [comment]
why did player.h-cdn.com/ads.js exist? are you still monitoring adblock users?

**Comment by ronkol** [comment]
Hi,

We don’t do it anymore for a long time now. 

We used to monitor this to get an idea of the extent adblockers are used. Don’t see why that should cause us to be blocked

But anyway, as I said, we don’t do it anymore for at least a year so I would appreciate being removed from your lists. 

Thanks,
Ron

**Comment by ryanbr** [comment]
Seems a bit strange to request a removal of a filter, that you've already removed server side. (since apparently doesn't affect you anymore anyways)

**Comment by ronkol** [comment]
other products/companies/people are looking at your lists and bulk adding the domains to their filters - i dont want our domain to appear in any such list anywhere.

**Comment by ryanbr** [comment]
I have no issues removing filters, but you can't push people around.

That said, If you get caught again trying to affect/monitor/disrupt adblock users, Legally* we are in our rights to what ever we want. People can pick and choose which filter sub they use, if they use this _optional_ filter subscription thats there personal decision.

* https://www.zdnet.com/article/adblock-plus-scores-big-legal-win-it-doesnt-break-antitrust-law-court-rules/
* https://arstechnica.com/tech-policy/2016/11/adblock-plus-wins-its-6th-court-case-brought-by-der-spiegel/
* https://www.theguardian.com/media/2016/mar/30/adblock-plus-publishers-suddeutsche-zeitung-adblocking

**Comment by ronkol** [comment]
yes, i agree but, for example, if you know that your lists are being watched by anti-virus companies and they bulk add them to their site blocks and you dont keep your list updated causing damage to legitimate businesses thats not helping the public, its just simply irresponsible and although most of the blame is on them, its partially yours as well. 

And after all this when you are asked to remove a certain domain (rather nicely i think) you act as if you are being bullied. i dont know how else i could have requested removal of our domain without being considered a bully in your eyes.

perhaps theres a chance we can agree that:
- not all businesses are evil, a few are ok 
- it would be the responsible thing to do to add an auto test monitor that keeps checking your list and removes those that have 'fixed' whatever you thought was wrong. iv seen other similar projects to yours that already do that.

**Comment by ronkol** [comment]
id appreciate it if our domain can also be removed from the list which the issue was opened for:
fanboy-problematic-sites.txt

**Comment by ronkol** [comment]
well, i dont have write access to your lists and not going to start creating pull requests for a text file. I found 4 more projects that mentioned our domain and they responded nicely and removed our domain from their lists very quickly understanding that it was a mistake.

I guess you are special.

If our domain is not removed from your lists in the next couple of days i will have to report it as abuse as its hurting our business for no good reason.

**Comment by ryanbr** [comment]
Report away, it was removed and its not listed in https://secure.fanboy.co.nz/fanboy-problematic-sites.txt

Pretty sure you know the difference between a whitelist and a blacklist too? 

@@||player.h-cdn.com/ads.js  wouldn't cause any user issues. Again, the fact you're saying the file "ads.js" is removed it shouldn't matter about the whitelist. We'd be whitelisting a dead file name, which doesn't affect you (because it was removed, according to you).

Ofcourse if ads.js is not removed, then we'll be having another look at your site.
