### ISSUE TITLE
Lots of outdated sites on adult list

### ISSUE THREAD

**Issue by stonecrusher** [ryanbr/fanboy-adblock#498]
I ran a linkchecker over all domains of the [adult elements](https://github.com/ryanbr/fanboy-adblock/blob/master/fanboy-adblock/fanboy-adult-elements.txt) filter and there are lots of outdated filters from pages that either don't exist anymore or are redirected to another domain (which makes the specific filter useless).

### List the website(s) you're having issues:

```
http://abc-celebs.com/
http://alphaporno.com/
http://amateurpovtube.info/
http://axatube.com/
http://bannedfromyoutube.com/
http://cam111.com/
http://cantoot.com/
http://cockcheese.com/
http://erotic-port.hu/
http://exgfpics.com/
http://fapgames.com/
http://fbooksluts.com/
http://filhadaputa.tv/
http://filthyrx.com/
http://fuckmetube.org/
http://imagehaven.net/
http://majorwager.com/
http://momisnaked.com/
http://momsteachboys.com/
http://myprops.org/
http://onlyukporn.co.uk/
http://peepinghunter.com/
http://picforshare.com/
http://pixhub.eu/
http://porntack.com/
http://pornvideoscout.com/
http://retrovidz.com/
http://scio.us/
http://sexy-toons.org/
http://shockingtube.com/
http://shufuni.com/
http://slutleech.com/
http://springbreaktubegirls.com/
http://subimg.net/
http://teenist.com/
http://tehvids.com/
http://tubesexmovies.com/
http://tutzone.net/
http://wankerhut.com/
http://wide6.com/
http://xvideo2.net/
http://yobt.tv/
http://youngartmodels.net/
http://ziporn.com/
http://amateurfarm.net/
http://bustnow.com/
http://craveonline.com/
http://depositfilesonic.com/
http://givemegay.com/
http://hollywoodrag.com/
http://imgchili.com/
http://io9.com/
http://jizzhut.com/
http://mylifetime.com/
http://pornbanana.com/
http://pornsharia.com/
http://porntubevidz.com/
http://protectlinks.com/
http://sharenxs.com/
http://starcelebs.com/
http://tubesexclips.com/
http://videarn.com/
http://xtravids.com/
http://xxxlinks.es/
http://yobt.com/
```
### What happens?

Outdated, can be deleted

By the way, `tutzone.net` works but doesn't look like an adult site at all, so imho can be deleted, too.

/edit:
HTML-List:
[list.html.log](https://github.com/ryanbr/fanboy-adblock/files/2219170/list.html.log)

**Comment by ryanbr** [comment]
wouldn't test against the old list in https://github.com/ryanbr/fanboy-adblock/blob/master/fanboy-adblock/fanboy-adult-elements.txt

**Comment by ryanbr** [comment]
would start on; https://github.com/easylist/easylist/blob/master/easylist_adult/adult_specific_block.txt

**Comment by stonecrusher** [comment]
Ah, sorry. Are fanboy's lists now merged to easylist?

**Comment by stonecrusher** [comment]
This is the result of the same procedure but for the easylist you posted:
[list_new.html.log](https://github.com/ryanbr/fanboy-adblock/files/2220405/list_new.html.log)

I deleted all the redirects from `http` to `https` or from `domain.com` to `www.domain.com`

**Comment by stonecrusher** [comment]
moved issue to easylist
https://github.com/easylist/easylist/issues/1588
