### ISSUE TITLE
Reddit subscribe button gone

### ISSUE THREAD

**Issue by Bluberius** [ryanbr/fanboy-adblock#5]
The social blocking list seems to remove the subscribe und unsubscribe buttons for subreddits. Is this intentional? How can I get them back?

**Comment by ryanbr** [comment]
Which subreddit?

https://www.reddit.com/r/firefox 
https://www.reddit.com/r/hometheater

Seem fine so far

**Comment by Bluberius** [comment]
Weird, it doesn't work for me:

![withsocialblock](https://cloud.githubusercontent.com/assets/15158778/14068399/8f0acdee-f482-11e5-8f9d-c4fdc56c4f2c.png)
![nosocialblock](https://cloud.githubusercontent.com/assets/15158778/14068400/90dc07aa-f482-11e5-99ec-8970800f54d9.PNG)

I'm using 
Firefox 45.0.1
Ublock Origin 1.6.6

Filter List:
[Adblock Plus 2.0]
 ! Checksum: D44NKgejlTahzbqX1WoyIA
 ! Version: 201603271851
 ! Title: Fanboy's Social Blocking List
 ! Last modified: 27 Mar 2016 18:51 UTC

**Comment by Bluberius** [comment]
Update: 

The subscribe button also disappears with the following two configurations:

SRWare Iron Version 44.0.2350.0 
Ublock Origin 1.6.4 (no other addons)
Fanboy's Social Blocking List

SRWare Iron Version 44.0.2350.0
Adblock Plus 1.11 (no other addons)
Fanboy's Social Blocking List

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/05346339bfb5

This should fix it.

**Comment by Bluberius** [comment]
Works now, thanks!

**Comment by lewisje** [comment]
Why did you add that as an add-on whitelist rule, instead of making an exception inside the general rule? I thought the latter course of action was only a last resort, intended for end-users who have filter-lists with *un*responsive maintainers.
