### ISSUE TITLE
Fanboy's Cookiemonster List : alternativeto.net###bottomNotifier

### ISSUE THREAD

**Issue by Alex131089** [ryanbr/fanboy-adblock#50]
Fanboy's Cookiemonster List : alternativeto.net###bottomNotifier hides an useful area that permit to report error on software ("report it")

**Comment by ryanbr** [comment]
If I replace it with "alternativeto.net##.darkNotifierContent", would that fix it?

**Comment by ryanbr** [comment]
tl;dr All I see is the Cookie element using this

**Comment by Alex131089** [comment]
https://alternativeto.net/software/ublock-origin/ : click "More app info" then "report it", this is using it (the replacement you proposed too).
You can block "alternativeto.net##.EUc__message", it will hide the cookie message. The bottom notifier with cookie message is disappearing when you scroll a bit or when you change page and seems to never return. But the bottom notifier can be used for things like report it seems.
Anyway, thank you for deleting those annoying messages.

**Comment by ryanbr** [comment]
The black bar still shows with ##.EUc__message, what issue false positive causes when we block bottomNotifier ?

**Comment by Alex131089** [comment]
The anwser is in the first message ;)
> Fanboy's Cookiemonster List : alternativeto.net###bottomNotifier hides an useful area that permit to report error on software ("report it")

and the steps to reproduce in the second : 
> https://alternativeto.net/software/ublock-origin/ : click "More app info" then "report it", this is using it (the replacement you proposed too).


Personally I prefer an empty black bar that vanishes when you start scrolling or when you start navigating on the website, than having a feature not working (again, it's "report it") so I whitelisted "alternativeto.net###bottomNotifier".

**Comment by ryanbr** [comment]
If that's the case, I'm fine leaving it as is.
