### ISSUE TITLE
https://www.theguardian.com/uk cookie banner

### ISSUE THREAD

**Issue by adblockreporter** [ryanbr/fanboy-adblock#502]
### List the website(s) you're having issues:

`https://www.theguardian.com/uk`

### What happens?

Shows a Privacy/Cookie banner at the bottom of the page on first page visit to UK visitors

> Your privacy
> 
> We use cookies to improve your experience on our site and to show you relevant advertising.
> 
> To find out more, read our updated privacy policy and cookie policy.
> More information

### List Subscriptions you're using:

Default uBlock Origin lists, plus Fanboy’s Annoyance List (which includes Fanboy’s Cookiemonster List?)

### Your settings

- OS/version: Intel Mac OS X 10.12
- Browser/version: Firefox/61.0
- Adblock Extension/version: uBlock Origin 1.16.14

### Other details:

None

**Comment by smed79** [comment]
It's already hidden by `theguardian.com##.site-message`
- https://i.imgur.com/BnODGgm.png

**Comment by adblockreporter** [comment]
Yes you're right :) I may have forgotten to turn on the right block list
