### ISSUE TITLE
https://www.bbc.co.uk/iplayer/

### ISSUE THREAD

**Issue by Sniper296** [ryanbr/fanboy-adblock#504]
### List the website(s) you're having issues:

`https://www.bbc.co.uk/iplayer/`

### What happens?

Play button displays loading spinner infinitely.

### List Subscriptions you're using:

- uBlock filters​​​​​
- uBlock filters – Badware risks​
- uBlock filters – Privacy​​​​​
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak​​​​​
- Adblock Warning Removal List
- EasyList
- EasyPrivacy
- Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 10 Version 1803 Build 17134.167
- Browser/version: Firefox 61.0.1 (64-bit)
- Adblock Extension/version: uBlock 1.16.14

### Other details:

Fixed by using rule to override Cookiemonster list rule.
`@@||bbci.co.uk/orbit-webmodules/*/cookie-banner/cookie-prompt/cookie-library.min.js`
Cookie prompts remain hidden despite the exception.

**Comment by ryanbr** [comment]
was fixed already, just update subs
