### ISSUE TITLE
passeidireto.com

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#507]
### List the website(s) you're having issues:

`https://www.passeidireto.com/login`

### What happens?

**Fanboy’s Annoyance List** hides Facebook and Google login options.

### Your settings

- Browser/version: Firefox 61.0.1
- Adblock Extension/version: uBlock Origin 1.16.14

**Comment by THEtomaso** [comment]
> Fanboy’s Annoyance List hides Facebook and Google login options.

..as it should!
If you want to use social media logins, then you shouldn't use Fanboy’s Annoyance List.

**Comment by adranger** [comment]
@THEtomaso valid login buttons aren't annoyances, and are whitelisted accordingly by this list.

**Comment by THEtomaso** [comment]
Well, they're annoyances in my book.
Third party logins is a nasty business, especially when they're social media!
