### ISSUE TITLE
coeffee.com

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#509]
`https://coeffee.com/login`

### What happens?

**Fanboy’s Annoyance List** hides login options.

### Your settings

- Browser/version: Firefox 61.0.1
- Adblock Extension/version: uBlock Origin 1.16.14

**Comment by THEtomaso** [comment]
It only hides the third party social logins.
In other words; the filter works as intended!

**Comment by adranger** [comment]
@THEtomaso valid login buttons aren't annoyances, and are whitelisted accordingly by this list.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a13cff34a5d22af079183723b12d04f77fe91dd0
