### ISSUE TITLE
stackoverflow.com missing button images

### ISSUE THREAD

**Issue by Bluscream** [ryanbr/fanboy-adblock#51]
![image](https://cloud.githubusercontent.com/assets/3318223/20063034/12dc7846-a506-11e6-8465-3fcb27ac1f51.png)
```
URL:                 https://cdn.sstatic.net/img/share-sprite-new.svg?v=78be252218f3
Source:              cdn.sstatic.net
Data type:           Image
Rule:                Fanboy's Annoyances:
                     /share-sprite-
```
![image](https://cloud.githubusercontent.com/assets/3318223/20063073/32b97d12-a506-11e6-80c2-c5f277bffc4a.png)

**Comment by ryanbr** [comment]
Already fixed here?

[code]
@@/share-sprite-$domain=askubuntu.com|mathoverflow.net|serverfault.com|stackapps.com|stackexchange.com|stackoverflow.com|superuser.com
[/code]

**Comment by Bluscream** [comment]
Hmm when was the fix applied?

**Comment by SMed79** [comment]
> Hmm when was the fix applied?

Manually update your filterlist https://adblockplus.org/faq_basics#update-filterlists
or wait 4 days, see the header of the list `! Expires: 4 days (update frequency)`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/41468acdd

~2014.

**Comment by Bluscream** [comment]
Hmm why does it get blocked then...

**Comment by ryanbr** [comment]
Still unable to reproduce this, safe to close unless provided with more info.
