### ISSUE TITLE
wrong domain still in your lists

### ISSUE THREAD

**Issue by ronkol** [ryanbr/fanboy-adblock#511]
https://github.com/ryanbr/fanboy-adblock/blob/1041192a5f2525f769bef5f324293e44cfa4524e/fanboy-problematic-sites.txt#L83

hi, Thanks for removing our domain from enhancedstats-addon.txt list but player.h-cdn.com still appears in fanboy-problematic-sites.txt and we were pointed to this list directly from anti-virus companies that added domains from it (including ours) into their blacklist.

Please remove it,
thanks

**Comment by smed79** [comment]
Post on the existing thread https://github.com/ryanbr/fanboy-adblock/issues/497

**Comment by ronkol** [comment]
i did, 2 days ago, and didnt get any response.

**Comment by smed79** [comment]
> Some days or weeks I have more time to work on it, other days I don't.

https://forums.lanik.us/viewtopic.php?p=66878#p66878

**Comment by ryanbr** [comment]
Not worth responding if you don't know how to update a list.
