### ISSUE TITLE
oantagonista.com

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#514]
### List the website(s) you're having issues:

Major political blog in Brazil:

`https://www.oantagonista.com/brasil/amor-e-briga-no-rodoanel/`

### What happens?

Share buttons at the top of the post and a floating Messenger/ManyChat button at the bottom right as you scroll down.

### List Subscriptions you're using:

Fanboy’s Annoyance List.

- Browser/version: Firefox 61.0.1 
- Adblock Extension/version: uBlock Origin 1.16.14

**Comment by krystian3w** [comment]
`##.share`
`###buttonopenmannychat`
`###backtotop`
