### ISSUE TITLE
Adding 'related videos', 'recommended articles', subscription prompts, etc to Annoyances list

### ISSUE THREAD

**Issue by prodan1234** [ryanbr/fanboy-adblock#515]
"Related videos", "recommended articles", "more on this topic", "subscribe here!", "join our newsletter",  infinite scrolling, slideshows, polls and unrelated videos on a web page are a distraction and should be blocked by the Annoyances filter.

Example webpages: 
`https://www.newyorker.com/magazine/2018/08/06/private-dreams-and-public-ideals-in-san-francisco`
`https://money.cnn.com/2018/08/05/media/jeff-fager-cbs-vacation/`
`https://www.vanityfair.com/news/2018/07/inside-the-trump-2020-campaigns-disorganized-attempt-to-keep-america-great`
`https://www.wired.com/story/tesla-self-driving-car-computer-chip-nvidia/`
`https://www.cnet.com/news/sorry-but-your-iphone-or-android-phone-is-going-to-get-even-more-expensive/`
`https://www.rollingstone.com/politics/politics-news/nra-financial-trouble-706371/`
`https://news.avclub.com/fx-head-says-marvel-killed-off-donald-glovers-deadpool-1828106301`
`https://www.theverge.com/2018/8/5/17648524/colony-cancelation-dystopia-usa-network-carlton-cuse-rip`

Screenshots:
https://imgur.com/a/QiM2bPx 

List Subscriptions I'm using:
Easy List, Easy Privacy, uBlock lists

- OS/version: macOS 10.13.6
- Browser/version: Chrome 68.0.3440.84
- Adblock Extension/version: uBlock Origin 1.16.14

**Comment by adranger** [comment]
If you want to remove everything but the main content, use a "Reader" extension (or the built-in feature included by Firefox).

Do not ask for the list maintainer to remove relevant content and features that may be used by other people. Also, never start threads about multiple different issues on any repository.

**Comment by ryanbr** [comment]
Update your subs, most of the pages look fine?
