### ISSUE TITLE
ITavisen.no - Embeded videos blocked (Fanboy's Enhanced Tracking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#519]
### Affected site:
`https://itavisen.no/`

### Issue:
Embeded videos are blocked.

### Problem filter:
Fanboy's Enhanced Tracking List

### Problem rule:
`/cdn-cgi/apps/head/*$script,~third-party`

### Screenshot (unblocked video):

![filterissue-itavisen3](https://user-images.githubusercontent.com/9382674/43742222-9e7fa8fe-99c0-11e8-8341-939c81328039.jpg)

### Possible fix:
`@@/cdn-cgi/apps/head/$first-party,script,domain=itavisen.no`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by ryanbr** [comment]
Is that an embedded video ad?

**Comment by THEtomaso** [comment]
No, it's not an ad.

**Comment by THEtomaso** [comment]
Yes, I gave it a "thumbs up". :)
I've added that rule to my personal filter, but that's just to prevent the video from becoming a "page floater".

But the rule found in **Fanboy's Enhanced Tracking List** (which this issue report is about) blocks the videos all together!

**Comment by THEtomaso** [comment]
The current video, on their front page, plays just fine with the blocking rule in place.
Things have either been changed server-side, or it may depend on which video they're showcasing.

**Comment by ryanbr** [comment]
I'm not seeing it, even with the suggested whitelist.
