### ISSUE TITLE
Blocks photos in newegg emails

### ISSUE THREAD

**Issue by jusitnboggs** [ryanbr/fanboy-adblock#52]
its blocking almost everything in neweggs emails

**Comment by SMed79** [comment]
Some more details & how to reproduce ? Submit an Adblock plus [issue report](https://adblockplus.org/en/getting_started#false-positives) then post the link here.

**Comment by ryanbr** [comment]
I did remove a test filter https://github.com/ryanbr/fanboy-adblock/commit/4526007d7fbe502f5da8d6436a6e26dff47c0ad7  But without more details of the issue I cant confirm its fixed.

**Comment by ryanbr** [comment]
No response, Closing ticket.
