### ISSUE TITLE
Cookie banner not blocked: elektrotresen.de, steckdosenleiste.org, jesus.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#523]
### List the website(s) you're having issues: 

`https://www.elektrotresen.de/` 
`https://www.steckdosenleiste.org/` 
`https://www.jesus.de`

### What happens? 
Cookie banner not blocked

### List Subscriptions you're using:

Fanboy's Cookiemonster List

### Your settings

- OS/version: win7 (64bit)
- Browser/version: FF v56.0.2
- Adblock Extension/version: uBlock Origin 1.16.14

**Comment by ryanbr** [comment]
Cheers, submit any others missing.
