### ISSUE TITLE
FranceTVinfo.fr 

### ISSUE THREAD

**Issue by CaptainLol** [ryanbr/fanboy-adblock#525]
### What happens?
Popup message for subscribing to newsletters or alerts : 
I suggest to block  : `<divclass="newsletterSubBlock">` 

### List Subscriptions you're using:
 Liste FR+EasyList 
 Fanboy's Annoyance List 

### Your settings:
- OS/version: Windows 7
- Browser/version: Firefox 61.0.2 (64 bits)
- Adblock Extension/version: Adblock Plus 3.2

**Comment by smed79** [comment]
```
/js/cnil-
```
```
://newsletters.
/newsletter/popin/*
##.newsletterSubBlock
```
