### ISSUE TITLE
animetake.tv

### ISSUE THREAD

**Issue by runboy93** [ryanbr/fanboy-adblock#526]
https://fanboy.co.nz/r/fanboy-ultimate.txt

`@@||animetake*.pro^$generichide` is not used anymore.

They use now `animetake*.stream`

such as https://animetake4.stream/watch/nanatsu-no-taizai-imashime-no-fukkatsu-episode-22/

**Comment by krystian3w** [comment]
`@@||animetake*.*^$generichide` - should works in uBO, but not in AdBlock / Adblock Plus / AdGuard.

**Comment by smed79** [comment]
> not in AdBlock / Adblock Plus

ticket https://issues.adblockplus.org/ticket/6773

**Comment by runboy93** [comment]
> `@@||animetake*.*^$generichide` - should works in uBO, but not in AdBlock / Adblock Plus / AdGuard.

Yeah thanks for filter, I need add it manually.

**Comment by ryanbr** [comment]
animetake4.stream dead?

**Comment by runboy93** [comment]
Currently pages are:

https://animetake13.stream/watch/grand-blue-episode-6/

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/669a57c591273fadfddcb19798eba1995fc58bcd
