### ISSUE TITLE
Overflow "pop-ups"

### ISSUE THREAD

**Issue by SEXXES** [ryanbr/fanboy-adblock#527]
https://de.statista.com

==>

![exp](https://user-images.githubusercontent.com/42209961/44163907-f2107880-a0c4-11e8-9cd9-8eb0056bf196.jpeg)
(meaning the overflow "pop-up")

https://tsri.ch/zh/wie-sehen-dann-diese-kinder-aus/

==>

![expi](https://user-images.githubusercontent.com/42209961/44163994-2c7a1580-a0c5-11e8-831c-1f4e36171aaf.jpeg)
(meaning the overflow "pop-up")

Im generally very pissed off by all these (I don't know the name but I call them) overflow "pop-ups" asking to sing-in for a news-letter, whatever (often I ALREADY have their fucking news-letter so why bother again asking....?)

Sometimes its only on the landing-page but often (and more and more) on every site you click… as I delete cookies often, im getting these flags also very often.

### List Subscriptions you're using:

![filters](https://user-images.githubusercontent.com/42209961/44164366-259fd280-a0c6-11e8-8eeb-23aadd8d4ada.jpeg)

### Your settings

 makes no difference… :/

- OS/version: 10.13.6
- Browser/version: Chrome Version 68.0.3440.106 but the same on FF…
- Adblock Extension/version: µBlock 1.16.14

**Comment by krystian3w** [comment]
`tsri.ch##.please`
`tsri.ch##.no-member:style(overflow: visible !important;)`

I do not have newsletter on `de.statista.com`

**Comment by krystian3w** [comment]
`tsri.ch##.please` 
 or:
`tsri.ch##.no-member > .please`
+
`tsri.ch##.no-member:style(overflow: visible !important;)` (unlock scroll if hidden)

---

I do not have newsletter on `de.statista.com` and no analyze on websites for "easier/simpler" blocking.

**Comment by ryanbr** [comment]
Couldn't see the first one, then 2nd one would require a ubo filter (not included in Easylist hosted)

**Comment by SEXXES** [comment]
so where do I have to report to add it on a filter?
i found some more, its getting very annoying!! im also using the extension called "I don't care about cookies" but it doesn't seem to work properly eather....

so I understand that this threat is closed, what do you want me to do?

1) open new threats, if so: WHERE?

2) open threat ALL (problem found) TOGETHER or one by one?

wikipedia calls the problem i mentioned "Layer ad"

there are different variations:

a) asking to sign-up for newsletters
b) just ads...
c) cookie warning due to new DSGVO laws
d) asking to switch off ad blockers...

THEN there's a new upcoming challenge form companies like:

https://www.smartwall.ai

![stupidwall 2](https://user-images.githubusercontent.com/42209961/44655626-1db12e00-a9f6-11e8-9a17-a5ea94530d76.jpeg)


If you go to https://medienwoche.ch your immeaditly redirected to https://medienwoche.ch/adblocker/

also
zentralplus.ch
omr.com
![exp 2](https://user-images.githubusercontent.com/42209961/44655670-446f6480-a9f6-11e8-8d7d-a0edbfc90aa2.jpeg)

![zentralplus ch 2](https://user-images.githubusercontent.com/42209961/44655682-4c2f0900-a9f6-11e8-9343-c19912694a11.jpeg)

and, as already mentioned, statista.com (need to wait some seconds)

**Comment by SEXXES** [comment]
smartwall.ai

asks you to watch a video (ad) bevor you can access the content, so there needs to be a more sophisticated filter…

**Comment by krystian3w** [comment]
> so where do I have to report to add it on a filter?

<ul>

If scroll is blocked, and no possible recover/unlock scroll by block `inline script` (**bad idea**) or `script file`, `css file`  / `xhtmlrequest` or something else compatiblode with adblock plus syntax, maybe should report to [uBlockOrigin/uAssets](/uBlockOrigin/uAssets/issues).

Later activate list `uBlock filters – Annoyances`  (most likely, there would be added rules cutting out difficult pop-ups)


![image](https://user-images.githubusercontent.com/35370833/44656179-36224800-a9f8-11e8-9523-bcb944532874.png) |
--- |

You can also try to report to AdGuard Team - although the patch will not necessarily be compatible with uBlock Origin (eg when fix with a simple script - then you would need to see how much you can transfer to the injection script rule uBlock Origin)

</ul>

----

> im also using the extension called "I don't care about cookies" but it doesn't seem to work properly eather....

<ul>

Try reporting websites them with the right mouse button - the extension has this function, maybe the author will pick up the "error" and fix it when updating addon.

If not, you should send an e-mail to the author with more detailed information.

</ul>

---


> If you go to https://medienwoche.ch your immeaditly redirected to https://medienwoche.ch/adblocker/

<ul>

[uBlockOrigin/uAssets](/uBlockOrigin/uAssets/issues) - this antiadblock it looks unreported _or there is no solution for it yet._

</ul>

**Comment by SEXXES** [comment]
thank you all, seems like the filters now have been updated… works almost everywhere about what I reported…

where should I report new "bugs", here again or open a new thread?

heres a site full of ads:

https://www.wieistmeineip.ch

**Comment by SEXXES** [comment]
![example](https://user-images.githubusercontent.com/42209961/45001521-f9dd8180-afcd-11e8-8f51-0323a71fd5df.jpeg)
seems like there'r new inline ad's, all coming from img.advertate.com
