### ISSUE TITLE
smplayer.info

### ISSUE THREAD

**Issue by anewuser** [ryanbr/fanboy-adblock#528]
After you finish installing a new version of [SMPlayer](https://www.smplayer.info/) , it launches your browser automatically with a URL like `http://www.smplayer.info/post-install.php?version=18.6.0`. The option to disable this behavior [has been removed on version 17.12](https://forum.smplayer.info/viewtopic.php?p=17024&f=2#p17024).

I suggest adding `||smplayer.info/post*$document` to **Fanboy’s Annoyance List**.

uBlock Origin 1.16.16
Firefox 61.0.2 (64-bit)

**Comment by ryanbr** [comment]
Not sure if an adblock should consider? If you want it, send an example page (outside of smplayer.info), then it'll be re-looked at.
