### ISSUE TITLE
abril.com.br

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#529]
### List the website(s) you're having issues:

`https://super.abril.com.br/historia/como-um-oficial-nazista-jogou-o-brasil-na-segunda-guerra-mundial/`
`https://exame.abril.com.br/brasil/onu-decide-que-lula-deve-ter-todos-os-direitos-politicos-mesmo-que-preso/`

### What happens?

Sharing bar on the left.

### List Subscriptions you're using:

**Fanboy’s Annoyance List**.

- OS/version:  Windows
- Browser/version: Firefox 61
- Adblock Extension/version: uBlock Origin 1.16.16

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/13ed4c3e29af612f7027f3706ea8bc39fc9aa72f
