### ISSUE TITLE
Cookie consents

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#534]
Few cookie consents:

```
www.betterads.org###wpcui_cookie_bar_main_body
www.worldstream.nl###cookie_prefs_bumper
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d3f81eb6de68b7a5d6c96afd48b20b8b2b4e3577
https://github.com/easylist/easylist/commit/1596f73995bb2e89d878b6feee9dfda5ce1719d0
