### ISSUE TITLE
vidcloud.co

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#535]
### List the website(s) you're having issues:

`https://vidcloud.co/v/5b85a572c4db9`

### What happens?

broken page

![2018-08-29-hdc55906ebefa027cae3e3ac31057bab8206934f0f44338c0df3c7b2d84cb5348a mp4 _ vidclou](https://user-images.githubusercontent.com/5884000/44765594-b5795e00-ab55-11e8-97f2-7df7c9ba6cf7.png)

### List Subscriptions you're using:

<details><summary>ubo settings</summary>

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

</details>

### Your settings

- OS/version: w10
- Browser/version: chr 68.0.3440.106
- Adblock Extension/version: ubo 1.16.18

### Other details:

Fanboy’s Annoyance List
Fanboy’s Social Blocking List

**Comment by smed79** [comment]
for the popup, add
```
||vidcloud.co/js/lib/script.js
||vidcloud.co/js/lib/license.js
```
