### ISSUE TITLE
zukxd6fkxqn redirect

### ISSUE THREAD

**Issue by runboy93** [ryanbr/fanboy-adblock#536]
kissanime.ru website has redirect by "zukxd6fkxqn.com" domain, ads seem to blocked as shows only Google.ico as placeholder, but I think popup itself is annoing and should be blocked.

http://kissanime.ru/

popups from that domain already blocked, but for some reason, still shows popup.

Only thing that is not blocked is this css:

`http://zukxd6fkxqn.com/libs/select2-bootstrap-theme/1.61.61/select2-bootstrap-theme.min.css`

**Comment by runboy93** [comment]
`||zukxd6fkxqn.com/libs/select2-bootstrap-theme/1.61.61/select2-bootstrap-theme.min.css$stylesheet`

Made this for test, and seem to work. It might still show popup, but not so aggressive as earlier.

**Comment by smed79** [comment]
```
||kissanime.ru^$subdocument
$stylesheet,third-party,domain=kissanime.ru
```

**Comment by runboy93** [comment]
uBO logger still shows this as not blocked:

`css	http://zukxd6fkxqn.com/libs/select2-bootstrap-theme/1.61.61/select2-bootstrap-theme.min.css`

**Comment by smed79** [comment]
Adblock Plus 

![https://i.imgur.com/ZcsO6hc.png](https://i.imgur.com/ZcsO6hc.png)
uBo

![https://i.imgur.com/PU5TyGy.png](https://i.imgur.com/PU5TyGy.png)

**Comment by runboy93** [comment]
Ah, sorry. it looks like I put filter wrong way xD I'm quite newbie with these stuff. Solved.
