### ISSUE TITLE
Cookie banner not blocked: bioapotheke.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#537]
### List the website(s) you're having issues: 
`https://www.bioapotheke.de/`

### What happens? 
Cookie banner not blocked

### List Subscriptions you're using:

Fanboy’s Cookiemonster List

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.20

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5c79587bdfc5a346cefaccd33c69c95af060d4b3
