### ISSUE TITLE
Hide non-responsive email

### ISSUE THREAD

**Issue by davidhedlund** [ryanbr/fanboy-adblock#54]
@ryanbr said:
> Personally I only read the issues via my personal git repo and the forums. I can't say much for the emails. fanboyadblock@googlegroups.com is defunct.

"author fanboynz <easylist.subscription+fanboy@gmail.com>" appear on hd.adblockplus.org, for example https://hg.adblockplus.org/easylist/rev/ec5112596c17

I've wasted my time to report to this source too. Can you please do something about it?

You can for example automatically bounce a email message to senders that says "Personally I only read the issues via my personal git repo and the forums".

**Comment by ryanbr** [comment]
This should now be fixed, https://github.com/ryanbr/fanboy-adblock/commit/8b01841dfbef57e7be59be4e1f1f12bfb4e06dcc

**Comment by davidhedlund** [comment]
@ryanbr That's about time. Thank you.

**Comment by davidhedlund** [comment]
@ryanbr Why didn't you add
> Reporting Issues: https://github.com/ryanbr/fanboy-adblock/issues

to most of the filters like chrome://ublock0/content/asset-viewer.html?url=https://www.fanboy.co.nz/fanboy-swedish.txt ?

**Comment by davidhedlund** [comment]
@ryanbr said:
> Personally I only read the issues via my personal git repo and the forums. I can't say much for the emails. fanboyadblock@googlegroups.com is defunct.

"author fanboynz <easylist.subscription+fanboy@gmail.com>" appear on hd.adblockplus.org, for example https://hg.adblockplus.org/easylist/rev/ec5112596c17

Can you please remove your email or hide it from there?

**Comment by ryanbr** [comment]
I can't remove it elsewhere.

**Comment by davidhedlund** [comment]
@ryanbr Ok.

@ryanbr Why didn't you add
> Reporting Issues: https://github.com/ryanbr/fanboy-adblock/issues

to language specific filters like https://www.fanboy.co.nz/fanboy-swedish.txt as you did for the rest of the files in https://github.com/ryanbr/fanboy-adblock/commit/8b01841dfbef57e7be59be4e1f1f12bfb4e06dcc?

There is no way for their users to know where to submit issues.

**Comment by ryanbr** [comment]
The regional lists have been depreciated, ie unsupported.

**Comment by davidhedlund** [comment]
@ryanbr A better term than "Officially unsupported" is "Deprecated" or "Discontinued". What do you think?

**Comment by davidhedlund** [comment]
Files in https://github.com/easylist/easylist/tree/master/easylistfanboy contain a invalid email

See "Email: fanboyadblock @ googlegroups . com Project homepage: http://fanboy.co.nz/" in https://github.com/easylist/easylist/blob/master/easylistfanboy/other/tracking-intl.txt for example.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
@ryanbr I'm not arguing with you, but can you please fix the [issue](https://github.com/ryanbr/fanboy-adblock/issues/54#issuecomment-280903486)?

**Comment by davidhedlund** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/53

**Comment by ryanbr** [comment]
Cant be fixed.  **"I can't remove it elsewhere."** as stated.

**Comment by davidhedlund** [comment]
@ryanbr What do you mean, the email is down.

Are you saying that I must contact the owner of https://github.com/easylist/easylist/ to remove it?
