### ISSUE TITLE
translate.google.com

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#541]
### List the website(s) you're having issues:

`https://translate.google.com/#auto/en/%EC%8B%9C%EB%AF%BC`

### What happens?

Chrome annoyance at the top when using Firefox.

![screeshot](https://user-images.githubusercontent.com/35470489/44961218-c1fa0f80-aee3-11e8-80a0-ecb1a01c043c.png)

### List Subscriptions you're using:

EasyList/EasyPrivacy + Fanboy’s Annoyance List

- OS/version: Windows 10
- Browser/version: Firefox 61.0.2 (64-bit)
- Adblock Extension/version:  uBlock Origin 1.16.20

**Comment by ryanbr** [comment]
Does this help?

`google.com##gb[style="min-width: 750px;"]`

**Comment by adranger** [comment]
That includes the "Sign In" row. 

`translate.google.com##.gb_g` hides the blue bar to me.

**Comment by ryanbr** [comment]
##.gb_g.gb_Xc.gb_yd

**Comment by smed79** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/631
