### ISSUE TITLE
telepolis.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#544]
### List the website(s) you're having issues:

`https://www.telepolis.pl/wyszukiwarka?q=facebook`

### What happens?

Fanboy's Social Blocking List hides miniature image of post.

### List Subscriptions you're using:
![screenshot_20180902_133837](https://user-images.githubusercontent.com/19818572/44955558-847e8d80-aeb5-11e8-9b5b-2ef17dfcf7e8.png)

### Your settings

- OS/version: Manjaro 17.1.12 Hakoila
- Browser/version:  Vivaldi 1.15.1147.64
- Adblock Extension/version: Nano Adblocker v1.0.0.66

### Other details:

Solution => `@@||www.telepolis.pl/media/cache/resolve/content_box/images/miniatury/Facebook_logo_1.png`
Before
![screenshot_20180907_220820](https://user-images.githubusercontent.com/19818572/45240893-8d72c300-b2ea-11e8-8385-d82942cb1838.png)

After
![screenshot_20180907_220730](https://user-images.githubusercontent.com/19818572/45240859-6e743100-b2ea-11e8-9554-6f826d33e2e5.png)

https://github.com/MajkiIT/polish-ads-filter/issues/8779

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f1640af904f3a5f39ead23e9e0a3aa752a4d2a60
