### ISSUE TITLE
freecharge.in displays just a blank page

### ISSUE THREAD

**Issue by in4u** [ryanbr/fanboy-adblock#545]
### List the website(s) you're having issues:

`https://www.freecharge.in`

### What happens?

Just a blank page is displayed.

### List Subscriptions you're using:

uBlock Origin filters list: "plowe-0", "mvps-0", "hphosts", "dpollock-0", "fanboy-cookiemonster", "adguard-annoyance", "fanboy-enhanced", "easyprivacy", "adguard-spyware", "easylist", "adguard-mobile", "adguard-generic", "ublock-unbreak", "ublock-abuse", "ublock-privacy", "ublock-annoyances", "ublock-filters"

### Your settings

- OS/version: Windows 7 SP1
- Browser/version:  Firefox 62.0
- Adblock Extension/version: uBlock Origin 1.16.20

### Other details:

The site loads normally after disabling Fanboy's Enhanced Tracking List filter in uBlock Origin.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/d31315ed9b71f0337b464a1fba7b01e94b9abcb1
