### ISSUE TITLE
openpli.org

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#546]
### List the website(s) you're having issues:

`https://forums.openpli.org/`

### What happens?

Rule `openpli.org##div[style^="background-color:#FF9595;"]` in Fanboy's Cookiemonster causes some bug. If i go to forum, then log in, then I got redirected to openpli.org, cuz I didn't accepted cookies and if I go again to forum, then there is the same and I can't accept it, cuz Cookiemonster ate it :smile:. It can be fixed on uBO/Nano, but not on AdBlock/ABP, so you should probably remove that :smile:.

### List Subscriptions you're using:
Fanboy's Cookiemonster

### Your settings

- OS/version: Manjaro 17.1.12 Hakoila
- Browser/version: Vivaldi 1.15.1147.64
- Adblock Extension/version: Nano Adblocker v1.0.0.66

**Comment by ryanbr** [comment]
test login?

**Comment by hawkeye116477** [comment]
You can see on source of forum, inline script with function that redirects. That should be enough :smile:.

```

<script>
function euReadCookie(name) {
	var nameEQ = name + "=";
	var ca = document.cookie.split(';');
	for(var i=0;i < ca.length;i++) {
		var c = ca[i];
		while (c.charAt(0)==' ') c = c.substring(1,c.length);
		if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
	}
	return null;
}
if (! euReadCookie('gdpr-accepted') && euReadCookie('coppa')) {
	window.location.replace('https://openpli.org');
}
</script>
```

**Comment by smed79** [comment]
> test login?

sent via email to `mp3geek`
