### ISSUE TITLE
miuipro.info

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#549]
### List the website(s) you're having issues:
`https://miuipro.info/roms/`

### What happens?
Fanboy's Social hides roms.

### List Subscriptions you're using:

<img src="https://user-images.githubusercontent.com/19818572/44955558-847e8d80-aeb5-11e8-9b5b-2ef17dfcf7e8.png">

### Your settings

- OS/version: Manjaro 17.1.11 Hakoila
- Browser/version:  Vivaldi 1.15.1147.64
- Adblock Extension/version: Nano Adblocker v1.0.0.66

### Other details:
Solution => `@@||miuipro.info/wp-content/plugins/easy-vkontakte-connect/js/social-likes.min.js`

Before:
![screenshot_20180910_143705](https://user-images.githubusercontent.com/19818572/45298011-76f58300-b507-11e8-876a-c51c771d7487.png)

After:
![screenshot_20180910_144114](https://user-images.githubusercontent.com/19818572/45298039-94c2e800-b507-11e8-915e-9223a37f8bdb.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/18d32413beb955ac66fee9ee59e75260185134c5
