### ISSUE TITLE
Whitelist images whose filenames contain '-social-media'?

### ISSUE THREAD

**Issue by zanetu** [ryanbr/fanboy-adblock#55]
Example: 
http://i2.cdn.cnn.com/cnnnext/dam/assets/161112192101-trump-60-minutes-social-media-overlay-tease.jpg

CNN homepage screenshot: 

![social](https://cloud.githubusercontent.com/assets/3144970/20243780/0417879c-a934-11e6-9bad-bf09399316fd.jpg)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/554a6ac45dfa719a646ca38059f1ba996167f161
