### ISSUE TITLE
de.wikipedia.org

### ISSUE THREAD

**Issue by dschuessler** [ryanbr/fanboy-adblock#551]
### List the website(s) you're having issues:

`de.wikipedia.org`

### What happens?

I can't scroll down.

### List Subscriptions you're using:

![bildschirmfoto 2018-09-11 um 10 27 08](https://user-images.githubusercontent.com/5774545/45347839-4d8f3280-b5ad-11e8-8b4b-5b45e7d1e0f7.png)

### Your settings

- OS/version: macOS 10.13.6
- Browser/version: Firefox 62.0
- Adblock Extension/version: uBlock Origin 1.16.20

### Other details:

Turning off the fanboy annoyance list shows a full screen Wikipedia overlay I suspect to be the cause. It will most certainly be gone with the EU referendum tomorrow.

![bildschirmfoto 2018-09-11 um 10 30 00](https://user-images.githubusercontent.com/5774545/45348028-cd1d0180-b5ad-11e8-909f-58e7e08f8229.png)

**Comment by ryanbr** [comment]
Does these filters help? or not cause false positives..

```
#@##centralNotice
||de.wikipedia.org/w/load.php$script
```

**Comment by dschuessler** [comment]
Adding these filters fixes the scrolling issue.

**Comment by Lomanic** [comment]
This filter is too broad and breaks many things (all JS?) on Wikipedia while logged in:

- can't switch between panels in the [[Special:Preferences]] page
- unable to load custom JS defined in [[Special:Preferences#mw-prefsection-rendering]]

Added the following filter to rollback

```
@@||wikipedia.org/w/load.php$script,first-party
```

**Comment by pkrasimirov** [comment]
Yeah, that was a site-breaking filter.  The initial script loading for Wikipedia does far more than just prevent scrolling.  Please revert.

**Comment by Hasshu** [comment]
Apparently, it also breaks search suggestions on Wikipedia.

**Comment by pkrasimirov** [comment]
Thanks for the quick response.  When can this be seen in effect?  https://www.fanboy.co.nz/r/fanboy-ultimate.txt still contains it.

**Comment by smed79** [comment]
> When can this be seen in effect?

Check the header of the filter list => ` Expires: ...`
