### ISSUE TITLE
Cookie banner not blocked: omr.com/de/

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#554]
### List the website(s) you're having issues: 
`https://omr.com/de/`

### What happens?
Cookie banner not blocked

### Your settings

- OS/version: win7 (64bit)
- Browser/version: firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.16.20

**Comment by ryanbr** [comment]
```
omr.com##body:style(overflow: auto !important;)
omr.com###dsgvoModal
omr.com##.modal-backdrop
```

I can't add these because it'll break ABP. but you're free it add them manually.
