### ISSUE TITLE
Cookie banner not blocked: pschyrembel.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#559]
### List the website(s) you're having issues:
`https://www.pschyrembel.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using: 
Fanboy’s Cookiemonster List​ 

### Your settings

- OS/version: win7 (64bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock origin 1.16.20

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7b968beb42aba4ae7b809bfea2012ef5acf7edb1
