### ISSUE TITLE
Please whitelist `surveygizmo.com^$third-party` for `qsurvey.mozilla.com`

### ISSUE THREAD

**Issue by Retia-Adolf** [ryanbr/fanboy-adblock#560]
### List the website(s) you're having issues:

`https://qsurvey.mozilla.com/s3/devpanels`

### What happens?

The rule `||surveygizmo.com^$third-party` triggered on the problem site, then the stars rating on the page would not working until I unsubscribed the following list ↓

### List Subscriptions you're using:

`Fanboy's Annoyance List`

### Your settings

- OS/version: Windows 10 1803
- Browser/version: Firefox Developer Edition 63.0b8 (64bit)
- Adblock Extension/version: uBlock Origin 1.16.20

### Other details:

![image](https://user-images.githubusercontent.com/34053927/45925329-fcead400-bee0-11e8-81c3-5ff54146334c.png)

**Comment by Retia-Adolf** [comment]
@smed79  I've searched for this. And it seems Fanboy allows adding a whitelist rule for this kind of domain for specific sites.
https://forums.lanik.us/viewtopic.php?f=64&t=23016

**Comment by smed79** [comment]
Old obsolete filter.

**Comment by Retia-Adolf** [comment]
@smed79 ? Searched for 'whitelist' in *current* filter list:
```
! *** easylist:fanboy-addon/fanboy_annoyance_whitelist.txt ***
@@/nk-sub.min.js$script,~third-party
@@/rutorrent/plugins/rss/*$image,~third-party
@@||adfoc.us/*/interstitial.js$~third-party
@@||amazonaws.com/downloads.mailchimp.com/js/mc-validate.js$domain=awal.com|bil24.no|blissneso.com|cnn.com|cover-up.com|eskuvo-kiallitas-osz.hu|fairprice.co.za|genuine-people.com|justrunlah.com|kliknijwzdrowie.pl|makewarnotlove.com|monetarywatch.com|nikopik.com|nowfoods.com|nyt.fi|propublica.org|sanbs.org.za|thegolfnewsnet.com|truenutrition.com
@@||amazonaws.com^*/feedback-v2.js?$domain=avgthreatlabs.com
@@||bestof.s3.amazonaws.com/twitter.png$domain=makeuseof.com
@@||bing.net/videos/thumbnail.aspx?$domain=bing.com
@@||blogsmithmedia.com^*/sailthru-newsletter.js?
@@||britishairways.com/cms/global/scripts/pages/interstitial.js
@@||buttons.reddit.com^$domain=redditstatic.com
@@||cdn.complexmedianetwork.com/cdn/$script,subdocument,domain=kicksonfire.com
@@||chip.de^*/outbrain.js
@@||chobani.com/js/views/newsletter-signup.js
@@||complexmedianetwork.com/js/cmnUNT.js
@@||config.parsely.com/config/$script,domain=dailystar.co.uk|express.co.uk
@@||disqus.com^*/social-icons.png
@@||ebuddy.com/website/*social-icons.png
@@||ecache.vzw.com/imageFiles/Myacct/*/onlineopinionV5/
@@||egmnow.com/wp-content/plugins/egm-interstitial/js/interstitial.js
@@||elance-odesk.com/marketing-ui/master/js/interstitial.js
@@||energytribune.com/wp-content/plugins/bwp-minify/*shareaholic
@@||examiner.com/sites/all/modules/custom/ex_omniture/s_code.js
@@||expedia.*/opinionlab/oo_engine.js$script
@@||footy-boots.com/wp-content*/comment-reply.js
@@||georiot.com/snippet.js$domain=bound2hiphop.com
@@||google.com/friendconnect/$script,domain=blogspot.com

(....)
```

Adding a rule `@@||surveygizmo.com^$script,domain=qsurvey.mozilla.com` does no harm because it's in effect only when you access a domain that ONLY used for surveying.

OK, maybe I should make a PR by myself now that I've searched all things about this issue and tried explaining why it does no harm...

**Comment by smed79** [comment]
Wait @ryanbr to check and decide what to do.

**Comment by ryanbr** [comment]
Ideally I just want to block the 3rd party scripts loaded by these sites, rather than block legit uses. I'd prefer to fix the blanket surveygizmo rule, but since its no longer working I'll use a whitelist.
