### ISSUE TITLE
ourl.io

### ISSUE THREAD

**Issue by bup4gr** [ryanbr/fanboy-adblock#567]
Has you can read
https://github.com/uBlockOrigin/uAssets/issues/3559
https://github.com/uBlockOrigin/uAssets/issues/3570
there is a preblem with this filter `@@/js/ads.js$script` on `ourl.io`

Can you modify the filter to resolve the problem?

**Comment by ryanbr** [comment]
I won't change it, but I've fixed it another way:

https://github.com/ryanbr/fanboy-adblock/commit/813ac28d2b002fa05029550ce78abf4b417cf6b0
