### ISSUE TITLE
Blocking mc-validate.js breaks page render (10yearhose.com)

### ISSUE THREAD

**Issue by injust** [ryanbr/fanboy-adblock#568]
### List the website(s) you're having issues:
- `https://10yearhose.com/register/`
- `https://www.canadianfreestuff.com/` (affects images on most pages)

### What happens?
`https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js` is blocked, leading the page to fail to render.

### List Subscriptions you're using:
- Fanboy Annoyances List

### Other details:

Rule in question is `/downloads.mailchimp.com/*`.
There exists a whitelist rule `@@||amazonaws.com/downloads.mailchimp.com/js/mc-validate.js`, but only for specific domains.

I strongly suggest whitelisting this file globally, instead. It seems to be a common script for signup forms, and blocking it breaks page rendering catastrophically.
This specific resource has repeatedly been an issue for me, across multiple sites.

**Comment by ryanbr** [comment]
Has been removed
