### ISSUE TITLE
Wix site completely blocked

### ISSUE THREAD

**Issue by borisb13** [ryanbr/fanboy-adblock#57]
I have a website that's hosted on Wix, and it's being completely blocked when this filter list is enabled. The website it www.acsteel.net

**Comment by SMed79** [comment]
needed filter:
`@@||static.parastorage.com/services/santa/*/packages-bin/rssButton/rssButton.min.js$script`

**Comment by borisb13** [comment]
That's not a solution -- you're telling me how to unblock it in my browser, but my I'm talking about the fact that any user that has this filter enabled aren't able to view that website (and, I assume, a lot of other websites on Wix).

**Comment by SMed79** [comment]
Wait the list author see this issue and decide what to do.
... or try reporting at **easylist forum** https://forums.lanik.us/viewforum.php?f=64

**Comment by Uricorn** [comment]
Reported the issue here: https://github.com/easylist/easylist/commit/7f16b3c7ed546ee2067feaa3a2a8e49a23c913dd
