### ISSUE TITLE
revistaforum.com.br

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#570]
### List the website(s) you're having issues:

`https://www.revistaforum.com.br/vinte-reitores-e-ex-reitores-de-universidades-federais-declaram-apoio-a-haddad/`

### What happens?

An overlay covers everything.

### List Subscriptions you're using:

Fanboy's Annoyance list.

### Your settings

- Browser/version: Firefox 62
- Adblock Extension/version: uBlock Origin 1.17.0

**Comment by smed79** [comment]
add
```
/um-gdpr.
```
```
||revistaforum.com.br^*/jquery.fancybox.
```
