### ISSUE TITLE
Rule breaking survey embeds (topbox.ca)

### ISSUE THREAD

**Issue by injust** [ryanbr/fanboy-adblock#573]
### List the website(s) you're having issues:
`https://topbox.ca/pages/ds-2018-10-burberry-b3s7i`

### What happens?
Page is blank

### List Subscriptions you're using:
Fanboy's Annoyance List

### Other details:
Rule in question is `||surveygizmo.com^$third-party`.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0bd4898ac56726052f77bb148c0a50ec9149de41

**Comment by injust** [comment]
@ryanbr Your commit doesn't modify the relevant rule.

**Comment by smed79** [comment]
Redundancy between 
```
||surveygizmo.com^$third-party
```
and
```
||surveymonkey.com^$~subdocument,third-party,domain=~surverymonkey.co.uk|~surveymonkey.co.uk|~surveymonkey.de
```

**Comment by injust** [comment]
@smed79 I don't understand the redundancy; `surveygizmo.com` and `surveymonkey.com` are different domains, no?

**Comment by smed79** [comment]
Sorry, I confused "**survey**gizmo.com" with "**survey**monkey.com"

the fix should be editing
```
||surveygizmo.com^$third-party
```
to
```
||surveygizmo.com^$~subdocument,third-party
```
not
```
||surveymonkey.com^$~subdocument,third-party,domain=
```

**Comment by injust** [comment]
That's what I have done in easylist/easylist#2083, PR is awaiting merge.
