### ISSUE TITLE
tvtropes.org

### ISSUE THREAD

**Issue by veikk0** [ryanbr/fanboy-adblock#574]
### List the website(s) you're having issues:
`https://tvtropes.org/`

### What happens?
There is a nag message that appears on the bottom of the viewport on every page, stating "This is page {pagenumber} you have viewed this month without ads" and how you should whitelist the site or create an account.

### List Subscriptions you're using:
* uBlock filters​​​​​
* uBlock filters – Badware risks
* uBlock filters – Privacy​​​​​
* uBlock filters – Resource abuse​​​​​​​
* uBlock filters – Unbreak​​​​​​​
* EasyList​
* EasyPrivacy​
* Malware Domain List​​​​​
* Malware domains​
* Adguard’s Annoyance List​
* Fanboy’s Annoyance List
* Peter Lowe’s Ad and tracking server list​
* FIN: Finnish Addition to Easylist​

### Your settings

- OS/version: Linux Mint 19 Mate edition
- Browser/version: Firefox 62.0 (64-bit)
- Adblock Extension/version: uBlock Origin v1.17.0

### Other details:
I created a fresh Firefox profile and only installed uBlock Origin to make sure other add-ons weren't intefering.

**Comment by ryanbr** [comment]
Clear the cookies, and install Enhanced Tracking List. See if that helps.

**Comment by practik** [comment]
You could also try adding this filter:

`tvtropes.org##div:matches-css(z-index: 100001)`

**Comment by veikk0** [comment]
Enabling the "uBlock filters – Annoyances​​​​​" list (which is not enabled by default in uBlock and also isn't prominently displayed) fixed the issue. Looking at the filter list, the relevant GitHub issue for uAssets is https://github.com/uBlockOrigin/uAssets/issues/3535 and the filter used is `tvtropes.org##+js(set-constant.js, valid_user, true)`

**Comment by ryanbr** [comment]
Re-tested with just Easylist, Fanboy Annoyances + Enhanced Trackers. Seems fine now.
