### ISSUE TITLE
taringa.net

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#575]
### List the website(s) you're having issues:

Open `https://www.taringa.net/buscar/`, type something into the search bar and click on "Buscar".

### What happens?

Overlay on the results page.

### List Subscriptions you're using:

Fanboy's Annoyance list.

### Your settings

- Browser/version: Firefox 62
- Adblock Extension/version: uBlock Origin 1.17.0

**Comment by smed79** [comment]
test
```
taringa.net###invite-modal
taringa.net##.t-modal__inner
```
