### ISSUE TITLE
Cookie notice on https://www.bitmoji.com/

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#576]
There's cookie notice on https://www.bitmoji.com/ with cookiemonster list enabled in uBlock Origin, Firefox Beta 63, Windows 10.

**Comment by krystian3w** [comment]
`###disclaimer`

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/blob/7ef4b54054b882531b102fda0a02298a094aa743/fanboy-addon/fanboy_cookie_specific_hide.txt#L70

https://github.com/easylist/easylist/blob/3638e8ce6430f36d0904a5b96a8db65e1dd9d11d/fanboy-addon/fanboy_cookie_international_specific_hide.txt#L27

https://github.com/easylist/easylist/blob/3638e8ce6430f36d0904a5b96a8db65e1dd9d11d/fanboy-addon/fanboy_cookie_international_specific_hide.txt#L163

**Comment by SeriousHoax** [comment]
So, it should be added there, right?

**Comment by krystian3w** [comment]
Ryanbr should add in a week.

Take easy.

**Comment by SeriousHoax** [comment]
Ok, no problem.
