### ISSUE TITLE
algerietelecom.dz

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#577]
### List the website(s) you're having issues:

`https://www.algerietelecom.dz/`

### What happens?

social icons

### filters:

```
##.fa-facebook-official
##.fa-linkedin-square
```

**Comment by krystian3w** [comment]
`##.fa-facebook-official` may cut header login button at `https://www.swiatebookow.pl/login/?next=/`

![image](https://user-images.githubusercontent.com/35370833/46859493-2fb42800-ce0e-11e8-8f36-667fe693cbad.png) |
--- |

**Comment by ryanbr** [comment]
```
Erreur: 19741180342323426

Veuillez envoyer la capture de cette page à : securite_reseau[at]at.dz
```
Guessing site has gone, tested on a VPN

**Comment by krystian3w** [comment]
It did not work for me on the third day after reporting, you can do a test on a French or Arabic VPN and not some Aligers.
