### ISSUE TITLE
is.fi cookie consent

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#578]
### List the website(s) you're having issues:

* `https://www.is.fi/`
* `https://www.hs.fi/` (Owned by the same company)

### What happens?

cookieconsent

### List Subscriptions you're using:

cookiemonster

### Your settings

- OS/version: solus
- Browser/version: ff nightly
- Adblock Extension/version: ubo

### Other details:

Screenshot from is.fi:

![](https://storage.theel0ja.info/misc/Screenshot_2018-10-10%20Ilta-Sanomat%20-%20IS%20-%20Suomen%20suurin%20uutismedia.png)

Finnish addition to EasyList (https://adb.juvander.net/Finland_adb.txt) fixes this.

**Comment by krystian3w** [comment]
```
||sn.sanoma.fi/js/sccm/sccm.js
```

one strange thing that they added it two times on the list.
