### ISSUE TITLE
gearbest.com

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#579]
### List the website(s) you're having issues:

`https://www.gearbest.com/`

### What happens?

newsletter overlay

### List Subscriptions you're using:

EL + EP + Annoyance list

- Browser/version: Firefox 62
- Adblock Extension/version: Adblock Plus 3.3.1

### Filters:
```
gearbest.com##.siteSubscribe
```
* https://i.imgur.com/15lE7uu.png
```
gearbest.com##.newUserPop
gearbest.com##.layui-layer-shade
```
* https://i.imgur.com/po6H8Y6.png

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c560e5cb947f302c5e079d130679befe78ca70a6
