### ISSUE TITLE
jornaldacidadeonline.com.br

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#585]
### List the website(s) you're having issues:

`https://www.jornaldacidadeonline.com.br/noticias/11762/a-carta-proibida-que-gleisi-tenta-esconder`

### What happens?

Overlay when the mouse cursor leaves the page frame. Wait for the page to load and then move the cursor to the address bar or out of the browser window to see it.

### List Subscriptions you're using:

Fanboy's Annoyance list.

### Your settings

- Browser/version: Firefox 62
- Adblock Extension/version: uBlock Origin 1.17.0

**Comment by smed79** [comment]
add
```
||static.jornaldacidadeonline.com.br/dist/chunk.
```
or
```
jornaldacidadeonline.com.br##.exit-screen
```
