### ISSUE TITLE
gamewatcher.com

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#587]
### List the website(s) you're having issues:

`https://www.gamewatcher.com/editorials/the-best-strategy-games-on-pc/12531`

### What happens?

It requires you to close an overlay to unlock scrolling. The overlay is hidden by the Annoyance List.

### List Subscriptions you're using:

Fanboy's Annoyance list.

### Your settings

- Browser/version: Firefox 62
- Adblock Extension/version: uBlock Origin 1.17.0

**Comment by smed79** [comment]
test
```
||d1nze30o6kn41u.cloudfront.net/assets/application-
```
