### ISSUE TITLE
Pole-Emploi.fr - Pages won't load (Fanboy's Annoyance List + Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#591]
### Affected site:
`pole-emploi.fr`

### Issue:
Several subpages are prevented from loading.

### Example:
`https://candidat.pole-emploi.fr/offres/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
Fanboy's Annoyance List
Fanboy's Cookie List

### Problem rule:
`-cookie-law-popup.`

### Possible fix:
`@@-cookie-law-popup.$domain=pole-emploi.fr`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by ryanbr** [comment]
Whats the full url? I'm not seeing it

**Comment by smed79** [comment]
I cannot reproduce the issue.

**Comment by THEtomaso** [comment]
Yeah, the person which reported it to me warned me that the link only would be available for a limitied time.
Apparently, the site belongs to a French work agency.
The reporter complained that none of the issued work announcments would load in his browser, when uBO was active.
So, I checked it out, confirmed the issue, and found the blocking rule.
Both me and that other person has confirmed that the exception that I made works, so I can assure you that this is a absolute certainty!

**Comment by smed79** [comment]
> Whats the full url?

`https://candidat.pole-emploi.fr/offres/modules/jquery-eu-cookie-law-popup.js`

https://i.imgur.com/AJhmBlT.png
https://i.imgur.com/heVFxTH.png

**Comment by THEtomaso** [comment]
> `@@||candidat.pole-emploi.fr/offres/modules/jquery-eu-cookie-law-popup.js$script`

Not sure if this completely covers it.
As I understand it, the "candidat" / "offres" subpage is just one example of where this cookie thing is used.
It would probably be better if you used the exception rule that I posted, or the one that was added to 'AdGuard Annoyances filter'.
That will cover the whole site.

**Comment by THEtomaso** [comment]
I was able to confirm my suspicion, simply by navigating to a different subpage:
`https://candidat.pole-emploi.fr/inscription/`

As you can see, the required script for the link above is located at this location:
`https://candidat.pole-emploi.fr/inscription/modules.gz/jquery-eu-cookie-law-popup.js`
..so, your exception rule doesn't work for it.

There's no telling how many places they've deployed this script, so you really need to make an exception rule that covers this whole domain:
`pole-emploi.fr`

**Comment by THEtomaso** [comment]
> 5df516f 

Still, your new exception rule is limited to the "candidat" subpages.
Why are you so hesitant to make an exception which covers the whole site?

**Comment by smed79** [comment]
> rule is limited to the "candidat" subpages.

Provide an example page.

> Why are you so hesitant to make an exception which covers the whole site?

filters must be as specific as possible.

**Comment by THEtomaso** [comment]
I don't have an account at that place, but I can ask the guy that reported it to me, to find out if the script exists elsewhere on the site.
It just seems very unneccesary to me that the exception rule should be so specific.
If the scrip does exist elsewhere on the site, I think it's a safe to say that it will be a required thing.
Therefore, I don't see any reason as to why parts of this particular site should be restricted from using it.
