### ISSUE TITLE
Cookie banner not blocked: rp-online.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#592]
### List the website(s) you're having issues:
`https://rp-online.de/`

### What happens?

Cookiebanner not blocked

### List Subscriptions you're using:

Fanboy’s Cookiemonster List

### Your settings

- OS/version: win7 (64bit)
- Browser/version: firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.17.0

**Comment by ryanbr** [comment]
`##.park-snackbar-cookies`

I see this being blocked, I dont see any cookie messages?

**Comment by practik** [comment]
I see `##.park-snackbar-cookies` in the list too, but the banner is showing up for me anyway:

![rponline](https://user-images.githubusercontent.com/12074235/47263152-fbe59c00-d4b8-11e8-9629-3fd11afc2d60.png)

(uBlock Origin 1.17.2 on FF 62.0.3 on macOS 10.12)

**Comment by ryanbr** [comment]
Can you use the Ubo picker and see what element shows?

**Comment by ryanbr** [comment]
Unless you have another filterlist that's applying generichide?
