### ISSUE TITLE
"Cookiebot" rule creates some issues (Fanboy's Annoyance List + Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#593]
### Issue:
Some third party elements are blocked.

### Example:
`https://www.refinery29.com/en-gb/2018/10/214421/emma-watson-trans-rights/`
(Instagram images are blocked)

### Problem filters:
Fanboy's Annoyance List
Fanboy's Cookie List

### Problem rule:
`||cookiebot.com^$third-party`

### Thoughts:
Desired behaviour, or not?
The rule might rather belong in '**Fanboy's Enhanced Tracking List**' perhaps?
That filter already blocks the Instagram images with the following rule:
`&referer=$image,script`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by ryanbr** [comment]
No issues with instagram here.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/686a7fc8d858888da197169f357c7676350b42e9
