### ISSUE TITLE
OrdetErMitt.com - Images won't load (Fanboy's Annoyance List + Fanboy's Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#594]
### Affected site:
`https://www.ordetermitt.com/`

### Issue:
Article images won't load.

### Example:
`https://www.ordetermitt.com/hvorfor-er-det-alltid-europas-ansvar-a-ta-seg-av-den-flyktningene-fra-den-tredje-verden/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
Fanboy's Annoyance List
Fanboy's Social Blocking List

### Problem rule:
`/jquery.sharrre.min.js`

### Blocked script:
`https://www.ordetermitt.com/wp-content/plugins/alx-extensions/js/jquery.sharrre.min.js`

### Possible fix:
`@@/jquery.sharrre.min.js$domain=ordetermitt.com`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by ryanbr** [comment]
removed.
