### ISSUE TITLE
Tyre test sites - minor issue (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#596]
### Affected sites:
```
https://www.autobandentest.com/
https://www.dacktest.com/
https://www.daektest.com/
https://www.dekktest.com/
https://www.gumiteszt.com/
https://www.padangutestas.lt/
https://www.pneu-test.com/
https://www.provadellagomma.com/
https://www.rehvitest.com/
https://www.reifentest.com/
https://www.rengastesti.com/
https://www.rieputesti.com/
https://www.testcauciucuri.com/
https://www.testedepneus.com/
https://www.testipnevmatik.com/
https://www.testiranjeguma.hr/
https://www.testopon.com/
https://www.testovanipneumatik.com/
https://www.testpneumatik.com/
https://www.testshiny.ru/
https://www.testvanenagumi.com/
https://www.tirestest.com/
https://www.tyretest.com/
https://www.valoresuneumatico.com/
```

### Issue:
Their newsletter subscription box (at the bottom of the pages) are broken.
It's not an annoyance, since it's a stationary thing, located all the way down at the footer.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
Fanboy's Annoyance List

### Problem rule:
`/api/newsletter`

### Possible fix:
`@@/api/newsletter$domain=autobandentest.com|dacktest.com|daektest.com|dekktest.com|gumiteszt.com|padangutestas.lt|pneu-test.com|provadellagomma.com|rehvitest.com|reifentest.com|rengastesti.com|rieputesti.com|testcauciucuri.com|testedepneus.com|testipnevmatik.com|testiranjeguma.hr|testopon.com|testovanipneumatik.com|testpneumatik.com|testshiny.ru|testvanenagumi.com|tirestest.com|tyretest.com|valoresuneumatico.com`

### Thoughts:
Someone asked my to fix this for them.
It's just a minor issue of course, but since a lot of different URLs are affected, and since I've already made a fix for it, I thought that I might just as well post it here. :)

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by smed79** [comment]
Still annoyance for me.

**Comment by THEtomaso** [comment]
Well, it's still there, and just as much of an "annoyance" to you, without my exception rule.
The only difference is that without it, the form is actually broken.

**Comment by ryanbr** [comment]
Its expected. Most people don't want newsletters and want content. even static forms, The moment you make one exception, then you open the flood gates.
