### ISSUE TITLE
MOVAGlobes.com - Blocked videos (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#598]
### Affected site:
`https://www.movaglobes.com/`

### Issue:
Videos are blocked.

### Example:
`https://www.movaglobes.com/relief-map-blue-mova-globe-cube-5/`
(Try clicking on the "WATCH VIDEO" button)

### Blocked script:
`https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js`

### Problem filter:
Fanboy's Annoyance List

### Problem rule:
`/downloads.mailchimp.com/*`

### Possible fix:
`@@/downloads.mailchimp.com/*$domain=movaglobes.com`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by smed79** [comment]
Seems fine here https://i.imgur.com/16cMjgk.png

**Comment by THEtomaso** [comment]
You're not accessing the videos from the correct place.
Follow the link that i posted under "**Example**"..
It's the "**WATCH VIDEO**" button that doesn't work!

**Comment by ryanbr** [comment]
Okay its removed.
