### ISSUE TITLE
Reddit and Twitch subscription buttons hidden by Fanboy's Social Blocking List

### ISSUE THREAD

**Issue by lewisje** [ryanbr/fanboy-adblock#6]
The offending hiding rule is `##.subscribe-button` and a fix is replacing that with `~reddit.com,~twitch.tv##.subscribe-button`; I have posted a thread in the EasyList forums about [the problem with Reddit](https://forums.lanik.us/viewtopic.php?f=64&t=29419), and someone else has posted a thread on the Adblock Plus forums about [the problem with Twitch](https://adblockplus.org/forum/viewtopic.php?f=2&t=44711).

**EDIT**: Now that I see how you've organized the lists, a better idea would be just adding `twitch.tv` to the domain specifiers for your whitelist rule.

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/fa4333bc7f82
