### ISSUE TITLE
DuckDuckGo Setting

### ISSUE THREAD

**Issue by Maxxxxxx** [ryanbr/fanboy-adblock#60]
Fanboy's Annoyances has a filter named ###back-to-top.  It is the DuckDuckGo arrow that (obviously) returns you to the top of the page.

I tried adding is as an exception to ABP custom filters, but I think it is battling against your list - possibly the reason it is greyed out?  It won't take on the exceptions list, so I have to block it (open blockable items) every time I reopen DDG, which is continuously throughout the course of a day.

If this is DDG's filter, can you remove it?  If it's a more universal code. would you please tell me how to block it permanently on Adblock Plus - or on FA List?

I use Adblock Plus and I use your lists, but I don't understand the technology.
Firefox 50.1.0
Adblock Plus 2.8.2
Fanboy's Annoyances List (US) updated constantly.  

I tried the forum, but when attempting to register an account, I was continually denied as a spammer when I entered my legitimate email address and correctly identified the CAPTCHA pictures. 

Thank you.

**Comment by SMed79** [comment]
The purpose of annoyances list is to removes all online annoyances (includes social list) and back to top botton is one of them.

add to your custom filters `duckduckgo.com###back-to-top`

> I tried the forum, but when attempting to register an account......

If you register with the forum you don't need to worry about that.
See https://forums.lanik.us/viewtopic.php?f=9&t=34073

**Comment by Maxxxxxx** [comment]
Ryan,


I understand the purpose of Fanboy's Annoyances, and I greatly appreciate using the list.

Thank you for explaining its inclusion on it; I thought it had wider-reaching implications.


I wasn't trying to post anonymously - I was trying to create an account.

  Obviously, I don't need it now.


Thank you for your unbelievably prompt response.

It took a second to fix.


Health, Happiness, Peace, & Prosperity in 2017.

S:F




________________________________

**Comment by SMed79** [comment]
> I wasn't trying to post anonymously - I was trying to create an account.

I get No issue to register an account

![http://i.imgur.com/JVB4ZgH.png](http://i.imgur.com/JVB4ZgH.png)

**Comment by Maxxxxxx** [comment]
Okay, so I'm struggling with everything.  I do not know why. 

At any rate, your filter in action: [https://imgur.com/a/oQNDt](url)

Thank you.

**Comment by Maxxxxxx** [comment]
Please ignore my last GitHub posting.

I had to delete the two (greyed out and shorter filters) and add it again to/in exceptions, but it is still greyed-out.  What does that mean?


I haven't yet tested it since, but I really have to focus on work.


Thank you.




________________________________

**Comment by SMed79** [comment]
Show me a screenshot of you custom filte http://i.imgur.com/ALDfj8f.png

**Comment by Maxxxxxx** [comment]
Will post it in a minute.

I noticed yesterday that there are three categories of exceptions.

I assume they are Element Hiding Exceptions, Ad Blocking Exceptions and Exception exceptions.  The third category being the relevant one .

Yesterday I added the filter to all three exceptions, which could be a mistake.

The screenshot is from the last category.

Thank you.



Happiness in 2017.

N:L




________________________________

**Comment by Maxxxxxx** [comment]
Done.


Thank you.

Good Health in 2017.


________________________________
