### ISSUE TITLE
simtropolis.com

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#602]
### List the website(s) you're having issues:

`https://community.simtropolis.com/files/file/21339-crime-doesnt-pay/`

### What happens?

Overlay annoyance.

### List Subscriptions you're using:

Annoyances list.

### Your settings

- Browser/version: Firefox 63.0 (64-bit)
- Adblock Extension/version:  uBlock Origin 1.17.2

**Comment by ryanbr** [comment]
Looks fine imo

**Comment by smed79** [comment]
@adranger add
```
community.simtropolis.com##.ipsModal
community.simtropolis.com##.ipsDialog
```
