### ISSUE TITLE
mundodoandroidapk.com / mundodroidgames.com [Fanboy’s Annoyance List] [images won't load]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#603]
### List the website(s) you're having issues:

`http://mundodoandroidapk.com/`
`https://mundodroidgames.com/`

### What happens?

Breakage - enabling `Fanboy’s Annoyance List` causes some elements on the website not loading (images etc), the issue is gone after disabling `Fanboy’s Annoyance List`.

### List Subscriptions you're using:

uBO default

### Your settings

OS: Windows 7 SP1 64bit
Browser/version: Firefox 63.0 64bit
uBlock Origin version: 1.17.2

### 1 `http://mundodoandroidapk.com/` with `Fanboy’s Annoyance List` enabled:
![ss1](https://user-images.githubusercontent.com/43844449/47601483-90785e80-d9d1-11e8-9d3e-4af13d3c7d34.png)

### 2 `http://mundodoandroidapk.com/` after disabling `Fanboy’s Annoyance List`:
![ss3](https://user-images.githubusercontent.com/43844449/47601494-cfa6af80-d9d1-11e8-9860-7ad888f55e6c.png)

### 3 `https://mundodroidgames.com/` with `Fanboy’s Annoyance List` enabled:
![ss2](https://user-images.githubusercontent.com/43844449/47601485-953d1280-d9d1-11e8-8ff3-487cfa395951.png)

### 4 `https://mundodroidgames.com/` after disabling `Fanboy’s Annoyance List`:
![ss4](https://user-images.githubusercontent.com/43844449/47601496-d46b6380-d9d1-11e8-8654-377413d90834.png)

**Comment by ryanbr** [comment]
If you install the enhanced trackers list, it'll get rid of the Anti-adblock also.

**Comment by kulfoon** [comment]
Woaa, I didn't know about it, I never suspected that tracking had something to do with Anti-Adblock but I do see now these sections: 

`! Warnings`

`! Adblock Warnings` 

`!---------- Anti Adblock Warnings ------`

```
!---------- Anti Adblock & Anti Adblock Tracking ------
! These filters are for websites tracking and monitoring adblock users
```

so I 'll turn the list back on then.
