### ISSUE TITLE
brightonandhovenews.org / gamerotic.com [Fanboy’s Enhanced Tracking List & Adblock Warning Removal List] [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#609]
### List the website(s) you're having issues:

`https://www.brightonandhovenews.org/`
`https://gamerotic.com/` NSFW

### What happens?
Anti-Adblock message (annoyance) when entering the websites, as reported here:
https://github.com/uBlockOrigin/uAssets/issues/3913
https://github.com/uBlockOrigin/uAssets/issues/3928

### List Subscriptions you're using:

uBO default + 
uBO annoyance +
Adblock Warning Removal List +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

The issue occurs only if both Adblock Warning Removal List & Fanboy’s Enhanced Tracking List  are enabled, so it seems that there is some interference between them, I'm not sure which one causes the issue, thus I decided to report on this issue tracker first. Don't forget to keep uBO annoyance list enabled as it fixes the issue on `gamerotic.com` after AWRL & FETL are disabled (both at once or just one of them).

**Comment by THEtomaso** [comment]
It seems to be whitlisted in 'Fanboy's Enhanced Tracking List' with the following rule:
`@@/wp-content/*/ad-$script,xmlhttprequest`

Since the above rule probably exists to fix some sort of breakage, perhaps a cosmetic fix might be a viable solution in this case?:
`brightonandhovenews.org|gamerotic.com##.special-message-wrapper`

**Comment by kulfoon** [comment]
Your solution works.
