### ISSUE TITLE
Blocks audio player from showing

### ISSUE THREAD

**Issue by ParticleMon** [ryanbr/fanboy-adblock#61]
The "Listen" anchor, on all such pages on the same site as the following example, appends "#listen=audio" to the URL and shows an audio player between the heading and the first subheading:

https://www.lds.org/scriptures/bofm/1-ne/1?lang=eng#listen=audio

Exhibited by Fanboy's Enhanced Tracking List as well as Fanboy+Easylist-Merged Ultimate List in uBlock Origin on Chromium, Firefox, and Pale Moon on Windows 7.

**Comment by ryanbr** [comment]
If I click on the "Listen" option on the right, it does nothing, even with adblock disabled.

**Comment by ryanbr** [comment]
https://www.youtube.com/watch?v=pJGaBvbxW90

Unless I'm doing something wrong, its working as expected

**Comment by ryanbr** [comment]
Closing issue, no response after 27 days, and unable to reproduce.
