### ISSUE TITLE
oattravel.com / moneycanbuylipstick.com / crstodayeurope.com / crstoday.com / millennialeye.com / bouwbedrijfhiemstra.nl / comradeagency.com / grupohpm.lgbt [Breakage - pages won't load ] [Fanboy’s Annoyance List]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#610]
### List the website(s) you're having issues:

`https://www.oattravel.com/`
`https://www.moneycanbuylipstick.com/`
`https://crstodayeurope.com/`
`https://crstoday.com/`
`https://millennialeye.com/`
`http://bouwbedrijfhiemstra.nl/`
`https://comradeagency.com/`
`http://grupohpm.lgbt/`

### What happens?

All the websites completely broken.

### 1 screenshoot: enabling Fanboy’s Annoyance List breaks completely all the mentioned websites:
![ss1](https://user-images.githubusercontent.com/43844449/47717419-ff5ded80-dc45-11e8-9401-0d2624c10fee.png)

### disabling Fanboy’s Annoyance List causes the website loading properly:

<details>
  <summary>Screenshoots</summary>

###  2 screenshoot (`https://www.oattravel.com/`) - 

![ss2](https://user-images.githubusercontent.com/43844449/47717499-37fdc700-dc46-11e8-93b7-f8877bca1238.png)

###  3 - screenshoot (`https://www.moneycanbuylipstick.com/`) 

![ss3](https://user-images.githubusercontent.com/43844449/47717769-edc91580-dc46-11e8-890b-5f943129d255.png)

###  4 - screenshoot (`https://crstodayeurope.com/`)
![ss4](https://user-images.githubusercontent.com/43844449/47718052-a8f1ae80-dc47-11e8-8e19-89830f5d8d56.png)

###  5- screenshoot (`crstoday.com`)
![ss1](https://user-images.githubusercontent.com/43844449/47770394-88753300-dcdf-11e8-994a-9e0be772415a.png)

###  6- screenshoot (`https://millennialeye.com/`)
![ss2](https://user-images.githubusercontent.com/43844449/47770396-8c08ba00-dcdf-11e8-8240-385857f4289a.png)

###  7 - screenshoot (`http://bouwbedrijfhiemstra.nl/`)
![ss1](https://user-images.githubusercontent.com/43844449/47771966-7f876000-dce5-11e8-9529-174b8c36047c.png)

###  8 - screenshoot (`https://comradeagency.com/`)
![ss2](https://user-images.githubusercontent.com/43844449/47771977-81e9ba00-dce5-11e8-9f0a-99a8e75cb87b.png)

###  9 - screenshoot (`http://grupohpm.lgbt/`)
![ss3](https://user-images.githubusercontent.com/43844449/47771981-8615d780-dce5-11e8-9ce5-b97755f94139.png)

</details>

### List Subscriptions you're using:

uBO default + 
uBO annoyance +
Fanboy’s Annoyance List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

**Comment by THEtomaso** [comment]
```
@@/selection-sharer.$domain=crstodayeurope.com
moneycanbuylipstick.com#@#.nav-social
oattravel.com#@#.mod_cookies
```

**Comment by kulfoon** [comment]
Your solution works.

**Comment by THEtomaso** [comment]
A couple of CRSToday's sister sites are also affected.
I've modified my exception rule here, to include those as well:
https://github.com/ryanbr/fanboy-adblock/issues/610#issuecomment-434291396

**Comment by kulfoon** [comment]
I've found 3 more:
`http://bouwbedrijfhiemstra.nl/`
`https://comradeagency.com/`
`http://grupohpm.lgbt/`

**Comment by THEtomaso** [comment]
I've updated the fix with them:
`https://github.com/ryanbr/fanboy-adblock/issues/610#issuecomment-434291396`
