### ISSUE TITLE
shoppable.com / foodnutritiontable.com / novojornal.co.ao / tappedout.net [Breakage - pages won't load - overlay] [Fanboy’s Annoyance List]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#611]
### List the website(s) you're having issues:

`https://www.shoppable.com/`
`http://www.foodnutritiontable.com/`
`http://novojornal.co.ao/`
`http://tappedout.net/`

### What happens?

All the websites broken - cookies overlay left (`https://www.shoppable.com/` , `http://www.foodnutritiontable.com/` and `http://tappedout.net/`), newsletter overlay left (`http://novojornal.co.ao/`)

### Screenshoots:

<details not-open>
<summary>screenshoots</summary>

### 1 screenshoot (`https://www.shoppable.com/`) - enabling Fanboy’s Annoyance List breaks the website - cookies's overlay left:
![ss1](https://user-images.githubusercontent.com/43844449/47718329-69779200-dc48-11e8-8f62-4cd6435617a0.png)

### 2 screenshoot (`https://www.shoppable.com/`) - disabling Fanboy’s Annoyance List causes the website loading properly (cookie message):
![ss2](https://user-images.githubusercontent.com/43844449/47718439-b8bdc280-dc48-11e8-9e69-482b794842e8.png)

###  3 - screenshoot (`https://www.shoppable.com/`) - clicking Close Cookie button causes the website loading properly:

![ss3](https://user-images.githubusercontent.com/43844449/47718378-8b711480-dc48-11e8-9523-7a0ea4fc8b32.png)

### 4 screenshoot (`http://www.foodnutritiontable.com/`) - enabling Fanboy’s Annoyance List breaks the website - cookies's overlay left:
![ss1](https://user-images.githubusercontent.com/43844449/47719015-274f5000-dc4a-11e8-867d-ca2b7fe88f24.png)

### 5 screenshoot (`http://www.foodnutritiontable.com/`)  - disabling Fanboy’s Annoyance List causes the website loading properly (cookie message):
![ss2](https://user-images.githubusercontent.com/43844449/47719077-536ad100-dc4a-11e8-846e-cb2e1af0f0ec.png)

### 6 - screenshoot (`http://www.foodnutritiontable.com/`)  - clicking Accept Cookie button causes the website loading properly:
![ss3](https://user-images.githubusercontent.com/43844449/47719115-739a9000-dc4a-11e8-9f91-e0dfe7b13dfa.png)

### 7 screenshoot (`http://tappedout.net/`) - enabling Fanboy's Cookiemonster List breaks the website - newsletter's overlay left:
![ss3](https://user-images.githubusercontent.com/43844449/47951172-4bb66f80-df5d-11e8-8c9c-f122e3457a31.png)

### 8 screenshoot (`http://tappedout.net/`)  - disabling Fanboy’s Cookiemonster List causes the website loading properly (cookie message):
![ss1](https://user-images.githubusercontent.com/43844449/47951175-51ac5080-df5d-11e8-843a-6a81cbe42324.png)

### 9 - screenshoot (`http://tappedout.net/`)  - clicking accept cookie button causes the website loading properly:
![ss2](https://user-images.githubusercontent.com/43844449/47951174-4eb16000-df5d-11e8-822f-25c2058359bb.png)

### 10 screenshoot (`http://novojornal.co.ao/`) - enabling Fanboy’s Annoyance List breaks the website - newsletter's overlay left:
![ss3](https://user-images.githubusercontent.com/43844449/47771131-5a452280-dce2-11e8-8a1c-40a9e058ad9a.png)

### 11 screenshoot (`http://novojornal.co.ao/`)  - disabling Fanboy’s Annoyance List causes the website loading properly (newsletter message):
![ss1](https://user-images.githubusercontent.com/43844449/47771114-51ece780-dce2-11e8-9124-8699000bf11f.png)

### 12 - screenshoot (`http://novojornal.co.ao/`)  - clicking close newsletter button causes the website loading properly:
![ss2](https://user-images.githubusercontent.com/43844449/47771135-5dd8a980-dce2-11e8-9c08-c9236eb68e77.png)

</details>

### List Subscriptions you're using:

uBO default + 
uBO annoyance +
Fanboy’s Annoyance List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

**Comment by THEtomaso** [comment]
```
foodnutritiontable.com#@##cooMessage
shoppable.com#@##cookiesModal
```

**Comment by kulfoon** [comment]
Your solution works.

**Comment by THEtomaso** [comment]
The whitelisting rules that I posted are site-specific.

**Comment by THEtomaso** [comment]
Removing the generic rules would result in cookie popups on a lot of sites, where those popups easely can be blocked without any ill effects.
However, I agree to what you're proposing, to some degree:
https://github.com/ryanbr/fanboy-adblock/issues/572#issuecomment-433723010

**Comment by kulfoon** [comment]
I edited my comment + isn't that `Fanboy’s Cookiemonster List` and `I don't care about cookies` to deal with Cookies?

**Comment by kulfoon** [comment]
I've cleand out my comment above.

**Comment by THEtomaso** [comment]
Yeah, I guess that it wouldn't be such a bad idea to differentiate between "annoyances" and "cookie consents".
There's a reason why uBlock's Annoyances filter leaves such consents alone!

**Comment by kulfoon** [comment]
Yea, just forgot that Fanboy Annoyances contains FanboyCookies, I've cleand my comment above.

**Comment by THEtomaso** [comment]
You're continously forcing me to edit my replies! :)

**Comment by kulfoon** [comment]
Yea, I like to edit if possible and clean the nosie, rather than to create another comment.

**Comment by THEtomaso** [comment]
> Can't say now - I would have to think about it

The question is for ryanbr. :)

**Comment by krystian3w** [comment]
> Still `###cooMessage` whitelisted by `foodnutritiontable.com#@##cooMessage`, and
> `###cookiesModal` whitelisted by `shoppable.com#@##cookiesModal`
> can't block cookie message.

* If website no block scroll (**but some they block ...**), you can add overlay pop-up in one filter (since some version supports this AdBlock Plus):

    `foodnutritiontable.com###cooMessage, #loading`
    `shoppable.com###cookiesModal, .modal-backdrop`


* You can also track an element in the html tree (it can be dangerous when, for example, the message is not loading, someone will have different versions of the page, etc.):

   `shoppable.com###page-top\ no-gutter > div:nth-child(57)` - pop-up
   `shoppable.com#page-top\ no-gutter > div:nth-child(81)` - fog

   `shoppable.com##body > div:nth-of-type(4)` - pop-up
   `shoppable.com##body > div:nth-of-type(8)` - fog

  `foodnutritiontable.com###form1 > div:nth-child(28)` - pop-up
  `foodnutritiontable.com###form1 > div:nth-child(29)` - fog

  `foodnutritiontable.com###form1 > div:nth-of-type(4)` - pop-up
  `foodnutritiontable.com###form1 > div:nth-of-type(5)` - fog


* Detect specific css formatting, with `:-abp-properties()` (however, this is as slow as `:-abp-has()` and `:-abp-contains ()`).

* Use CLASS instead of ID added to exceptions if possible.

**Comment by ryanbr** [comment]
Not sure if this would cause any issues, but this helps?

`||js.stripe.com^$script,domain=shoppable.com`

**Comment by ryanbr** [comment]
I had no issues with novojornal.co.ao

**Comment by krystian3w** [comment]
> 
> 
> I had no issues with novojornal.co.ao

Try pruge cookies for this website and catch newsletter.

```
###modal-newsletter-register
##.newsletter-register
##.box-newsletter
```

Seems **no unlock** scroll on first visit.

**Comment by krystian3w** [comment]
```css
modal, .modal-open {
    overflow: hidden;
}
```
```html
<body class="novojornal page-home modal-open" oncontextmenu="return false;" id="bodyTag" style="padding-right: 17px;">
```

**Comment by kulfoon** [comment]
As per https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-435299238, yes, it fixes the both issues.
As per https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-435303049, still the issue is here for me, adding this:
`novojornal.co.ao##.in.fade.modal-backdrop` (for hiding the overlay)
`novojornal.co.ao##body:style(overflow: auto !important;)` (for restoring the scroll bar)
Fixes the issue.

**Comment by ryanbr** [comment]
novojornal.co.ao##body:style(overflow: auto !important;) isn't ABP compatible.

**Comment by kulfoon** [comment]
Uh, forgot that the list is for ABP only.

**Comment by kulfoon** [comment]
Just've found one more `http://tappedout.net/`, I've edited my 1st comment - screenshoots 7 ,8 ,9.

**Comment by THEtomaso** [comment]
Unfortunately, from what I've seen of this type of GDPR popup annoyances before, the only properly working solution is to simply allow them:

Post updated:
https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-434293455

**Comment by ryanbr** [comment]
Closing ticket, submit a ticket per website, with a suggestion of fix. I dont have the time to go through this.

**Comment by THEtomaso** [comment]
I've already posted fixes for all of these sites here:
https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-434293455

**Comment by kulfoon** [comment]
> ryanbr : Closing ticket, submit a ticket per website, with a suggestion of fix. I dont have the time to go through this.

Ok but next time paste the rules into README.md / CONTRIBUTING.md / issue_template.md file rather than in a ticket. As for the time, others may not have time too. Also - I intentionally placed several domains in one ticket to avoid being accused of spamming with too many tickets...
