### ISSUE TITLE
gazetadopovo.com.br

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#615]
### List the website(s) you're having issues:

`https://www.gazetadopovo.com.br/politica/republica/temer-tem-so-dois-meses-para-aprovar-suas-ultimas-reformas-quais-as-prioridades-6her0qeam8304wyio6skohbn8/#social2_comentario_form`

### What happens?

Comments aren't loaded when the Fanboy’s Annoyance List is on.

### List Subscriptions you're using:

Fanboy’s Annoyance List.

### Your settings

- Browser/version: 63.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.17.2

![Comments](https://user-images.githubusercontent.com/35470489/47950403-87871000-df30-11e8-83ab-b56f8cba413f.png)

**Comment by krystian3w** [comment]
`/sociabilizacao/scripts/` - afected in Fanboy's Social Blocking List.

```
@@||cdnimg.gazetadopovo.com.br/sociabilizacao/scripts/PROD/js/scripts.js$script,domain=www.gazetadopovo.com.br
```
enough for my end.

---

I do not rule out that a script is still blocked in the Annoynace list.
