### ISSUE TITLE
sportingnews.com / opentuition.com / heyepiphora.com / epson.pl [Breakage - page won't load + missing scroll bar / overlay] [Fanboy's Cookiemonster List]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#616]
### List the website(s) you're having issues:

`http://www.sportingnews.com/`
`https://opentuition.com/`
`https://heyepiphora.com/`
`https://www.epson.pl/`

### What happens?

The websites are completely broken:
`http://www.sportingnews.com/` blank page + missing scroll bar
`https://www.epson.pl/` blank page
`https://opentuition.com/` overlay
`https://heyepiphora.com/` overlay

### Screenshoots:

<details not-open>
<summary>screenshoots</summary>

### 1 screenshoot (`http://www.sportingnews.com/` and `https://www.epson.pl/`): enabled
![ss1](https://user-images.githubusercontent.com/43844449/47717419-ff5ded80-dc45-11e8-9401-0d2624c10fee.png)

### 2 screenshoot (`http://www.sportingnews.com/`): disabled
![ss1](https://user-images.githubusercontent.com/43844449/47951087-18271580-df5c-11e8-8068-a1b80cef0494.png)

### 2a screenshoot (`https://www.epson.pl/`): disabled
![ss1](https://user-images.githubusercontent.com/43844449/48124875-b2999880-e27d-11e8-98e9-c6e1d82266ea.png)

### 3 screenshoot (`https://opentuition.com/`): enabled
![ss10](https://user-images.githubusercontent.com/43844449/48056682-97ae2200-e1b2-11e8-9936-45143f36dfc1.png)

### 4 screenshoot (`https://opentuition.com/`): disabled
![ss1](https://user-images.githubusercontent.com/43844449/48056707-a563a780-e1b2-11e8-89fe-bc495af53edc.png)

### 5 screenshoot (`https://opentuition.com/`): disabled + closed
![ss1a](https://user-images.githubusercontent.com/43844449/48056714-a8f72e80-e1b2-11e8-8dfd-14d09a93bfbe.png)

### 6 screenshoot (`https://heyepiphora.com/`): enabled
![ss20](https://user-images.githubusercontent.com/43844449/48056728-b01e3c80-e1b2-11e8-89a8-61d23f766ec7.png)

### 7 screenshoot (`https://heyepiphora.com/`): disabled
![ss2](https://user-images.githubusercontent.com/43844449/48056744-b90f0e00-e1b2-11e8-903b-c91368c1772a.png)

### 8 screenshoot (`https://heyepiphora.com/`): disabled + closed
![ss2a](https://user-images.githubusercontent.com/43844449/48056759-be6c5880-e1b2-11e8-9426-05f675a723e9.png)

</details>

### List Subscriptions you're using:

uBO default + 
uBO annoyance +
Fanboy's Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.1 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

**Comment by ryanbr** [comment]
Seems fine here

**Comment by kulfoon** [comment]
I'm sick of same websites broken in Firefox and not broken in Opera (or vice versa) all the fu... time, the wbesite is broken in Firefox, and after your comment, I've just checked in Opera 56 right now and yes - indeed - the page is loading, but the scroll bar is missing anyway:

<details not-open>
<summary>screenshoot</summary>

![ss4](https://user-images.githubusercontent.com/43844449/47951363-faf44600-df5f-11e8-8ad6-505df36b6e9d.png)

</details>
.

Another weird thing is a white ad-container in the middle seen on the screenshoot
And yet another weird thing is that the fu..ing website takes forever to load.

**Comment by ryanbr** [comment]
My primary browser is Firefox, I loaded the site, looked fine. It does load plenty adservers, but eventually renders.

**Comment by kulfoon** [comment]
That's even more weird, just f... great ! Hey, and what about the scroll bar, do you have it? (You didn't complain about the missing scroll bar, so I guess you have it, but just want to make sure. (Could you also check if you have it on a diff browser (chrome-based)?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/47952684-73b0cd80-df73-11e8-985f-352316a88609.png) |
--- |

**Comment by kulfoon** [comment]
Your solution is working, the website now works fine in Firefox.
But still the missing scroll bar issue in Opera.

**Comment by krystian3w** [comment]
> But still the missing scroll bar issue in Opera.

quantcast GDPR wall and everything is clear **why there is no scrolling**:

![obraz](https://user-images.githubusercontent.com/35370833/47952910-76f98880-df76-11e8-90a6-96341fe78e0f.png) |
--- |

**Comment by THEtomaso** [comment]
At my end, Fanboy filters completely breaks it.

### Affected site:
`http://www.sportingnews.com/`

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`##.flash.cookies`

### Possible Fix:
`sportingnews.com#@#.flash.cookies`

### Additional note:
The page is also broken by the '**hpHosts Ad and tracking servers**' filter, with the following rule:
images.performgroup.com
This fixes it:
`@@images.performgroup.com$domain=sportingnews.com`
(I'll report the issue to the filter's author)

**Comment by THEtomaso** [comment]
> quantcast GDPR

No GDPR thing at that site from my end.
This is exactly what makes those things such a big problem!
Often when reporting GDPR issues, filter authors are completely unable to repruce the problem at their ends, and therefore refuse to do anyting about it!! :(

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/47953377-1883d880-df7d-11e8-93e9-c64830d376c7.png) |
--- |

It is for me and I do not know how it neutralizes Firefox, that the scroll lock does not work.

**Comment by THEtomaso** [comment]
I was able to connect to the site through a German proxy, and successfully reproduce the GDPR issue.
Fix added:
https://github.com/ryanbr/fanboy-adblock/issues/616#issuecomment-435589053

**Comment by kulfoon** [comment]
Again the same solution as in https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-435337890: `sportingnews.com##body:style(overflow: auto !important;)` brings the scrollbar back, but it's not ABP compatible...

**Comment by THEtomaso** [comment]
Like I've pointed out many times before; bypassing these things often proves to be a bad idea.
It might seem OK at first, until you discover things like images that aren't displayed, videos that can't be played, and generally broken functions.
GDPR consents is a hell of a thing!

The abolutely worst of the bunch are the "**Evidon**" ones, which are so nasty that I've completely stopped reporting problems for them!
I recently added all the necessary fixes in my own filter, and I've never looked back!:
`https://github.com/DandelionSprout/adfilt/issues/7/#issuecomment-431578932`
What a relief it has been!! :)

**Comment by kulfoon** [comment]
Two more: 
`https://opentuition.com/` (screnshoots 3,4,5)
`https://heyepiphora.com/` (screenshoots 6,7,8)

**Comment by krystian3w** [comment]
Simple overlays?

```
opentuition.com###spu-bg-443557
heyepiphora.com###spu-bg-84149
```

"`spu-box`" usually no block scroll.

**Comment by kulfoon** [comment]
One more: `https://www.epson.pl/`

**Comment by krystian3w** [comment]
I can not repoduce bug with `www.epson.pl`, in logger I can't see `##.cookies` or `##.cookie-is-open` to block `<html>` or `<body>` tag.

**Comment by ryanbr** [comment]
I had no issues visiting `https://www.epson.pl/products/printers/inkjet-printers` from an EU ip.

**Comment by ryanbr** [comment]
Closing ticket, submit a ticket per website, with a suggestion of fix. I dont have the time to go through this.

**Comment by THEtomaso** [comment]
I've already posted fixes for `epson.*` and `sportingnews.com` here:
https://github.com/ryanbr/fanboy-adblock/issues/616#issuecomment-435589053

**Comment by kulfoon** [comment]
> ryanbr : Closing ticket, submit a ticket per website, with a suggestion of fix. I dont have the time to go through this.

Ok but next time paste the rules into README.md / CONTRIBUTING.md / issue_template.md file rather than in a ticket. As for the time, others may not have time too. Also - I intentionally placed several domains in one ticket to avoid being accused of spamming with too many tickets...
