### ISSUE TITLE
push.abs-cbn.com [Fanboy’s Annoyance List]

### ISSUE THREAD

**Issue by AmperAndSand** [ryanbr/fanboy-adblock#619]
### List the website(s) you're having issues:

`https://push.abs-cbn.com/2018/7/2/fresh-scoops/look-janella-salvador-bonds-with-her-dad-juan-mig-186859 `

### What happens?

If Fanboy Annoyances list is enabled, most of the page, including the article doesn't show up. Also, a "deactivate your adblocker" message shows up after a few seconds. Clicking on the confirm button on the message returns you to the initial page with most parts not showing up and then showing the "deactivate your adblocker" message again after a few seconds. If Fanboy Annoyances list is disabled while all other lists I use are enabled, the issue does not happen and the website appears just fine.

### List Subscriptions you're using:

all built-in uBlock filters 
EasyList
EasyPrivacy​​​​​
Fanboy’s Enhanced Tracking List​​​​
Fanboy’s Annoyance List​​​​​ (website shows up fine if only Fanboy’s Annoyance List is disabled)
Fanboy’s Anti-Thirdparty Social 
Fanboy’s Cookiemonster List​​​​​

### Your settings

- OS/version:  Windows 7
- Browser/version:  70.0.3538.77 (Official Build) (64-bit)
- Adblock Extension/version:  uBlock Origin v1.17.0

### Other details:

Screenshot with Fanboy Annoyances enabled:
![](https://user-images.githubusercontent.com/1404745/47987645-ffb12980-e11a-11e8-9e06-6cb82dbbdc60.png)

After a few seconds:
![](https://user-images.githubusercontent.com/1404745/47987661-0b9ceb80-e11b-11e8-9e0f-3ec2a15bc3d5.png)

Screenshot with Fanboy Annoyances disabled (EasyList and EasyPrivacy + other lists still enabled):
![taszhh5](https://user-images.githubusercontent.com/1404745/47987684-1bb4cb00-e11b-11e8-8a46-1d658afe6b75.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/65336e6f29e9fb35462ae5b569a609b1cca4e89b
https://github.com/ryanbr/fanboy-adblock/commit/4432a5f6def25ba87edd831f77af9dec2221011c
