### ISSUE TITLE
Please add *snowplowanalytics* to tracker list

### ISSUE THREAD

**Issue by forgetso** [ryanbr/fanboy-adblock#62]

**Comment by ryanbr** [comment]
got an example page?

**Comment by forgetso** [comment]
You can view it in action [here](https://www.secretescapes.com/)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3779feef8b570d1594d83438d2bfa39aceeefc01

**Comment by forgetso** [comment]
Thanks!
