### ISSUE TITLE
myszyniec.nowoczesnagmina.pl, mrozy.bip.net.pl

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#620]
### List the website(s) you're having issues: [](https://github.com/MajkiIT/polish-ads-filter/issues/9471)

`http://myszyniec.nowoczesnagmina.pl/`
`http://mrozy.bip.net.pl/`

### List Subscriptions you're using:

uBO default + Fanboy's Cookiemonster List

### Your settings

- OS/version: Windows 7
- Browser/version:  Opera 56
- Adblock Extension/version: uBlock Origin 1.17.0 

### Other details:

Cut body website: `##.show_cookie` filter guilty.

![image](https://user-images.githubusercontent.com/35370833/48003447-c5da2600-e10e-11e8-88cd-3afd04457bd3.png) |
--- |

![image](https://user-images.githubusercontent.com/35370833/48003482-d68a9c00-e10e-11e8-91d6-60b46cb4edfd.png) |
--- |

### Fix:

`myszyniec.nowoczesnagmina.pl,mrozy.bip.net.pl#@#.show_cookie`

**Comment by hawkeye116477** [comment]
Or you can just add `:not(body):not(html)` to rule `##.show_cookie`, so it will be `##.show_cookie:not(body):not(html)`.
