### ISSUE TITLE
hundeopversicherung-test.de: Cookie banner not blocked

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#622]
### List the website(s) you're having issues:
`https://www.hundeopversicherung-test.de/`

### What happens?
Cookie banner (very small at the top of website) not blocked

### List Subscriptions you're using:
fanboy's cookiemonster list

### Your settings

- OS/version: win7(64bit)
- Browser/version: firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.17.2

**Comment by smed79** [comment]
add
```
##.orakelAdvice
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/64e172f1bc5fb3e6b192228ac190efb91550155a
