### ISSUE TITLE
datanyze.com [GDPR/Cookie]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#623]
### List the website(s) you're having issues:

`
https://www.datanyze.com/`

### What happens?

GDPR/Cookie wall appears (breaks scroll if hidden)

### List Subscriptions you're using:

uBO default + Fanboy's Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBO 1.17.2

### Other details:

Screenshoot 1:

![ss1](https://user-images.githubusercontent.com/43844449/48050900-b78a1980-e1a3-11e8-9240-e80c13705fb9.png)

Screenshoot 2 (after checking all the 3 boxes) a button appears:

![ss2](https://user-images.githubusercontent.com/43844449/48052544-88c27200-e1a8-11e8-98ea-881395d479f8.png)

**Comment by krystian3w** [comment]
Inline script, I do not see the solution at the ABP, without any possible damage to the site.

```html
<script type="text/javascript">
var cookieName = 'CookieUsage';
var cookieValue = 'true';

function addGDPRCookie(){
	$( 'body' ).removeClass( 'overflow-hidden' );
	$( '.overlay-gdpr' ).addClass( 'hidden' );
	document.cookie = cookieName +"=" + cookieValue + ";expires=December 31, 2099;domain=.datanyze.com;";
	return false;
}

$( document ).ready( function() {
	if ( getCookie( cookieName ) ) {
		return;
	} else {
		$( '.overlay-gdpr' ).removeClass( 'hidden' );
		$( 'body' ).addClass( 'overflow-hidden' );
	}

});
</script>
```

**Comment by ryanbr** [comment]
When we have support for snippets for all abp. we'll relook at it.
