### ISSUE TITLE
animatedshortfilms.net / gayecho.com / mragus.com / auswandern.uy / loginissue.help / nasice.com / dollardestruction.com / portalcineindio.com / terradrift.com / tillystoreline.com / uniters.org / wpcolt.com / zistaz.com [Breakage - pages won't load - shadow overlay] [Fanboy’s Enhanced Tracking List]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#624]
### List the website(s) you're having issues:

```
http://animatedshortfilms.net/
http://gayecho.com/news/
http://mragus.com/
http://www.auswandern.uy/
http://www.loginissue.help/
http://www.nasice.com/
https://dollardestruction.com/
https://portalcineindio.com/
https://terradrift.com/
https://tillystoreline.com/
https://uniters.org/
https://wpcolt.com/
https://zistaz.com/

```
### What happens?

The websites are completely broken - an overlay appears.

### Example screenshoot 1 - Fanboy’s Enhanced Tracking List enabled:

![ss1](https://user-images.githubusercontent.com/43844449/48058250-3ee08880-e1b6-11e8-9e62-4ecfaee22009.png)

### Example screenshoot 2 - Fanboy’s Enhanced Tracking List disabled:
![ss1](https://user-images.githubusercontent.com/43844449/48058325-6c2d3680-e1b6-11e8-938c-47f71ac628fc.png)

### List Subscriptions you're using:

uBO default + 
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

**Comment by ryanbr** [comment]
I dont see issues with many of those sites, unless they are directly related (same company), then grouping many links like this isn't good. I'm not going to bother reviewing or fixing your issue reports if I see this again

**Comment by kulfoon** [comment]
> ryanbr : I dont see issues with many of those sites, unless they are directly related (same company), then grouping many links like this isn't good. I'm not going to bother reviewing or fixing your issue reports if I see this again

Great but next time paste the rules into README.md / CONTRIBUTING.md / issue_template.md file rather than in a ticket. Also - I intentionally placed several domains in one ticket to avoid being accused of spamming with too many tickets...
