### ISSUE TITLE
tutorialxiaomi.com / wotinfo.net / pilerats.com / wowthugger.com / alphahistory.com [Anti-Adblock] [Fanboy’s Enhanced Tracking List]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#625]
### List the website(s) you're having issues:

```
http://www.tutorialxiaomi.com/
http://wotinfo.net/
http://pilerats.com/
https://wowthugger.com/
https://alphahistory.com/
```

### What happens?

Anti-Adblock appears - triggered by Fanboy’s Enhanced Tracking List.
Enabling regional ABP Bindu (in case of `http://www.tutorialxiaomi.com/`) doesn't solve the issue.
Disabling Fanboy’s Enhanced Tracking List solves the issue on all the websites.

### List Subscriptions you're using:

uBO default + Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBO 1.17.2

### 1 `http://www.tutorialxiaomi.com/`

![ss1](https://user-images.githubusercontent.com/43844449/48062710-16ab5680-e1c3-11e8-9218-bb87b33c3966.png)

### 2 `http://wotinfo.net/`
![ss2](https://user-images.githubusercontent.com/43844449/48063104-4dce3780-e1c4-11e8-8704-c1659c58c429.png)

### 3 `http://pilerats.com/`
![ss3](https://user-images.githubusercontent.com/43844449/48063110-532b8200-e1c4-11e8-8be8-8fa706bd1c42.png)

### 4 `https://wowthugger.com/`
![ss4](https://user-images.githubusercontent.com/43844449/48063118-57f03600-e1c4-11e8-981c-34829ab8cbbd.png)

### 5 `https://alphahistory.com/`
![ss1](https://user-images.githubusercontent.com/43844449/48064459-1e212e80-e1c8-11e8-9254-669b93f89390.png)

**Comment by THEtomaso** [comment]
'**fuckadblock.js**' is whitelisted in '**Fanboy's Enhanced Tracking List**', by the following rule:
`@@/fuckadblock.$script`

Apparently, this seems to fix it:
`/fuckadblock.$script,important,domain=pilerats.com|tutorialxiaomi.com|wotinfo.net|wowthugger.com`
..but I'm not so sure that it is a proper solution, as I assume that the script is whitelisted for a good reason.

AlphaHistory only need a cosmetic fix:
`alphahistory.com###the_champ_sharing_more_providers`

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/52919561-40355b80-3336-11e9-9413-1523ef1951d7.png)
[
![image](https://user-images.githubusercontent.com/19517680/52919584-707cfa00-3336-11e9-93f2-aa070ce30bb1.png)
](url)
remove this rule
`@@/fuckadblock.$script`

**Comment by kulfoon** [comment]
3xploiton3 - I confirm the AA message on lewat.in, but from my experience I know that Fanboy doesn't look into closed issues, and he always says to create / reopen a new issue, so it seems that the best is to create so.

**Comment by 3xploiton3** [comment]
> 3xploiton3 - I confirm the AA message on lewat.in, but from my experience I know that Fanboy doesn't look into closed issues, and he always says to create / reopen a new issue, so it seems that the best is to create so.

ok thx for your attention
