### ISSUE TITLE
lyricsfreak.com

### ISSUE THREAD

**Issue by FadeMind** [ryanbr/fanboy-adblock#629]
### List the website(s) you're having issues:

`https://www.lyricsfreak.com/a/adam+nickey/letting+go_20849103.html`

### What happens?

Cookie popup overlay.

### List Subscriptions you're using:

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Cookiemonster List
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social
| Spam404

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1803 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth mode:					       | enabled

<details><summary><b>Screenshot:</b></summary>

![scr-1541610251-001](https://user-images.githubusercontent.com/9846948/48147537-d8439380-e2b7-11e8-93d8-cd21c9bb8485.png)

</details><br/>

**Comment by bogachenko** [comment]
I can not reproduce the pop up window with cookies as in the screenshot

**Comment by FadeMind** [comment]
Even If I leave enabled only Basic English and Cookiemonster - popup showup. Maybe this is related with Adguard specify blocking rules and it is not related with Cookiemonster at all.

CC @adamwr

**Comment by bogachenko** [comment]
Have you thought about switching to NORMAL blocker?
<https://github.com/gorhill/uBlock>

**Comment by smed79** [comment]
@Alex-302 Would you help here, please.

**Comment by Alex-302** [comment]
I don't see this popup enen without ad blocker and US proxy.
@FadeMind please show html code of this element.

**Comment by FadeMind** [comment]
@Alex-302 
![scr-1541616116-001](https://user-images.githubusercontent.com/9846948/48152851-3a56c580-e2c5-11e8-91b0-78a91f2eb190.png)
![scr-1541616177-001](https://user-images.githubusercontent.com/9846948/48152899-58242a80-e2c5-11e8-9745-bfb20679b8b5.png)

**Comment by FadeMind** [comment]
Guys, this will show up in EU countries against RODO 🇪🇺  cookie law notice. IN 🇺🇸  RODO does not work ❌

**Comment by Alex-302** [comment]
This is `AppNexus CMP` 
Added to AdGuard Annoyances filter: `/cmp/cmp.*.js`
