### ISSUE TITLE
vuokraovi.com

### ISSUE THREAD

**Issue by gitarra** [ryanbr/fanboy-adblock#63]
Same issue again as in here: https://forums.lanik.us/viewtopic.php?f=64&t=33595

Following rules break the Fonecta map embed from Fanboy’s Enhanced Tracking List:

[code]&referer=$image,domain=~24ur.com|~cdon.dk|~cdon.fi|~cdon.no|~cdon.se|~ratp.fr|~skype.com[/code]

[code]&referer=$script,domain=~24ur.com|~cdon.dk|~cdon.fi|~cdon.no|~cdon.se|~ratp.fr|~skype.com[/code]

E.g. here http://www.vuokraovi.com/vuokra-asunto/nurmijarvi/klaukkala/kerrostalo/kaksio/586008?locale=en

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/a1e196243ef930130387acf1d19edf4072882d77
