### ISSUE TITLE
The Guardian, cookie warning

### ISSUE THREAD

**Issue by aaaxx** [ryanbr/fanboy-adblock#632]
### List the website(s) you're having issues:

`https://www.theguardian.com`

### What happens?

Cookie warning banner pops up at the bottom of the page.

### List Subscriptions you're using:

Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 8.1 Pro
- Browser/version: Firefox Quantum 63.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin v1.17.2

### Other details:

![screenshot of the cookie warning](https://user-images.githubusercontent.com/6186480/48231795-b3cae280-e3af-11e8-8fdb-db66a87fc932.png)

**Comment by ryanbr** [comment]
Not seeing it.  already have this filter:

`##.site-message--first-pv-consent`

**Comment by aaaxx** [comment]
So what am I doing wrong? I've got Fanboy’s Cookiemonster List checked in uBlock Origin, and Guardian isn't on my whitelist. Any ideas?

**Comment by ryanbr** [comment]
are you using another subscription? maybe another sub is using theguardian.com^$generichide

**Comment by smed79** [comment]
@aaaxx test this filter
```
theguardian.com##.site-message--first-pv-consent
```
