### ISSUE TITLE
sourcepoint cookies notice

### ISSUE THREAD

**Issue by smed79** [ryanbr/fanboy-adblock#633]
### List the website(s) you're having issues:

```
beaute-addict.com
businessinsider.fr
caminteresse.fr
capital.fr
cuisineactuelle.fr
femmeactuelle.fr
gala.fr
geo.fr
prima.fr
programme-tv.net
programme.tv
voici.fr
```

### What happens?

Annoying sourcepoint cookies notice

### Screenshot

- https://i.imgur.com/9ahiooa.png

### List Subscriptions you're using:

- EasyList
- EasyPrivacy
- Fanboy's Annoyances

### Your settings

- Browser/version: Firefox 63
- Adblock Extension/version: Adblock Plus 3.4

### Filters:

```
||src.voici.fr^
||src.gala.fr
||source.femmeactuelle.fr^
||prima-fr.prima.fr^
||geo-fr.geo.fr
||capital-fr.capital.fr
||source.cuisineactuelle.fr^
||source.programme-tv.net^
||caminteresse-fr.caminteresse.fr^
||businessinsider-fr.businessinsider.fr^
||source.beaute-addict.com^
||source.programme.tv^
```
(https://forums.lanik.us/viewtopic.php?f=91&t=42106)

**Comment by ryanbr** [comment]
Would this help?

`##div[class^="sp_message_container"] > [class^="sp_message"] > [class^="sp_message_panel"]`

**Comment by smed79** [comment]
Yes.

**Comment by THEtomaso** [comment]
Video playback for most of those sites is already broken, because of the following rule (found in '**EasyList**'):
`/ima3.js`
This results in audio only.

The rule should probably be removed all together.
I've reported problems with before, here:
https://github.com/easylist/easylist/issues/1996/

**Comment by smed79** [comment]
> Video playback for most of those sites is already broken

Do you have an example?

**Comment by THEtomaso** [comment]
It seems to affect all of them.
I get a black screen with a spinning loading wheel, while the sound plays normally.

However, I have found a way around it..
By skipping back and forth in the videos seek bar, the video appears!

However, after adding the following exception rule, all videos play just fine, without any trickery:
`@@/ima3.js`
