### ISSUE TITLE
shoppable.com [Breakage] [FAL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#634]
### List the website(s) you're having issues:

`https://www.shoppable.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Annoyance List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

As per: https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-434293455 - possible fixes:
`shoppable.com#@##cookiesModal`

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Annoyance List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47718329-69779200-dc48-11e8-8f62-4cd6435617a0.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Annoyance List</summary>

![ss2](https://user-images.githubusercontent.com/43844449/47718439-b8bdc280-dc48-11e8-9e69-482b794842e8.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the cookie message (the page loading properly)</summary>

![zrzut1](https://user-images.githubusercontent.com/43844449/48310915-26e27d80-e597-11e8-9b3f-4f405d7eca0e.png)

</details>

**Comment by krystian3w** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-435299238

`||js.stripe.com^$script,domain=shoppable.com`

break functions on website?
