### ISSUE TITLE
foodnutritiontable.com [Breakage] [FAL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#635]
### List the website(s) you're having issues:

`http://www.foodnutritiontable.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Annoyance List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

As per: https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-434293455 - possible fixes:
`foodnutritiontable.com#@##cooMessage`

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Annoyance List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47719015-274f5000-dc4a-11e8-867d-ca2b7fe88f24.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Annoyance List</summary>

![ss2](https://user-images.githubusercontent.com/43844449/47719077-536ad100-dc4a-11e8-846e-cb2e1af0f0ec.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the cookie message (the page loading properly)</summary>

![ss3](https://user-images.githubusercontent.com/43844449/47719115-739a9000-dc4a-11e8-9f91-e0dfe7b13dfa.png)

</details>

**Comment by krystian3w** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-435299238

We can cut `###loading`
