### ISSUE TITLE
sportingnews.com [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#637]
### List the website(s) you're having issues:

`http://www.sportingnews.com/`

### What happens?

Breakage - the page won't load - completely broken + missing scroll bar

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

As per: https://github.com/ryanbr/fanboy-adblock/issues/616#issuecomment-435589053 - possible fixes:
`sportingnews.com#@#.qc-cmp-ui-container`

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47717419-ff5ded80-dc45-11e8-9401-0d2624c10fee.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47951087-18271580-df5c-11e8-8068-a1b80cef0494.png)

</details>

**Comment by ryanbr** [comment]
Okay closing. retested here. no issues here.
