### ISSUE TITLE
epson.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#638]
### List the website(s) you're having issues:

`https://www.epson.pl/`

### What happens?

Breakage - the page won't load - completely broken

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

As per: https://github.com/ryanbr/fanboy-adblock/issues/616#issuecomment-435589053 - possible fixes:
`epson.*#@#.flash.cookies`

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47717419-ff5ded80-dc45-11e8-9401-0d2624c10fee.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/48124875-b2999880-e27d-11e8-98e9-c6e1d82266ea.png)

</details>

**Comment by ryanbr** [comment]
Dont mind added, epson.pl#@#.flash.cookies  but I'm not seeing this filter being hit..

Filters affecting the site;
```

##.gdpr:not(body):not(html)
##.cookie-policy
```

**Comment by ryanbr** [comment]
Just re-test, re-open ticket or create a new one if its still an issue.
