### ISSUE TITLE
opentuition.com [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#639]
### List the website(s) you're having issues:

`https://opentuition.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Possible fixes: https://github.com/ryanbr/fanboy-adblock/issues/616#issuecomment-436198187

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss10](https://user-images.githubusercontent.com/43844449/48056682-97ae2200-e1b2-11e8-9936-45143f36dfc1.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/48056707-a563a780-e1b2-11e8-89fe-bc495af53edc.png)
</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss1a](https://user-images.githubusercontent.com/43844449/48056714-a8f72e80-e1b2-11e8-8dfd-14d09a93bfbe.png)

</details>

**Comment by ryanbr** [comment]
Not sure if its still an issue, update lists and retest.
