### ISSUE TITLE
filter for removing tradingview ads

### ISSUE THREAD

**Issue by sarmad84** [ryanbr/fanboy-adblock#64]
pleas make a filter for removing tradingview ads

**Comment by SMed79** [comment]
Do you have any example page/link?

**Comment by sarmad84** [comment]
https://www.tradingview.com/chart/?symbol=TVC%3ADXY

**Comment by SMed79** [comment]
Which ads? Please provide more details: browser, adblocker, filter lists, **screenshot**?

**Comment by sarmad84** [comment]
please review posts I send in this page:
https://greasyfork.org/en/forum/discussion/11401/x

**Comment by SMed79** [comment]
I cannot reproduce, no ads for me :interrobang:

**Comment by ryanbr** [comment]
`tradingview.com###tv-toasts`
and maybe? `@@||engine.adzerk.net^$xmlhttprequest,domain=tradingview.com`

**Comment by ryanbr** [comment]
Given the lack of feedback, I've just added the trackers only. Closing this.
