### ISSUE TITLE
nasice.com [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#640]
### List the website(s) you're having issues:

`http://www.nasice.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/48058250-3ee08880-e1b6-11e8-9e62-4ecfaee22009.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![ss1](https://user-images.githubusercontent.com/43844449/48058325-6c2d3680-e1b6-11e8-938c-47f71ac628fc.png)

</details>

**Comment by kulfoon** [comment]
The both fixes are working.

**Comment by ryanbr** [comment]
Testing in Firefox and Ubo. working fine here.
