### ISSUE TITLE
loginissue.help [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#650]
### List the website(s) you're having issues:

`http://www.loginissue.help/`

### What happens?

Breakage - the page won't load - shadow overlay (after closing anti-adblock message).

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - the anti-adblock message with or without enabling Fanboy’s Enhanced Tracking List</summary>

![ss_024](https://user-images.githubusercontent.com/43844449/48312123-62d30e00-e5aa-11e8-8529-3ff7b8fbca40.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after enabling Fanboy’s Enhanced Tracking List + after accepting the anti-adblock message</summary>

![ss_025](https://user-images.githubusercontent.com/43844449/48312131-7d0cec00-e5aa-11e8-9d65-8193d19f788c.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after disabling Fanboy’s Enhanced Tracking List + after accepting the anti-adblock message</summary>

![ss_026](https://user-images.githubusercontent.com/43844449/48312133-826a3680-e5aa-11e8-9aae-1413511033be.png)

</details>
.

Additional note: 

Because there is no "X/close/accept" button in the anti-adblock message window, to skip the message and reproduce the issue, you have to hide the message by filters for. ex. 
`www.loginissue.help##div[id][class]:-abp-has(> [class$="-default"])`
`www.loginissue.help##[class$="-bg"]`

**Comment by THEtomaso** [comment]
`@@||loginissue.help^$generichide` takes care of it.

**Comment by kulfoon** [comment]
You sure you have `Fanboy’s Enhanced Tracking List` enabled only, and not other Fanboy's lists like in the case here: https://github.com/ryanbr/fanboy-adblock/issues/648#issuecomment-437667491?

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`http://www.loginissue.help/`

### Issues:
* Anti-adblock message
* Shadow overlay

### Possible fix:
```
@@||loginissue.help^$generichide
/plugins/super-socializer/*
```

### Note:
* `/plugins/super-socializer/*` is needed for '**Fanboy's Enhanced Tracking List**', since the overlay is triggered by the following blocking rule:
`/favicon.ico$image,third-party`
