### ISSUE TITLE
farmacja.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#654]
### List the website(s) you're having issues:

`https://farmacja.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_010](https://user-images.githubusercontent.com/43844449/48342025-f1a95e80-e66e-11e8-8643-7b8c448a7acb.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_012](https://user-images.githubusercontent.com/43844449/48342050-fa019980-e66e-11e8-9a8d-03eecd147f8e.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_014](https://user-images.githubusercontent.com/43844449/48342057-ff5ee400-e66e-11e8-8e9d-3a9364d2a6a8.png)

</details>

**Comment by THEtomaso** [comment]
### Affected site:
`https://farmacja.pl/`

### Issue:
Modal backdrop prevents site navigation.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`##.rodo-modal`

### Possible fix:
`farmacja.pl#@#.rodo-modal`

**Comment by krystian3w** [comment]
Only unlock pop-up...
