### ISSUE TITLE
obiektyspa.com [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#655]
### List the website(s) you're having issues:

`http://www.obiektyspa.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_011](https://user-images.githubusercontent.com/43844449/48342147-3d5c0800-e66f-11e8-825d-c7677127e708.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_013](https://user-images.githubusercontent.com/43844449/48342161-4351e900-e66f-11e8-9e6d-e92a12c54c91.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_015](https://user-images.githubusercontent.com/43844449/48342166-48169d00-e66f-11e8-859a-1b0b7bb683b0.png)

</details>

**Comment by THEtomaso** [comment]
Are you searching all these sites up through `PublicWWW.com` or something?
This will get out of control real fast.
Instead of flooding the issue tracker with a huge amount of identically affected sites, I think we should first try to solve the ones that you've already posted.
Then it will be a simple of matter of testing the fixe(es) that we come up with for similar sites afterwards.
What do you think, kulfoon..
Should we take a look at the ones that you've already reported?

**Comment by THEtomaso** [comment]
Here's a summary for `obiektyspa.com`:

### Affected site:
`http://www.obiektyspa.com/`

### Issue:
Modal backdrop prevents site navigation.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`###privacy-alert`

### Possible fix:
`obiektyspa.com#@##privacy-alert`

**Comment by THEtomaso** [comment]
Now, test the fixes that I've already provided, and include the problem rules and potential fixes in your initial reports.
This will make things a lot easier for ryanbr.

**Comment by THEtomaso** [comment]
> krystian3w reacted with confused emoji

ryanbr specifically gave these instructions himself, here:
https://github.com/ryanbr/fanboy-adblock/issues/611#issuecomment-437544084
..and here:
https://github.com/ryanbr/fanboy-adblock/issues/616#issuecomment-437544215

> submit a ticket per website, **with a suggestion of fix**. I dont have the time to go through this.

**Comment by krystian3w** [comment]
Maybe he did not want to add overlay cutting, I'm not there for unlocking the pop-up (scroll works), until someone finds a problem with unloaded graphics / images, comments, video.

**Comment by smed79** [comment]
Fooding this repo is very annoying and will have negative effect. Unsubscribed...

**Comment by THEtomaso** [comment]
> ryanbr told me to not do so

He also told you to include "**a suggestion of fix**".
That's what I tried to point out.

**Comment by kulfoon** [comment]
> THEtomaso : He also told you to include "**a suggestion of fix**".

As for it, I've skipped that part because have seen you posting suggestions of fix in all my issues, so I thought you like to post fixes, so I left fixes for you, as seen now - all my issues have now suggestions of fix attached by you, it seems like a good cooperation!

> THEtomaso : Also, if we really were to check every problem rule up against PublicWWW.com, many filters would have to include hundreds of thousands exception rules, to cover all the obscure sites that exist!

I don't get it, if I find an issue, I report it, that's what an issue tracker is for, a filters list must not break websites, and I don't check rules against publicwww, I randomly and accidentaly find broken websites and add them to bookmarks, if a reasonable ammount of them gets bookmarked I report issues. Also just take a look at these huge filters Do you want to stop reporting issues and let the filter list stay bugged or what or maybe consider closing the issue tracker then.

> THEtomaso : many filters would have to include hundreds of thousands exception rules, to cover all the obscure sites that exist!

There already are several lists like EasyList or uBlock filters that contain such huge filters (which contain hundreds of domains attached to a filter) and what is the problem with Fanboy's Lists having them too?

**Comment by THEtomaso** [comment]
I'm not harassing you.
You didn't answer my question regarding `PublicWWW.com` earlier, so I simply pointed out the "downside" of using it.
Extremely large filter lists are not preferable, in regards to performance.

**Comment by kulfoon** [comment]
> THEtomaso : Extremely large filter lists are not preferable, in regards to performance.

So what is your point, 

- limit how many broken websites can be reported to the issue tracker (like one per day/ week)?
- or you gonna cherry-pick which broken websites to be fixed (more popular / important ones), and which ones to be not fixed (less popular/important ones)?
- and what about the rest of broken unfixed websites? Should not all broken websites be fixed? If people  can't visit a webpage because it's broken by a list, they will simply disable the list or even completely stop using it. Do you want people to use the list or to not use the list? If you want them to use it, broken websites must be fixed. People don't want to use lists which break so many websites.

Also as per `https://github.com/uBlockOrigin/uBlock-issues#ublock-issues`

> **Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data + analysis supporting the claim.**

(despite the fact that these are the rules froms another issue tracker, but it's true that speculated performance issues should be proven by some analysis data.)

Do you have any profilng data to prove your performance issues? (Not just the fact that adding every filter takes a small ammount of additional resources, but any kind of slowdown, lag , freeze or limit how many filters can be added to a list - 40000, 50000 etc?)

**Comment by THEtomaso** [comment]
> So what is your point

My point was that people shouldn't flood the issue tracker with obscure websites, found through `PublicWWW.com`.
..but you have clearly stated that you don't use it now, so don't worry. :)

> Do you have any profilng data to prove your performance issues?

Here's a recent example, regarding a filter which was trimmed down a lot:
https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-437710556

**Comment by THEtomaso** [comment]
I've wasted enough time on this.
All worth saying has already been said.

**Comment by THEtomaso** [comment]
Indeed, I see things being turned upside down in this thread.
Especially when it comes to "trollish behaviour".

I've only been helping you with all the issues that you've been reporting.
My suggestions (which you are so offended by), were only given to prevent all of your reports from being closed again, without being fixed.

**Comment by kulfoon** [comment]
No arguments = no conversation, stop speculations, stop hijacking the thread, I'll ignore you.

**Comment by THEtomaso** [comment]
@kulfoon:

Earlier, I got the feeling that you were only trying to pick a fight, for reasons that was beyond my understanding.
But this question of yours makes me wonder if it was all because of a simple misunderstanding:

> Can you give me example links to one or more of my issues here containing "obscure" website?

I haven't called any of the sites that you've pointed out in your reports "obscure".
The reason why I warned about obscure sites, is that you posted a large amount of identically affected pages, all within a short period of time.
I therefore suspected that you searched those sites up through `PublicWWW.com`, and simply warned you about the potential downside of using that search engine.

Does this clear things up?
I don't want there to be any "bad blood" between us, for no reason at all!

**Comment by kulfoon** [comment]
> THEtomaso : Earlier, I got the feeling that you were only trying to pick a fight, for reasons that was beyond my understanding.

I didn't fight, because I don't need to fight, because I have arguments, and those who have arguments don't need to fight, but they need to defend against those who are out of arguments and who keep too much speculating / talking / pressing on the basis of their feelings or trolling. So if I would use your vocabulary I would say that it was you who began the "fight", and now seeing you calling me the one, I can say I'm getting the "feeling" you're just continuing your turning things upside down to make me look like the one who began the "fight".

> THEtomaso : I haven't called any of the sites that you've pointed out in your reports "obscure"...

 I've been aware of that, so all that is not because of that, but because still you've been talking too much and too hard about it like I've been posting a lot of "obscure" pages, wherein I have been not a single one.

> THEtomaso : simply warned you

nope, as written above, too much pressure / talking / speculations / feelings from you side, without a single real case provided in the both cases: the "obscure" page, and the "performance". Why even talking so much.
