### ISSUE TITLE
Cookie banner not blocked: www.kek-online.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#658]
### List the website(s) you're having issues: 
`https://www.kek-online.de/`

### What happens?
Cookie banner not Blocked

### List Subscriptions you're using: 

Fanboy's Cookiemonster List

### Your settings

- OS/version: Win7(64bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.17.2

**Comment by ryanbr** [comment]
Unlikely this can be fixed, until we get snippet support.
