### ISSUE TITLE
mobile.twitter.com

### ISSUE THREAD

**Issue by LESHIY-ODESSA** [ryanbr/fanboy-adblock#66]
Hello

https://mobile.twitter.com/

When the built cosmetic filters it does not open the two buttons ("Report" and "retweet") causing pop-up menu.

http://i.imgur.com/rIyXr79.gif

**Comment by ryanbr** [comment]
caused by: `mobile.twitter.com##[data-reactroot] > [class] + [class]:last-child`

I'll see if there is better work around / filter.

**Comment by ryanbr** [comment]
Might be resolved already? I don't see it anymore.

**Comment by LESHIY-ODESSA** [comment]
SORRY!!! Everything works great, thank you.

P.S. I'm not used to closing tickets. :)
