### ISSUE TITLE
poszalu.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#661]
### List the website(s) you're having issues:

`https://poszalu.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/48547712-8c9e7480-e8cb-11e8-9bb5-9b94dfa06728.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_006](https://user-images.githubusercontent.com/43844449/48547720-9031fb80-e8cb-11e8-868f-ef5c59971f73.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_014](https://user-images.githubusercontent.com/43844449/48547801-c2dbf400-e8cb-11e8-903f-6436d9005c23.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`https://poszalu.pl/`

### Issue:
Blocked GDPR consent prevents site navigation (Modal backdrop overlay).

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`###gdpr-modal`

### Possible fix:
`poszalu.pl#@##gdpr-modal`

**Comment by krystian3w** [comment]
Bad photos, I support the exclusion due to blocked page scrolling.
