### ISSUE TITLE
przedawnione.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#662]
### List the website(s) you're having issues:

`https://przedawnione.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_003](https://user-images.githubusercontent.com/43844449/48547926-fdde2780-e8cb-11e8-9f91-cbaac331d22f.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_007](https://user-images.githubusercontent.com/43844449/48547989-1c442300-e8cc-11e8-840a-3462cf32717a.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_015](https://user-images.githubusercontent.com/43844449/48547998-223a0400-e8cc-11e8-8203-1de3e8b8eeb8.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`https://przedawnione.pl/`

### Issue:
Blocked cookie-related popup prevents site navigation (Modal backdrop overlay).

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`##div[data-nconvert-cookie]`

### Possible fix:
`przedawnione.pl#@#div[data-nconvert-cookie]`
