### ISSUE TITLE
spkomandytowa.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#663]
### List the website(s) you're having issues:

`http://spkomandytowa.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_004](https://user-images.githubusercontent.com/43844449/48548086-62998200-e8cc-11e8-97b0-7a49e732facf.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_008](https://user-images.githubusercontent.com/43844449/48548089-64fbdc00-e8cc-11e8-91b4-12e60528c5fc.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_016](https://user-images.githubusercontent.com/43844449/48548095-688f6300-e8cc-11e8-96cd-393369b16560.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`http://spkomandytowa.pl/`

### Issue:
Blocked cookie-related popup prevents site navigation (Modal backdrop overlay).

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`##div[data-nconvert-cookie]`

### Possible fix:
`spkomandytowa.pl#@#div[data-nconvert-cookie]`
