### ISSUE TITLE
kartanauczycielablog.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#664]
### List the website(s) you're having issues:

`http://kartanauczycielablog.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_001](https://user-images.githubusercontent.com/43844449/48569312-9e027380-e901-11e8-984c-0a8b8d613fd9.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/48569319-a2c72780-e901-11e8-9217-5654206e53c7.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_003](https://user-images.githubusercontent.com/43844449/48569324-a8247200-e901-11e8-9d3f-cce896c17b21.png)

</details>

**Comment by THEtomaso** [comment]
Duplicate:
https://github.com/ryanbr/fanboy-adblock/issues/661/

**Comment by kulfoon** [comment]
Not anymore, it was copy & paste error, had to be another website, I've just reedited the issue.

**Comment by krystian3w** [comment]
Remove `##div[data-nconvert-cookie]`? 
It will turn out once that there will be more exceptions than correct cutting out cookies.
