### ISSUE TITLE
Ads on video player pages (kissanime.ru, masterani.me)

### ISSUE THREAD

**Issue by ghost** [ryanbr/fanboy-adblock#665]
`http://kissanime.ru/Anime/Karakuri-Circus/Episode-006?id=152262&s=default`

`https://ptocmaux.com/` host does these ads (some already blocked, but looks like not block enough on Fanboy Ultimate list)

![kissanimeplayerads](https://user-images.githubusercontent.com/21213705/48570019-ede63800-e90b-11e8-9fe1-2fa4351752f4.png)

https://www.masterani.me/anime/watch/3011-karakuri-circus/6

`https://www.masterani.me/static/hoho/` does these ads.

![masteranimeplayerads](https://user-images.githubusercontent.com/21213705/48570037-fb032700-e90b-11e8-9082-835e610e35f4.png)

**Comment by Karmesinrot** [comment]
Adguard Base filters fixes both these issues
