### ISSUE TITLE
Cookie banner not blocked: instagram.com

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#668]
### List the website(s) you're having issues: 
`https://www.instagram.com/` 

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:

fanboy's cookiemonster list
### Your settings

- OS/version: win7 (64bit)
- Browser/version: firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.17.2

**Comment by krystian3w** [comment]
`instagram.com##.lOPC8`  - class can change quickly
`instagram.com#?#body > span > section > div:-abp-has(.coreSpriteDismissLarge)` - lazy

**Comment by ryanbr** [comment]
##.lOPC8
