### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#669]
### URL(s) where the issue occurs

`https://www.filmweb.pl/film/Dziewczyny+do+wzi%C4%99cia-1972-5307/posters`

### Describe the issue

Cookie overlay annoyance.

### Versions

- Browser/version: Firefox 63
- uBlock Origin version: uBlock Origin 1.17.2

### Settings

+Fanboy’s Annoyance List

**Comment by ryanbr** [comment]
Cant fix this
