### ISSUE TITLE
sentraali.fi cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#671]
### List the website(s) you're having issues:

`https://www.sentraali.fi/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy’s Cookiemonster List

### Your settings

    OS/version: Windows 10
    Browser/version: Firefox 63.0.3
    Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

A filter that would fix it would be:

`www.sentraali.fi###popmake-4055`

**Comment by ryanbr** [comment]
Sure, didn't see it. Taking your word.
