### ISSUE TITLE
youtube.com osd keyboard not showing properly

### ISSUE THREAD

**Issue by giann3** [ryanbr/fanboy-adblock#674]
The onscreen keyboard does not show both on youtube and google, using ublock origin, chrome 70.0.3538.102, windows 10, if i disable "Fanboy’s Annoyance List​​​​​​​​​" it works again.

**Comment by THEtomaso** [comment]
### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.vk-btn`

### Possible fix:
```
google.*#@#.vk-btn
youtube.com#@#.vk-btn
```

### Note:
I don't see any onscreen keyboard at `YouTube.com`, so that last exception rule is just a guess.

**Comment by ryanbr** [comment]
sure.

**Comment by THEtomaso** [comment]
@ryanbr:

The exception rule that you added only covers `youtube.com`.
I were only able to find the onscreen keyboard that giann3 refered to at `google.com`, where I confirmed the issue.
E.g. here (right next to the search box):
`https://www.google.com/maps/`

**Comment by smed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=42152
