### ISSUE TITLE
wars.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#675]
### List the website(s) you're having issues:

`https://wars.pl/`

### What happens?

Breakage - the page won't load - shadow overlay.

### List Subscriptions you're using:

uBO default + uBO annoyances +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/48702823-36467400-ebf2-11e8-9b5c-c2f7f6bde4e0.png))

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_005](https://user-images.githubusercontent.com/43844449/48702831-3b0b2800-ebf2-11e8-9597-8b78e24012f7.png)

</details>
.
<details not-open>
<summary>screenshoot 3 - after accepting the messages</summary>

![ss_010](https://user-images.githubusercontent.com/43844449/48702925-86bdd180-ebf2-11e8-9e29-6447f1791157.png)

</details>
.

Example fix: I have no time for looking for fixes for endless breakages, consider refactoring the list so that it  doesn't break so many websites, optionally I can stop to use this problematic list.

**Comment by krystian3w** [comment]
`###spu-bg-1773` or propose "generic": https://github.com/ryanbr/fanboy-adblock/issues/677#issuecomment-440580824

> ```
> ##DIV.spu-bg[id]:not(body):not(html)
> ```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/982c2703d7eeec14ac80075f81a51b0ae63c065f
