### ISSUE TITLE
warunki-zabudowy.com.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#676]
### List the website(s) you're having issues:

`https://warunki-zabudowy.com.pl/`

### What happens?

Breakage - the page won't load - shadow overlay.

### List Subscriptions you're using:

uBO default + uBO annoyances +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_003](https://user-images.githubusercontent.com/43844449/48703285-7fe38e80-ebf3-11e8-908d-b22b4833ba35.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_006](https://user-images.githubusercontent.com/43844449/48703293-84a84280-ebf3-11e8-876c-c3a56dab78f9.png)

</details>
.
<details not-open>
<summary>screenshoot 3 - after accepting the messages</summary>

![ss_011](https://user-images.githubusercontent.com/43844449/48703366-b6210e00-ebf3-11e8-857b-9a466bca7a30.png)

</details>
.

Example fix: I have no time for looking for fixes for endless breakages, consider refactoring the list so that it  doesn't break so many websites, optionally I can stop to use this problematic list.

**Comment by krystian3w** [comment]
newsletter, We need thing about delete `##div[data-nconvert-cookie]`
