### ISSUE TITLE
bezprawaanirusz.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#677]
### List the website(s) you're having issues:

`https://bezprawaanirusz.pl/`

### What happens?

Breakage - the page won't load - shadow overlay.

### List Subscriptions you're using:

uBO default + uBO annoyances +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_004](https://user-images.githubusercontent.com/43844449/48703442-09935c00-ebf4-11e8-99c6-feb8271ed47b.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_007](https://user-images.githubusercontent.com/43844449/48703452-0e581000-ebf4-11e8-8366-9acb646b6ba2.png)

</details>
.
<details not-open>
<summary>screenshoot 3 - after accepting the messages</summary>

![ss_012](https://user-images.githubusercontent.com/43844449/48703459-144df100-ebf4-11e8-98b4-cbcdb98b44bb.png)

</details>
.

Example fix: I have no time for looking for fixes for endless breakages, consider refactoring the list so that it  doesn't break so many websites, optionally I can stop to use this problematic list.

**Comment by krystian3w** [comment]
Again newsletter and generic `##div[data-nconvert-cookie]`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/982c2703d7eeec14ac80075f81a51b0ae63c065f
