### ISSUE TITLE
naszefutrzaki.eu [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#678]
### List the website(s) you're having issues:

`https://naszefutrzaki.eu/`

### What happens?

Breakage - some cookie message remains.

### List Subscriptions you're using:

uBO default + uBO annoyances +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss_014](https://user-images.githubusercontent.com/43844449/48704133-17e27780-ebf6-11e8-8450-3732da679066.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss_013](https://user-images.githubusercontent.com/43844449/48704139-1b75fe80-ebf6-11e8-9b61-00866ac96f9c.png)

</details>
.
<details not-open>
<summary>screenshoot 3 - after accepting the messages</summary>

![ss_015](https://user-images.githubusercontent.com/43844449/48704154-26c92a00-ebf6-11e8-9532-4fb725c34a45.png)

</details>
.

Example fix: I have no time for looking for fixes for endless breakages, consider refactoring the list so that it  doesn't break so many websites, optionally I can stop to use this problematic list.

**Comment by krystian3w** [comment]
`naszefutrzaki.eu##.cookies`
