### ISSUE TITLE
kotimikro.fi subpage breakage

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#679]
Hi!

On this domain, Cookiemonster blocks the cookie popup as it should, but it also breaks a separate subpage where this site gives a detailed information about their cookie usage. It should not be blocked.

Here is the subpage (word "evästepolitiikka" means cookie policy in English):

`https://kotimikro.fi/evastepolitiikka`

This whitelist filter fixes the problem:

`@@||cookieinformation.com/$script,domain=kotimikro.fi`

Also after that this filter should be added as well because it blocks the top bar that is only used to host a link for the cookie policy. It's unnecessary as the link (evästepolitiikka) is also on the bottom of the webpage:

`kotimikro.fi##.hidden-xs.afubar-top`

**Comment by ryanbr** [comment]
Not seeing it.
