### ISSUE TITLE
Imgur sticky header

### ISSUE THREAD

**Issue by TeffenEllis** [ryanbr/fanboy-adblock#68]
Is it possible to remove the block for  `imgur.com###post-jump-container` from the annoyance list?

This header appears when scrolling through a long list of images. Without it you'll have to scroll all the way back up the gallery, or reach to the keyboard and use the arrows.

Cheers

**Comment by SMed79** [comment]
> People should know how to use the scroll bar/scroll wheel on mouse or arrow keys, We don't need a button overlay to do this.

https://forums.lanik.us/viewtopic.php?p=112841#p112841

**Comment by TeffenEllis** [comment]
@SMed79,

This is a matter of accessibility. It's a bit extreme to require users to decide between using the annoyance list or using imgur with their mouse.

**Comment by SMed79** [comment]
add as custom filter

`imgur.com##.post-jump-container`
