### ISSUE TITLE
ScandinavianSoul.com - Modal backdrop (Fanboy's Annoyance List + Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#682]
### Affected site:
`https://scandinaviansoul.com/`

### Issue:
The cookie consent is blocked by the following rule (found in **Fanboy's Annoyance Lis**t and **Fanboy's Cookie List**):
`##div[data-cookie]`
..but the modal backdrop remains, preventing site access.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Possible fix:
Simply block the modal backdrop too, with this rule:
`scandinaviansoul.com###overlay_rstbox_2`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/100366ec9b567dd1e91ba7e57532f2ae2fdbb418
