### ISSUE TITLE
"##.socialbutton" exception

### ISSUE THREAD

**Issue by zanetu** [ryanbr/fanboy-adblock#69]
<ul role="menu" class="dropdown-menu socialbutton">

1. Go to https://jobs.realogy.com/job/New-York-Executive-Assistant-NY/387424900/
2. Click "Apply now"
Expected: 
Dropdown-menu is shown.
Actual: 
Dropdown-menu is not shown.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cb2a98e4d9237890f43a6659b458a3ee14ba8e66
