### ISSUE TITLE
 albeco.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [ryanbr/fanboy-adblock#690]
### List the website(s) you're having issues:
` albeco.com.pl`

### What happens?

GDPR message.

### List Subscriptions you're using:

![screenshot_20181125_125344](https://user-images.githubusercontent.com/19818572/48978768-2ecf1100-f0b1-11e8-8402-173f5b7151f4.png)

### Your settings

- OS/version: Manjaro Linux 18
- Browser/version: Vivaldi 2.1.1337.47
- Adblock Extension/version: Nano Adblocker v1.0.0.77

### Other details:
![obraz](https://user-images.githubusercontent.com/44813765/48978454-fb3db800-f0ab-11e8-866a-6e3843d044b2.png)
It should be blocked by `||www.albeco.com.pl/scripts/jquery/plugins/cookie/jquery.cookie.js`, but that rule `@@/cookie*/jquery.cookie.js$script,~third-party` whitelist it, so I propose to change that to `@@/cookie*/jquery.cookie.js$script,~third-party,domain=~albeco.com.pl`.

https://github.com/MajkiIT/polish-ads-filter/issues/10183

**Comment by ryanbr** [comment]
i could see this causing issues elsewhere

**Comment by ryanbr** [comment]
Okay, added. but if it causes issues. re-open ticket.
