### ISSUE TITLE
NYTimes.com [Issue #483 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#692]
One more exception rule is needed for '**Fanboy's Annoyance List**' and '**Fanboy's Cookie List**':
`https://github.com/ryanbr/fanboy-adblock/issues/483/#issuecomment-433690831`

**Comment by ryanbr** [comment]
blocking the notification is too important, and works well. no issues, which is why its left.

**Comment by THEtomaso** [comment]
No, it does NOT work well!
Depending on your location, some videos won't play.
E.g. this one:
`https://www.nytimes.com/2018/09/24/style/robot-furniture-beep-beep-boop.html`

I've already pointed this out before, in my post here:
`https://github.com/ryanbr/fanboy-adblock/issues/483/#issuecomment-425114662`

**Comment by THEtomaso** [comment]
@ryanbr:

The issue has been confirmed by krystian3w here:
https://github.com/AdguardTeam/AdguardFilters/issues/25957#issuecomment-441597918

**Comment by THEtomaso** [comment]
Also confirmed by DandelionSprout now (with detailed proof):
https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-441990973
