### ISSUE TITLE
www.sandisk.com Cookiemonster list breaks the page

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#693]
### List the website(s) you're having issues:

`https://www.sandisk.com/`

### What happens?

I try to access Sandisk web page but it's blank

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 63.0.3
- Adblock Extension/version: Ublock Origin 1.17.2

### Other details:

Webpage works if I disable Cookiemonster, set cookie settings and then re-enable the list.

**Comment by THEtomaso** [comment]
When connecting from my location (Norway), there is no such issue.
But when I tried to connect through a US proxy, I got a white page, just like you described.

It seems to be caused by the following rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Cookie List**'):
`###consent_blackbar`

Does this exception rule fix the problem at your end (add to 'My filters' in uBO)?:
`sandisk.*#@##consent_blackbar`

**Comment by peace2000** [comment]
Norway is not part of EU so that's the reason I guess ;)

I'm from Finland.

But this filter
`sandisk.*#@##consent_blackbar`

Fixes the problem. Thank you and hopefully list upkeepers will fix this also.

**Comment by THEtomaso** [comment]
Yeah, this stuff can be really confusing sometimes.
And it makes things very difficult for filter authors too, when it comes to confirming GDPR-related issues.

**Comment by THEtomaso** [comment]
@peace2000:

The '**I don't care about cookies**' filter also breks those pages, with the following rule:
`###consent_blackbar:not(body):not(html):not(.mm-page)`
I've reported the issue to the filter's author.

**Comment by peace2000** [comment]
> 
> 
> @peace2000:
> 
> The '**I don't care about cookies**' filter also breaks those pages, with the following rule:
> `###consent_blackbar:not(body):not(html):not(.mm-page)`
> I've reported the issue to the filter's author.

That's good.

Sites change, maybe these rules have worked fine before.

**Comment by kiboke** [comment]
The problematic rule will be be removed from the next version of "I don't care about cookies".

**Comment by ryanbr** [comment]
I tested on a Norway and French IP, couldn't see it?

**Comment by kiboke** [comment]
I see it without proxies from croatia on sandisk.com.

**Comment by peace2000** [comment]
> 
> 
> I tested on a Norway and French IP, couldn't see it?

Norway cannot be used for testing because it's not part the EU. France is however so it's strange that it's working fine for you.

However kiboke had this issue at least.

`###consent_blackbar` is not anyway necessary on sandisk.com since even if I whitelist that rule I don't see a cookie notification.

**Comment by THEtomaso** [comment]
> I tested on a Norway and French IP, couldn't see it?

Try using the USA proxy here:
`https://hide.me/en/proxy/`
That's how I confirmed it.

--

**OFF-TOPIC:**
Also, ryanbr; read my reply here:
https://github.com/ryanbr/fanboy-adblock/issues/692#issuecomment-441579791

**Comment by ryanbr** [comment]
A screenshot of the before and after will help

**Comment by THEtomaso** [comment]
That screenshot would be entirely white (blank page)! :)

**Comment by krystian3w** [comment]
Me too se without proxy and UE conuntry:


![image](https://user-images.githubusercontent.com/35370833/49008998-9cda0d80-f16f-11e8-9915-ac304041db19.png) |
--- |
![image](https://user-images.githubusercontent.com/35370833/49008982-8cc22e00-f16f-11e8-9528-cd906b6eb748.png) |

**Comment by peace2000** [comment]
![sandisk blank](https://user-images.githubusercontent.com/17256841/49009270-d06d6580-f178-11e8-9399-38653c0a8580.png)
![sandisk work](https://user-images.githubusercontent.com/17256841/49009275-d2cfbf80-f178-11e8-8f26-b65263899e0a.png)

Here are my screenshots. It works when that whitelist rule THEtomaso provided, is applied.

Interestingly I noticed that Cookiemonster is blocking this request on the background:

`https://consent.trustarc.com/notice?domain=sandiskgdpr.com&c=teconsent&cdn=1&gtm=1&text=true&language=en`

**Comment by kiboke** [comment]
"I don't care about cookies" also blocks it, that's why the CSS blocking rule isn't needed at all anymore.

**Comment by THEtomaso** [comment]
@ryanbr:

You exception rule only covers the `.com` domains.
What about the rest of them?:
```
http://www.sandisk.cn/
https://www.sandisk.ae/
https://www.sandisk.co.uk/
https://www.sandisk.com.au/
https://www.sandisk.com.br/
https://www.sandisk.co.jp/
https://www.sandisk.co.kr/
https://www.sandisk.com.tr/
https://www.sandisk.com.tw/
https://www.sandisk.de/
https://www.sandisk.es/
https://www.sandisk.fr/
https://www.sandisk.hk/
https://www.sandisk.id/
https://www.sandisk.in/
https://www.sandisk.it/
https://www.sandisk.nl/
https://www.sandisk.sg/
```
I tried a few of them, and they're also affected!

**Comment by krystian3w** [comment]
If he finds the time, he will probably add other language versions, if there is no list of domains (hidden by javascript slide menu), it is difficult to do it yourself.

optionally old:

```css
:not(body):not(html)
```

**Comment by peace2000** [comment]
> 
> 
> @ryanbr:
> 
> Your exception rule only covers the `.com` domains.
> What about the rest of them?:
> 
> ```
> https://www.sandisk.ae/
> http://www.sandisk.cn/
> https://www.sandisk.co.uk/
> https://www.sandisk.com.au/
> https://www.sandisk.com.br/
> https://www.sandisk.co.jp/
> https://www.sandisk.co.kr/
> https://www.sandisk.com.tr/
> https://www.sandisk.com.tw/
> https://www.sandisk.de/
> https://www.sandisk.es/
> https://www.sandisk.fr/
> https://www.sandisk.hk/
> https://www.sandisk.id/
> https://www.sandisk.in/
> https://www.sandisk.it/
> https://www.sandisk.nl/
> https://www.sandisk.sg/
> ```
> 
> I tried a few of them, and they're also affected!

I have issues also with those. Good that you pointed them out.

So instead of using
`sandisk.com#@##consent_blackbar `

this should be applied
`sandisk.*#@##consent_blackbar`

**Comment by krystian3w** [comment]
> this should be applied
> `sandisk.*#@##consent_blackbar`

`sandisk.*#@##consent_blackbar` not supported by Adblock Plus 3.4.1

**Comment by THEtomaso** [comment]
Use this then:
`sandisk.ae,sandisk.cn,sandisk.co.uk,sandisk.com,sandisk.com.au,sandisk.com.br,sandisk.co.jp,sandisk.co.kr,sandisk.com.tr,sandisk.com.tw,sandisk.de,sandisk.es,sandisk.fr,sandisk.hk,sandisk.id,sandisk.in,sandisk.it,sandisk.nl,sandisk.sg#@##consent_blackbar`
