### ISSUE TITLE
cbc.ca

### ISSUE THREAD

**Issue by adranger** [ryanbr/fanboy-adblock#694]
### List the website(s) you're having issues:
`https://www.cbc.ca/`

### What happens?

Cookie notice.

### List Subscriptions you're using:

Fanboy’s Annoyance List

### Your settings

- Browser/version: 63.0.3 (64-bit)
- Adblock Extension/version: uBlock Origin 1.17.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8e824f9e0c46524637bc563065f1745f27090669
