### ISSUE TITLE
Cookie banner not blocked: soeren-hentzschel.at

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#699]
### List the website(s) you're having issues: 
`https://www.soeren-hentzschel.at/`

### What happens? 
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookiemonster list

### Your settings

- OS/version: Win7 (64 bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.17.2

**Comment by ryanbr** [comment]
Should be resolved.
