### ISSUE TITLE
Wrongly blocked map at https://www.4ka.sk/

### ISSUE THREAD

**Issue by JacobFascinator** [ryanbr/fanboy-adblock#7]
With  Fanboy’s Annoyance List‎ turned ON, the entire map of this carriers coverage disappears,
I dont know how to find out which rule blocks it,

please fix it,

Thanks

**Comment by SMed79** [comment]
I have annoyance list‎ enabled http://i.imgur.com/X45Zf77.jpg 
Could you be more specific and give more details (browser? adblocker? lists? addons? screenshot?).

**Comment by JacobFascinator** [comment]
Oh, sorry, I forgot to add the exact link, its 

https://www.4ka.sk/mapa-pokrytia

My apology :/ (Firefox, uBlock origin)

**Comment by SMed79** [comment]
add:
`@@||4ka.sk/js/cookiebar.min.js`

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/9f11eb8aaac3

**Comment by JacobFascinator** [comment]
Now its fixed, that was really fast

Thanks!

**Comment by ryanbr** [comment]
Issue closed?
