### ISSUE TITLE
niania.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#700]
Just like in here https://github.com/ryanbr/fanboy-adblock/issues/697 and here https://github.com/ryanbr/fanboy-adblock/issues/698

### List the website(s) you're having issues:

`https://www.niania.pl/`

### What happens?

Breakage of Cookie Message.

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List +
I don't care about cookies addon

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List and / or I don't care about cookies addon</summary>

![ss073](https://user-images.githubusercontent.com/44813765/49078830-5f44b580-f23f-11e8-84d2-636e14249f62.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List and I don't care about cookies addon</summary>

![ss072](https://user-images.githubusercontent.com/44813765/49078811-53f18a00-f23f-11e8-9a9b-20ddf0097318.png)

</details>
.

Notes: just BTW FYI, I don't care about cookies addon is also affected - I've already sent the mail just right now.

**Comment by ryanbr** [comment]
Update, and retest, should be fixed.
