### ISSUE TITLE
nowasprzedaz.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#704]
### List the website(s) you're having issues:

`https://nowasprzedaz.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss071](https://user-images.githubusercontent.com/43844449/49081325-cb76e780-f246-11e8-9e34-2077f16757cf.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss069](https://user-images.githubusercontent.com/43844449/49081328-cf0a6e80-f246-11e8-9d5b-973373724e4a.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss070](https://user-images.githubusercontent.com/43844449/49081332-d2055f00-f246-11e8-951f-5472d59a84e1.png)

</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3df21953cdb8d076c62b679b9ba55c157f42fa79
