### ISSUE TITLE
sds-automatyka.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#707]
### List the website(s) you're having issues:

`http://sds-automatyka.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss069](https://user-images.githubusercontent.com/43844449/49082429-06c6e580-f24a-11e8-9442-b3045030e2cb.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss070](https://user-images.githubusercontent.com/43844449/49082435-0af30300-f24a-11e8-8f60-1bd2cf484908.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss071](https://user-images.githubusercontent.com/43844449/49082441-0e868a00-f24a-11e8-9540-ad6d6f537206.png)

</details>

**Comment by krystian3w** [comment]
`##.spu-bg` rather, you can not count on more
