### ISSUE TITLE
intercyza-blog.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#709]
### List the website(s) you're having issues:

`https://www.intercyza-blog.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss076](https://user-images.githubusercontent.com/43844449/49082895-4f32d300-f24b-11e8-8af4-b36426e1c7ee.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss074](https://user-images.githubusercontent.com/43844449/49082908-5823a480-f24b-11e8-8d66-ded8a58f9ce0.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss075](https://user-images.githubusercontent.com/43844449/49082915-5c4fc200-f24b-11e8-9ca4-67ca1df8ac59.png)

</details>

**Comment by krystian3w** [comment]
`##.spu-bg`
