### ISSUE TITLE
thefreedictionary

### ISSUE THREAD

**Issue by joey04** [ryanbr/fanboy-adblock#71]
Thanks for recently adding a clever regex to block tfd.com random-string ad images. It's doing the job!

As a user of your Ultimate list, I have 2 follow-on requests:
1) Remove this rule:
`||thefreedictionary.com^$image,script,~third-party`
2) Add a regex copy for the base domain:
`/\.thefreedictionary\.com/.*[a-zA-Z0-9]{22}/$image`

Blocking the first-party script causes about a 2 second delay before the now-blocked image holder is collapsed. But overriding that in uBO and allowing the script causes it to be collapsed right away.
And it's better to replace the 1p image rule with a copy of the regex.

example page:
`http://www.thefreedictionary.com/example`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/223be791754b36523022f431473fde32f38512b0

**Comment by ryanbr** [comment]
The script generates the image ads (as I see it)

**Comment by ryanbr** [comment]
http://pastebin.com/dJpZmchW  

the javascript thats being loaded ^

**Comment by joey04** [comment]
Yes, it does but then your new regex blocks the image from displaying. It's actually a repeat of an inline script generating the same image from tfd.com that your original regex blocks.

So you're right in that blocking the 1p script prevents the second instance of image attempt, but my point is in doing so it delays the collapsing of the placeholder. Either way image is blocked. Do you see the delay on your end when the script is blocked?

**Comment by joey04** [comment]
I tried it in a different browser, and now I see it's probably best to block the script and incur the extra delay. There's other stuff on the site I'd forgotten about because I have my own extra blocking rules in my regular browser.

**Comment by ryanbr** [comment]
A few more cleanups to the related sites;

https://github.com/easylist/easylist/commit/581e6c0643af85ce6723927c75e0fa3cf6decbd9
https://github.com/easylist/easylist/commit/48ecd9f567df73adea5f28535b923a2fc30415d4
https://github.com/easylist/easylist/commit/eff8b02276473b7f87dee404a716b8b6a4b280fa
https://github.com/ryanbr/fanboy-adblock/commit/7593ddf5f4466371d324d730554b337a159296f1
https://github.com/ryanbr/fanboy-adblock/commit/6752e146536fef315b55c453b3693e91e8618c8c
