### ISSUE TITLE
bellpolska.com.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#710]
### List the website(s) you're having issues:

`https://bellpolska.com.pl/ `

### What happens?

Breakage - the page won't load - white shadow overlay (most of them are dark, this time it's white)

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss079](https://user-images.githubusercontent.com/43844449/49083135-0e878980-f24c-11e8-88af-782eb56d002e.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss077](https://user-images.githubusercontent.com/43844449/49083142-15160100-f24c-11e8-8238-393b25a11671.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss078](https://user-images.githubusercontent.com/43844449/49083146-19dab500-f24c-11e8-92a4-164c59a88ae7.png)

</details>

**Comment by krystian3w** [comment]
`##.spu-bg`
