### ISSUE TITLE
samsonite.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#711]
### List the website(s) you're having issues:

`https://www.samsonite.pl`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List +
I don't care about cookies addon

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List and / or I don't care about cookies addon</summary>

![ss066](https://user-images.githubusercontent.com/43844449/49083787-f284e780-f24d-11e8-9d9b-d3b25fdf079e.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List and I don't care about cookies addon</summary>

![ss067](https://user-images.githubusercontent.com/43844449/49083797-f87ac880-f24d-11e8-8fa8-8cde887c4964.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss068](https://user-images.githubusercontent.com/43844449/49083805-00d30380-f24e-11e8-932a-dee7a2de821e.png)

</details>
.

Notes: just BTW FYI, I don't care about cookies addon is also affected - I've already sent the mail just right now.

**Comment by krystian3w** [comment]
`##div[aria-labelledby="ui-dialog-title-cookies-dialog"]`
`##.ui-widget-overlay`

**Comment by krystian3w** [comment]
`samsonite.pl##div[aria-labelledby="ui-dialog-title-cookies-dialog"], .ui-widget-overlay`

but widget block reload page - strange and silly...

**Comment by krystian3w** [comment]
It probably will not be problem, this is the typical background for this web plugin.

**Comment by kiboke** [comment]
"I don't care about cookies" will implement this instead, for greater precision and to allow other modals to have an overlay:
`.ui-dialog.cookies-dialog ~ .ui-widget-overlay:not(body):not(html)`

**Comment by krystian3w** [comment]
I would be more worried if the store works without cookie permission than if I need to check if the message and the background are in the same parent (html element).

**Comment by krystian3w** [comment]
I have not checked yet almost whether elements are immediately after to use the plus.

Pseudo code CSS - what I mean (children next to each other):
   ```css
   .ui-dialog.cookies-dialog + .ui-widget-overlay:not(body):not(html)
   ```

https://www.w3schools.com/cssref/sel_element_pluss.asp

**Comment by ryanbr** [comment]
Simplified filters, generally will be faster. (like my initial commit) though if there is a better filter available I'm happy to modified it.

**Comment by ryanbr** [comment]
personally not overusing :not(...) , and +/~ improves extension/browser performance, only really limited to problematic filters
