### ISSUE TITLE
madameedith.com [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#713]
### List the website(s) you're having issues:

`https://madameedith.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss073](https://user-images.githubusercontent.com/43844449/49084559-1a754a80-f250-11e8-8d60-6167fafeed90.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss074](https://user-images.githubusercontent.com/43844449/49084571-1f39fe80-f250-11e8-9676-ffd6201bdc62.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss075](https://user-images.githubusercontent.com/43844449/49084574-22cd8580-f250-11e8-8594-bf3b8d213bf5.png)

</details>

**Comment by krystian3w** [comment]
##.spu-bg

:rofl:
