### ISSUE TITLE
esportnow.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#714]
### List the website(s) you're having issues:

`https://esportnow.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss077](https://user-images.githubusercontent.com/43844449/49084693-7cce4b00-f250-11e8-9820-86c5897e30c2.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss078](https://user-images.githubusercontent.com/43844449/49084697-82c42c00-f250-11e8-8fb0-2011d7203e9d.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss079](https://user-images.githubusercontent.com/43844449/49084702-8788e000-f250-11e8-8668-d267350618ec.png)

</details>

**Comment by krystian3w** [comment]
`##.spu-bg`

:rofl:
