### ISSUE TITLE
przedszkolankowo.pl [Breakage] [FCL] 

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#715]
### List the website(s) you're having issues:

`https://przedszkolankowo.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss080](https://user-images.githubusercontent.com/43844449/49084831-dfbfe200-f250-11e8-81b9-a5dfcb5e9bde.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss081](https://user-images.githubusercontent.com/43844449/49084835-e3ebff80-f250-11e8-880d-b920c06ba245.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss082](https://user-images.githubusercontent.com/43844449/49084841-e64e5980-f250-11e8-9cec-f7dbf7182a61.png)

</details>

**Comment by krystian3w** [comment]
`#.spu-bg`

:rofl:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8ffdfab9d1d3bc5d1c007a2cf3217ab34ac9aee2
