### ISSUE TITLE
modr.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#717]
### List the website(s) you're having issues:

`http://modr.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List +
I don't care about cookies addon

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List and / or I don't care about cookies addon</summary>

![ss087](https://user-images.githubusercontent.com/43844449/49085614-b30cca00-f252-11e8-8818-23b76399eeed.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List and I don't care about cookies addon</summary>

![ss088](https://user-images.githubusercontent.com/43844449/49085621-b6a05100-f252-11e8-83f5-7fab864caf06.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss089](https://user-images.githubusercontent.com/43844449/49085626-ba33d800-f252-11e8-81f6-032d6ecc5aad.png)

</details>
.

Notes: just BTW FYI, I don't care about cookies addon is also affected - I've already sent the mail just right now.

**Comment by krystian3w** [comment]
`##.region-gdpr`
