### ISSUE TITLE
freshfile.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#718]
![2018-11-27-window](https://user-images.githubusercontent.com/5884000/49088167-f79b6400-f258-11e8-9027-baef9cfbe37e.png)
`http://freshfile.pl/dl/uSdx954QWG1Fy6YT/`

### Describe the issue

broken title

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by krystian3w** [comment]
Social cut to heavy.
