### ISSUE TITLE
Enhanced Tracking List blocks PNC main page

### ISSUE THREAD

**Issue by mister-sir** [ryanbr/fanboy-adblock#72]
PNC's main page, http://pnc.com (redirects to https://www.pnc.com/en/personal-banking.html) is left totally blank when Fanboy's Enhanced Tracking List is enabled.

**Comment by SMed79** [comment]
I can not reproduce in Firefox / Chromium + ABP !

**Comment by mister-sir** [comment]
Tried it again, and it's still tied to Enhanced Tracking being enabled or not. PNC recently (since I created the issue) redid their home page, but it still has the same problem.

My system:
Mozilla Firefox 52.0.1
Adblock Plus 2.8.2
Linux Mint 18.1 Cinnamon edition
List Updated: 27 Mar 2017

Also occurs in Chromium 56.0.2924.76 with AdBlock Plus 1.13.2 on the same system.

**Comment by mister-sir** [comment]
Yes, that appears to have fixed it!
