### ISSUE TITLE
wspolnotakrzyzasmolec.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#720]
### List the website(s) you're having issues:

`http://wspolnotakrzyzasmolec.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss096](https://user-images.githubusercontent.com/43844449/49313281-0a2acd00-f4e7-11e8-81f0-3ae3bb2723af.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss105](https://user-images.githubusercontent.com/43844449/49314315-5fb4a900-f4ea-11e8-9503-f5f06776e949.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss104](https://user-images.githubusercontent.com/43844449/49314321-63e0c680-f4ea-11e8-9658-f3aa7557ca3e.png)

</details>

**Comment by krystian3w** [comment]
`##.spu-bg`
