### ISSUE TITLE
kuba-pichci.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#721]
### List the website(s) you're having issues:

`http://www.kuba-pichci.pl/`

### What happens?

Breakage - the page's stylesheet is broken
### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss100](https://user-images.githubusercontent.com/43844449/49313783-a86b6280-f4e8-11e8-9fef-4b56c60e38df.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List or applying the fix</summary>

![ss099](https://user-images.githubusercontent.com/43844449/49313798-b4572480-f4e8-11e8-9747-ae9130bc7c31.png)

</details>
.

Offending filter: `/plugins/cookie-`

Offended request: `http://www.kuba-pichci.pl/wp-content/plugins/wp-minify/min/?f=wp-content/themes/blossom-child/style.css,wp-content/themes/wp-blossom102/style-font.css,wp-content/themes/wp-blossom102/style-responsive.css,wp-content/plugins/google-plus-badge/css/retioSlider.css,wp-content/plugins/sn-facebook-like/css/sn-facebook-like.css,wp-content/plugins/google-custom-search/css/smoothness/jquery-ui.theme.min.css,wp-content/plugins/google-custom-search/css/gsc.css,wp-content/plugins/google-custom-search/css/gsc-no-search-button.css,wp-content/plugins/cookie-law-info/css/cli-style.css,wp-content/plugins/wordpress-popular-posts/public/css/wpp.css,wp-content/plugins/wp-postratings/css/postratings-css.css,wp-content/themes/wp-blossom102/pagenavi-css.css,wp-content/themes/wp-blossom102/styles/default.css,wp-content/themes/wp-blossom102/custom.css&m=1531931495`

Example fix: `@@||www.kuba-pichci.pl/wp-content/plugins/wp-minify/min/*$stylesheet,domain=www.kuba-pichci.pl`

**Comment by krystian3w** [comment]
Thx.

**Comment by krystian3w** [comment]
@ryanbr  filter in social:

`/google-plus-` also cut this minify CSS in one file.

```
http://www.kuba-pichci.pl/wp-content/plugins/wp-minify/min/?f=wp-content/themes/blossom-child/style.css,wp-content/themes/wp-blossom102/style-font.css,wp-content/themes/wp-blossom102/style-responsive.css,wp-content/plugins/google-plus-badge/...
                                                                                                                                                                                                                              ^^^^^^^^^^^^
```

**Comment by krystian3w** [comment]
@ryanbr  filter in social:

`/google-plus-` also cut this minify CSS in one file.

---

`@@/google-plus-$stylesheet,domain=www.kuba-pichci.pl,~third-party`

```
http://www.kuba-pichci.pl/wp-content/plugins/wp-minify/min/?f=wp-content/themes/blossom-child/style.css,wp-content/themes/wp-blossom102/style-font.css,wp-content/themes/wp-blossom102/style-responsive.css,wp-content/plugins/google-plus-badge/...
                                                                                                                                                                                                                              ^^^^^^^^^^^^
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ccc11811e31592aba7c2e200c0534c71fe00f9e8  should help

**Comment by krystian3w** [comment]
should help if user subscribe to Fanboy's Social Blocking List, without not.
