### ISSUE TITLE
autoaukcje.net [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#725]
### List the website(s) you're having issues:

`https://autoaukcje.net/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss117](https://user-images.githubusercontent.com/43844449/49315350-ac4db380-f4ed-11e8-812e-f61448c4b31e.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss116](https://user-images.githubusercontent.com/43844449/49315358-b1aafe00-f4ed-11e8-90a7-730010c364ff.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message or applying the fix</summary>

![ss115](https://user-images.githubusercontent.com/43844449/49315361-b5d71b80-f4ed-11e8-8cde-f281c9c08ee7.png)

</details>
.

Offending filter: `##.cookies-block`
Example fix: `autoaukcje.net#@#.cookies-block`

**Comment by krystian3w** [comment]
`##.bg-warning.cookiewarning`

**Comment by krystian3w** [comment]
`##.popup_cookies`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e861f00cb69eb04265422349d0f364019e5b524d
