### ISSUE TITLE
bierhalle.pl [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#726]
### List the website(s) you're having issues:

`http://bierhalle.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List</summary>

![ss119](https://user-images.githubusercontent.com/43844449/49315985-ba043880-f4ef-11e8-85d9-bff5dddced36.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List</summary>

![ss120](https://user-images.githubusercontent.com/43844449/49315990-bf618300-f4ef-11e8-8bbe-8a263abef5b4.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss121](https://user-images.githubusercontent.com/43844449/49316000-c7b9be00-f4ef-11e8-90b2-8390e2edcd9a.png)

</details>

**Comment by krystian3w** [comment]
`##.rstboxes`

:question:

**Comment by ryanbr** [comment]
Getting; 

> 403	
> Wniosek ten jest blokowany przez Admin Tools. Proszę zmienić tę wiadomość w opcjach składnika.
> 
> Spróbuj jednej z następujących stron:

**Comment by krystian3w** [comment]
For me works fine, no errors.

![obraz](https://user-images.githubusercontent.com/35370833/49323732-1a12d300-f520-11e8-96d1-d13accf0f580.png) |
--- |

Maybe geolock for only Poland...

**Comment by ryanbr** [comment]
Sure; https://github.com/easylist/easylist/commit/f032bf728b35caa5e54aee983a82298fb4cf93d7
