### ISSUE TITLE
korepetycje.edu.pl [Breakage] [FCL] 

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#729]
### List the website(s) you're having issues:

`https://korepetycje.edu.pl/`

### What happens?

Breakage - the cookie message is broken, only the text is removed and still the container is left.

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookiemonster List +
I don't care about cookies addon

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookiemonster List and / or I don't care about cookies addon</summary>

![ss132](https://user-images.githubusercontent.com/43844449/49316856-9e4e6180-f4f2-11e8-9e27-5c72037c9dab.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookiemonster List and I don't care about cookies addon</summary>

![ss133](https://user-images.githubusercontent.com/43844449/49316863-a3abac00-f4f2-11e8-981c-7437f0e75a76.png)

</details>
.

Notes: just BTW FYI, I don't care about cookies addon is also affected - I've already sent the mail just right now.

**Comment by krystian3w** [comment]
Use maybe latest name `Fanboy's Cookie List​​​​​​​​​`, shorter and used in `uBO 1.17.0`/`1.17.2`.

**Comment by krystian3w** [comment]
`korepetycje.edu.pl##.cookies_message_bar`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5c5f9ff678abc3e1c031125688e26519882fe230

**Comment by krystian3w** [comment]
Thanks.
