### ISSUE TITLE
blocking amp-analytics and amp-iframe breaks site functionality

### ISSUE THREAD

**Issue by erwinmombay** [ryanbr/fanboy-adblock#73]
Hello we'd like to have `amp-analytics` and `amp-iframe` removed from the list as it breaks site functionality for AMP HTML sites. One valid example is amp-experiment which is used for A/B testing has a dependency on amp-analytics.

**Comment by erwinmombay** [comment]
We'd like to note that amp-analytics actually does not track anything and the non amp specific rules will work fine blocking the actual tracking scripts.

**Comment by ryanbr** [comment]
I removed the amp iframe filter.

**Comment by ryanbr** [comment]
Given the Enhanced trackers will block far more trackers than Easyprivacy, its safe to leave.
