### ISSUE TITLE
zszp.pl [Breakage] [FETL] 

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#730]
Just the same case like here https://github.com/ryanbr/fanboy-adblock/issues/651 or here https://github.com/ryanbr/fanboy-adblock/issues/652 or here https://github.com/ryanbr/fanboy-adblock/issues/705 or here https://github.com/ryanbr/fanboy-adblock/issues/708 , and here https://github.com/ryanbr/fanboy-adblock/issues/716. I've created the issue just for informational purpose, closing in 24h as won't fix as per https://github.com/ryanbr/fanboy-adblock/issues/688#issuecomment-441432194.

### List the website(s) you're having issues:

`https://zszp.pl/ `

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![ss134](https://user-images.githubusercontent.com/43844449/49317316-444e9b80-f4f4-11e8-9abd-77d009917907.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![ss137](https://user-images.githubusercontent.com/43844449/49317323-49abe600-f4f4-11e8-946d-b68dd0a8eed9.png)

</details>

**Comment by ryanbr** [comment]
Seems fine here?

**Comment by ryanbr** [comment]
may help? https://github.com/easylist/easylist/commit/b52d36449a2702d81ce1eddbddb9adb416310c92

**Comment by kulfoon** [comment]
Nope, the issue is still here.
