### ISSUE TITLE
Cookie banner not blocked: duden.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#731]
### List the website(s) you're having issues: 
`https://www.duden.de/`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:
fanboy's cookiemonster list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: Firefox 56.0.2
- Adblock Extension/version: uBlock Origin 1.17.3

**Comment by krystian3w** [comment]
`duden.de###sliding-popup`

**Comment by krystian3w** [comment]
`##body.sliding-popup-processed > #sliding-popup`

https://github.com/AdguardTeam/AdguardFilters/commit/4ada6bb1f57004f20084b7c01b8bb2dd57a572b9
