### ISSUE TITLE
shoppable.com [Cookie Wall] [FCL] FAL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#733]
In this report https://github.com/ryanbr/fanboy-adblock/issues/634 the breakage has been fixed, but the cookie message is still here like on the screenshoot 2, thus I'm not sure whether:

- the cookie message hasn't been removed intentionally because it wasn't reported - thus it was the breakage issue reported only and not the cookie message appearing issue reported, so only the reported (the breakage) issue was fixed, thus therefore the cookie message should be reported as a separate issue, and then it will be fixed (if doable of course) (just like I'm doing now)
- the cookie message hasn't been removed intentionally because it cannot be fixed without breaking the page etc.
- the cookie message hasn't been removed because it was forgotten

### List the website(s) you're having issues:

`https://www.shoppable.com/`

### What happens?

Cookie Wall 

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Annoyance List or Fanboy's Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

<details not-open>
<summary>BTW enabling I don't care about cookies addon removes the Cookie Wall but it also breaks the scrolling - missing scroll bar (I already have reported the issue via email to the author just right now) :</summary>

![ss138](https://user-images.githubusercontent.com/43844449/49326651-b86d5b80-f555-11e8-873d-98381f2e8560.png)

</details>

**Comment by ryanbr** [comment]
If it breaks the scrolling (making the site unusable) then thats an issue. 

> ||stripe.com^$script,domain=shoppable.com

Will remove the cookie message, but may cause other issues.
