### ISSUE TITLE
businesstraveller.pl [shadow overlay] [FCL] [reopen]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#734]
Reopening https://github.com/ryanbr/fanboy-adblock/issues/706 because the issue still is here, I've found the offending filter: `##div[data-cookie]`

**Comment by ryanbr** [comment]
Still not seeing it.  would businesstraveller.pl##.spu-bg help?

**Comment by kulfoon** [comment]
> ryanbr : Still not seeing it

I'm still seing it on both Firefox and Opera and on both PL and US IP.

> ryanbr : would businesstraveller.pl##.spu-bg help?

Yes, but again, as per https://github.com/ryanbr/fanboy-adblock/issues/739 , this is not a proper fix, why would you like to remove a newsletter message in a cookie list? Your fix applies to FAL, and not to FCL, unless here is something I don't know about - is it intented for FL to remove newsletter messages too?
