### ISSUE TITLE
sportingnews.com [blank page + missing scroll bar] [FCL] [reopen]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#736]
Similiar case as here: https://github.com/ryanbr/fanboy-adblock/issues/735

Reopening https://github.com/ryanbr/fanboy-adblock/issues/637 because the issue still is here, the following filters from FCL are present in the logger on Firefox: `12:25:03 |   | ##.flash.cookies |   | dom | http://www.sportingnews.com/`

Unable to reproduce the issue on Opera, the filter above it's not present in the logger.

**Comment by THEtomaso** [comment]
@ryanbr:
I've already confirmed this issue.
Otherwise, I wouldn't have posted these fixes:
https://github.com/ryanbr/fanboy-adblock/issues/616#issuecomment-435589053

**Comment by ryanbr** [comment]
Filter was removed. shouldnt be an issue now
