### ISSUE TITLE
opentuition.com [shadow overlay] [FCL] [reopen]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#737]
Reopening https://github.com/ryanbr/fanboy-adblock/issues/639 because the issue still is here, the following filters from FCL are present in the logger on Firefox and Opera: 

```
12:33:05 |   | ##div[data-nconvert-cookie] |   | dom | https://opentuition.com/
12:33:05 |   | ##.cookie-notice-container  |   | dom | https://opentuition.com/
12:33:05 |   | ###cookie-notice            |   | dom | https://opentuition.com/
```

![ss141](https://user-images.githubusercontent.com/43844449/49327753-8c59d680-f565-11e8-9296-d4c266f005df.png)

**Comment by ryanbr** [comment]
Not helpful, which filter is causing it, and whiltelist it will cause other issues?

**Comment by kulfoon** [comment]
This one: `##div[data-nconvert-cookie]`.
