### ISSUE TITLE
nowasprzedaz.pl [shadow overlay] [FCL] [reopen]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#738]
Reopening https://github.com/ryanbr/fanboy-adblock/issues/704 because the issue still is here, the following filters from FCL are present in the logger on Firefox and Opera:

```
12:38:16 |   | ##div[data-cookie] |   | dom | https://nowasprzedaz.pl/
12:38:16 |   | ##.cookiespanel    |   | dom | https://nowasprzedaz.pl/
```

![ss142](https://user-images.githubusercontent.com/43844449/49327804-2c176480-f566-11e8-87db-8d0a220b0cc2.png)

**Comment by ryanbr** [comment]
Does nowasprzedaz.pl##.spu-bg help?

**Comment by kulfoon** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/734#issuecomment-443488884

**Comment by krystian3w** [comment]
`##.spu-bg` in part help - remove overlay background.

But `##div[data-cookie]` / `##div[data-nconvert-cookie]` maid `Annoyance pop-up remover List` form `Fanboy's Cookie List`.
