### ISSUE TITLE
12 issues [FCL] [mass reopen] [why non-cookie/gdpr popups are being fixed in FCL instead of in FAL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#739]
The following 12 issues have been inproperly (most probably) fixed:
https://github.com/ryanbr/fanboy-adblock/issues/662 , https://github.com/ryanbr/fanboy-adblock/issues/707 , https://github.com/ryanbr/fanboy-adblock/issues/710 , https://github.com/ryanbr/fanboy-adblock/issues/712 , https://github.com/ryanbr/fanboy-adblock/issues/713 , https://github.com/ryanbr/fanboy-adblock/issues/714 , https://github.com/ryanbr/fanboy-adblock/issues/715 , https://github.com/ryanbr/fanboy-adblock/issues/720 , https://github.com/ryanbr/fanboy-adblock/issues/722, new : https://github.com/ryanbr/fanboy-adblock/issues/741, https://github.com/ryanbr/fanboy-adblock/issues/744, https://github.com/ryanbr/fanboy-adblock/issues/745 see ==> https://github.com/ryanbr/fanboy-adblock/issues/739#issuecomment-443729596

Not sure about these 5:
https://github.com/ryanbr/fanboy-adblock/issues/661 , https://github.com/ryanbr/fanboy-adblock/issues/663 , https://github.com/ryanbr/fanboy-adblock/issues/664 , https://github.com/ryanbr/fanboy-adblock/issues/677 , https://github.com/ryanbr/fanboy-adblock/issues/709

As for the 12 issues the problem is that the fixes are hiding the shadow-overlay, as remains of the messages, but the messages are not cookie/gdpr messages, so they should not be hidden at all in FCL but in FAL instead (if FAL is affected), so the proper fix for FCL is to unhide the messages instead of hiding the shadow overlays. (if possible of course, perhaps it wasn't possible so they have been hidden instead). And the fixes which have been already added to FCL should be moved to FAL (if FAL is affected).

As for the 5 not sure, because the messages there are newsletter messages combined with cookie/gdpr messages like 50%/50% so not sure whether they should belong to FCL or to FAL, if they have been intentionally fixed in FCL that's fine, but perhaps they should belong to FAL? (I don't know, just asking in case you were mistaken). I'm asking because in polish filters we also have separately a cookie list and an annoyance list, and the newsletter message with mixed cookie/gdpr warning message in like 50%/50% is to be fixed in the annoyance list. (perhaps in Fanboy's lists they are to be  fixed in the cookie list). It does not make a difference to me really in the 5 issues case, just wanted to make sure in case you were mistaken.

**Comment by krystian3w** [comment]
This is bug when maid filter: 

`##div[data-nconvert-cookie]`

by @smed79 https://github.com/ryanbr/fanboy-adblock/issues/445

**Comment by krystian3w** [comment]
This is bug when maid filter: 

`##div[data-nconvert-cookie]`

by @smed79 https://github.com/ryanbr/fanboy-adblock/issues/445 + https://github.com/easylist/easylist/commit/9539f4031dce65c19d89627bdeee4d1d7331fb22

**Comment by kulfoon** [comment]
Despite the fact of an existence of:
- this thread
- warning in https://github.com/ryanbr/fanboy-adblock/issues/741#issuecomment-443638636
- warnings in https://github.com/ryanbr/fanboy-adblock/issues/744, https://github.com/ryanbr/fanboy-adblock/issues/745 :

> kulfoon: 
> Notes: this is not a cookie/gdpr message, so the proper fix for FCL is not to hide the shadow overlay like #739 (it's proper to FAL if it's affected) but to unhide the message.

as seen - non cookie/gdpr popups are still being removed ("fixed") - couple hours ago for the 3 above reported issues. So we finally would like to know why non-cookie/gdpr popups are fixed in FCL and not in FAL.

**Comment by ryanbr** [comment]
There is no easy fix for the overlays. and whitelisting or removing the filter won't stop it either.

**Comment by kulfoon** [comment]
> ryanbr : There is no easy fix for the overlays. 

Really? whitelisting or removing `##div[data-nconvert-cookie]` seems to be as easy as adding it to the list before.

> ryanbr : and whitelisting or removing the filter won't stop it either.

FCL is not for stopping non cookie/gdpr popups/messages/overlays, it's job for FAL

You should change the description to warn all people that use the list, from:
> 
> Anti-Cookie Filters
> 
> This will remove cookie and privacy warnings (List already included in Annoyances List, don't add list if you're using the Annoyances List)

to:

> This will remove cookie and privacy warnings and often other unrelated messages, it also breaks high ammount of websites  (List already included in Annoyances List, don't add list if you're using the Annoyances List)

Fanboy Cookie List: 
- breaks too many websites
- hides too many cookie/gdpr unrelated popups/messages which makes it annoyances list partially 
- sometimes hides even desirable and useful popups/messages
