### ISSUE TITLE
szkoleniamaciolek.com [Breakage] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#741]
### List the website(s) you're having issues:

`https://szkoleniamaciolek.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List</summary>

![ss146](https://user-images.githubusercontent.com/43844449/49328395-4fdfa800-f570-11e8-9738-2004147c8c54.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookie List</summary>

![ss148](https://user-images.githubusercontent.com/43844449/49328396-55d58900-f570-11e8-8cf0-3bb111d62ed3.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the both messages</summary>

![ss147](https://user-images.githubusercontent.com/43844449/49328399-5a9a3d00-f570-11e8-8c4d-2184d344d62d.png)

</details>

**Comment by krystian3w** [comment]
> > https://github.com/ryanbr/fanboy-adblock/issues/739
>
> This is bug when maid filter:
> 
> `##div[data-nconvert-cookie]`
> 

`##.spu-bg` and cut another newsletter in `Fanboy’s Cookie List`?
