### ISSUE TITLE
GameWatcher.com [Issue #587 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#749]
Reference (**Fanboy's Annoyance List - Whitelist**):
https://github.com/easylist/easylist/commit/f942483ffbbd4e5775bd59c45009ac2a7698e9a9

The exception rule in the commit above is also needed for '**Fanboy's Cookie List**'!

**Comment by krystian3w** [comment]
No "also", in only cookies section, to no create duplicates in Annoyance.

**Comment by THEtomaso** [comment]
I'm not sure what you mean, krystian3w.
But both '**Fanboy's Annoyance List**' and '**Fanboy's Cookie List**' contains the following blocking rule:
`###gdpr-modal`
Since there is absolutely no guarantee that someone who uses one of the above filters, also uses the other one, the exception rule is needed for BOTH of them!
This is standard procedure from ryanbr, so in this case, it must be due to a simple slipup.

**Comment by krystian3w** [comment]
> I'm not sure what you mean, krystian3w.

**Fanboy's Annoyance List** should still included all **Fanboy's Cookie List** filters (with exceptions).

**Comment by THEtomaso** [comment]
Yes, but not the other way around!

**Comment by krystian3w** [comment]
Move here is enough for me:

https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_cookie_whitelist.txt

@ryanbr consider moving in your free time.

**Comment by ryanbr** [comment]
done

**Comment by krystian3w** [comment]
Thanks!
