### ISSUE TITLE
Error in rule processing

### ISSUE THREAD

**Issue by IRainman** [ryanbr/fanboy-adblock#75]
To repeat this problem, enough:

1. Enable the subscription of "Fanboy’s Enhanced Tracking List" in the settings
2. Open the site https://www.gismeteo.ru
3. Go to the bottom of the page
4. Click the orange link "Оставить отзыв" ( "Leave a review" )
5. Watch an inoperative form to send feedback.

- Browser/version: Firefox 52.0.2 (32 bit app on Windows 7 x64)
- uBlock Origin version: 1.11.4

In subscription "Fanboy’s Enhanced Tracking List"  there is a rule:

&referer=$xmlhttprequest,domain=~vuokraovi.com|~24ur.com|~cdon.dk|~cdon.fi|~cdon.no|~cdon.se|~ratp.fr|~skype.com 

This rule is treated incorrectly and blocks excess:

https://gismeteo.userecho.com/inplace/leave-topic/9/?lang=ru&referer=https%3A%2F%2Fwww.gismeteo.ru%2F&return_forum_id=9

Full settings:

[ublock-backup.txt](https://github.com/gorhill/uBlock/files/889068/ublock-backup.txt)

Original issue here:  https://github.com/gorhill/uBlock/issues/2509

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/d43edf3dfa5c8994a478b667c4e536308dc8ce12
