### ISSUE TITLE
Sky.com - Broken video playback [Issue #751 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#753]
Regarding this commit:
`https://github.com/easylist/easylist/commit/329860a16b76c25114cbf978ac0b7c17e508972a`

`@@||sky.com^*_cookie_notice.js$script` doesn't fix the issue from my end.

In the particular case which I posted a link to in my original report, this is the script which is being blocked:
`https://news.sky.com/scripts/sdc_site_cookie_notice-1d7d45c7d93454b00eee84d06c0cd076.js`

The fix that I suggested here works:
https://github.com/ryanbr/fanboy-adblock/issues/751/

**Comment by THEtomaso** [comment]
Only problem with the `*` of course, is that it isn't ABP compatible.

**Comment by krystian3w** [comment]
For my works in Adblock Plus 3.4.1 on Opera 57 in "my filters" section.
