### ISSUE TITLE
Nasa.gov - Pages are prevented from loading (Fanboy's Annoyance List + Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#756]
The report is here:
https://github.com/AdguardTeam/AdguardFilters/issues/26464/

Pay attention to this post, where the issue is explained in detail, by DandelionSprout:
`https://github.com/AdguardTeam/AdguardFilters/issues/26464/#issuecomment-443789165`

**Comment by krystian3w** [comment]
Bad filter `##.flash.cookies` when have active adobe flash player plugin.

**Comment by ryanbr** [comment]
Has been fixed.
