### ISSUE TITLE
teatr-capitol.pl

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#757]
### List the website(s) you're having issues:

`https://teatr-capitol.pl` [](https://github.com/MajkiIT/polish-ads-filter/issues/10497)

### What happens?

Overlay after removed cookie / GDPR / privacy policy.

### List Subscriptions you're using:

Fanboy's Cookie List

### Your settings

- OS/version:  Windows 7
- Browser/version: Opera 57
- Adblock Extension/version:  uBO 1.17.0

**Comment by krystian3w** [comment]
try use ID?

`teatr-capitol.pl###spu-bg-4768`

**Comment by THEtomaso** [comment]
Yes, that works too.
..but I didn't like those numbers at the end, which looks to me like something that might change.

**Comment by krystian3w** [comment]
I prefer ID there, I do not want to make another Polish Annoyance Filters in a cookie / GDPR / privacy policy List.

Example: https://github.com/ryanbr/fanboy-adblock/issues/739#issuecomment-443464649

Filter now cut allmost every pop-up for `spu` plugin / widget.

**Comment by krystian3w** [comment]
@THEtomaso try this:

`##.spu-bg, .spu-total-` maybe better as `##.spu-box, .spu-bg`

**Comment by krystian3w** [comment]
o per domain `teatr-capitol.pl###.sp-bg` maybe similar bug as `##.ad` generic filter.

**Comment by THEtomaso** [comment]
I see now that this whole thing is just because of a simple misunderstanding.
There's a typo in your first post..
You wrote `##.sp-bg` instead of `##.spu-bg`

There's another typo in your last post, which is even worse.
See if you can spot it! :)

**Comment by krystian3w** [comment]
Dyslexia, dysortography, dysmosis :roll_eyes:.

**Comment by kulfoon** [comment]
THEtomaso tell everyone why did u blacklisted me, for .ex. I can't  comment in your issues:

![ss220](https://user-images.githubusercontent.com/43844449/49576629-ed0e5800-f945-11e8-965e-05fbccf0e162.png)

**Comment by THEtomaso** [comment]
*Unblocked*
