### ISSUE TITLE
Doesn't block Bestbuy popup

### ISSUE THREAD

**Issue by RogerTheShrubber1** [ryanbr/fanboy-adblock#76]
![picture0001](https://cloud.githubusercontent.com/assets/20523680/24681117/70b93356-1959-11e7-85ec-3cc0fa4a825d.jpg)

**Comment by SMed79** [comment]
Add:

`/email_submission_modal.`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7ab147a8c575adf283737b7c53d40b20a2aa4513
