### ISSUE TITLE
Add Fandom/Wikia Featured Videos to filter

### ISSUE THREAD

**Issue by joootdooot** [ryanbr/fanboy-adblock#760]
### List the website(s) you're having issues:

This page has a list of fandom/wikia pages that have video ads, for the warframe fandom:
`https://warframe.fandom.com/wiki/Category:FANDOM_Video`

### What happens?

Fandom/Wikia runs videos on select wikia pages. They profit from the pre-roll ads, and the video content is supposed to be relevant to the page. As the videos are added by Fandom/Wikia and not the wiki community, they are often outdated and without value even after the pre-roll ads have been blocked by uBO. The video frame should be treated as an ad, and blocked.

### List Subscriptions you're using:

All the uBO provided subscriptions. All.

### Your settings
This is the filter I wish to add:
`fandom.com##.featured-video`

- OS/version: Windows
- Browser/version: Firefox Nightly
- Adblock Extension/version: uBO

### Other details:

The main issue for argument is that the videos are not ads per se, but as I mentioned it is added by Fandom/Wikia for monetization, and not curated by the wiki community. I hope to have it added to a supplementary list at the very least.

**Comment by joootdooot** [comment]
The filter for the mobile site is slightly different:
`fandom.com##.article-featured-video__player`

**Comment by krystian3w** [comment]
`fandom.com,wikia.com##.featured-video__wrapper` works on mobile?

**Comment by ryanbr** [comment]
I think its better as a manual filter. But blocking third-party discord from loading, should make things faster.
