### ISSUE TITLE
wsiswoi.pl [shadow overlay] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#766]
### List the website(s) you're having issues:

`http://wsiswoi.pl/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Trcking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![ss230](https://user-images.githubusercontent.com/43844449/49649506-aabe4700-fa29-11e8-8879-1c11a08af272.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![ss231](https://user-images.githubusercontent.com/43844449/49649514-aeea6480-fa29-11e8-88a7-0228f4816b86.png)

</details>

**Comment by ryanbr** [comment]
seems fine here.
