### ISSUE TITLE
rutube.ru - Fanboy’s Enhanced Tracking List

### ISSUE THREAD

**Issue by aggat** [ryanbr/fanboy-adblock#78]
Videos are not played due to this filter

`&referer=$image,script,xmlhttprequest,domain=~gismeteo.ru|~vuokraovi.com|~24ur.com|~cdon.dk|~cdon.fi|~cdon.no|~cdon.se|~ratp.fr|~skype.com `

[E.g.](https://rutube.ru/video/af7aa8430fb2a24e4f63512bd971455e/)

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/0243bc675a0e26648763cedbac05ea3e0ce9b2d3
