### ISSUE TITLE
topschool.pl [missing banner] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#783]
### List the website(s) you're having issues:

`http://topschool.pl/`

### What happens?

Breakage - missing banner.

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List +
Polskie Filtry RODO-Ciasteczkowe

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List and/or Polskie Filtry RODO-Ciasteczkowe</summary>

![ss293](https://user-images.githubusercontent.com/43844449/49656309-50c77c80-fa3d-11e8-87c0-8d93bb534ba9.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookie List and Polskie Filtry RODO-Ciasteczkowe</summary>

![ss292](https://user-images.githubusercontent.com/43844449/49656314-5624c700-fa3d-11e8-9405-9c4c52ba110c.png)

</details>

**Comment by krystian3w** [comment]
`@@/wp-content/plugins/CookieInfo/js/CookieInfo.js$script,domain=topschool.pl`

:question:
