### ISSUE TITLE
zabieganamama.com [shadow overlay] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#784]
### List the website(s) you're having issues:

`https://zabieganamama.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List</summary>

![ss294](https://user-images.githubusercontent.com/43844449/49656752-62f5ea80-fa3e-11e8-822a-9a39d89ba5ce.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookie List</summary>

![ss295](https://user-images.githubusercontent.com/43844449/49656756-67220800-fa3e-11e8-8d21-8147994e6362.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss296](https://user-images.githubusercontent.com/43844449/49656762-69846200-fa3e-11e8-8c75-1250977a226b.png)

</details>
.

Notes: this is not a cookie/gdpr message, so the proper fix for FCL is not to hide the shadow overlay like https://github.com/ryanbr/fanboy-adblock/issues/739 (it's proper to FAL if it's affected)  but to unhide the message.

**Comment by ryanbr** [comment]
didnt see it, but i presumed this fixed it.
