### ISSUE TITLE
Crucial.* - Can't access sites ('Fanboys Annoyance List' + 'Fanboys Cookie List')

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#788]
### Affected domains:
```
https://www.crucial.com/
https://www.crucial.com.ru/
https://www.crucial.de/
https://www.crucial.es/
https://www.crucial.fr/
https://www.crucial.in/
https://www.crucial.jp/
https://www.crucial.kr/
https://www.crucial.mx/
```

### Issue:
The sites can't be accessed (blank pages).

### Screenshot:
Not needed, as the problem is obvious (completely blank/white pages).

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`##.flash.cookies`

### Possible fix:
`crucial.com,crucial.com.ru,crucial.de,crucial.es,crucial.fr,crucial.in,crucial.jp,crucial.kr,crucial.mx#@#.flash.cookies`

### Note:
The original report is here:
https://github.com/easylist/easylist/issues/2416/

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.2.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.6 (XUL)

**Comment by ryanbr** [comment]
I've removed .flash.cookies
