### ISSUE TITLE
[social blocking list] Blocked Content on magentacloud.de

### ISSUE THREAD

**Issue by shrugg1e** [ryanbr/fanboy-adblock#79]
Hi,

i use the Fanboy Social List but i realize that it will block important content from the german cloudservice magentacloud.de

**Screenshots**
With activated Social List: http://img5.fotos-hochladen.net/uploads/unbenanntz612l78s5u.jpg
Without Social List: http://img5.fotos-hochladen.net/uploads/unbenannt1zkij4q5c1h.jpg

Used URL: https://www.magentacloud.de/lnk/UrtgviCa

Thank you for fixing!

**Comment by SMed79** [comment]
Hi, 
add this filter `magentacloud.de#@#.sharelink` 
... and wait the social list author see this issue.

**Comment by shrugg1e** [comment]
Thank you!

For workaround i add the complete domain to the whitelist. But much of my friends an family uses social blocking list to, if i send them magentacloud links they couldnt see the content.

So i report this bug in hope that fanboy will fix the source list :-)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/15b43ce15887b7bcd2f9a232d60cce60a39f9653
