### ISSUE TITLE
wsiswoi.pl [shadow overlay] [FETL] [reopen]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#791]
Reopening https://github.com/ryanbr/fanboy-adblock/issues/766 coz still having it on both Firefox and Opera, offending rule: `###the_champ_sharing_more_providers`

**Comment by ryanbr** [comment]
Not seeing this, possibly resolved by the site.

**Comment by kulfoon** [comment]
The issue is gone for me too, perhaps something fixed it during the 55 days.
