### ISSUE TITLE
TMZ.com - Blocked videos (Fanboy's Annoyance List + Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#794]
### Affected site:
`http://www.tmz.com/`

### Issue:
Blocked privacy consent prevents video playback.
**(A region-dependent GDPR thing again!)**

### Example:
`http://www.tmz.com/videos/0_j7qblyw6/`

### Screenshots:
* **Screenshot 1 (consent dialogs blocked):**

![filterissue-tmz1](https://user-images.githubusercontent.com/9382674/49809062-461f2700-fd5e-11e8-920b-57e920ea9b9b.jpg)

* **Screenshots 2 and 3 (exception rules in place, allowing the consent dialogs to be accepted):**

![filterissue-tmz2](https://user-images.githubusercontent.com/9382674/49809119-6818a980-fd5e-11e8-9863-be821b7120af.jpg)

![filterissue-tmz3](https://user-images.githubusercontent.com/9382674/49809152-7797f280-fd5e-11e8-8fcf-32ceac9cc9b9.jpg)

* **Screenshot 4 (after having accepted the privacy consent):**

![filterissue-tmz4](https://user-images.githubusercontent.com/9382674/49809193-8f6f7680-fd5e-11e8-99fe-4a21c16ed417.jpg)

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rules:
```
##.truste_box_overlay
||consent.truste.com^$third-party
||policies.warnerbros.com^
||trustarc.com^$third-party
```

### Possible fix (confirmed working!):
```
tmz.com#@#.truste_box_overlay
@@||consent.truste.com^$third-party,domain=tmz.com
@@||policies.warnerbros.com^$domain=tmz.com
@@||trustarc.com^$third-party,domain=tmz.com
```

### Direct URLs to required assets (when connecting from my location):
```
http://consent.trustarc.com/asset/notice.js/v/v1.7-97
http://consent.trustarc.com/asset/notice.js/v/v1.7-152
http://consent.truste.com/notice?js=bb&noticeType=bb&gtm=1&c=teconsent&domain=warnerbros.com&country=NO&privacypolicylink=https%3A%2F%2Fpolicies.warnerbros.com%2Fprivacy%2Fen-gb
http://policies.warnerbros.com/privacy/js/wbconsent-1.x.x.js?domain=warnerbros.com&country=NO
```

### Notes:
* **IMPORTANT: ALL of the above exception rules are needed!!**

* After having accepted the privacy consent, the page needs to be refreshed before the videos will play (site issue).

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.2.2 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.6 (XUL)

**Comment by krystian3w** [comment]
I can reproduce, video won't play without accept cookie policy.

**Comment by THEtomaso** [comment]
Thanks for confirming!

**Comment by THEtomaso** [comment]
Also confirmed by AdamWr here:
https://github.com/AdguardTeam/AdguardFilters/issues/26793#issuecomment-446569272

**Comment by THEtomaso** [comment]
@ ryanbr:

From my end, the cookie consent is still blocked by the following rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Cookie List**':
`||policies.warnerbros.com^`
This still prevents the videos from being played!

Possible fix (like I pointed out in my first post):
`@@||policies.warnerbros.com^$domain=tmz.com`

**Comment by THEtomaso** [comment]
Yet another rule is blocking the cookie consent @ `tmz.com`.

Details:
* Problem filters: **Fanboy's Annoyance List** / **Fanboy's Cookie List**
* Problem rule: `/wbconsent-`
* Possible fix: `@@/wbconsent-$domain=tmz.com`

**Comment by krystian3w** [comment]
Where find no third party video (no from YouTube).

**Comment by krystian3w** [comment]
Crap, no works on tribes:

<table><tr><td>

## Required cookies

These cookies are required to perform the basic functions of the website.

</td><td>

 Allow this function

    Ensuring secure login
    Remembering the stage of ordering


DO NOT allow this feature

    Remembering login details
    Remembering the contents of the basket
    Ensuring a consistent website design
    The ability to share pages on social networks
    Ability to post comments
    Presenting ads that match the interests of the user



<tr><td>



## Functional cookies

These files allow us to analyze how the website is used to measure and improve performance.

</td><td>

 Allow this function

    Ensuring secure login
    Remembering the stage of ordering
    Remembering login details
    Remembering the contents of the basket
    Ensuring a consistent website design


DO NOT allow this feature

    The ability to share pages on social networks
    Ability to post comments
    Presenting ads that match the interests of the user

</td></tr></table>

**Comment by krystian3w** [comment]
Crap, no works on tribes:

<table><tr><td>

## Required cookies

These cookies are required to perform <br>the basic functions of the website.

</td><td>

 Allow this function

  -  Ensuring secure login
  -  Remembering the stage of ordering


DO NOT allow this feature

  -  Remembering login details
  -  Remembering the contents of the basket
  -  Ensuring a consistent website design
  -  The ability to share pages on social networks
  -  Ability to post comments
  -  Presenting ads that match the interests of the user



</tr><tr></tr><tr><td>



## Functional cookies

These files allow us to analyze how the <br>website is used to measure and improve performance.

</td><td>

 Allow this function

  -  Ensuring secure login
  -  Remembering the stage of ordering
  -  Remembering login details
  -  Remembering the contents of the basket
  -  Ensuring a consistent website design


DO NOT allow this feature

  -  The ability to share pages on social networks
  -  Ability to post comments
  -  Presenting ads that match the interests of the user

</td></tr></table>

Any have "you can't play video".

**Comment by THEtomaso** [comment]
@krystian3w:
After having accepted the cookie consent, did you refresh the page, like I pointed out in the first post?

**Comment by krystian3w** [comment]
Yes,  no works if no accept all cookies:

<table> <tr><td>

## Advertising cookies

These files are used by advertising agencies <br>to place ads tailored to the interests of users.

</td><td>

Allow this function

  -  Ensuring secure login
  -  Remembering the stage of ordering
  -  Remembering login details
  -  Remembering the contents of the basket
  -  Ensuring a consistent website design
  -  The ability to share pages on social networks
  -  Ability to post comments
  -  Presenting ads that match the interests of the user

</td></tr></table>
