### ISSUE TITLE
amd.com [Breakage - page won't load]

### ISSUE THREAD

**Issue by betterwebleon** [ryanbr/fanboy-adblock#795]
### List the website(s) you're having issues:

<code>https&#58;//www.amd.com/en/support</code>

### What happens?

The rule <code>/js/analytics/*</code> is blocking redirection to a download page on "AMD Drivers and Support" website.

<b>Steps to reproduce</b>
1. Open "AMD Drivers and Support" website.
2. Select any product on the list.
3. Click "Submit" button. --> Nothing happens (it should redirect to a software download page).

<b>Solution</b>
Add the exception rule:
<code>@@||download.amd.com/js/analytics/analyticscore.js$script,domain=amd.com</code>

### Your settings

- OS/version: Microsoft Windows 10 (32-bit)
- Browser/version: Mozilla Firefox 60.4 ESR
- Adblock Extension/version: uBlock Origin 1.17.4

**Comment by ArmynC** [comment]
Any update? The bug is still present. :disappointed:

**Comment by ryanbr** [comment]
works here fine. tried it multiple times too. not reproducible.

**Comment by ArmynC** [comment]
Did you tried with uBlock Origin - built-in "Fanboy’s Enhanced Tracking List" ? For me, the bug is there...

![bug](https://user-images.githubusercontent.com/16375271/52175205-15310080-27a9-11e9-81c2-028ef55d8daa.png)

**Comment by ryanbr** [comment]
Okay, i just added the whitelist.
