### ISSUE TITLE
www.modrykonik.sk cookie warning

### ISSUE THREAD

**Issue by Hakatitla** [ryanbr/fanboy-adblock#797]
### List the website(s) you're having issues:
https://www.modrykonik.sk/

### What happens?

cookie warning

### List Subscriptions you're using:

https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt

### Your settings

- OS/version: win7
- Browser/version: chrome latest 
- Adblock Extension/version: Adblock 3.36

**Comment by krystian3w** [comment]
from https://github.com/ryanbr/fanboy-adblock/pull/798/files

```
www.modrykonik.sk##DIV[class="nc_a pl_nz pl_a pl_j pl_q"]
www.modrykonik.sk##[id="mk-branding-0"]
```

**Comment by krystian3w** [comment]
and why use `[ ]` without real reason?

Who to much hide:

<p><code>www.modrykonik.sk##DIV<b>.nc_a.pl_nz.pl_a.pl_j.pl_q</b></code><br>
<code>www.modrykonik.sk##<b>#mk-branding-0</b></code></p>

**Comment by Hakatitla** [comment]
@krystian3w  is there a diference which syntax is used?

**Comment by DandelionSprout** [comment]
I'm not a leading authority on Slovak websites, but I can see that `modrykonik.sk###mk-branding-0` is for an overly big banner on the top of the front page. Although I'm a fan of removing such large boxes, it's not related to the cookie warning.

As far as I can tell, `modrykonik.sk##.nc_a` should be sufficient to remove only the cookie warning.

**Comment by Hakatitla** [comment]
Good job!

**Comment by DandelionSprout** [comment]
An extra hint to you, @Hakatitla: Feel free to re-open this issue thread, so that Fanboy can notice it when he gets back online.

(I've submitted it to *I Don't Care About Cookies* as well, for good measure.)

**Comment by Hakatitla** [comment]
@DandelionSprout I already submited I to _I Don't Care About Cookies_ last week

**Comment by DandelionSprout** [comment]
Ah, okay. 🙂

**Comment by Hakatitla** [comment]
https://github.com/easylist/easylist/pull/2465
