### ISSUE TITLE
Social Blocking List — Wikipedia sports fixture lists are gone

### ISSUE THREAD

**Issue by DandelionSprout** [ryanbr/fanboy-adblock#799]
### List the website(s) you're having issues:
`wikipedia.org` (Example page: `https://en.wikipedia.org/wiki/UEFA_Regions%27_Cup#Finals`)

### What happens?

Lists of sports fixtures (e.g. for football), are replaced by a bunch of lines in quick succession.
![image](https://user-images.githubusercontent.com/22780683/49973941-6c4bef00-ff37-11e8-85ae-f22e352caabe.png)

### List Subscriptions you're using:
```
Fanboy's Social Blocking List
Nano Defender Integration
Nano filters
Nano filters - Whitelist
uBlock filters - Badware Risks
uBlock filters - Unbreak
Adblock Warning Removal List
Adguard Base Filters
Adguard Mobile Filters
EasyList
Malvertising filter list by Disconnect
Malware Domain List
Malware domains
Spam404
Dandelion Sprouts nordiske filtre
Shalla Malware
Confirmed Phishing Threats (by MrThreat)
Streaming Ads (by FadeMind)
AbuseCH Ransomware Tracker RW URLBL
Hosts-File PUP
Hosts-File EMD
Phishing Hosts (by Kurobeats)
Anti-FiM List
Anti-Futa List
MeWe Pink Theme
Dandelion Sprout's Website Stretcher
I Hate Overpromoted Games
I don't care about cookies
YouTube: Pure Video Experience
YouTube: Even More Pure Video Experience
Wikia: Pure Browsing Experience
Twitch: Pure Viewing Experience
Browse Websites Without Logging In
Anti-IMDB List
I Don't Want to Download Your Browser
Anti-'Abuse porn' List
Anti-'Battle Royale' List
Anti-'Notification pre-prompt banners' List
Stop AutoPlay on YouTube
Anti-Elsagate List
```

### Your settings

- OS/version: Windows 10 April 2018 Update (Recentmost installed update: KB4471324)
- Browser/version: Chrome 71.0.3578.98
- Adblock Extension/version: Nano Adblocker 1.0.0.82

### Other details:

I believe that the problem-causing entry is `##.fbbox` in Fanboy's Social Blocking List, as per Nano Adblocker's logging function. Although `wikipedia.org#@#.fbbox` does fix the issue on Wikipedia, I cannot confirm whether `##.fbbox` is causing problems on other wiki sites or not.

**Comment by THEtomaso** [comment]
> I believe that the problem-causing entry is `##.fbbox` in Fanboy's Social Blocking List

Confirmed.
The same blocking rule is also found in '**Fanboy's Annoyance List**'.

**Comment by krystian3w** [comment]
As for me, one more serious is enough to add an exception and one day to consider deleting the filter.

**Comment by DandelionSprout** [comment]
The problem seems to have gone away now, although I'm unsure how. So I suppose I can just as well close this issue.

**Comment by THEtomaso** [comment]
They probably updated the page, and choose a different method.
I think the problem should be fixed regardlessly, as the element in question obviously is available to contributors in Wikipedia's editor.

**Comment by DandelionSprout** [comment]
Ah, okay. I'll take your word for it (as I've only used Wikipedia's editor a low two-digit amount of times), and will reopen this issue. 🙂

**Comment by THEtomaso** [comment]
I've actually never used it myself.
But all Wikipedia pages seems to use the same layout codes, and since I've already confirmed that `##.fbbox` indeed was present earlier, it's only logical to assume that it is availaible somewhere in their editor.

**Comment by DandelionSprout** [comment]
Having not had any problems with this in the past month, I think I'll re-close this issue again now, to give Fanboy one less thing to have to worry about.

**Comment by THEtomaso** [comment]
Does `@@||wikipedia.org^$generichide` really fix this particular issue?
I'm using several cosmetic rules for Wikipedia myself, and they still seem to work, despite the `$generichide` fix.

**Comment by THEtomaso** [comment]
Ah, of course, that's right, I don't use generic ones. :)
