### ISSUE TITLE
ad appers at etc.se

### ISSUE THREAD

**Issue by jvodotse** [ryanbr/fanboy-adblock#8]
if you open etc.se there will allways be a big window blockning the screen.

**Comment by SMed79** [comment]
Hi, 
i think you can only block the iframe with `||www.etc.se/node/*/ajax|$subdocument`
if you use hidding rules to hide the overlay this will break page scrolling.

**Comment by jvodotse** [comment]
Does not solve the problem completely, now the screen is black anyway

**Comment by SMed79** [comment]
Click anywhere to hide/close.

**Comment by jvodotse** [comment]
yes i know that i can just click anywhere on the screen, but is there not any other solution?

**Comment by ryanbr** [comment]
I saw this initially, but it seems to not appear now. Did the site remove the popup?

**Comment by SMed79** [comment]
@ryanbr always here http://i.imgur.com/zbiJXkI.png
* http://pastebin.com/ZPkP71kj
```
        "mkts_splashify": {
            "js_splash_always": "0",
            "js_expire_after": 604800,
            "js_mode": "lightbox",
            "js_mode_settings": {
                "mode": "random",
                "system_splash": "",
                "urls": ["\/node\/1785\/ajax"],
                "total_urls": 1,
                "size_width": "930",
                "size_height": "620"
            },
```

**Comment by jvodotse** [comment]
Oe problem that appers now is that ypu cant scroll on the page... :/

**Comment by ryanbr** [comment]
I can't resolve these with the current rules in Adblock Plus. Blocking the magnific-popup. script or hiding the elements will break the scrollbars.
