### ISSUE TITLE
bad caching policy

### ISSUE THREAD

**Issue by joey04** [ryanbr/fanboy-adblock#80]
Ryan, I opened [this issue](https://github.com/gorhill/uBlock/issues/2592) at uBO yesterday because Fanboy Ultimate wasn't updating properly, but the problem turned out to be the Fanboy server telling the browser to cache the list for the next 11 years! Thus any list updates (auto or manual) just re-applied the cached list. This was seen in both the latest Pale Moon and Firefox.

I have all the info at the other issue so won't duplicate it here. I will note here that other lists hosted at Github show that their browser cache entries expire after a few minutes. Can you change Fanboy server code to do the same?

**Comment by ryanbr** [comment]
I use cloudflare for cache/ssl, Browser Cache Expiration in cloudflare is set to 12hrs. No other cache settings are used

**Comment by joey04** [comment]
That's good, but perhaps Cloudflare is changing it?

BTW, gorhill added a workaround for stale browser cache entries so it shouldn't be a problem going forward regardless of the cache setting.
