### ISSUE TITLE
Philips.* - Many pages fails to load properly (Fanboy's Annoyance List + Fanboy's Cookie List)

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#800]
### Affected domains:
`http://www.philips.*`
`*` = All of the 95 domains which are listed here:
`https://www.philips.com/a-cs/global-country-selector.html`
(PS: This page fails to load properly because of the problem rule mentioned below)

### Issue:
Many pages fails to load properly.

### Example:
`http://www.lighting.philips.com/`

### Screenshot:
Not needed, as the problem should be obvious.

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`##[data-cookie-id]`

### Possible fix:
`philips.ae,philips.am,philips.at,philips.az,philips.be,philips.bg,philips.by,philips.ca,philips.ch,philips.cl,philips.co.id,philips.co.il,philips.co.in,philips.co.jp,philips.co.ke,philips.co.kr,philips.co.nz,philips.co.th,philips.co.uk,philips.co.za,philips.com,philips.com.ar,philips.com.au,philips.com.bh,philips.com.br,philips.com.cn,philips.com.co,philips.com.bh,philips.com.eg,philips.com.ge,philips.com.gh,philips.com.hk,philips.com.kw,philips.com.lb,philips.com.mx,philips.com.my,philips.com.om,philips.com.pe,philips.com.ph,philips.com.pk,philips.com.qa,philips.com.sg,philips.com.tr,philips.com.tw,philips.com.uy,philips.com.vn,philips.cz,philips.de,philips.dk,philips.ee,philips.es,philips.fi,philips.fr,philips.gr,philips.hr,philips.hu,philips.ie,philips.iq,philips.it,philips.jo,philips.kz,philips.lt,philips.lv,philips.ma,philips.ng,philips.nl,philips.no,philips.pl,philips.pt,philips.ro,philips.rs,philips.ru,philips.sa,philips.se,philips.si,philips.sk,philips.ua,philips.uz#@#[data-cookie-id]`

**Comment by ryanbr** [comment]
Not really obvious? I loaded a few international sites. from a UK vpn, and seems to work fine?

**Comment by THEtomaso** [comment]
Must be a regional thing then.

@DandelionSprout / @krystian3w:
Can you confirm from your locations?

**Comment by DandelionSprout** [comment]
Can confirm.

With *Fanboy's Cookie List* turned on: 
![image](https://user-images.githubusercontent.com/22780683/52177658-a82b6400-27c4-11e9-8d34-f5b74190a993.png)
—————————————————————————————————————
With `#@#[data-cookie-id]`:
![image](https://user-images.githubusercontent.com/22780683/52177669-c98c5000-27c4-11e9-8b3d-d2d70dd0c7c1.png)

**Comment by THEtomaso** [comment]
@ DandelionSprout:

Thanks for confirming.

Would you mind confirming thses issues too?:
https://github.com/ryanbr/fanboy-adblock/issues/754#issuecomment-445531430
https://github.com/ryanbr/fanboy-adblock/issues/794#issuecomment-460050916
I'm getting tired of constantly having to reopen closed issues!

**Comment by krystian3w** [comment]
Yes filter cut too much:

![obraz](https://user-images.githubusercontent.com/35370833/52177790-96e35700-27c6-11e9-8fd0-982b0fa808ae.png) |
--- |

Red list gone with this filter and I can't select regional version.

**Comment by THEtomaso** [comment]
@ryanbr:
I've saved you the trouble of writing the required exception rule.
It's in my first post now.

**Comment by THEtomaso** [comment]
@Khrin:
This issue has been lingering for more than a quarter of a year now.
I updated the first post 5 weeks ago, to include a ABP-compatible fix.
Could you just add it to **Fanboy's Cookie List**?

**Comment by THEtomaso** [comment]
Not much happening here.

@okiehsch:
Considering the amount of affected sites and all, perhaps you could add `philips.*#@#[data-cookie-id]` to '**uBlock filters - Unbreak**' for the time being?

**Comment by okiehsch** [comment]
`Unbreak` is only for lists that are enabled by default.
````
! Description:
!     Filters optimized for uBlock Origin, to unbreak sites broken as
!     a result of 3rd-party filter lists enabled by default.
````

**Comment by okiehsch** [comment]
`http://www.lighting.philips.com/`

@ryanbr I can repoduce the breakage with a US-IP, so this is not some EU only issue.

**Comment by krystian3w** [comment]
#300  - this is also shuld fixed somehow
