### ISSUE TITLE
Panel to chose emission hidden on https://ici.radio-canada.ca/premiere/emissions/l-autre-midi-a-la-table-d-a-cote

### ISSUE THREAD

**Issue by mikhoul** [ryanbr/fanboy-adblock#802]
The panel to choose emission on podcast is not available on `https://ici.radio-canada.ca/premiere/emissions/l-autre-midi-a-la-table-d-a-cote`

the culprit is the /webtrends. filter

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/5678673/50045670-eded6b00-0064-11e9-8e48-8355bab2bbc5.png)

Nano Adblocker under latest Chromium under Win7

### Other details:

With the filter **enabled**:
![image](https://user-images.githubusercontent.com/5678673/50045675-2ee57f80-0065-11e9-9b2b-f1081592212a.png)

With the   /webtrends. filter **disabled**:
![image](https://user-images.githubusercontent.com/5678673/50045693-7835cf00-0065-11e9-859c-1e79efd21b1c.png)

Regards :octocat:

**Comment by ryanbr** [comment]
has been fixed, update list.
