### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by WalrusInAnus** [ryanbr/fanboy-adblock#81]
Could you add filters to remove "Featured for you" at the top of pages?

**Comment by ryanbr** [comment]
Not sure what you're trying to ask here

**Comment by WalrusInAnus** [comment]
I thought this was the place to ask about Fanboy's Adblock filters. Is it not?

**Comment by ryanbr** [comment]
Clarify your question

**Comment by WalrusInAnus** [comment]
Ok I'll try with a picture, because there is clearly a language barrier.
![fb featured](https://cloud.githubusercontent.com/assets/17233430/26024908/5b3dcf72-37dc-11e7-8a0b-f6803997e28e.JPG)

**Comment by ryanbr** [comment]
Facebook keep changing the div elements making it near impossible to fix or hide.

If I did manage to add something like this I'd get complaints because of it. Its a no-win either way

**Comment by WalrusInAnus** [comment]
ok :(

**Comment by joey04** [comment]
@WalrusInAnus just add your own personal filter for it. Should be a snap using the element picker. I've got a bunch of these types of filters.

**Comment by WalrusInAnus** [comment]
I don't understand any of this, sorry :( No idea what element picker is.

**Comment by ryanbr** [comment]
A few videos on how to use the element picker, (Firefox).

https://www.youtube.com/watch?v=3nnKJxuzX-0
https://www.youtube.com/watch?v=XcZThrKXCjI
https://www.youtube.com/watch?v=HbnS6mibcVg
