### ISSUE TITLE
rozterkistartuperki.pl [blank white page] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#813]
### List the website(s) you're having issues:

`https://rozterkistartuperki.pl/`

### What happens?

Breakage - a half of the page won't load - broken - white page, animated icon infinite loop

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List +
Polskie Filtry RODO-Ciasteczkowe

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 64 64bit / Opera 57 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List or/and Polskie Filtry RODO-Ciasteczkowe</summary>

![ss_207](https://user-images.githubusercontent.com/43844449/50053928-b225d480-013c-11e9-8755-58751398f34d.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookie List and Polskie Filtry RODO-Ciasteczkowe</summary>

![ss_208](https://user-images.githubusercontent.com/43844449/50053935-b9e57900-013c-11e9-8085-d58e6e5a446b.png)

</details>

**Comment by ryanbr** [comment]
Works fine, pictures loaded

**Comment by kulfoon** [comment]
The issue is gone for me too, perhpas something fixed it during the 49 days.
