### ISSUE TITLE
167.206.10.148

### ISSUE THREAD

**Issue by PlNG** [ryanbr/fanboy-adblock#816]
### List the website(s) you're having issues:
http websites (not on HTTPS websites), periodically.

### What happens?
Altice / Optimum / CableVision injects ads and notices into your http requests with your original request in the form of an iFrame. https://i.imgur.com/0Db6m8o.png

### List Subscriptions you're using:
uBlock Origin:
(All but regional lists)
Custom lists:
Malware domains (long-lived)​​​​​
Nano Defender Integration​​​​​
Prebake - Filter Obtrusive Cookie Notices

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 71
- Adblock Extension/version:  uBlock Origin v1.17.4

### Other details:
Altice / Optimum / CableVision periodically injects ads and notices into responses with your original requested page in the form of an iFrame. Not using their DNS servers.

**Comment by DandelionSprout** [comment]
Speaking as an adblocking enthusiast who is not affiliated with Fanboy: I'm absolutely flabbergasted that a European ISP can sink so low as to bring themselves to insert ads in such ways as these.

Although I do not try to excuse the ISPs' awful behaviour in the slightest, have you checked out https://www.eff.org/https-everywhere and/or https://github.com/ilGur1132/Smart-HTTPS? They attempt to always load websites in HTTPS mode insofar as the websites have such a mode.
