### ISSUE TITLE
investjourney.pl [shadow overlay] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#819]
### List the website(s) you're having issues:

`http://investjourney.pl/`

### What happens?

breakage - shadow overlay, it will fit into https://github.com/ryanbr/fanboy-adblock/issues/739

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 64 64bit / Opera 57 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List</summary>

![ss_224](https://user-images.githubusercontent.com/43844449/50057233-d21ebd80-0167-11e9-9bf6-587002b68149.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookie List</summary>

![ss_225](https://user-images.githubusercontent.com/43844449/50057236-d6e37180-0167-11e9-9be2-3eeaf3892de2.png)

</details>
<br>
<details not-open>
<summary>screenshoot 3 - after accepting the message (this is not a cookie message)</summary>

![ss_223](https://user-images.githubusercontent.com/43844449/50057238-db0f8f00-0167-11e9-974a-8d521c5d5632.png)

</details>

**Comment by ryanbr** [comment]
re-test, if still an issue. couldn't see it.

**Comment by krystian3w** [comment]
`##.spu-bg`
