### ISSUE TITLE
dianping.com

### ISSUE THREAD

**Issue by Fezreal** [ryanbr/fanboy-adblock#82]
http://www.dianping.com/search/category/206/10/g224o5##

![image](https://cloud.githubusercontent.com/assets/6703674/26273347/3fac3ea8-3d61-11e7-9f73-54f107b78aeb.png)

if i open the "Fanboy’s Enhanced Tracking List" will broke the function in the picture of the pane

please test it.

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/47f3e7cd33721c46c6afdc5e81077264bec91c94
