### ISSUE TITLE
mobilier-mirjan24.ro [shadow overlay] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#825]
### List the website(s) you're having issues:

`https://www.mobilier-mirjan24.ro/`

### What happens?

breakage - shadow overlay.

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List +
I don't care about cookies addon +
Polskie Filtry RODO-Ciasteczkowe

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 64 64bit / Opera 57 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List and/or I don't care about cookies addon and/or Polskie Filtry RODO-Ciasteczkowe</summary>

![ss_239](https://user-images.githubusercontent.com/43844449/50057707-55dba880-016e-11e9-9924-f478b5c6f924.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Cookie List and I don't care about cookies addon and Polskie Filtry RODO-Ciasteczkowe</summary>

![ss_240](https://user-images.githubusercontent.com/43844449/50057712-5a07c600-016e-11e9-88c2-f597c49186f1.png)

</details>
<br>
<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_241](https://user-images.githubusercontent.com/43844449/50057713-5d9b4d00-016e-11e9-86f8-4ada0c68bcfd.png)

</details>
<br>
I've emailed IDCACA

**Comment by ryanbr** [comment]
Should be fixed.
