### ISSUE TITLE
Please add gjirafa adnewtork to the block list

### ISSUE THREAD

**Issue by akagami7** [ryanbr/fanboy-adblock#83]
There is a new AdNetwork in my country which ads won't be blocked by adblock, please consider adding the following filter:
##IFRAME[class="gjc "][src*="https://gjc.gjirafa.com/"]

example can be found here (check header):

`https://stupcatvideo.gjirafa.com/?video=stupcat-egjeli-2017-episodi-8`

Also there are video ads, which I couldn't find the filter for that.

**Comment by ryanbr** [comment]
Add to your personal filters, ||gjc.gjirafa.com^
