### ISSUE TITLE
walkingdead.fandom.com - unblocked cookie notification

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#832]
### List the website(s) you're having issues:

`walkingdead.fandom.com`

### What happens?

Cookie notification is not blocked

### List Subscriptions you're using:

Fanboy's Cookie list

### Your settings

- OS/version: Windows 10 
- Browser/version: Firefox 64.0
- Adblock Extension/version: Ublock Origin 1.17.4

### Other details:

I think that blocking should be applied in the form of `fandom.com` so that any address that has `fandom.com` suffix would block the cookie notification.

**Comment by ryanbr** [comment]
can't be blocked
