### ISSUE TITLE
pop-up issue

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#836]

**Comment by hawkeye116477** [comment]
Similar problem on `fashionvoyager.pl`
![screenshot_20181222_112001](https://user-images.githubusercontent.com/19818572/50373212-9490b900-05db-11e9-939a-5a00302c7009.png)

**Comment by krystian3w** [comment]
What give is unblocking the plugin, better to display this plugin to users?

**Comment by krystian3w** [comment]
`makulscy.com`
