### ISSUE TITLE
Fanboy's Annoyance List breaks Google Books previews

### ISSUE THREAD

**Issue by jeffreymcclain** [ryanbr/fanboy-adblock#84]
https://i.imgur.com/G3CFbli.png (with the list enabled)

http://i.imgur.com/jcvYtXi.png (with the list disabled)

using Ublock Origin on Google Chrome 64-bit, Windows 10.

**Comment by SMed79** [comment]
temporary solution add https://forums.lanik.us/viewtopic.php?p=118723#p118723

**Comment by ryanbr** [comment]
filter was removed
