### ISSUE TITLE
xnview.com (Fanboy's Cookie List)

### ISSUE THREAD

**Issue by Gitoffthelawn** [ryanbr/fanboy-adblock#843]
### List the website(s) you're having issues:

`https://www.xnview.com`

### What happens?

Content from cloudflare.com is still accessed.

### List Subscriptions you're using:

Fanboy's Cookie List

### Other details:

The filter `/cookieconsent.$script` should probably be changed to `/cookieconsent.` so that cloudflare.com is not accessed at all for the cookie consent code (currently, the CSS is still loaded from cloudflare.com).

**Comment by Gitoffthelawn** [comment]
@THEtomaso Thank you for the helpful details.  Good info.

From what I see,

```
https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js
https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css
```

are both being accessed, but only the first is blocked via the `/cookieconsent.$script` filter.  Unless the CSS really needs to be loaded for some reason (I don't see any reason), the filter can be simplified to `/cookieconsent.` to block all the cloudflare calls.

**Comment by THEtomaso** [comment]
> blocked via the `/cookieconsent.$script` filter

The blocking rule is actually `/cookieconsent.$~stylesheet`.
`/cookieconsent.$script` is just how it's displayed in uBO's logger, indicating that it's blocking a script.
And like I pointed out before, the `$~stylesheet` part of it deliberately allows **cookieconsent.min.css**, so we'll have to wait for ryanbr to explain why.
I'm sure there must be a reason for it.

--

> the filter can be simplified to `/cookieconsent.` to block all the cloudflare calls.

Making it that aggressive might not be the best idea, considering all the mandatory GDPR stuff these days.
That being said, '**AdGuard Annoyances filter**' already has that exact rule, and a few exceptions to go with it:
```
@@/cookieconsent.$domain=sammobile.com
@@||hypinvest.mijnhypotheekonline.nl/*/cookieconsent.stater.js
@@||mac4ever.com/min.php?*/javascript/cookieconsent.js
@@://m.*/js/wub/AMD/Components/CookieConsent.js$~third-party
@@||dixons.nl/catalog/view/theme/dixons/assets/js/vendor/*/cookieconsent.min.js
```

**Comment by Gitoffthelawn** [comment]
@ryanbr 
https://github.com/easylist/easylist/commit/3802a991333e832145b4d8eb2797edf0b518e5f9 blocks less from cloudflare on xnview.com instead of more.

Why was this done?

Also, as @THEtomaso mentioned, why are the CSS calls being allowed in general (re: `/cookieconsent.$~stylesheet`)?
