### ISSUE TITLE
aftonbladet.se

### ISSUE THREAD

**Issue by dregol73** [ryanbr/fanboy-adblock#85]
Hi,

The ads are not blocked on this website:`www.aftonbladet.se`
Whatever video I am looking at an ad starts directly.
Please fix this problem.

![image](https://cloud.githubusercontent.com/assets/29040483/26548031/4dbba390-4472-11e7-89b0-4c49a0d2b560.png)

BR
Dregol

**Comment by ryanbr** [comment]
Unable to stop the auto-play ad video

**Comment by SMed79** [comment]
If you web browser run HTML5 video player by default test this filter 

`||damoh.aftonbladet.se^$media`

**Comment by dregol73** [comment]
I tested the filter but now nothing shows up. The video should be played where I marked with X
![1](https://cloud.githubusercontent.com/assets/29040483/26619115/5373544c-45dd-11e7-90bd-8f7620091cbb.PNG)

**Comment by dregol73** [comment]
Sorry closed by "misstake" :)

**Comment by SMed79** [comment]
Test these filters :
```
.damoh.*/0*/|$domain=tv.aftonbladet.se
.damoh.*/2*/|$domain=tv.aftonbladet.se
.damoh.*/3*/|$domain=tv.aftonbladet.se
.damoh.*/4*/|$domain=tv.aftonbladet.se
.damoh.*/9*/|$domain=tv.aftonbladet.se
```
But
1. blocking the video ads is not guaranteed.
2. can show you an anti adblock message => click **F5** to refresh a page.

**Comment by dregol73** [comment]
Now I get the message that I need to disable the adblocker in order to watch the video :(
http://tv.aftonbladet.se/abtv/articles/218308
![1](https://cloud.githubusercontent.com/assets/29040483/26726990/55b02400-47a5-11e7-864c-76e73e1f9dab.PNG)

**Comment by SMed79** [comment]
So, unfortunately can't be blocked :-(
