### ISSUE TITLE
deadbydaylight.gamepedia.com/Dead_by_Daylight_Wiki [FETL]

### ISSUE THREAD

**Issue by kaiten1** [ryanbr/fanboy-adblock#854]
### List the website(s) you're having issues:
`https://deadbydaylight.gamepedia.com/Dead_by_Daylight_Wiki`
`https://deadbydaylight.gamepedia.com/Kenneth_%22Jeffrey_Hawk%22_Chase`

### What happens?
Recently the small images/icons/ that are infront of the perks /related to the game Dead by Daylight/ disappeared. On most subpages for the same game on gamepedia where you can see the perks in the column "icon" - the icons are missing. For example here `https://deadbydaylight.gamepedia.com/Kenneth_%22Jeffrey_Hawk%22_Chase` it is very visible  - all the icons images are missing.

### List Subscriptions you're using:
uBlock filters
EasyList
Adguard Spyware Filters
EasyPrivacy
Fanboy’s Enhanced Tracking List
Malware domains
Fanboy’s Annoyance List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Google Chrome 71.0.3578.98 64 bit
- Adblock Extension/version: uBlock Origin version: 1.17.4

### Other details:
I tried disabling just Fanboy’s Enhanced Tracking List and the icons were back. From what I could find out I think it is caused by this - gamepedia.com##.floatnone

Screenshots: 
1. With Fanboy’s Enhanced Tracking List enabled
![1](https://user-images.githubusercontent.com/46202528/50494905-b2707a80-0a2e-11e9-8252-619cf8c04c5d.png)
2 With Fanboy’s Enhanced Tracking List disabled
![2](https://user-images.githubusercontent.com/46202528/50494908-b6040180-0a2e-11e9-9623-e3856113889e.png)

**Comment by THEtomaso** [comment]
> From what I could find out I think it is caused by this - `gamepedia.com##.floatnone`

Confirmed.

**Comment by krystian3w** [comment]
I play everyday in DBT: https://www.youtube.com/watch?v=HGweuzKmUmE :question:

**Comment by krystian3w** [comment]
I play DBT everyday: https://www.youtube.com/watch?v=HGweuzKmUmE :question:
