### ISSUE TITLE
IFTTT blocked icons

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#856]
### List the website(s) you're having issues:

`https://ifttt.com/create`

### What happens?

Useful icons are blocked

### List Subscriptions you're using:

fanboy annoyance

### Your settings

- OS/version: linux
- Browser/version: firefox
- Adblock Extension/version: ublock origin

### Other details:

```
! ifttt
ifttt.com#@#img[title="YouTube"]
ifttt.com#@#img[title="Twitter"]
ifttt.com#@#img[title="Instagram"]
ifttt.com#@#img[title="Facebook"]
ifttt.com#@#img[title="Pinterest"]
ifttt.com#@#img[title="Flickr"]
ifttt.com#@#img[title="LinkedIn"]

ifttt.com#@#img[alt="Flickr"]
ifttt.com#@#img[alt="Twitter"]
ifttt.com#@#img[alt="Pinterest"]
ifttt.com#@#img[alt="Facebook"]
ifttt.com#@#img[alt="Instagram"]
ifttt.com#@#img[alt="LinkedIn"]
```

**Comment by krystian3w** [comment]
Mabye generichide? downdetector to use generichide #484
