### ISSUE TITLE
trivago.* cookie notification

### ISSUE THREAD

**Issue by jounihh** [ryanbr/fanboy-adblock#857]
### List the website(s) you're having issues:

trivago.*

### What happens?

When you go to any trivago website you see a cookie notification at the bottom

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/40239267/50519910-d16e1b80-0ac5-11e9-800d-2f35e325ba9d.png)

### Your settings

- OS/version: windows 10
- Browser/version: waterfox latest
- Adblock Extension/version: nano adblocker 1.0.0.81

### Other details:

Screenshot trivago.co.uk:
![image](https://user-images.githubusercontent.com/40239267/50519963-2c077780-0ac6-11e9-80a1-5e1b1ea305c2.png)

Screenshot trivago.fi:
![image](https://user-images.githubusercontent.com/40239267/50519978-43466500-0ac6-11e9-8875-d7bdfc4032b1.png)

You can change the language if you scroll all the way down

Possible fix:
trivago.*##.alert--bottom-notification

**Comment by jounihh** [comment]
I lied only European ones had the notification:
trivago.bg,trivago.be,trivago.cz,trivago.dk,trivago.gr,trivago.es,trivago.fr,trivago.hr,trivago.ie,trivago.hu,trivago.nl,trivago.at,trivago.pl,trivago.pt,trivago.ro,trivago.ch,trivago.si,trivago.sk,trivago.rs,trivago.fi,trivago.se,trivago.com.tr,trivago.co.uk##.alert--bottom-notification

**Comment by THEtomaso** [comment]
'**I don't care about cookies**' already blocks it, with the following rule:
`##.alert.alert--bottom.alert--bottom-notification`

**Comment by jounihh** [comment]
oh nice

**Comment by krystian3w** [comment]
Hello we can remove this filter. @khrin fyi.

Now website use:

```
##.js-cookie-notification.alert--cookie-notification.alert
```

**Comment by kiboke** [comment]
Thank you, I will remove the old filter `.alert.alert--bottom.alert--bottom-notification` from "I don't care about cookies".
