### ISSUE TITLE
Blizzard forums "Yes" and "No" Feedback buttons blocked

### ISSUE THREAD

**Issue by jeffreymcclain** [ryanbr/fanboy-adblock#86]
With list enabled: https://i.imgur.com/WH6QgyT.png

Without Fanboy's annoyance list: https://i.imgur.com/BoWXt1U.png

Using Ublock Origin on Chrome 64-bit, Windows 10.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/940b89a70c67f7d7aaa44290766509e22f4ef9ec
