### ISSUE TITLE
latest update breaks ProtonMail 

### ISSUE THREAD

**Issue by B09B1** [ryanbr/fanboy-adblock#860]
ProtonMail is the world's largest secure email provider with over 10 million users worldwide. It is popular among privacy conscious internet users, most of who also use ad-blockers

Issue was originally reported here, but belongs here instead:
https://github.com/uBlockOrigin/uAssets/issues/4474

### List the website(s) you're having issues:

mail.protonmail.com/inbox (must login first. accounts can be created for free at mail.protonmail.com/signup).

### What happens?

In the ProtonMail inbox, the subject lines are vanishing when you look at the emails in the web interface. Disabling ad blocker fixes the issue. A screenshot of the problem can be found here: https://www.reddit.com/r/ProtonMail/comments/aakms3/how_to_turn_this_thing_back_on/

### Other details

Issue has been isolated as a bad filter in fanboy's annoyances list
protonmail.com##.top

**Comment by mapx-** [comment]
fixed here:
https://github.com/easylist/easylist/commit/48c7d1872434e52d25be237019788e2ecfc9bf00
