### ISSUE TITLE
theverge.com cookie notification

### ISSUE THREAD

**Issue by jounihh** [ryanbr/fanboy-adblock#863]
### List the website(s) you're having issues:

theverge.com

### What happens?

when you go to the site you see a cookie notification at the bottom

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/40239267/50572669-945b9f00-0dcd-11e9-9042-5bca60044101.png)

### Your settings

- OS/version: windows 10
- Browser/version: waterfox latest
- Adblock Extension/version: Nano Adblocker 1.0.0.81

### Other details:

Possible fix:
theverge.com###privacy-consent.m-privacy-consent

**Comment by theel0ja** [comment]
Can reproduce.

uBO 1.17.4 on Firefox 64

![screenshot_20190101_172009](https://user-images.githubusercontent.com/5832930/50574078-bb6b9e00-0dd8-11e9-8c1b-1b20dd7ccd6f.png)

**Comment by THEtomaso** [comment]
Unfortunately, this cookie notification can't be blocked, because of GDPR issues:
https://github.com/easylist/easylist/issues/2256/

**Comment by jounihh** [comment]
I see. The video doesn't work.

**Comment by Pro899999** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/863
