### ISSUE TITLE
narew.info

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#865]
### List the website(s) you're having issues:

`http://www.narew.info/`

### What happens?

* Social login buttons **are hidden**:

   ![image](https://user-images.githubusercontent.com/35370833/50633890-2807a980-0f4d-11e9-9f88-be38016fd144.png) |
   --- |

   ![image](https://user-images.githubusercontent.com/35370833/50633938-508fa380-0f4d-11e9-8f8e-11c1bcfa590d.png) |
   --- |

    on right form :lock: or "<kbd>zaloguj się</kbd>" on small screen (`.visible-sm`) e.g. smartphone :iphone:.

---

* And link social button on left at login section is still visible with `Fanboy's Social Blocking List`

### List Subscriptions you're using:

uBO Default + Fanboy's Social Blocking List

### Your settings

- OS/version: Windows 7
- Browser/version:  Opera 57
- Adblock Extension/version: uBO 1.17.0 

### Other details:

propose exceptions: 

```
narew.info#@#.btn-fb
narew.info#@#.icon-facebook
narew.info#@#.btn-gplus
narew.info#@#.icon-googleplus
```

propose add to hide left social links in header:

![image](https://user-images.githubusercontent.com/35370833/50633717-9ef07280-0f4c-11e9-949b-5835887e1c99.png) |
--- |

```
narew.info##.fb
narew.info##.tw
narew.info##.gp
narew.info##.yt
narew.info##A[data-original-title="RSS"]
```

**Comment by krystian3w** [comment]
I changed `href="http://www.narew.info/rss"` to `data-original-title="RSS"`, maybe better  ("more generic" than static href).

**Comment by ryanbr** [comment]
So why are we fixing social icons again?

**Comment by krystian3w** [comment]
> `So why are we fixing social icons again?`

I don't understand? We do not still block in `Fanboy's Social Blocking List buttons to login?

---

As my suggestion blocks login buttons them, you have to block, for example:

`##.top-mini-nav > .container > .sbuttons.list-inline.list-unstyled > li > a`

**Comment by krystian3w** [comment]
> `Note, this wasn't stated in the original post.`

Are you asking for a Polish supplement to the Fanboy's Social Blocking List?

```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt
```

**Comment by ryanbr** [comment]
I was stating that your orginal post didnt explain the issue and why it was a problem.

**Comment by krystian3w** [comment]
>  ` why it was a problem.`

OK now I understand.

- one problem - blocked login social buttons (orange rectangles)
- second problem - unblocked social links button on left from login section
