### ISSUE TITLE
NSFW womenshealthmag.com

### ISSUE THREAD

**Issue by mapx-** [ryanbr/fanboy-adblock#87]
`https://forums.lanik.us/viewtopic.php?f=62&t=36960`

`http://www.womenshealthmag.com/life/nude-selfies?internal_recirc=outbrain_arr`
`@@||womenshealthmag.com/*ads`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/fb193c39db59a867866d276d0427d8f7a39ee446
https://github.com/ryanbr/fanboy-adblock/commit/bcb67ad8e64bd3addf287fd10dec22148e1b6483
