### ISSUE TITLE
aftonbladet.se

### ISSUE THREAD

**Issue by blekfitta** [ryanbr/fanboy-adblock#88]
Please help to fix this fucking ads on this web tv news site.

same shitty ads going on and on! 

really irritating.

http://www.aftonbladet.se/nyheter/a/6ObP0/vittnet-till-vansinnesfarden-han-var-helt-tom-i-blicken

**Comment by SMed79** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/85
