### ISSUE TITLE
mobile.twitter.com - unblocked cookie notification

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#886]
### List the website(s) you're having issues:

`mobile.twitter.com`

### What happens?

Cookie box not blocked.

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Android Oreo
- Browser/version: Firefox 64.0.2
- Adblock Extension/version: Ublock Origin 1.17.4

### Other details:

The class name of the cookie notification changes sometimes. These are the ones Ubo's selector is currently offering for me (no id available):

`##.rn-1lgpqti.rn-13qz1uu.rn-bnwqim.rn-1hfyk0a.rn-1mi0q7o.rn-1qfoi16.rn-m611by.rn-bcqeeo.rn-ifefl9.rn-11wrixw.rn-p1pxzi.rn-61z16t.rn-1mnahxq.rn-eqz5dr.rn-1mlwlqe.rn-1qe8dj5.rn-6koalj.rn-deolkf.rn-eps6nq.rn-gxnn5r.rn-ndvcnb.rn-fnigne.rn-13yce4e.rn-mm0ijv.rn-rull8r.rn-14skgim.rn-1efd50x.rn-gvpnoh.rn-1oszu61`

`##.rn-1lgpqti.rn-zchlnj.rn-1xcajam.rn-12vffkv.rn-gy4na3.rn-1mdbw0j.rn-9aemit.rn-wk8lta.rn-bcqeeo.rn-ifefl9.rn-11wrixw.rn-p1pxzi.rn-61z16t.rn-1mnahxq.rn-1d2f490.rn-eqz5dr.rn-1mlwlqe.rn-1qe8dj5.rn-6koalj.rn-deolkf.rn-1p0dtai.rn-gxnn5r.rn-ndvcnb.rn-fnigne.rn-13yce4e.rn-mm0ijv.rn-rull8r.rn-14skgim.rn-1efd50x.rn-aqfbo4.rn-1oszu61`

The beginning seems to be the same: `rn-1lgpqti.rn` so I was wondering would it be possible to implement somekind of wildcard based solution?

Or hide by specific text? (This of course would need multiple languages).

`mobile.twitter.com` can also be viewed through computer also but you need to shrink the window size of your browser, otherwise the notification is not visible.

**Comment by krystian3w** [comment]
Polish list GDPR-Cookies use: `mobile.twitter.com###react-root > div > div > .rn-gvpnoh`

Where found second filter to tests to change `.rn-gvpnoh` to `.rn-1lgpqti.rn`?

**Comment by krystian3w** [comment]
or procedural filtering with `[href]` attrib:

`mobile.twitter.com#?#div:-abp-has(>div>div>span>a[href="https://help.twitter.com/rules-and-policies/twitter-cookies"])`

**Comment by peace2000** [comment]
`mobile.twitter.com###react-root > div > div > .rn-gvpnoh`
and
`mobile.twitter.com###react-root > div > main > div > div > .rn-gvpnoh`

Worked fine for me. Thanks. I consider this fixed. :)

**Comment by krystian3w** [comment]
Again comeback

```
mobile.twitter.com###react-root > div > div > .r-gvpnoh
mobile.twitter.com###react-root > div > main > div > div > .r-gvpnoh
```

**Comment by peace2000** [comment]
Thank you krystian3w for pointing out this change.

I don't understand why they changed that - just to annoy people.

Any way to implement some kind of "has text" based blocking rule?

**Comment by krystian3w** [comment]
Now old filter has does not work and must create again.

**Comment by krystian3w** [comment]
> I don't understand why they changed that - just to annoy people?

Maybe twitter update apps - removed `n` from class names.
