### ISSUE TITLE
Broken login page (www.security.online-banking.hsbc.ca)

### ISSUE THREAD

**Issue by injust** [ryanbr/fanboy-adblock#887]
### List the website(s) you're having issues:
`https://www.security.online-banking.hsbc.ca/gsa/SECURITY_LOGON_PAGE/`

### What happens?
Username cannot be entered into the input field.

### List Subscriptions you're using:
- Fanboy's Annoyance List

### Other details:

`https://www.security.online-banking.hsbc.ca/gsp/saas/Components/default/resources/script/modules/common/widget/Interstitial.js?3.0` is being blocked by the rule `/interstitial.js`.

**Comment by THEtomaso** [comment]
Correct link for testing:
`https://www.services.online-banking.hsbc.ca/gpib/`

Possible fix:
`@@||online-banking.hsbc.ca/gsp/saas/Components/default/resources/script/modules/common/widget/Interstitial.js$script`
