### ISSUE TITLE
Twitch sound info (Fanboy’s Annoyance List​​​​​​​​​)

### ISSUE THREAD

**Issue by fabiabi** [ryanbr/fanboy-adblock#892]
### List the website(s) you're having issues:

`https://www.twitch.tv/videos/361782961`

### What happens?

There is a notification pop up in the video, that informs, that some parts of the video are muted because of copyright

### List Subscriptions you're using:

Fanboy’s Annoyance List

### Your settings

- OS/version: win10
- Browser/version:  chrome
- Adblock Extension/version: ublock origin

### Other details:

![twitch](https://user-images.githubusercontent.com/46575586/51139617-aa914280-1844-11e9-8756-5c85e116a94a.png)
 www.twitch.tv##.player-alert   <-- will fix it

**Comment by ryanbr** [comment]
Leaving, it'll probably cause issues.
