### ISSUE TITLE
directive.com

### ISSUE THREAD

**Issue by KenEDirective** [ryanbr/fanboy-adblock#894]
`directive.com`

### What happens?

When we visit the site at the footer there is a newsletter form that's being blocked it should be here.
https://drive.google.com/a/directive.com/file/d/1pnF229ghoGwH28HlsTgQjXPAGo9ZDL59/view?usp=drivesdk

### List Subscriptions you're using:

Fanboy's Annoyances (blocks in-page pop-ups, social media and related widgets, and other annoyances)

### Your settings

- OS/version: Windows 10 Pro 64-bit 1803
- Browser/version: Chrome Version 71.0.3578.98 (Official Build) **(64-bit)**
- Adblock Extension/version: AdBlock 3.36.0

### Other details:

newsletter-signup
newsletter_subscribe
Are the two I believe are blocking the form from showing up at all.

I also have a question about the Blocking of social media widgets and if you intend to block these on websites based on what it's called. https://drive.google.com/a/directive.com/file/d/1CBkLpLRw8yEmo5Jo_m_NEUT_yiGqjEc2/view?usp=drivesdk

Thanks,

**Comment by Khrin** [comment]
The Annoyances list also block newsletter banners, links, widgets and other related stuff. 

I'm not sure to have fully understood your question. If I understand correctly, to block e.g. social media-related stuff, we use a number of both generic and specific filters, which are applied to websites regardless of their content.

**Comment by KenEDirective** [comment]
So to verify all these are meant to be blocked? Even the form that allows you to subscribe to a newsletter but is not intrusive or forcing itself on anyone?

Thanks for the input

**Comment by THEtomaso** [comment]
ryanbr's opinion:
`https://github.com/ryanbr/fanboy-adblock/issues/596/#issuecomment-433657629`
