### ISSUE TITLE
gathering.tweakers.net - unblocked cookie notification

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#899]
### List the website(s) you're having issues:

`gathering.tweakers.net`

### What happens?

Cookie notification not blocked (the site cannot be used without accepting cookies)

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 64.0.2
- Adblock Extension/version: Ublock Origin 1.17.4

### Other details:

-

**Comment by ryanbr** [comment]
no way to stop these type of cookie messages unfortantly.
