### ISSUE TITLE
Why was this rule added?

### ISSUE THREAD

**Issue by collinbarrett** [ryanbr/fanboy-adblock#9]
Does anybody know why this rule was added to enhancedstats-addon.txt for domain=wired.com? We've been discussing over on the [uAssets repo](https://github.com/uBlockOrigin/uAssets/issues/28). Thanks.

`@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=playonlinux.com|wired.com`

**Comment by SMed79** [comment]
(https://github.com/ryanbr/fanboy-adblock/commit/178551d4954113d6d5550d49d9645def3e9450e5?diff=unified#diff-d88786646d8d046cb375ba7ae71d71ea). 
I think you already answered by  gorhill https://github.com/uBlockOrigin/uAssets/issues/28#issuecomment-214086169

**Comment by ryanbr** [comment]
Has been reviewed, and removed.

https://github.com/ryanbr/fanboy-adblock/commit/ed4abbb90e3cf8cf9e3a2086a1ee56e99855dc33
