### ISSUE TITLE
medipe.pl [banners not loading] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#908]
### List the website(s) you're having issues:

`http://medipe.pl/`

### What happens?

breakage - banners not loading

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 64.0.2 64bit / Opera 57 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.8

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List</summary>

1
![ss_019](https://user-images.githubusercontent.com/43844449/51760853-d1186e80-20cb-11e9-9c5d-4446c348838f.png)

2
![ss484](https://user-images.githubusercontent.com/43844449/51760859-d4abf580-20cb-11e9-86d2-3fb8a73ec771.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the list</summary>

1
![ss_020](https://user-images.githubusercontent.com/43844449/51760887-e2fa1180-20cb-11e9-9e37-c4628eb25e68.png)

2
![ss485](https://user-images.githubusercontent.com/43844449/51760891-e7bec580-20cb-11e9-8dd8-745583a3011f.png)

</details>

**Comment by ryanbr** [comment]
I get the picture at the top, without issue

**Comment by kulfoon** [comment]
The issue is gone for me too, perhpas something fixed it during the 9 days.
