### ISSUE TITLE
blog.google

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#91]
social
```
##.uni-selection-sharer
##.uni-selection-sharer-active
```
* http://i.imgur.com/K1cIB1a.png
```
##[aria-label="Toggle social share buttons"]
```
* http://i.imgur.com/ZOEb57z.png

`https://blog.google/topics/journalism-news/building-better-web-everyone/`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6746be787ceced5913433000db3d9f0e2992d113
