### ISSUE TITLE
intelihotel.pl [animation not loading] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#913]
### List the website(s) you're having issues:

`https://intelihotel.pl/`

### What happens?

breakage - animation not loading

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 64.0.2 64bit / Opera 57 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.8

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List</summary>

![ss_054](https://user-images.githubusercontent.com/43844449/51785839-55b2cd80-215c-11e9-817c-89f07910e24a.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the list</summary>

![ss_053](https://user-images.githubusercontent.com/43844449/51785841-5a778180-215c-11e9-9bfc-45691a079281.png)

</details>

**Comment by ryanbr** [comment]
Flow player animation on the right, works fine here.

**Comment by kulfoon** [comment]
The issue is gone for me too, perhaps something fixed.
