### ISSUE TITLE
Blank page: playosmo.com

### ISSUE THREAD

**Issue by injust** [ryanbr/fanboy-adblock#916]
### List the website(s) you're having issues:
`https://www.playosmo.com/en/`

### What happens?
Page is blank.

### List Subscriptions you're using:
- Fanboy's Annoyance List

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.js-share`

### Possible fix:
`playosmo.com#@#.js-share`
