### ISSUE TITLE
Coockie banner not blocked: dict.leo.org

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#918]
### List the website(s) you're having issues:
`https://dict.leo.org`

### What happens?

cookie banner not blocked
### List Subscriptions you're using:

fanboy's cookie list

### Your settings

- OS/version: win7 (64bit)
- Browser/version: ff 56.0.2
- Adblock Extension/version: uBlock Origin 1.18.2

**Comment by ryanbr** [comment]
I'm not seeing anything, I'm open to other users testing this/filter suggestions.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/52178080-44a43500-27ca-11e9-8439-da1f9b1bdc35.png) |
--- |
 
`##.as-oil-content-overlay`

**Comment by krystian3w** [comment]
Maybe someone list use generic hide and this when does not work:

`##.as-oil-content-overlay`
`##.as-oil[data-qa="oil-Layer"]`
`||vendorlist.consensu.org^$third-party`

**Comment by krystian3w** [comment]
@bestoernesto  try find in uBO logger:

```
@@||dict.leo.org^$generichide
```

![obraz](https://user-images.githubusercontent.com/35370833/52178186-5fc37480-27cb-11e9-82e7-17185c939c69.png) |
--- |

**Comment by ryanbr** [comment]
I have no control of another list using; @@||dict.leo.org^$generichide 

If its your personal filter, disable it. Or report it to the list owner (who includes this generichide filter).

Basically $generichide will override any generic filters, including cookie filters.
