### ISSUE TITLE
Cookie banner not blocked: din.de

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#919]
### List the website(s) you're having issues:
`https://www.din.de/de`

### What happens?
Cookie banner not blocked

### List Subscriptions you're using:

fanboy's cookie list
### Your settings

- OS/version: win7 (64bit)
- Browser/version: ff 56.0.2
- Adblock Extension/version: uBlock Origin 1.18.2

**Comment by krystian3w** [comment]
`##.cookie-banner__cnt`
or
`##.js-cookie-banner.cookie-banner`
