### ISSUE TITLE
Motherboard.vice.com cookie consent

### ISSUE THREAD

**Issue by theel0ja** [ryanbr/fanboy-adblock#923]
### List the website(s) you're having issues:

`https://motherboard.vice.com/en_us/article/9a3wja/cockli-email-server-seized-after-la-bomb-scare-admin-says`

### What happens?

cookie popup

### List Subscriptions you're using:

fanboy all

### Your settings

- OS/version: linux
- Browser/version: firefox
- Adblock Extension/version: ublock origin

**Comment by ryanbr** [comment]
Can't be fixed atm, further developments in ABP need to happen.
