### ISSUE TITLE
Content is blocked on www.stern.de

### ISSUE THREAD

**Issue by cjeroch** [ryanbr/fanboy-adblock#924]
Please have a look on www.stern.de. Nearly all content is blocked with this filter list. 

Thank you 

### Your settings

- OS/version: Mac 10.14.2
- Browser/version: Chrome 72.0.3626.81
- Adblock Extension/version:  ABP 3.4.3

**Comment by ryanbr** [comment]
Force update.

**Comment by cjeroch** [comment]
i use the latest version. i only see the picture gallery and no content

**Comment by ryanbr** [comment]
give it 15mins geez.
