### ISSUE TITLE
superesportes.com.br

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#925]
### List the website(s) you're having issues:

`https://www.mg.superesportes.com.br/app/noticias/futebol/cruzeiro/2019/02/04/noticia_cruzeiro,565310/thiago-neves-do-cruzeiro-se-desculpa-apos-piada-com-barragem.shtml`

https://github.com/AdguardTeam/AdguardFilters/issues/29236

### What happens?

Incorrect blocked social buttons.

Filters cut print button on top: 

![image](https://user-images.githubusercontent.com/35370833/52265076-8b616e80-2933-11e9-8ee7-43ab8246d1b2.png) |
--- |

and  cut button load disqus comment above article:

![image](https://user-images.githubusercontent.com/35370833/52265105-9ddba800-2933-11e9-903a-fa6c5396fd28.png) |
--- |

---

~~And I do not know why does not work function load disqus when click with link~~ "`javascript:scrolltocomments()`" - **this is only scroll to section button**, disqus blocked is by EasyPrivacy.

### List Subscriptions you're using:

Fanboy’s Social Blocking List

### Your settings

- OS/version: Windows 7
- Browser/version:  Chrome 72
- Adblock Extension/version:  uBO 1.18.2

### Other details:

**badfilters**:

`mg.superesportes.com.br#@#.docs`
`mg.superesportes.com.br#@#.btn-share`

My proposition:

`mg.superesportes.com.br###shareFace`
`mg.superesportes.com.br###shareGoogle`
`mg.superesportes.com.br###shareTwitter`

**Comment by THEtomaso** [comment]
> Incorrect blocked social buttons.

How is this "incorrect"?
Looks to me like the social buttons are blocked, like the should be!

--

> Filters cut print button on top

Unlike on some other sites, that 'Print' button is completely useless!
It doesn't provide a clean version of the pages, optimized for printing, or anyting like that.
Instead, it simply does the same job as the Print function in your browser.

--

> I do not know why does not work function load disqus

'A**dGuard Tracking Protection filter**' (a.k.a. '**AdGuard Spyware filter**') already contains the necessary exceptions.
When disabling that filter, Disqus gets blocked by the following filters, at my end:
* EasyPrivacy
* hpHosts' Ad and tracking servers
* MVPS HOSTS
* uBlock filters – Privacy

Blocked scripts:
```
https://www.googletagservices.com/tag/js/gpt.js
https://d.tailtarget.com/profiles.js
```

Possible fix:
```
@@googletagmanager.com/gtm.js$domain=superesportes.com.br
@@tailtarget.com/profiles.js$domain=superesportes.com.br
```

**Comment by krystian3w** [comment]
Print is not social (possible safe cut without :printer:), also hidden disqus button.

**Comment by krystian3w** [comment]
> '**AdGuard Tracking Protection filter**' (a.k.a. '**AdGuard Spyware filter**') already contains the necessary exceptions.

I do no use this in uBO / Nano Adblocker.

**Comment by peace2000** [comment]
It doesn't seem they have disqus anymore on that site.

**Comment by peace2000** [comment]
Printer button is still blocked. But in my opinion, if this is fixed, things would look like a bit uggly :D

![kuva](https://user-images.githubusercontent.com/17256841/72103657-4ce9e600-3332-11ea-9d04-62d950b9e3e6.png)

It's looks stupid to have that printing button without those social media icons.

**Comment by krystian3w** [comment]
Bullshit:

https://disqus.com/embed/comments/?base=default&f=superesportes&t_u=https%3A%2F%2Fwww.mg.superesportes.com.br%2Fapp%2Fnoticias%2Ffutebol%2Fcruzeiro%2F2019%2F02%2F04%2Fnoticia_cruzeiro%2C565310%2Fthiago-neves-do-cruzeiro-se-desculpa-apos-piada-com-barragem.shtml&t_d=%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20Thiago%20Neves%2C%20do%20Cruzeiro%2C%20se%20desculpa%20ap%C3%B3s%20%27piada%27%20com%20barragem%3A%20%27N%C3%A3o%20percebi%20que%20estava%20excedendo%20os%20limites%27%0A%20%20%20%20&t_t=%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20Thiago%20Neves%2C%20do%20Cruzeiro%2C%20se%20desculpa%20ap%C3%B3s%20%27piada%27%20com%20barragem%3A%20%27N%C3%A3o%20percebi%20que%20estava%20excedendo%20os%20limites%27%0A%20%20%20%20&s_o=default#version=628b6417a65008f761f2933339274e3b

**Comment by peace2000** [comment]
For some strange reason I don't see that even though I disable my adblocker.

**Comment by peace2000** [comment]
`@@||tags.t.tailtarget.com/$script,domain=www.mg.superesportes.com.br`

For Disqus-comments

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/pull/4678
