### ISSUE TITLE
malywrednymis.pl [shadow overlay + button] [FSBL] 

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#928]
### List the website(s) you're having issues:

`http://malywrednymis.pl/`

### What happens?

breakage - shadow overlay + button

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Social Blocking List +
AdGuard Social Media filter

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 65 64bit / Opera 57 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Social Blocking List or/and AdGuard Social Media filter</summary>

![ss_004](https://user-images.githubusercontent.com/43844449/52271679-a4bee680-2944-11e9-81bb-c9520beff860.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the both lists</summary>

![ss_005](https://user-images.githubusercontent.com/43844449/52271699-b1dbd580-2944-11e9-9460-7ff622d3c491.png)

</details>
<br>
<details not-open>
<summary>screenshoot 3 - after closing the message</summary>

![ss_006](https://user-images.githubusercontent.com/43844449/52271726-cf10a400-2944-11e9-9651-219a5358030d.png)

</details>

**Comment by ryanbr** [comment]
Not seeing this, closing. If you have a (decent) filter suggestion, submit away.

**Comment by kulfoon** [comment]
The issue is gone for me too, perhaps something fixed it during the 11 days.
