### ISSUE TITLE
koditalk.org

### ISSUE THREAD

**Issue by SMed79** [ryanbr/fanboy-adblock#93]
anti adblock

`||koditalk.org/uploads/set_resources_1/*_jquery.blockUI.js`
or
`@@||koditalk.org/uploads/set_resources_1/*_adframe.js$script`

`http://koditalk.org/`

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/f3453472f3e1fe5079b3ca48f93bdb56a75b9c6b
