### ISSUE TITLE
nytimes gdpr cookie notification (Fanboy’s Annoyance List​​​​​​​​​)

### ISSUE THREAD

**Issue by fabiabi** [ryanbr/fanboy-adblock#930]
`www.nytimes.com`

### What happens?

gdpr cookie notification

### List Subscriptions you're using:

Fanboy’s Annoyance List

### Your settings

- OS/version: windows 10
- Browser/version: ff 65
- Adblock Extension/version: ublock origin

### Other details:
the filter "nytimes.com#@#.expanded.gdpr" seems to be outdated?!

new filter: www.nytimes.com##.e1x0szx60.css-442f5c.expanded-dock.expanded.shown.gdpr

**Comment by ryanbr** [comment]
had to be removed, because it caused issues (with video).
