### ISSUE TITLE
Over 90% of all cookie banners are not blocked

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#931]
### What happens?

After my two problem postings (#918, #919) I noticed that more than 90 percent of all websites didn't block the cookie banner anymore. Later I discovered that only 1,015 of 14,092 filters on Fanboy's Cookie List were used. 
After numerous experiments it turned out that there is an incompatibility between "Fanboy's Cookie List" and the setting "Evaluate cosmetic filters and force their application" in uBlockOrigin. The latter is enabled by default. If you uncheck this setting, most filters on "Fanboy's Cookie List" won't work anymore. I don't know if the cause is in the filter list or in uBlockOrigin, but you'll find out for sure. 

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 56.0.2
- Adblock Extension/version: uBlock Origin

**Comment by kulfoon** [comment]
> bestoernesto: If you uncheck this setting, most filters on "Fanboy's Cookie List" won't work anymore.

This is expected, and what else did you expect, as most of filters on Fanboy's Cookie List are cosmetic filters, it's logical that disabling cosmetic filters in uBO will make them not being used anymore.

**Comment by ryanbr** [comment]
2 report issues representing "90% of sites", of which 1 report was out of my control, and the other seemed filtered already. If you have other sites, report them.

**Comment by krystian3w** [comment]
> I discovered that only 1,015 of 14,092 filters on Fanboy's Cookie List

remove from uBlock "`https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fanboy-cookiemonster.txt`" and should jump used filters to ~14000.

**Comment by krystian3w** [comment]
uBO no support reddirect, because is to dangerous in opinion **`@`gorhill**.

**Comment by ryanbr** [comment]
Re-directed feature saved me a few times in the history of the list, pre-Easylist. I haven't seen any sense of abuse.

**Comment by kulfoon** [comment]
krystian3w and ryanbr: it seems u haven't got the whole issue, it's not about a redirect, (because even enabling both the old "Fanboy's Cookiemonster List" and then the new "Fanboy's Cookie List" still gives over 5000 filters enabled on the new list), the issue is simply: the OP just disabled cosmetic filtering...(unchecked "parse and enforce cosmetic filters") in uBO:

![ss506](https://user-images.githubusercontent.com/43844449/52328655-a6de7f00-29f0-11e9-82f8-3e0e42953a90.png)

**Comment by kulfoon** [comment]
With **un**checked* "parse and enforce comsmetic filters" (the OP case) that's not possible.

**Comment by krystian3w** [comment]
And 5k is more than 10% (~35%) :sun_behind_rain_cloud: :1234:.

**Comment by kulfoon** [comment]
Again, this is not about 5k (the both old and the new list enabled case),  the OP simply used "Fanboy's Cookie List" with "parse and enforce comsmetic filters" disabled which gives about 1000 filters used.
