### ISSUE TITLE
Annoyance banner on https://www.datanyze.com/market-share/dns#market-share-table

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#932]
Wait for few seconds if it doesn't show up immediately.
Browser: Firefox 66 Beta
Adblocker: uBlock Origin
Filter: Fanboy's Annoyance List

Screenshot: <img src="https://mnmlsv.net/images/7f7998cc5647759b0db70cf6d69eab86.png" alt="7f7998cc5647759b0db70cf6d69eab86.png" border="0" />

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/37b353f96841a4293c21286c2b58753ba73d9d5a
