### ISSUE TITLE
Bad filter: costa.co.uk

### ISSUE THREAD

**Issue by funkydude** [ryanbr/fanboy-adblock#937]
### List the website(s) you're having issues:

URL ```https://www.costa.co.uk/contact/#faq-coffeeclub```

### What happens?

Clicking on the various FAQ entries is broken.

### List Subscriptions you're using:

Fanboy’s Annoyance List

### Other details:

The issue is the following filter entry: ```/cookieconsent.$script```

![image](https://user-images.githubusercontent.com/16833/52613119-a2004c00-2e84-11e9-9fd4-c84ca752c8ec.png)

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`/cookieconsent.$~stylesheet`

### Possible fix:
`@@||costa.co.uk/js/libs/cookieconsent.min.js`

### Note:
The script is also blocked by the following rule (found in '**AdGuard Annoyances filter**'):
`/cookieconsent.`

Issue report here:
https://github.com/AdguardTeam/AdguardFilters/issues/29556/
