### ISSUE TITLE
FETL breaks 6abc.com tab Icon

### ISSUE THREAD

**Issue by pjpreilly** [ryanbr/fanboy-adblock#938]
The tab icon is filtered on this site https://6abc.com/ when enabling "Fanboys Enhanced Tracking List".
Enable the filter & load the page to observe the issue.

**Comment by ryanbr** [comment]
Its expected.

**Comment by pjpreilly** [comment]
Any further explanation would be appreciated. This works fine on the current version of Waterfox though.

**Comment by ryanbr** [comment]
its blocked via favicon.ico tracking. I expect some sites would be affected.
