### ISSUE TITLE
favicon blocking

### ISSUE THREAD

**Issue by joey04** [ryanbr/fanboy-adblock#94]
[This rule](https://github.com/ryanbr/fanboy-adblock/blob/50a6b7547cecbf0fdb1241805f66a8da96c2c1b9/enhancedstats-addon.txt#L369) has the comment that it's for popads tracking:

`/favicon.ico$image,third-party,domain=~reddit.com`

Favicons are "behind-the-scene" (BTS) in uBlock Origin on Firefox and other Gecko-based browsers. BTS is entirely whitelisted with default uBO settings, so this rule normally wouldn't take effect. I don't whitelist BTS, hence favicons are blocked by this rule, but I like having them so override it.

I'm wondering why this broad favicon blocking rule. Are they really a tracking threat?

Edit: I forgot about [ETag tracking](http://lucb1e.com/rp/cookielesscookies/) when I posted earlier. Perhaps that's the concern here. (But it's still kinda odd that only Reddit is exempt.)

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=36987

**Comment by ryanbr** [comment]
Still waiting on a response.

**Comment by joey04** [comment]
some follow-up info:

For me, this rule seems to only affect uBO on Pale Moon. The way it fetches favicons causes uBO to not know which tab they come from, which means they're considered "behind the scene" 3rd party requests. Hence they get blocked with this rule, which I override.

Oddly, though, on Firefox 53 this rule doesn't take effect even though the same favicons are also 3rd party behind the scene.

On Chrome favicons are fetched like any other 1st party resource, so the rule doesn't matter.

**Comment by ryanbr** [comment]
Pale Moon should be fixed if that was the case, I have no love for a old/outdated Firefox fork

**Comment by Brottweiler** [comment]
The **Fanboy’s Enhanced Tracking List** filter seems to block the favicon for Twitter and 4chan for me.

**Comment by ryanbr** [comment]
Took a while, but its still used for popads. But Fixed Twitter and 4chan.

https://github.com/ryanbr/fanboy-adblock/commit/3c65ef7669241885639dd217e62959e0d95e451d

**Comment by Brottweiler** [comment]
@ryanbr The Enhanced Tracking List is also blocking the favicon for https://www.duolingo.com/

**Comment by SMed79** [comment]
I checked and it is not blocked http://i.imgur.com/p5wh14f.png

**Comment by Brottweiler** [comment]
@SMed79 you're right, it's not blocked for me anymore. Weird...
