### ISSUE TITLE
kobiecareaktywacja.pl [shadow overlay] [FSBL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#940]
### List the website(s) you're having issues:

`https://www.kobiecareaktywacja.pl/`

### What happens?

breakage - shadow overlay + not fully cut popup

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Social Blocking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 65.0.1 64bit / Opera 58 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Social Blocking List</summary>

![ss_004](https://user-images.githubusercontent.com/43844449/52899087-4288a000-31e6-11e9-8447-675722f9900d.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the list</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/52899077-30a6fd00-31e6-11e9-9883-47e9b6b7f1ac.png)

</details>
<br>
<details not-open>
<summary>screenshoot 3 - after closing the message</summary>

![ss_003](https://user-images.githubusercontent.com/43844449/52899081-3997ce80-31e6-11e9-9dea-3914bc265ea0.png)

</details>

**Comment by ryanbr** [comment]
can't fix it. the window still pops up, so atleast it can be closed.
