### ISSUE TITLE
akkukauppa.com cookie notification

### ISSUE THREAD

**Issue by jounihh** [ryanbr/fanboy-adblock#941]
### List the website(s) you're having issues:

https://akkukauppa.com/

### What happens?

cookie notification at the top

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/40239267/52900163-4246cf80-31fb-11e9-8cd9-3f04eb05e7a8.png)

### Your settings

- OS/version: windows 10
- Browser/version: waterfox latest
- Adblock Extension/version: Nano Adblocker 1.0.0.87

### Other details:

 
Possible fix:
akkukauppa.com###enhanced-privacy-popup
or maybe just:
###enhanced-privacy-popup

**Comment by THEtomaso** [comment]
Before anyone can look into this issue, the site really needs to fix their security certificate!:
`https://www.ssllabs.com/ssltest/analyze.html?d=akkukauppa.com/`
