### ISSUE TITLE
jyllands-posten.dk

### ISSUE THREAD

**Issue by jhg21** [ryanbr/fanboy-adblock#943]
### List the website(s) you're having issues:
`https://jyllands-posten.dk/`

### What happens?
Unable to scroll through the page.

### List Subscriptions you're using:
uBO default +
Fanboy's Cookie List

### Your settings
- OS/version: Windows 10 64 bit
- Browser/version: Firefox 65.0.1
- Adblock Extension/version: uBlock Origin 1.18.4

### Other details:
Disabling adblock reveals a pop-up window from Quantcast stating they use cookies, all the standard stuff. Pressing ok/accept, and then re-enabling adblock the site now works.

**Comment by jhg21** [comment]
I think you're missing the first character, isn't supposed to say:
```
jyllands-posten.dk#@#.qc-cmp-showing
jyllands-posten.dk#@#.qc-cmp-ui-container
```

**Comment by Khrin** [comment]
Fixed yesterday https://github.com/easylist/easylist/commit/cc0cb89630737812ce2edc0012cb2c77a05ae696
