### ISSUE TITLE
lewat.in

### ISSUE THREAD

**Issue by 3xploiton3** [ryanbr/fanboy-adblock#946]
![image](https://user-images.githubusercontent.com/19517680/52919561-40355b80-3336-11e9-9413-1523ef1951d7.png)
[
![image](https://user-images.githubusercontent.com/19517680/52919584-707cfa00-3336-11e9-93f2-aa070ce30bb1.png)
](url)
remove this rule
`@@/fuckadblock.$script`

_Originally posted by @3xploiton3 in https://github.com/ryanbr/fanboy-adblock/issues/625#issuecomment-464512556_

**Comment by THEtomaso** [comment]
If you consider the existing fixes, this seems to be the prefered solution:
`@@*$generichide,domain=lewat.in`

**Comment by krystian3w** [comment]
Possible reproduce without Fanboy Enhanced Trackers List?
