### ISSUE TITLE
khronos.org

### ISSUE THREAD

**Issue by Khronoswebmaster** [ryanbr/fanboy-adblock#947]
### List the website(s) you're having issues:

`www.khronos.org`

### What happens?

With fanboy list enabled in Adblock (tested in Chrome and Firefox), no content shows.

### List Subscriptions you're using:

Default settings with Fanboy list enabled. Disable Fanboy list and the issue goes away.

### Your settings

One Adblock extension with no other extensions installed. 

- OS/version:  macOS 10.13.6  and Windows 8.1
- Browser/version: 
Chrome Version 72.0.3626.109 (Official Build) (64-bit) (macOS and Windows)
Firefox 65.0 (64-bit) (macOS)
- Adblock Extension/version: 3.25.0

### Other details:

No screen shot as it shows only a big empty dark blue page (our site background colour).

**Comment by Khrin** [comment]
You're the webmaster, right? Why can't you fix your own website?

**Comment by outofcontrol** [comment]
I am. What am I fixing? What is it that the fanboy block list doesn't like? How do I figure this out?

**Comment by Khronoswebmaster** [comment]
Our site content is blocked because we have id="backtop" as a wrapper div, which is linked to by the Back to Top button. Changing this from a wrapping div to a single closed div at the top fixed the issue. Clarification on why is welcome.

**Comment by THEtomaso** [comment]
I'm unable to reproduce this issue from my end, using **uBlock Origin**.

Just to make sure, I added all these blocking rule variants, and even made them site-specific:
```
khronos.org##[id="backtop"]
khronos.org##.backtop
khronos.org###backtop
```
Regardlessly, the site site still loads just fine!

This should be added to '**Fanboy's Annoyance List**' though:
`khronos.org##.fa-arrow-up`

**Comment by outofcontrol** [comment]
Thank you for looking @THEtomaso.  I did change the wrapping div #backtop to just a single closed div at the top. Your addition is welcome to avoid any static pages that might not get update right away.
