### ISSUE TITLE
Block "Open in app" banners

### ISSUE THREAD

**Issue by KAMiKAZOW** [ryanbr/fanboy-adblock#949]
On mobile many websites display annoying banners urging users to download their app instead.

Prominent examples include Twitter and Reddit.

Any chance those get added to the Annoyances list?

**Comment by krystian3w** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/759

I do not think so without domains list.

**Comment by krystian3w** [comment]
Also see this:

`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/uBO%20list%20extensions/BrowseWebsitesWithoutLoggingIn-uBOExtension.txt`

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/uBO%20list%20extensions/BrowseWebsitesWithoutLoggingIn-uBOExtension.txt

**Comment by krystian3w** [comment]
Also see this: 

* "🚪 Browse websites without logging in"

`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt` <sup>[\[open\]](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt), [\[subscribe\]](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt&title=Browse%20websites%20without%20logging%20in)</sup>

**Comment by ryanbr** [comment]
Most are taken care of in the Annoyances list, some sites wont work well however (very selective on whats blocked)
