### ISSUE TITLE
Tinder.com - Various issues

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#950]
Affected site:
`https://tinder.com/`

--

### Issue 1:
The page won't load.

Screenshot:
Not needed, as the problem is obvious.

Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

Problem rule:
`/CookiePolicyBanner-`

Blocked script:
`https://tinder.com/static/build/chunks/CookiePolicyBanner-b5d6093be999ca5944b5.js`

Possible fix:
`@@/CookiePolicyBanner-$domain=tinder.com`

--

### Issue 2:
Anti-adblock function.

Screenshot:
![filterissue-tinder](https://user-images.githubusercontent.com/9382674/53288956-cc5cde00-378f-11e9-96f1-1445b9571192.jpg)

How to reproduce:
Click on the "LOG IN" or "SIGN UP" button, to open the "GET STARTED" window.
(You might have to close and re-open it, for the warning to trigger)

Problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

Problem rule:
`##.button--facebook`

Possible fixes:
`#@#.button--facebook`
or
`@@||tinder.com^$generichide`

--

### Issue 3:
Can't log in with Facebook.
(The site offers a dating service, and the whole damn thing seems to depend on Facebook)

Problem filter:
* Anti-Facebook List

Problem rule:
`||connect.facebook.net^$third-party`

Possible fix:
`@@||connect.facebook.net^$third-party,domain=tinder.com`

--

System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.8 (XUL)

**Comment by THEtomaso** [comment]
> `2cdd913`

A problem seems to have occured with this commit.
Somehow, it didn't make it to the list!

**Comment by krystian3w** [comment]
Maybe cookie bar visible:

```
tinder.com#?#div[class="Pos(f) Start(0) End(0) Z(90210) Bxsh($bxsh-4-way-spread) B(0) Bgc(#fff) C($c-secondary)"]:-abp-contains(cookie)
```

**Comment by ryanbr** [comment]
is there a more extension agnostic filter?

**Comment by THEtomaso** [comment]
Found in '**AdGuard Annoyances filter**':
`tinder.com##.App > div[class="Pos(f) Start(0) End(0) Z(90210) Bxsh($bxsh-4-way-spread) B(0) Bgc(#fff) C($c-secondary)"]`

Found in '**I don't care about cookies**':
`tinder.com###content > span > .App > div[class*="Start"]`

Both of the above filters seems to work just fine.

**Comment by krystian3w** [comment]
I reported white block into uAssets:

```
tinder.com###content > span > .App main div[class^="Pos"][class*="NetHeight"]:style(height: 100% !important;)
```
