### ISSUE TITLE
TMZ.com [Issue #794 reopen-reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#951]
Turns out that yet another exception rule is needed for `TMZ.com`.

All details here:
`https://github.com/ryanbr/fanboy-adblock/issues/794/#issuecomment-466716793`

**Comment by krystian3w** [comment]
```
/wbconsent-$domain=~tmz.com
```

But Nano can't find "`wbconsent-`" in both files.

**Comment by THEtomaso** [comment]
What the hell!?
This is weird.
I can confirm that the rule doesn't exist anymore.
However, I can find no record of it being removed!

Here's proof that it actually existed:
https://github.com/uBlock-LLC/uBlock/blob/master/assets/thirdparties/secure.fanboy.co.nz/fanboy-cookiemonster.txt#L628

Oh well, guess I can close this report then.
