### ISSUE TITLE
Tinder.com [Issue #950 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#952]
There was a problem with one of the commits.
More info here:
https://github.com/ryanbr/fanboy-adblock/issues/950#issuecomment-466758171

**Comment by ryanbr** [comment]
was resolved now

**Comment by THEtomaso** [comment]
No, the issue has NOT been resolved!
The cookie bar is an entirely different issue all together, which was pointed out later, by krystian3w.
Please follow the link in my previous post, to see what the real issue is all about!
