### ISSUE TITLE
3obieg.pl [popup/message/error] [FSBL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#953]
### List the website(s) you're having issues:

`https://3obieg.pl/`

### What happens?

Fanboy's Social Blocking List blocks social icons, what triggers a message with an error:
"The skin icon with label can't be loaded". Clicking on the message closes it.

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Social Blocking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 65.0.1 64bit / Opera 58 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Social Blocking List</summary>

![ss578](https://user-images.githubusercontent.com/43844449/53350976-9d29a680-3920-11e9-9142-6512e7d59b5e.png)

</details>
.
</details>
<br>
<details not-open>
<summary>screenshoot 2 - after disabling the list or closing the message</summary>

![ss579](https://user-images.githubusercontent.com/43844449/53350980-a0249700-3920-11e9-9005-bcf371f536c2.png)

</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9b8f2fe4d1058244fc5fb3b95f4e9add1994d02f
