### ISSUE TITLE
web2.0calc.com [Cookie message + breakage] [FCL + IDCACA]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#956]
### List the website(s) you're having issues:

`https://web2.0calc.com/`

### What happens?

This is a 2in1 issue:

1. Cookie Message (Fanboy's Cookie List)
2. The breakage of the website ([I don't care about cookies addon/filter](https://www.i-dont-care-about-cookies.eu/)) the calculator won't work, can't do any math, because it instead will display you a message: "This feature requires your approval of cookies.". I put here the 2nd issue because it's the best calculator online, so it's good to inform as many people as possible about it's breakage by IDCACA.

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy's Cookie List +
I don't care about cookies addon

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 65.0.1 64bit / Opera 58 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.4

### Other details:

Screenshoots (Fanboy's Cookie List is enabled too):

<details not-open>
<summary>screenshoot 1 - after enabling I don't care about cookies addon</summary>

![ss_060](https://user-images.githubusercontent.com/43844449/53473835-c571ec00-3a6b-11e9-9f40-4dc98cf5b9f9.png)

</details>
<br>

<details not-open>
<summary>screenshoot 2 - after disabling I don't care about cookies addon</summary>

![ss_061](https://user-images.githubusercontent.com/43844449/53473849-cb67cd00-3a6b-11e9-80ae-19c4fcd83172.png)

</details>
<br>

<details not-open>
<summary>screenshoot 3 - after accepting the cookie message</summary>

![ss_062](https://user-images.githubusercontent.com/43844449/53473863-d9b5e900-3a6b-11e9-9098-09b2f2ac4073.png)

</details>
<br>
I've emailed an author of IDCACA.

**Comment by kiboke** [comment]
In the next version, "I don't care about cookies" extension will auto-accept the cookie policy; IDCAC filterlist will stop hiding the cookie message so it can be manually accepted. Thanks for reporting!

**Comment by ryanbr** [comment]
Doesn't affect Fanboy Cookie list here, it'll show it. Since its needed for the calc stuffs.
