### ISSUE TITLE
ostrzegamy.online

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#957]
![2019-02-28-zagrozenia duchowe](https://user-images.githubusercontent.com/5884000/53571760-f59fb480-3b69-11e9-97a1-0c7f795184d7.png)

![2019-02-28-ublock rejestrator](https://user-images.githubusercontent.com/5884000/53571774-fd5f5900-3b69-11e9-97d1-381dea9c7a4f.png)

broken page

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`##.rodo-popup`

### Possible fix (allowing the privacy consent):
`ostrzegamy.online#@#.rodo-popup`

### Other filters blocking it:
* I don't care about cookies (Report sent)

**Comment by krystian3w** [comment]
I try fix in Polish :cookie: / :shield: filters.

**Comment by krystian3w** [comment]
uBO / AdGuard fix:

```
ostrzegamy.online##.rodo-popup, .rodo-overlay
ostrzegamy.online##body.rodo-locked #page-container > *:style(filter: none !important;)
ostrzegamy.online##body.rodo-locked, html.rodo-locked:style(overflow: auto !important;)
```

**Comment by ryanbr** [comment]
was resolved.
