### ISSUE TITLE
enhanced stats list allows

### ISSUE THREAD

**Issue by jawz101** [ryanbr/fanboy-adblock#958]
Is there a reason for all of these whitelisted entries in the enhanced tracking list?  I opt not to use this list because I see so much that it goes ahead and allows rather than block.

https://www.fanboy.co.nz/enhancedstats.txt

Examples

@@/advertising.js$script 
@@/assets/advertisement-$script 
@@/common/ads.js$script 
@@/javascript/ads.js$script
@@/javascripts/ads.js 
@@/js/adblock.js$script
@@/js/ads.js$script
@@/js/adsense.js$script 
@@/js/advertisement-$script 
@@/js/advertisement.$script 
@@/js/adverts.$script
@@/nonAdBlock/*$script 
@@/plugins/ad-blocking-detector/*$script
@@/script/ad.js$script 
@@/script/ad.php$script 
@@/scripts/ads.js$script 
@@/Shared/ads.js$script 
@@/static/ads.js$script 
@@/wp-content/*/ad-$script,xmlhttprequest 
@@/wp-content/*/ads*.js$script,xmlhttprequest 
@@/wp-content/*/adve*.js$script,xmlhttprequest 
@@/wp-content/*/show-ads.js$script,xmlhttprequest
@@||2giga.link^*/ads.js 
@@||a-o.ninja/*ad-$script,~third-party 
@@||a-o.ninja/wp-content/*ad.$script,~third-party 
@@||abcnews.com/assets/js/adblocker.js 
@@||adcash.com/showads.js @@||ads.bumq.com/ad_show*.js$script 
@@||ads.mic.com/host.js
@@||ads1-adnow.com/js/ads.js

**Comment by ryanbr** [comment]
Because its for stopping anti-adblock from detecting us.

**Comment by jawz101** [comment]
ah
