### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#959]
### List the website(s) you're having issues:

```
https://www.dropbox.com/s/7cuieg0a4yss7of/policies.json?dl=0
```

### What happens?

Blocked download bar for files manager:

![obraz](https://user-images.githubusercontent.com/35370833/53607889-e009a980-3bc0-11e9-8068-d0a6fba1b441.png) |
--- |

after disable social list:

![obraz](https://user-images.githubusercontent.com/35370833/53607916-ffa0d200-3bc0-11e9-8d12-d7e78623ae58.png) |
--- |

"zaloguj się" = "Log in". | "Pobierz" = "Download".
 --- | ---

### List Subscriptions you're using:

Fanboy's Social Blocking List

### Your settings

- OS/version: Windows 7
- Browser/version: Firefox 65.0.1
- Adblock Extension/version: uBO 1.18.4

###### badfilter:

`/icon_google_` - removed now.
`/share_button.`  - Drobpox again no tested in real time Fanoy Annoyance / Fanboy Social.

###### works exception:

`@@||dropboxstatic.com/static/compiled/js/$script,domain=www.dropbox.com`

**Comment by THEtomaso** [comment]
Confirmed.

**Comment by krystian3w** [comment]
I suppose dropbox read this issue and change name for script...

**Comment by THEtomaso** [comment]
Leave any filter issue unattended long enough, and they'll all fix themselves in the end! :)

**Comment by krystian3w** [comment]
Unfortunately, not always.

**Comment by krystian3w** [comment]
Again broken by other generic.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5657993edef055083e8014bf6936d1165c764ff3
