### ISSUE TITLE
en.uptodown.com

### ISSUE THREAD

**Issue by clementine123** [ryanbr/fanboy-adblock#96]
Hi,

I am using uBO for Chrome on Windows and observed that the thumnail images do not show for certain social apps listed on this page:

http://en.uptodown.com/android

I researched and conclude that this is due to some filters included in the "Fanboy’s Annoyance List".

/icons/youtube
/icons/facebook
/icons/youtube
/icons/instagram
etc...

As seen in the screenshot, the thumbnail images do not show. Please exclude the filters.

![thumbnail missing](https://user-images.githubusercontent.com/6959116/27226309-fd2587d6-52bb-11e7-9446-4d630f252aa6.jpg)

**Comment by ryanbr** [comment]
has the site changed? 

`
http://i.utdstc.com/icons/150/facebook-android.png
http://i.utdstc.com/icons/150/facebook-lite-android.png
http://i.utdstc.com/icons/150/facebook-messenger-android.png
http://i.utdstc.com/icons/256/facebook-android.png
`

Nothing hitting /icons/facebook

**Comment by clementine123** [comment]
I just checked again and see the links in the log in uBO. How are you checking?

1. Visit this page

http://en.uptodown.com/android/top

2. Click on uBO extension icon and click on the open log icon.

3. On the log page, refresh the page and you will see the links.

**Comment by ryanbr** [comment]
http://imgur.com/1fBqv3p

Heres what I see.

**Comment by ryanbr** [comment]
I'll just add the whitelist, doesn't seem harmful.

https://github.com/easylist/easylist/commit/88f8eb2facaf304f1429e5c1c4498b544fa2f9cd

**Comment by clementine123** [comment]
Thank you. Fixed the issue. I can now see the app thumbnails. Not sure why was it added in the first place.
