### ISSUE TITLE
autonaminuty.org [shadow overlay] [FSBL + ASMF]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#963]
### List the website(s) you're having issues:

`http://autonaminuty.org/ `

### What happens?

breakage - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Social Blocking List +
AdGuard Social Media filter

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 65.0.2 64bit / Opera 58 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Social Blocking List and/or AdGuard Social Media filter</summary>

![ss_033](https://user-images.githubusercontent.com/43844449/53731055-e5dde400-3e79-11e9-856e-bc943d1957c8.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the lists</summary>

![ss_031](https://user-images.githubusercontent.com/43844449/53731070-ee361f00-3e79-11e9-8958-a29f2d1107e5.png)

</details>
<br>
<details not-open>
<summary>screenshoot 3 - after closing the message</summary>

![ss_035](https://user-images.githubusercontent.com/43844449/53731780-1c1c6300-3e7c-11e9-8487-10cc50269489.png)

</details>

**Comment by ryanbr** [comment]
In this case, use the above filter supplement ^
