### ISSUE TITLE
google.com HTML <a> ping

### ISSUE THREAD

**Issue by fghhfg** [ryanbr/fanboy-adblock#964]
### List the website(s) you're having issues:

google search results:

```html
<a href="https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns" ping="/url?sa=t&amp;source=web&amp;rct=j&amp;url=https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns&amp;ved=2ahUKEwiDqubUk-vgAhWFL6YKHf0dCQMQFjAJegQICRAB">
  <h3 class="LC20lb">Referer header: privacy and security concerns - Web security | MDN</h3><br>
  <div class="TbwUpd"><cite class="iUh30">https://developer.mozilla.org/en.../Referer_header:_privacy_and_security_concerns</cite></div>
</a>
```

### What happens?

When you click links on google search results page, it sends a tracking...

### List Subscriptions you're using:

Enhanced Trackers List (could cause some false positives, please report any issues)

### Your settings

- OS/version: Windows 7
- Browser/version: Chrome 72
- Adblock Extension/version: adguard

### Other details:

![2019-03-05 22_04_58-_referrer_ privacy - google search](https://user-images.githubusercontent.com/1284845/53810845-cedee500-3f92-11e9-82ca-9e8e0dfb4ff1.jpg)

you can verify this on DevTools of chrome:

![2019-03-05 21_51_43-devtools - developer mozilla org_en-us_docs_web_security_referer_header__privacy](https://user-images.githubusercontent.com/1284845/53810477-0305d600-3f92-11e9-9fe1-041e4e8a9523.jpg)

ref:
https://www.eff.org/deeplinks/2018/10/privacy-badger-now-fights-more-sneaky-google-tracking

---
2019/march/5

- AdGuard Spyware filter
- EasyPrivacy
- Fanboy's Enhanced Tracking List

no one block this...

Is this a tracking or I just misunderstand something...

**Comment by krystian3w** [comment]
uBO: `google.*##+js(remove-attr.js, ping, div[class] > a[ping])`

**Comment by krystian3w** [comment]
@mapx- / @okiehsch:

```js
!#if env_chromium
google.*##+js(remove-attr.js, ping, div[class] > a[ping])
!#endif
```

**Comment by uBlock-user** [comment]
Here's your uBO fix --

`google.*##+js(set-constant.js, navigator.sendBeacon, noopFunc)`

**Comment by krystian3w** [comment]
Remove attr works too late?

**Comment by ryanbr** [comment]
there is $ping in ABP, does this fix the issue?

`google.com^$ping`

**Comment by Khrin** [comment]
For what I can see, all «ping» elements generated on Google search pages, are already all blocked by Easyprivacy.

**Comment by ryanbr** [comment]
Does UbO support $ping?

**Comment by okiehsch** [comment]
> Does UbO support $ping?

Yes, but all "ping" requests are already blocked on my end.

**Comment by uBlock-user** [comment]
ping is only used for hyperlinks, `navigator.sendBeacon` can be used anywhere

**Comment by ryanbr** [comment]
@fghhfg might be an adguard issue with $ping, maybe they don't support it? but ubo and ABP seem fine here

**Comment by fghhfg** [comment]
@ryanbr @Khrin 
the track __disappear__ with default setting of `uBlock Origin`.

Adblock Plus don't block it.

May I ask your setting? or which rule?

**Comment by uBlock-user** [comment]
> but Adblock Plus does not block it.

because ABP don't have https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-hyperlink-auditing

**Comment by ryanbr** [comment]
Not something I can fix here. closing this ticket.
