### ISSUE TITLE
 Cookie banner not blocked - kirjasto.kyyti.fi

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#966]
### List the website(s) you're having issues:

`kirjasto.kyyti.fi` (the exact url where I encountered the banner: `https://kirjasto.kyyti.fi/cgi-bin/koha/opac-detail.pl?biblionumber=874107`

### What happens?

Cookie banner not blocked

### List Subscriptions you're using:

Fanboy's cookie list

### Your settings

    * OS/version: Win 10

    * Browser/version: Firefox 65.0.2

    * Adblock Extension/version: uBlock Origin 1.18.4

### Other details:

It can be blocked by this general sounding rule:

`###cookie-law`

**Comment by ryanbr** [comment]
Should be blocked already?
