### ISSUE TITLE
sklep.visionexpress.pl [shadow overlay] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#967]
The bug orginally found here: https://github.com/MajkiIT/polish-ads-filter/issues/12395

### List the website(s) you're having issues:

`https://sklep.visionexpress.pl/`

### What happens?

breakage - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 65.0.2 64bit / Opera 58 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.4

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List</summary>

![ss_001](https://user-images.githubusercontent.com/43844449/54045570-451d5a80-41d2-11e9-8902-f6ac464e4782.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the list</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/54045585-4f3f5900-41d2-11e9-882b-0b3221c03f2b.png)

</details>
<br>
<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_003](https://user-images.githubusercontent.com/43844449/54045605-5a928480-41d2-11e9-80c6-264e4f64b813.png)

</details>

**Comment by krystian3w** [comment]
I suppose no possible block  Pop-Up in Adblock Plus without breaking completly shop.
