### ISSUE TITLE
Cookie banner not blocked: derstandard.at

### ISSUE THREAD

**Issue by bestoernesto** [ryanbr/fanboy-adblock#969]
### List the website(s) you're having issues:
`https://derstandard.at/`

### What happens?
Cookie banner not blocked. 
However, the banner attached directly under the cookie banner to subscribe to the website should be retained in any case.

### List Subscriptions you're using:
fanboy's cookie list

### Your settings

- OS/version: Win7 (64bit)
- Browser/version: FF 65.0.2
- Adblock Extension/version: uBlock Origin 1.18.4

**Comment by ryanbr** [comment]
Can't be blocked unfortunately..
