### ISSUE TITLE
Blocks privatechat on social media sites

### ISSUE THREAD

**Issue by ajan1** [ryanbr/fanboy-adblock#97]
These lists blocks private chat on my site:
###cometchat
###cometchat_base

My site uses: https://www.cometchat.com/

**Comment by ryanbr** [comment]
What is the site where its breaking?

**Comment by ajan1** [comment]
https://randomi.fi/ (site is in finnish) 2 site users have reported that to me.

**Comment by ryanbr** [comment]
Page loaded fine, didn't see cometchat.

**Comment by ajan1** [comment]
You must be logged in to site, it is private chat.

**Comment by ajan1** [comment]
It is easier to test with cometchat own demo: https://chat.phpchatsoftware.com/docked.php

**Comment by ryanbr** [comment]
Took a while, but I'm removed it. I guess there is some value in it.

https://github.com/easylist/easylist/commit/d79e92411013719e4611e897d16e6e4f15ac0d7e
