### ISSUE TITLE
polskikoszyk.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#971]
### List the website(s) you're having issues:

`https://polskikoszyk.pl/`

### What happens?

empty

### List Subscriptions you're using:

https://gist.github.com/KonoromiHimaries/9bc55fcafd3fab612f1f8dfa59f8f572

### Your settings

- OS/version: w10
- Browser/version: chr latest stable 
- Adblock Extension/version: ubo latest stable

**Comment by THEtomaso** [comment]
Summary:

### Problem filter:
* Fanboy's Annoyance List

### Problem rule:
`##.scroll-top`

### Possible fix (allowing the site to load, and blocking the scroll-to-top button):
```
polskikoszyk.pl#@#.scroll-top
polskikoszyk.pl##.btn-scroll-top
```

**Comment by krystian3w** [comment]
uBO / AdGuard:

```css
polskikoszyk.pl##body.cookie .topsubbar:style(top: 57px !important;)
polskikoszyk.pl##body.cookie .search-box:style(top: 61px !important;)
polskikoszyk.pl##body.cookie .topbar:style(top: 0 !important;)
polskikoszyk.pl##body.cookie .promocja-header:style(top: 90px !important;)
polskikoszyk.pl##body.cookie .layout-right-col:style(padding-top: 25px !important;)
polskikoszyk.pl##body.cookie .menu-toggle, body.cookie .fixed-actions-mobile:style(top: 12px !important;)
```
