### ISSUE TITLE
Polska Press Group [over 17 websites] [broken videos] [FCL + IDCAC + PFRC]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#973]
### List the website(s) you're having issues:

https://github.com/MajkiIT/polish-ads-filter/issues/11631#issue-402465122

### What happens?

breakage - broken videos (3 cookie filters lists affected...nasty bug)

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List  +
I dont'care about cookies +
Polskie Filtry RODO-Ciasteczkowe

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 65.0.2 64bit / Opera 58 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.9rc2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling one or any of the lists: </summary>

![ss_001](https://user-images.githubusercontent.com/43844449/54608812-dc47a500-4a51-11e9-859c-7b194702163c.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the lists</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/54608845-f1bccf00-4a51-11e9-8cb3-350ded4bb112.png)

</details>

**Comment by krystian3w** [comment]
```
@@||sso.ppapi.pl/rodo.js$xmlhttprequest
```

**Comment by krystian3w** [comment]
Or specifi filter:

<h1>

```
/rodo.js$script
```

</h1>

**Comment by kiboke** [comment]
On all of these websites there are 2 related requests:
1. `rodo.js?pp_pr=` which displays a cookie warning
2. `rodo.js?consents=true` which is related to video

I will remove blocking of `rodo.js` in "I don't care about cookies". Instead, I will block `rodo.js?pp_pr= `. Cookie warnings will be gone and videos will work fine then.

**Comment by krystian3w** [comment]
`pp_pr=` bad idea see this:

```
/rodo.js$domain=discopolomusic.pl|geekweek.pl|mowianamiescie.pl|obi.pl|playa.pl|polsat.pl|polsat1.pl|polsat2.pl|polsatcafe.pl|polsatfilm.pl|polsatnews.pl|polsatplay.pl|poszkole.pl|reklamowy-sklep.pl|superstacja.tv|tv4.pl|tv6.com.pl|trendu.pl|styluva.pl 
||ad.prv.pl/rodo.js
||openid.pino.pl/app/static/global/rodo.js ||sso.ppapi.pl/rodo.js$script
```

**Comment by kiboke** [comment]
those can be reviewed and blocked with other rules. instead of `rodo.js`, `/templates/rodo/rodo.js` will cover all polsat* websites, `/js/rodo/rodo.js` and `/js/rodo.js` most of others... IDCAC extension will cover all above mentioned websites in alternative ways. Thanks for the list!
