### ISSUE TITLE
store.hp.com broken due to filter /omniture/*$script

### ISSUE THREAD

**Issue by crssi** [ryanbr/fanboy-adblock#974]
### List the website(s) you're having issues:

`https://store.hp.com/us/en/mdp/laptops/envy-17-344517--1#!&tab=vao`

### What happens?

Missing options, by the filter `/omniture/*$script`

### List Subscriptions you're using:

Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Win 10 
- Browser/version: Firefox 65/66
- Adblock Extension/version: uBlock Origin v1.18.6

### Other details:

`/omniture/*$script` filter from Fanboy’s Enhanced Tracking List

Cheers

**Comment by THEtomaso** [comment]
Confirmed.

### Screenshot of blocked objects:
![filterissue-hp](https://user-images.githubusercontent.com/9382674/54717870-76464500-4b59-11e9-90dd-850695e7bf25.jpg)

### Possible fix:
`@@||hp.com/wcsstore/HPStorefrontAssetStore/js/omniture/omniture-tag.js`

**Comment by crssi** [comment]
Or perhaps less complicated:
`@@/omniture/*$script,~domain=store.hp.com`

Or replace the current one `/omniture/*$script` with `/omniture/*$script,domain=~store.hp.com` or `/omniture/*$script,domain=~hp.com`

?

**Comment by THEtomaso** [comment]
or
`@@||hp.com/*/omniture/$script`
or
`@@omniture-tag.js$first-party,domain=hp.com`

ryanbr will probably come up with something slightly diffrent anyway. :smile:

**Comment by krystian3w** [comment]
```
@@/omniture/*$script,~domain=store.hp.com
```

Invalid?

**Comment by ryanbr** [comment]
https://github.com/ryanbr/fanboy-adblock/commit/4dfcf3b12a0fbc01c5005244c29370d44aab103e

**Comment by THEtomaso** [comment]
The objects are still blocked by the following rule (found in **Fanboy's Enhanced Tracking List**):
`/omniture-$script`
