### ISSUE TITLE
milliyet.com.tr

### ISSUE THREAD

**Issue by ahmetonuraral** [ryanbr/fanboy-adblock#98]
Every page at this news website has a autoplay video. i couldn't block it manually. its annoying with sound and have much load time.

some pages;

http://www.milliyet.com.tr/-g-saray-acik-soylemeli--galatasaray-2470322-skorerhaber/
http://www.milliyet.com.tr/galatasaray-maicon-ile-anlasti-galatasaray-2470261-skorerhaber/
http://www.milliyet.com.tr/manisa-da-200-asker-zehirlenme-gundem-2470247/

**Comment by ryanbr** [comment]
Adblock isn't really the extension to stop autoplay videos.

**Comment by SMed79** [comment]
For firefox try **FlashStopper** https://addons.mozilla.org/en-US/firefox/addon/flashstopper/
Chrome [https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdh...](https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai)

see also https://www.groovypost.com/howto/disable-auto-play-videos-mobile-phones-save-data/
