### ISSUE TITLE
yahoo.com [reopen] [shadow overlay] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#980]
Reopening https://github.com/ryanbr/fanboy-adblock/issues/764 as this now happens on yahoo.com

**Comment by krystian3w** [comment]
can you reporoduce with other subdomain as:

`consent.yahoo.com`?

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/dca0d41922ad637f6addeb820d36ab14a8ffa3c1

**Comment by krystian3w** [comment]
if you no detect other subdomains in yahoo domains.
