### ISSUE TITLE
Bethesda.net - Message system blocked (Fanboy's Annoyance List + Fanboy's Cookie List) 

### ISSUE THREAD

**Issue by THEtomaso** [ryanbr/fanboy-adblock#981]
### Affected site:
`https://bethesda.net/`

### Issue:
The cookie alert is blocked, like intended.
However, the blocking rule has an unfortunate side effect, which breaks the site's entire messaging system.
E.g., when a login attempt fails, the message which explains why is blocked!

### Screenshot (unblocked message):
![filterissue-bethesda](https://user-images.githubusercontent.com/9382674/54942903-63a08700-4f30-11e9-89fa-96a55ef00d4a.jpg)

### Problem filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List

### Problem rule:
`bethesda.net##visor-alert`

### Possible fix:
Delete the problem rule.

### Other filters blocking it:
* I don't care about cookies (*Reported*)

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by krystian3w** [comment]
```
##app > visor-alert[class^="__tag_"] > div[class] > div[class] > div[class]:not([id])
```

Also bad?

**Comment by krystian3w** [comment]
This is should safe:

```
bethesda.net#?#app > visor-alert[class^="__tag_"] > div[class] > div[class] > div[class]:not([id]):-abp-has(a[href$="/document/cookie-policy"])
```

**Comment by THEtomaso** [comment]
> `bethesda.net#?#app > visor-alert[class] > div[class] > div[class] > div[class]:-abp-has(a[href$="/document/cookie-policy"])`

Unfortunately, that doesn't work in Pale Moon.
The rule still blocks the site's messaging system.

**Comment by krystian3w** [comment]
You are added exception:

```
bethesda.net#@#visor-alert
```

❓

**Comment by THEtomaso** [comment]
No.
You rule works in Chromium, but not in Pale Moon.

**Comment by krystian3w** [comment]
For my works also in Firefox 57+ (now 66.0.2).

Try this for only uBO:

```
##a[href$="/document/cookie-policy"]:xpath(..)
```

**Comment by THEtomaso** [comment]
> `##a[href$="/document/cookie-policy"]:xpath(..)`

Yes, that works for all browsers. :+1: 
But only if it's site specific:
`bethesda.net##a[href$="/document/cookie-policy"]:xpath(..)`

Don't think that ryanbr will be adding it though, since it's a uBO only solution.

**Comment by krystian3w** [comment]
I cannot reproduce to wide block (or none block elements) on PaleMoon 28.4.1...

![obraz](https://user-images.githubusercontent.com/35370833/55689042-577ce680-5980-11e9-963c-e37d146275c7.png) |
--- |
![obraz](https://user-images.githubusercontent.com/35370833/55689053-7e3b1d00-5980-11e9-972d-793b819a3cbb.png) |

Maybe update to X.X.1 hotfix or try in Portable PaleMoon if no possible add profiles into palemoon `about:profiles`.

**Comment by THEtomaso** [comment]
I'm already using v28.4.1.

**Comment by krystian3w** [comment]
```
##app > visor-alert[class] > div[class] > div[class] > div[class]:has(a[href$="/document/cookie-policy"])
```

You have  any detection? Also used tribe compatibility Native / Gecko / Firefox and send `do not track` header.

**Comment by THEtomaso** [comment]
> `bethesda.net#?#app > visor-alert[class] > div[class] > div[class] > div[class]:-abp-has(a[href$="/document/cookie-policy"])`

> `bethesda.net##app > visor-alert[class] > div[class] > div[class] > div[class]:has(a[href$="/document/cookie-policy"])`

I've re-tested everything now, and I can confirm that both of those solutions seems to work just fine in all browsers (when they're site-specific)!
Sorry for the confusion, but I think I simply must have forgotten to disable the 'I don't care about cookies​' filter, when I first tested it in Pale Moon. :confused:

**Comment by krystian3w** [comment]
OK, no problem.

**Comment by krystian3w** [comment]
I hope that the filter is in a good file and you do not have to move it to another one.

**Comment by ryanbr** [comment]
I'm not seeing this. bethesda.net##visor-alert seems to do enough imo

**Comment by krystian3w** [comment]
Try use login form and put to from bad data.

**Comment by THEtomaso** [comment]
> Try use login form and put to from bad data.

Yes, that's the exact same example which I refered to in the first post.
It's a simple way of reproducing the issue, without having to sign up for an account.
Bethesda's messaging system is important for the site's general functionallity and correspondance towards/between users!

*Reopening this issue*
