### ISSUE TITLE
Cookie Notice on https://www.mywot.com/

### ISSUE THREAD

**Issue by SeriousHoax** [ryanbr/fanboy-adblock#983]
It's at the bottom part. 

Browser: Firefox Beta 67
Adblocker: uBlock Origin
Fanboy's Filter: Fanboy's Annoyances List

**Comment by THEtomaso** [comment]
Already blocked by '**I don't care about cookies**', with this site-specific rule:
`mywot.com###root > div > div[direction="up"][style*="transform"]`

**Comment by SeriousHoax** [comment]
Ok, sorry then. I wasn't subscribed to 'I don't care about cookies'. I'm closing this issue.

**Comment by THEtomaso** [comment]
Well, ryanbr might want to add a blocking rule of his own.
I'm not proposing that he should copy the one found in IDCAC, but I posted it here, since its complexity indicates that a somewhat special approach might be necessary. :)

**Comment by SeriousHoax** [comment]
Ow I see :) Should I reopen this?

**Comment by THEtomaso** [comment]
Sure.

**Comment by SeriousHoax** [comment]
Ok done.

**Comment by krystian3w** [comment]
omg another `.js-XXX` random classes.

**Comment by krystian3w** [comment]
`mywot.com#>#body > #root > div[class] > div[class][style]:-abp-has(button[data-automation="accept-cookie"])`

Similar to bethesta proposition, if style attrib it will not be too unique.
