### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#984]
`https://github.com/github/404/issue_comments/404`

No blocked social in footer on error 404 pages.

```
github.com##.lh-condensed-ultra.mb-sm-0.mb-3.flex-items-center.d-flex.list-style-none > li.mr-3
```

###### Maybe possible block by better filters.

```
github.com##footer > div > div > ul > li > a[title^="GitHub on"]
```

**Comment by ryanbr** [comment]
Probably not worth trying to fix.
