### ISSUE TITLE
This rule breaks website logins that use Alibaba captcha

### ISSUE THREAD

**Issue by doio** [ryanbr/fanboy-adblock#985]
Rule:

`/\.com/.*[a-f0-9]{110}/$script,image,third-party,domain=~parship.com|~feedbin.com|~aliexpress.com|~alipay.com|~bilibili.com|~namu.wiki|~fastmail.com`

### List the website(s) you're having issues:

https://bbs.kafan.cn/member.php?mod=logging&action=login
https://www.52pojie.cn/member.php?mod=logging&action=login

And I think many more websites that use this captcha method and those that are not whitelisted.

uBlock Origin

- OS/version: Windows 10
- Browser/version: Firefox 67.0 beta5
- Adblock Extension/version: uBlock Origin 1.18.11b2

**Comment by ryanbr** [comment]
Filter was disabled. should be resolved.
