### ISSUE TITLE
psychologiazycia.com [shadow overlay] [FCL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#987]
### List the website(s) you're having issues:

Example article's subpage: 
`https://psychologiazycia.com/eliksir-pewnosci-pigulce-czyli-pytania-odpowiedzi-2/`

### What happens?

breakage - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Cookie List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 66.0.2 64bit / Opera 58 64bit
- Adblock Extension/version: uBlock Origin version: 1.18.11b2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Cookie List</summary>

![ss_003](https://user-images.githubusercontent.com/43844449/55143825-da5f9f00-513f-11e9-9423-09380c247092.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the list</summary>

![ss_001](https://user-images.githubusercontent.com/43844449/55143841-dfbce980-513f-11e9-81f8-a976aae0ffdd.png)

</details>
<br>
<details not-open>
<summary>screenshoot 3 - after accepting/closing the message</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/55143846-e4819d80-513f-11e9-9d3c-99b56c1085b9.png)

</details>

**Comment by ryanbr** [comment]
Seems fine here.
