### ISSUE TITLE
Swedroid.se

### ISSUE THREAD

**Issue by Bajen222** [ryanbr/fanboy-adblock#988]
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by oceanic84** [comment]
Problem with the site that some ads slip thru for instance "willys" ads. But the biggest problem is that ads are for 99% of the time removed but they leave a big empty block both in the blog and on the forum, especially irritating on the forum where the empty block from the removed add take up half of the top screen. I really hope this will be fixed.

**Comment by THEtomaso** [comment]
For Swedish sites, you should be using '**Frellwit's Swedish Filter**':
https://github.com/lassekongo83/Frellwits-filter-lists/#frellwits-filter-lists

Issues should be reported here:
https://github.com/lassekongo83/Frellwits-filter-lists/issues/

**Comment by ryanbr** [comment]
site looks clean, but yeah, include a swedish list and report ads to them ^
