### ISSUE TITLE
Enhanced Tracking List is breaking Qatar Airways website

### ISSUE THREAD

**Issue by gashtal** [ryanbr/fanboy-adblock#99]
The "/s_code_" filter in the Enhanced Tracking List breaks a lot of profile functionality in Qatar Airways website since it blocks a crucial script loaded from "https://qmiles.qatarairways.com/ffponline/js/s_code_4.js".

**Comment by ryanbr** [comment]
sure.

https://github.com/ryanbr/fanboy-adblock/commit/9d94b8d1ec9d7a674e756902ef5269c462daf7c9
