### ISSUE TITLE
www.rauhanpuolustajat.org Cookiemonster list blocks notification (not cookie-related)

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#991]
### List the website(s) you're having issues:

`www.rauhanpuolustajat.org` (sample link where I encountered this issue: `https://www.rauhanpuolustajat.org/ukraina-konflikti-joka-ei-koskaan-jaatynyt%E2%80%A8%E2%80%A8/?v=f0aa03aaca95` You have to scroll the page down and a dimmed notification will appear.

### What happens?

Cookie monster list blocks a notification that is not cookie related stuff. (Overlay dim is left untouched.)

Wrong:
![wrong](https://user-images.githubusercontent.com/17256841/55280432-46075f00-532e-11e9-83aa-1c7d2c5a4415.png)

Correct:
![correct](https://user-images.githubusercontent.com/17256841/55280436-515a8a80-532e-11e9-989f-69e1bdd5bd24.png)

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 66.0.2
- Adblock Extension/version: Ublock Origin 1.18.14

### Other details:

The rule that causes this issue:

###div[data-nconvert-cookie]

**Comment by krystian3w** [comment]
`##.spu-bg` #976

**Comment by krystian3w** [comment]
@peace2000 Rather, it can not be repaired, it seems to be too effective to block real cookie messages.

**Comment by peace2000** [comment]
All right that's sad then. Thank you anyway.
