### ISSUE TITLE
Bad filter: hyperoptic.com

### ISSUE THREAD

**Issue by funkydude** [ryanbr/fanboy-adblock#997]
### List the website(s) you're having issues:

`https://hyperoptic.com/contact-us/`

### What happens?

Scroll to bottom of website.
Click "live chat".
Popup opens, but popup is blank.

### List Subscriptions you're using:

Fanboy’s Annoyance List

### Other details:

The issue is the following filter entry: `##.scroll_top`
The following entry resolves the issue: `hyperoptic.com#@#.scroll_top`
In my opinion, I wouldn't class "scroll to top" buttons as annoyances. I didn't actually realize they would be blocked when I opted into this list!

![image](https://user-images.githubusercontent.com/16833/55656503-0ab5d600-57ef-11e9-963a-0a3284ddf1d2.png)

**Comment by krystian3w** [comment]
> In my opinion, I wouldn't class "scroll to top" buttons as annoyances. 

Do you like other fixed / sticky buttons?

**Comment by krystian3w** [comment]
```
||zopim.com^$third-party,domain=~nordvpn.com|~egb.com|~apteline.pl
```
