### ISSUE TITLE
 kulttuurivihkot.fi - cookie notification not blocked

### ISSUE THREAD

**Issue by peace2000** [ryanbr/fanboy-adblock#999]
### List the website(s) you're having issues:

`http://kulttuurivihkot.fi/`

### What happens?

Cookie notification not blocked

### List Subscriptions you're using:

Fanboy Cookiemonster

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 66.0.2
- Adblock Extension/version: Ublock Origin 1.18.16

### Other details:

-

**Comment by krystian3w** [comment]
`kulttuurivihkot.fi##.activebar-container`
